### ISSUE TITLE
Input group [Radio] validation fails 

### ISSUE THREAD

**Issue by roosh-t3** [angular/angular.js#10043]
I have been banging my head since today morning only for this issue. 

If I apply required on this input this thing makes me to click each and every input. Let's say If I have several radio button such as 
> UPS
> FedEx 

I have to click on both value to get this button enabled. I have tried lots of combination. using required, value... bla bla.. 

this is an example (omitted some parts)
http://jsfiddle.net/cvpbwbm5/1/

you can try http://www.ilmiocorriere.com/ 
for example

**Comment by petebacondarwin** [comment]
Duplicate (really) of #7647

**Comment by allantokuda-zipnosis** [comment]
I'm on Angular 1.5.  I had this:
```
<input type="radio" ng-model="radioVar" ng-repeat="o in $ctrl.options" required>
```

Issue I saw was that only one of the radios (the last one) would appear to clear required validations. Setting my variable to belong to the parent controller fixed it:

```
<input type="radio" ng-model="$ctrl.radioVar" ng-repeat="o in $ctrl.options" required>
```

I suppose this is because the model variable no longer belongs to the scope of the ng-repeat's controller(s) which as noted above are instantiated for each individual radio button in the ngRepeat.

Reminds me of an Angular tip I picked up way back, that you pretty much always want a dot `.` in there.

Thanks to @ryanhart2 for the helpful comment!
