### ISSUE TITLE
ngModel parse errors always use named parser

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#10076]
For our core parsers, we use a private / undocumented property called `$$parserName`, so that the $error is named, e.g. `$error.date`. Other parsers will always set `$error.parse`. When you have something like this:

```
<input type="date" my-parser ng-model="asdf"/>
```

where myParser adds:

```
ctrl.$parsers.push(function() {
  return undefined;
});
```

the `$error` will nevertheless be `date`, because the `$$parserName` is set in the link function, and $$runValidators will always use the `$$parserName` if it is set.

**Comment by matthiasdailey-ccri** [comment]
I just ran into this bug when writing a directive for an `input[type=number]` element. Returning `undefined` from its parser made the element have an error key of `'number'`. Calling `setValidity()` allows me to set an additional error class, but it does not remove the `'number'` error class.

It seems that a single instance of `ngModelCtrl` is shared between all directives on an element, so changing `$$parserName` would overwrite Angular's native `numberInputType` directive, which is not ok.

I don't see a fix for this. Does anyone have a workaround?

Here's my use case:
My directive is meant to support having a unit suffix ("feet") at the end of a number in an input field. The directive inserts a parser function before the numberInputType directive's parser. It takes the viewValue string, removes the "feet" part, and passes the number string to the numberInputType parser. So it should work seamlessly. 
But I want to have an error case – if the user types "10 meters", I want to invalidate the field with an error class of `'ng-invalid-units'`. So I call `$setValidity()` and return `undefined`. But because of this error, I get the `'ng-invalid-number'` error class as well.

While I was writing that out, I figured out a solution -- return `null` instead of `undefined`. That will indicate "no value", which is acceptable. Or I could use the `$validators` object to avoid doing it from a parser.

So, hopefully this information might help someone else.
