### ISSUE TITLE
$resource DELETE doesn't set the Request Body if provided

### ISSUE THREAD

**Issue by pmariduena** [angular/angular.js#10128]
I know this a similar issue has been closed, but I think it should be added. When I try to set a request body on a delete (array of JSON objects), it is put in the URL as a request params, instead of the request body.

Maybe a custom property could be added to $resource (under "options", say "enableDeleteRequestBody" in addition to already supported "stripTrailingSlashes"), with a warning in the doc that states that this is not the officially Spec-compliant use of a DELETE (use at your own risk). 

But I would really like to use it. 

It would allow for batch deletes of multiple, non-consecutive objects that represent, say, rows in a database. specifying those rowIds as, say, query string params in the URL, or request headers, is messy. Apache Jetty server is definitely accepting my DELETE body request that I send from POSTman.

**Comment by daniel-nagy** [comment]
According to the [documentation](https://docs.angularjs.org/api/ngResource/service/$resource) for `$resource`,

* non-GET "class" actions: `Resource.action([parameters], postData, [success], [error])`

Implying that the first parameter, `parameters`, is optional but this is inconsistent with `DELETE` methods. For `DELETE` methods, if only one argument is provided it will be sent as query parameters instead of the request body.

This is because the `DELETE` method is not considered to have a body.

```javascript
var hasBody = /^(POST|PUT|PATCH)$/i.test(action.method);
```
