### ISSUE TITLE
Flickering with ngAnimate and ngShow

### ISSUE THREAD

**Issue by trs79** [angular/angular.js#10156]
Please take a look at this jsfiddle: http://jsfiddle.net/1op08u1o/4/ in IE 11. If you click on link 2, then quickly click on link 1 sometimes you can see a flicker where the orange block is bumped down by the green box before the orange block disappears.

This only seems to happen in IE11, and only if I include the ngAnimate module. Even without css transitions and just showing or hiding there is still a flicker. It may take a few tries to see the flicker happen. I'm using angular 1.3.3

**Comment by CToner3223** [comment]
+1

I'm seeing this as well, its very frustrating. I found that replacing the offending ng-shows with ng-ifs fixes the issue but this isn't a very nice fix at all. In the end I've decided to removed NgAnimate from the application all together to fix the flickering but its a less that desirable solution.

**Comment by ian-autotrader** [comment]
just as a side note @VitalyTomilov 

we added a .ng-hide-add with 0ms which seems to fix your fiddle..?

http://jsfiddle.net/wkse7bgy/

**Comment by VitalyTomilov** [comment]
Guys, the solution is only a work-around, it is not a proper fix!

Why was this issue closed???

**Comment by chinchang** [comment]
+1 Facing same issue with 1.2.28

**Comment by Narretz** [comment]
It's a very irritating issue, that also affects Firefox in 1.4.8. I assume that the overall implementation of ngAnimate has become slower rather than faster to handle edge cases.

One thing that is good to know is that due to the way animations are detected, ngAnimate handles "mirror" animations best, that means when both add/remove are animated. That's why adding style such as 
```
.ng-hide-add {
  transition: all 0s ease;
  opacity: 0;
}
```
helps with this issue.
That said, whenever you have very fast user interaction, it's always possible that the browser cannot keep up with animation updates.

**Comment by Narretz** [comment]
THis issue is actually not browser specific, and it affects all animations that have a transition / animation on add / enter but not on remove / leave (or vice versa). When you change very fast between the two states, the following is happening:
- addClass animation with animation styles runs
- removeClass animation without styles runs 
- addClass animation with animation styles runs -> at this point, the animation is somehow messed up, and it doesn't actually animate, because somehow the removeClass non-animation has interfered with the next addClass animation

**Comment by matsko** [comment]
This guy should fix it: https://github.com/angular/angular.js/pull/13814
