### ISSUE TITLE
Incorrect Croatian translations

### ISSUE THREAD

**Issue by Victa** [angular/angular.js#10247]
[The generated Croatian locale](https://github.com/angular/angular.js/blob/3831e45a7d414cfa44297856689bd9added929f5/src/ngLocale/angular-locale_hr.js) isn't correct. Two last letters are misspelled in all months.

However, the sources (Google Closure) are correct https://github.com/angular/angular.js/blob/d3b1f502e3099d91042a1827a006ad112ea67d36/i18n/closure/datetimeSymbolsExt.js#L11328

**Comment by lgalfaso** [comment]
I think the issue is that there are two ways to write a month, this is when the month is part of a date and when it is stand-alone. This is already defined at the CLDR, but angular does not copy nor adds the pattern support for this.

A PR that adds support for this would be welcome.

**Comment by Janneman84** [comment]
The Angular's localization files now have both versions present ("MONTH" and "STANDALONEMONTH"). But the date filter doesn't seems to be always using the right ones, actually it still only seems to use the "MONTH" version at all times

For example if you use "MMMM" to just get the month's name it should show the version from "STANDALONEMONTH".

Would it be possible to at least make the plain "MMMM" one behave correctly? Because if it does then AngularUI's datepicker will work correctly too. Thanks.

**Comment by Narretz** [comment]
@Janneman84 This seems like an additional problem. Can you please open a new issue for that?
