### ISSUE TITLE
Angular HTTP interceptor executed for embedded ng-templates

### ISSUE THREAD

**Issue by xieranmaya** [angular/angular.js#10257]
see here:
https://stackoverflow.com/questions/16747705/angular-http-interceptor-executed-for-embedded-ng-templates

**Comment by bbottema** [comment]
any update on this?

**Comment by bbottema** [comment]
As a workaround, I'm currently checking the cache before doing anything:

``` javascript
...
.factory('myIntelligentInterceptor', function($log, $templateCache) {
		return {
			request : function(config) {
				config.alreadyCached = $templateCache.get(config.url);
				if (!config.alreadyCached) {
					// do intercept-things with request
				}
				return config;
			},
			response : function(response) {
				if (!response.config.alreadyCached) {
					// do intercept-things with response
				}
				return response;
			}
		};
	});
})();
```

**Comment by gkalpak** [comment]
I believe that not running interceptors for (cached) templates, would be too much of a breaking change (not to mention there are valid cases where you might want to indeed intercept the template requests).

That said, now we are using `$templateRequest` (which is a wrapper around `$http`) for all template requests (duh) and since `v1.5.0-beta.2` there is [`$templateRequestProvider.httpOptions()`][1], which can be used to (among other things) set a special flag on your configs. Then you can easily check the flag from your interceptors and skip interception (if you interceptor does not apply to template requests).
This is similar to checking the `$templateCache`, but avoids the overhead.

E.g.:

```js
// During config phase
.config(function ($templateRequestProvider) {
  $templateRequestProvider.httpOptions({_isTemplate: true};
})

// In the interceptor
.factory('myInterceptor', function () {
  return {
    ...
    request: function (config) {
      if (config._isTemplate) return config;

      /* Do intercept */
    }
  };
})
```

[Demo pen][2]

--
A viable "built-in" solution (that wouldn't break existing apps), would be to have `$templateRequest` add a special flag (pretty much as shown in the example above) and (somehow) allow interceptors to specify an `ignoreTemplateRequests` option. Then `$http` could check the flag added by `$templateRequest` and not pass the template request/response/error through interceptors with `ignoreTemplateRequest: true`.

Considering all the above, I don't think this is a high priority, but if anyone want's to take a shot at a PR, they're more than welcome :smiley:


[1]: https://docs.angularjs.org/api/ng/provider/$templateRequestProvider#httpOptions
[2]: https://codepen.io/ExpertSystem/pen/EPJmbq?editors=0012

**Comment by Narretz** [comment]
I agree that changing this would be a BC and that there's an adequate workaround

**Comment by nciuprina** [comment]
sfsfgdgdfgdfg
