### ISSUE TITLE
ng-switch enter animation issue with first switch-when/switch-default

### ISSUE THREAD

**Issue by digitalicarus** [angular/angular.js#10261]
Versions
=======
seen in 1.3.3 and 1.3.4

Overview
=======
There's an issue when attempting to tween enter animations on the first switch when. In the plunkr example the header and footer are suppose to recede when the first view is leaving and return from the edges when returning to the first view. Using ng-switch causes the enter animation for the default view to not tween properly. There's no delay and no header and footer animation as there should be. Using ng-ifs yields the expected result.

You can comment the blocks on and off in the plunkr to see the difference. I tried many approaches with varying specificity but now believe there's a problem with switch and enter animations.

http://plnkr.co/edit/6P2alBYQ7pGANKzyRy4Z?p=preview

**Comment by Narretz** [comment]
This looks similar to the problem in https://github.com/angular/angular.js/issues/13250

Basically, if you use angular animation classes to trigger animations on child elements, you have to be aware that angular does not block these animations like it does with enter etc. animations. 
In the example, you are putting transition styles on the descendents of elements with the ng-animate class. What that means is, that you `transform: translateY(-@headerHeight);` will animate when the ng-animate class is added on the switch element. So instead of bringing the elment to the starting position immediately, it will try to animate it, and because ng-enter-active is added almost immediately afterwards, the element remains at translateY(0). Bottomline is, when you try to trigger animations on child elements of animated elements, apply the transition styles on the active classes, not on ng-animate or the event classes, and apply the starting styles on the event classes.
