### ISSUE TITLE
Angular compiler throws exception when ng-repeat-start compiles after being called from a higher priority terminal directive on the same element

### ISSUE THREAD

**Issue by stumpymoose** [angular/angular.js#10399]
Hello angular folks,

I may be doing something silly here, but basically I have a need to run a custom directive on the same element that ng-repeat-start is on. My custom directive is terminal and runs before ng-repeat, as it has a priority of 1001. I run it before ng-repeat as I want to do some one off work in the directive compile function, then remove the directive so it does not run on the copies created by ng-repeat.

When using vanilla ng-repeat the process works. When I try to use ng-repeat-start angular throws the following exception:

RangeError: Invalid array length
    at compositeLinkFn (https://code.angularjs.org/1.3.5/angular.js:6970:28)
    at publicLinkFn (https://code.angularjs.org/1.3.5/angular.js:6888:30)
    at link (http://run.plnkr.co/Dmq2BMsu6rllhj4a/script.js:14:40)
    at invokeLinkFn (https://code.angularjs.org/1.3.5/angular.js:8141:9)
    at nodeLinkFn (https://code.angularjs.org/1.3.5/angular.js:7653:11)
    at compositeLinkFn (https://code.angularjs.org/1.3.5/angular.js:7009:13)
    at nodeLinkFn (https://code.angularjs.org/1.3.5/angular.js:7648:24)
    at compositeLinkFn (https://code.angularjs.org/1.3.5/angular.js:7009:13)
    at publicLinkFn (https://code.angularjs.org/1.3.5/angular.js:6888:30)
    at https://code.angularjs.org/1.3.5/angular.js:1439:27 

I have tried debugging and it appears to be attempting to access a node list on the comment element created by ngRepeat which has a length of -1.  

To reproduce use the following plunker, the first span uses vanilla ngRepeat and works, the second
set uses ng-repeat-start and end without the terminal directive, and works, and the third set uses both
ng-repeat-start and the terminal directive, and fails

http://plnkr.co/edit/vZ3pqhqpAFb76Zcav7Kl?p=preview

Reproducable: always
Browsers: Chrome 39.0.2171.71 m, IE 10
OS: Windows 7

Many thanks if anyone can point me in the right direction to get around this issue.

**Comment by petebacondarwin** [comment]
This is not a valid pattern of use for Angular. If you think about what you are doing here it will be clear that this is not likely to work. Consider this bit of HTML:

```html
<div terminal ng-repeat-start="...">...</div>
<div>...</div>
<div ng-repeat-end></div>
```

If the `terminal` directive terminates compilation and then tries to recompile itself you will end up with the following `element`, which are you trying to compile inside this directive's link function:

```html
<div ng-repeat-start="...">...</div>
```

Notice that the element that you are passing to `$compile` no longer contains an `ng-repeat-end` element, since it is only the element where the original `terminal` directive was found.

You could perhaps get around this in some way by making the terminal directive accept start and end elements too...
