### ISSUE TITLE
$filter number: Could we display an Infinity symbol in case of Infinity value?

### ISSUE THREAD

**Issue by QuentinFchx** [angular/angular.js#10421]
Could we display an Infinity symbol (∞) instead of an empty string through the "number" filter, when it's applied to `Infinity/-Infinity`?
According to [this thread](http://stackoverflow.com/questions/2254913/infinity-symbol-with-html), we could use `&infin;` or `&#8734;` (decimal) or `&#x221E;` (hex)

I can come with a PR if it's in the framework's scope. I guess we only have to add a case [here](https://github.com/angular/angular.js/blob/master/src/ng/filter/filters.js#L141).

**Comment by lgalfaso** [comment]
landed as #10422

**Comment by leodido** [comment]
I think this issue is not yet completely fixed.

I explain myself with some bits of code:

```html
  Infinity (1): <span>{{1/0 | number:4}}</span><br> 
  Infinity (2): <span>{{Infinity | number:4}}</span><br>
  Infinity (3): <span>{{'Infinity' | number:4}}</span><br>
```

* cases (1) and (3) work as expected: they both print `∞`.
* **case (2) does not work**, it prints an empty string because `number` parameter passed to the filter has `undefined` value.

But Calling `numberFilter(Infinity, 4)` works.

Therefore I believe that most likely the problem resides in the expression evaluation.

**Comment by gkalpak** [comment]
I think it works as expected.

`<span>{{Infinity | number:4}}</span>` is equivalent to `numberFilter($scope.Infinity, 4)`, which is undefined (unless explicitly defined by the user).

Keep in mind, that JS expressions in the controller are evaluated against the global object, whereas Angular expressions in the view are evaluated against the local `$scope`.

**Comment by leodido** [comment]
Okay, I get it. Sorry and thanks.
