### ISSUE TITLE
Watch File on Safari causes infinite $digest loop

### ISSUE THREAD

**Issue by hugomallet** [angular/angular.js#10524]
Hi,

On Safari with angular 1.3, watching changes on a JavaScript File object throws:
```
[Error] Deprecated attempt to access property 'name' on a non-File object.
	equals (angular.js, line 934)
	$digest (angular.js, line 14036)
	$apply (angular.js, line 14304)
	setFile (runner, line 33)
	handleFiles (runner, line 39)
	eventHandler (angular.js, line 2979)
```
and causes a infinite $digest loop.

**Reproducable here:**
http://jsbin.com/vaketipeyo/1/edit?js,console,output
*Choosing a file will produce the error*

**Angular version:** > 1.3

My config:
**Browser:** safari 8.0.2
**OS:** OS X 10.10.1

This issue might be related to: #10370 #10210

**Comment by lgalfaso** [comment]
@petebacondarwin everybody is happy is `$watchCollection` is used

**Comment by caitp** [comment]
$watchCollection doesn't really make sense here

**Comment by lgalfaso** [comment]
@caitp why do you think it does not make sense to use `$watchCollection`? Using it would check for changes in the properties values (and we would never clone `File`). I am not saying this is a perfect solution, just that we do not run into the `$digest` error and that the listener is triggered when the file changes

**Comment by caitp** [comment]
because it's very different, semantically

**Comment by lgalfaso** [comment]
I think that everybody knows that `$watchCollection` and `$watch` with `deepWatch=true` are different things. Also, everybody is aware that using a different function that works is a different way does not solve the original issue, that is that Safari is reflecting properties on the prototype and not on the instance.

Is this what you mean when you say that they are semantically different?

Now, the question is if we should solve this or not. If we should solve this then how, and if not then what are the possible work-arounds. The one solution I can think of (without adding special rules for host objects) is https://github.com/angular/angular.js/issues/10524#issuecomment-67740949. This is not perfect and for sure it is not for free. If we are not going to solve this then we have to be clear that Safari does not behave well when you are deep watching a host object, and have solution for the community to use. In this case, using `$watchCollection` is a possible work-around

**Comment by caitp** [comment]
semantically different means exactly what it sounds like, the semantics of the two functions are different, and are not interchangeable. This isn't a real workaround, because it will only work under certain conditions (when array or object valued properties aren't considered, and when the prototype chain of the object being watched doesn't matter). Beyond that, you're telling people to write text which does not represent their intentions, or the actions they're actually performing, which is always a bad recipe.

Unfortunately, there isn't much we can do about it. Fixing one use-case harms other use cases. There are other solutions, which are a bit more complicated, but work better.

You can watch the specific properties you care about. If you need to watch multiple properties, you can use `$watchGroup` and supply a set of expressions to watch. That's probably the best case scenario for deep-watching host objects.

**Comment by petebacondarwin** [comment]
It seems that this issue is a corner case that has a couple of workarounds: i.e. to use `$watchCollection` or to watch individual properties of the file object (via `$watch` or `$watchGroup`) so we are not going to prioritize a fix for this. @hugomallet - if you have time to look into it and come up with a decent solution then do please send in a pull request.

**Comment by wesleycho** [comment]
A suitable workaround for something like this is to do
```js
$scope.$watch(() => scope.file && scope.file.name, (fileName) => ...)
```
IMO this can probably be closed.

**Comment by Narretz** [comment]
Yes, I agree this is a very uncommon scenario with a number of workarounds, so no need to change the core for this.
