### ISSUE TITLE
Misc/contribute docs appear to be out of date

### ISSUE THREAD

**Issue by chrisfosterelli** [angular/angular.js#10634]
Hi there!

I'm trying to figure out how to build the Angular.js documentation, and I stumbled across [these docs](https://docs.angularjs.org/misc/contribute). Unfortunately, they don't appear at all to work with the current git repository. It looks like the `misc/contribute` docs reference `grunt`, but that appears to now be replaced by git, as well as some other things (such as a `build` directory not existing).

This is problematic because it's one of the first hits in Google when searching for how to build the project's documentation.

**Comment by gkalpak** [comment]
I think the docs are fine. What exactly are you having problems with ?

BTW, both `git` and `grunt` are used (which are tools for totally different tasks). If you meant `gulp` (instead of `git`) that is indeed used as well (for the docs app), but executing `grunt package` (as instructed by the aforementioned docs) will take care of it (as well as creating the `build` directory).

**Comment by chrisfosterelli** [comment]
@gkalpak Wow, my apologies.

I definitely did mean `gulp`, but my confusion here was entirely related to the fact that I have been working on a fork of `angular/angular` instead of `angular/angular.js`. That explains _alot_ of my confusions.

Closing this issue, sorry for the trouble :)
