### ISSUE TITLE
Change views frequently lead to too much memory consumed

### ISSUE THREAD

**Issue by karimfikry** [angular/angular.js#10638]
Using ng-view and switch its content frequently consume too much memory in Chrome, Firefox, Safari as I noticed it goes larger and never clear the memory of the previous used view.

For example: when I launch the application for the first time let's say It consume ~100 MB of RAM, then I change the view 10 times, then It almost reach ~800 MB. So It appends the memory and don't destroy the old view's content.

I checked https://github.com/angular/angular.js/issues/3543 and It seems to be fixed by 1.3.0-beta.20, but after testing my application it seems that it's not resolved yet.

**Comment by lgalfaso** [comment]
would it be possible for you to create a plunker that shows this?

**Comment by karimfikry** [comment]
I created a small [plunker](http://plnkr.co/edit/1SVYdCHXs0KbkDLMws6E?p=preview) which of course don't match the original case (As I have private data in it), but at least will show you the problem I'm pointing to. To regenerate the issue, please click on the bottom button (switch view) frequently and track the memory in Task Manager, you will find it increasing rapidly

Also, kindly find my question on [stackoverflow](http://stackoverflow.com/questions/27749383/memory-reserved-is-not-freed-after-changing-ng-view-content) regarding this issue

**Comment by Narretz** [comment]
I have downloaded the plnkr and opened the test page as the only tab in FF and Chrome, and then switched ways every other second, and checked the memory consumption in Windows Task Manager.
- with FF, I notice a slight increase in memory (maybe 10 MB for every 10 switches), but that is reduced to almost baseline after a certain amount of time (even when continuing to switch)
- Chrome does not cause any rise in memory consumption.

Can you reproduce the problem with this plnkr? Otherwise it might be content / a directive inside the view that is not cleaned up properly.

**Comment by Narretz** [comment]
I'm gonna close this, but feel free to reopen this issue when you have updated the plnkr.
