### ISSUE TITLE
Confusing $location.state behaviour

### ISSUE THREAD

**Issue by dpogue** [angular/angular.js#10657]
Can anyone clarify the reasoning for https://github.com/angular/angular.js/blob/e9bf93d510a6a0c105d8f5d036ec35c7ce08a588/src/ng/location.js#L944 ?

It tripped me up where I'm trying to store a "page depth" number in the state for detecting back navigation, and when navigating between pages of the same level the state would suddenly be null instead of my value.

I suspect it has to do with the null vs undefined behaviour or an IE bug, but it would be helpful to have a comment in the code explaining why it sometimes appears to discard the state.

/cc @mzgol

**Comment by Narretz** [comment]
Are you overwriting `$$state`?. Just asking, because it is private and you should not rely on it.

**Comment by mzgol** [comment]
This is done to differentiate between two situations:

1. The user invoked `$location.state({a: 2})` and Angular hasn't invoked `pushState`/`replaceState` yet; we're keeping the value to be saved in `$location.$$state`.
2. Angular did its work and we store the saved state in `$location.$$state` so that `$location.state()` returns the correct state.

We need to differentiate because if you do:
```js
$location.url('/first-path').state({a: 2});

// Later:
$location.url('/second-path');
```
then we want Angular to go to the new URL *with a `null` state*. This mimicks the browser native behavior:
```js
location.pushState({a: 2}, '', '/first-path');
// history.state equals {a: 2}

// Later:
location.pathname = '/first-path';
// history.state is now `null`, not {a: 2}
```

This will all break badly if you mess with `$location.$$state` so I hope you're not doing that.

@dpogue can you share the code snippet showcasing the problem?

**Comment by dpogue** [comment]
Okay, that case about changing the URL later and needing a null state makes sense. It seems to only be a problem if the state is a primitive type, and I got it working by using objects.

I am actually forced to use `$$state` directly because `state()` doesn't work in non-html5 mode, and becuase I'm running as a packaged mobile app I can't enable html5 mode. :(

**Comment by mzgol** [comment]
> becuase I'm running as a packaged mobile app I can't enable html5 mode.

What doesn't work in HTML5 mode in packaged apps?

BTW, `$location.state()` setter works with primitives as well; this is not the case with `$location.$$state`. Using the latter is not supported, it can change in a patch release, it may even completely disappear one day if it makes sense in fixing an issue. We cannot fix any problems you might have if you're using `$location.$$state` directly. :(
