### ISSUE TITLE
control of updating of ng-repeat with $$hashKey of items has been lost since adding of 'track by'

### ISSUE THREAD

**Issue by Alexsey** [angular/angular.js#10655]
Hello

Here if <a href='http://plnkr.co/edit/ksIm5jRLIKTDgKXTqonr?p=preview'>Plunker</a> with current version of Angular, and it has error of ```10 $digest() iterations reached. Aborting!``` in console. But if we change version to 1.1.3 (in 1.1.4 ```track by``` where introduced) - everything works fine. And there is nothing in Angular`s change logs to guess is it a bug or by design.

Here is a <a href='https://groups.google.com/forum/#!topic/angular/IEIQok-YkpU'>real problem</a> I also came up with, but none of their solutions are working with current versions. So I post <a href='http://stackoverflow.com/questions/27780049/angular-js-ng-repeat-track-by-dynamic-collection'>this question</a>. If some one would give a good answer on it I will adapt it to PR to appropriate parts of documentation (because according to current text there should be no issues)

Thanks

**Comment by Narretz** [comment]
Two things about this: `$$hashKey` is a quasi private variable (like all that start with `$$`). Due to the nature of Javascript, it is accessible, but private means that angular core makes no guarantees about its behavior or even its existence. So you should not rely on it.
In 1.1.4, something about the dirty checking must have changed, but in general, angular cannot stabilize your source array, because each call to the function returns a new array. This is explained here: https://groups.google.com/d/msg/angular/IEIQok-YkpU/InEXv61MrkMJ
Since this is more of a support question, I'll have to close this issue. You'll have to use one of the workarounds - quite a few are mentioned on stack overflow. See also https://github.com/angular/angular.js/issues/2302
