### ISSUE TITLE
Browser freezes on invalid json

### ISSUE THREAD

**Issue by joshribakoff** [angular/angular.js#10686]
If an ajax call with $.http results in invalid json, for example, if the json is prefixed with a PHP error - the whole browser freezes & becomes permanently unresponsive.

Seems like Angular is lacking some logic to abort parsing when invalid json is encountered in a response. The user sees a "a script on this page is unresponsive" dialog... even after pressing "stop script", the page will continue to freeze up.

Instead of crashing the browser, it would be nice if an error message is logged to console.

**Comment by lgalfaso** [comment]
Hi, would it be possible for you to create a plunker that shows this issue?

**Comment by pkozlowski-opensource** [comment]
@joshribakoff I can't reproduce the problem you are describing with a simple plunker: http://plnkr.co/edit/NA4tY9vVDMy0sHotit1B?p=preview and we haven't heard from you. As such we are still missing vital pieces to info that would allow us to reproduce your issue:
* the exact scenario that leads to the pb
* AngularJS version used
* OS / browser and its version used

Please provide more info otherwise this issue is not actionable and will be closed

**Comment by pkozlowski-opensource** [comment]
@joshribakoff we haven't heard from you and since we can't fix what we can't reproduce I'm going to close this issue for now. Happy to re-open when / if you've got more details.

**Comment by greghesom** [comment]
I am also experiencing this issue on the following:
Windows 8.1
IE 11 (11.0.9600.17498). Update versions 11.0.15 (KB3008923).

I have modified the example above with the data which I am trying to post: http://plnkr.co/edit/yYaDy8d00VGV6WcjaUu3?p=preview

The issue is occuring consistently across varying controllers and data json structures. 

Please run that in IE11 and watch the browser crash!

**Comment by pkozlowski-opensource** [comment]
@greghesom I don't have IE11 handy atm so what would be very helpful is a bit of debugging on your side to exactly pin-point a line in AngularJS which triggers the crash. I suspect that we are going to uncover some problem in IE11 XHR impl. Anyway - since you've got a constant reproduce secanario a bit of debugging help would be much appreciated!

**Comment by greghesom** [comment]
Sure thing. The issue only started occuring after the xmas break, so this
issue definitely is a result of an IE11 patch. I will debug to the line and
let you know.

**Comment by pkozlowski-opensource** [comment]
@greghesom awesome!

**Comment by joshribakoff** [comment]
Maybe this will help. I don't get a crash with your data either. It seems to depend on how your invalid data looks. When my invalid json is this string:

```
{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{{{{invalid{{{{{
```

the browser becomes a bit sluggish on load, and my `ng-repeat` ends up with 100s of items rendered in the DOM. 

Instead, I would expect the `.error` promise to be invoked. The json is objectively invalid.

With certain server respones in this same vein, the ng-repeat becomes so overloaded that the browser is crashed.

**Comment by pkozlowski-opensource** [comment]
@joshribakoff so, the response you get from server doesn't seem to be a valid JSON. As of today AngularJS will [leave non-JSON responses alone](https://github.com/angular/angular.js/blob/301663e7343178e45a43470dcda4e2fffd196b53/src/ng/http.js#L12-L26) and what you are going to get in the end is a string. This will be treated by `ngRepeat` as a collection of characters.

So, while we've got explanation for the behaviour you are seeing, things are still "not right". I think that the first problem is that your server is responding with the "success" status code while the response is clearly invalid. Secondly - you happen to return a string that is not JSON and we can't make it being an object... 

There is a potentially an actionable item here - that is - failing responses if those are indicated as JSON (by response headers) and happen to not be a valid json in the end. But to move forward on this I would need to know:
* what is the status code returned by your server
* what is the content type header returned by your server

BTW: for now the best course of action is to make sure that your server sends back error status code for invalid responses.

**Comment by joshribakoff** [comment]
That makes sense.  It occurs mostly when i do a print_r followed by exit in php for manual debugging. Ill wrap it in a function that sends a non 200 status code or log my debug data to a file instead of outputting it

**Comment by greghesom** [comment]
@pkozlowski-opensource FYI, I have posted the question to stackoverflow and the IE team have picked it up. I'll keep you posted if anything comes of it.

http://stackoverflow.com/questions/28114732/internet-explorer-11-crashes-when-angulars-http-post-is-used-with-large-complex?noredirect=1#comment44605608_28114732
