### ISSUE TITLE
Promise returned by $animate.addClass() is resolving immediately

### ISSUE THREAD

**Issue by antch** [angular/angular.js#10688]
When using `$animate.addClass()` to trigger a CSS animation, the returned promise appears to resolve immediately, instead of after the animation completes.

I [created a Plunker](http://plnkr.co/edit/dwBGodZiKM8fTQVKnEm1?p=preview) that demonstrates the issue.

**Comment by caitp** [comment]
there are 2 problems with your plunker

1. you are mixing and matching versions of angular and angular-animate. Make sure they are the same version, always!
2. You are not actually using the `ngAnimate` module. The `$animate` service in the `ng` module (from angular.js rather than angular-animate.js) will always resolve this promise immediately, because it's just a dummy API. Using the actual ngAnimate module, it appears to work correctly, see http://plnkr.co/edit/oulm9gcPf795nLTcuWqY?p=preview

**Comment by antch** [comment]
Simply making my module dependent on `ngAnimate` fixed it, thanks!  (The mismatching versions of the modules were simply the latest versions that Plunker had available already.)  Sorry for cluttering up the issues list!

**Comment by caitp** [comment]
no problem, glad to help~
