### ISSUE TITLE
When initializing ngModel to the last item of a select control inside of a $timeout, UI is not updating

### ISSUE THREAD

**Issue by trees4** [angular/angular.js#10718]
When defining a select control as follows:

     <select data-ng-model="selected" data-ng-options="n for n in [0,1,2,3]"></select>

And initializing the 'selected' variable to the last item inside of a $timeout handler in an ngController:

    function ctrl($scope, $timeout) {
      $timeout(function() {
          $scope.selected = 3;
      },50);
    }

The drop down list remains blank (it should be initialized to 3).

Here is a plunker demonstrating the issue:  http://plnkr.co/edit/AGlwxCoe1vlvzXyvvk2b?p=preview
Here is the original stack overflow post where the issue was found: http://stackoverflow.com/questions/27892564/angular-strange-behavior-with-ng-options

This issue exists for version 1.2.26, and 1.2.28, but is working in version 1.3.*

**Comment by Narretz** [comment]
This was most likely introduced by, then fixed by https://github.com/angular/angular.js/commit/2435e2b8f84fde9495b8e9440a2b4f865b1ff541. However, the fix didn't fix all cases, which is why we now have the big refactor by @petebacondarwin 
This is going to be quite an effort to fix in 1.2.x, I'm not sure this is going to happen. Upgrading to 1.3.x or using `ng-repeat` for you select is not an option?

**Comment by Narretz** [comment]
1.2.x only receives critical bug fixes; closing.
