### ISSUE TITLE
Stranger Loop

### ISSUE THREAD

**Issue by claudsan** [angular/angular.js#10776]
In **ng-repeat** something strange happens when you use any function within the element that contains the directive.

In the example I created a list of seven items with the id and name elements, and a function call every execution that resulted in 77 checks but has only 7 items.

Here's a link to the example:
http://embed.plnkr.co/aStkK3ghGasdIJNuYFG8/preview

**Comment by pkozlowski-opensource** [comment]
This happens because you are constantly incrementing `$scope.qtd++` and as such your JS model on a scope never stabilizes. AngularJS will keep evaluating expressions on a scope till the model gets stable - in your case in never happens and this is why you are getting this repeated calls. See the version without the increment: http://plnkr.co/edit/aStkK3ghGasdIJNuYFG8?p=preview

I'm going to close this one as this is more of a support question and things work as expected on the AngularJS side.

**Comment by claudsan** [comment]
Did not understand, the link is the same as envei unchanged.

**Comment by pkozlowski-opensource** [comment]
@claudsan sorry, linked wrong plunk: http://plnkr.co/edit/vxvumhP919kTVkDJCE87?p=preview
Check JS console and see errors indicating that the model never stabilizes....
