### ISSUE TITLE
using $applyAsync breaks async unit tests

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular.js#10788]
It seems that if I use `$applyAsync` over `$apply` causes my previously working unit tests to fail. I have a simple deferred object (using `$q.defer`) that is created and resolved after a while (a while meaning that I have a RequestAnimationFrame event loop and when the animation is done then it resolves).

Inside the event loop I have to use either `$apply` or `$applyAsync` in order to notify Angular of a change so it can actually resolve the promise.

```javascript
function loop (timestamp) {

	current = timestamp;
	percentage = (current - past) / duration;

	if (current >= future || canceled)
	{
		$rootScope
			.$applyAsync(resolve);

		id = $timing
				.caf(id);
	}
	else
	{
		id = $timing
				.raf(loop);
	}

	if (!notified) notified = $rootScope.$applyAsync(notify) || true;

	callback(
		that.easing(1 > percentage ? percentage : 1)
		);
}
```

And in my unit tests I simply call `$rootScope.$digest()` after I trigger that animation.

```javascript
it("should invoke callback function", function (done) {

	animate(
		callback,
		200
		)
		.then(function () {
			callback.should.have.been.called;
		})
		["finally"](function () {
			done();
		});

	$rootScope.$digest();

});
```

But the promise never resolves  I am unsure what to do about that or how to fix my tests, because the functionality works in the browser.

If this cannot be fixed, is there another way to notify angular that something happened in my animation loop so it can resolve/reject the promise?

**Comment by pkozlowski-opensource** [comment]
`$applyAsync()` will schedule a new digest loop in the "next JS tick" (which pretty much boils down to calling `setTimout`) so under unit tests you need to synchronously trigger this next tick. In AngularJS next ticks are abstracted behind `$browser.defer` and those are `$browser.defer` is mocked under unit tests.

In order to simulate deferred execution under unit test you would have to call `$browser.defer.flush();`, see: http://plnkr.co/edit/IHGoa2d6sXd8mCegi4Kn?p=preview 

Anyway, this is more of a support question and as such should be directed to [one of the support channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question) so closing this one.

**Comment by rolandjitsu** [comment]
@pkozlowski-opensource I've looked at the source and I noticed that it runs under `$browser.defer` which is a `setTimeout(...,0)`, I just didn't know about the `$browser.defer.flush()` API. I'll try it out and hope it works :)

Thanks for the help and sorry for opening an issue, but I was not familiar with the support options, I will definitely ask on IRC next time :)

**Comment by pchiwan** [comment]
@pkozlowski-opensource genius!! I was going crazy with this for days. I couldn't find a way to test my code whenever I used $scope.$applyAsync, I was sure there had to be a way to do it! Thanks man!
