### ISSUE TITLE
parse.js functionCall()  no proper function found behaivor

### ISSUE THREAD

**Issue by eladh** [angular/angular.js#10792]
Hello.

Its seems like when invoking $eval([function call...] you use parse.js lib to retrieve and apply the relevant function from the scope.
if you cannot find the proper function in fnGetter() you returning angular.noop
in this case the apply don't return any value but don't throw any error.

take for example do the following (even if its not recommended) lets say : 
if registerPanelScope(this) cannot be found , for example someone forgot to bind it to the scope.
we will not get any error and its very hard to debug/find the reason way.

and generally speaking this behavior effects every usage of $eval ?

10x 
elad

```html

<dddiv ng-if="channelType==CONST.PANELS_STYLE.DEFAULT || !displayAccordion">
    <div ng-repeat="panel in panels track by $index" sticky-section-header>
        <div class="header" mobile-section-title>
            {{::panel.title}}
        </div>
        <div class="mobile-panel-wrapper">
                                <ng-include src="panel.url" ng-init="currentPanel = panel.panel; registerPanelScope(this)" class="wizard-panel" panel-id="{{::panel.panel.connItemID}}"></ng-include>
                </div>
    </div>
</div>
```

```javascript
functionCall: function(fnGetter, contextGetter) {
    var argsFn = [];
    if (this.peekToken().text !== ')') {
      do {
        argsFn.push(this.expression());
      } while (this.expect(','));
    }
    this.consume(')');

    var expressionText = this.text;
    // we can safely reuse the array across invocations
    var args = argsFn.length ? [] : null;

    return function $parseFunctionCall(scope, locals) {
      var context = contextGetter ? contextGetter(scope, locals) : isDefined(contextGetter) ? undefined : scope;
      var fn = fnGetter(scope, locals, context) || noop;

      if (args) {
        var i = argsFn.length;
        while (i--) {
          args[i] = ensureSafeObject(argsFn[i](scope, locals), expressionText);
        }
      }

      ensureSafeObject(context, expressionText);
      ensureSafeFunction(fn, expressionText);

      // IE doesn't have apply for some native functions
      var v = fn.apply
            ? fn.apply(context, args)
            : fn(args[0], args[1], args[2], args[3], args[4]);

      return ensureSafeObject(v, expressionText);
      };
  },

```

**Comment by pkozlowski-opensource** [comment]
@eladh this is kind of by design, since [AngularJS expressions are forgiving](https://docs.angularjs.org/guide/expression). I understand that it might problematic when debugging but if we change this all of the sudden expression like this: `user.getName().first` would start to break, if I'm not mistaken.

@lgalfaso and @jbdeboer know better this part of the code so can provide more meaningful input. I guess we _could try_ to distinguish between functions on a scope and functions on objects and throw for functions not defined on a scope. But even this would be a breaking change since people can use expression referencing functions that are only defined at the later stage.

Me feeling is that it won't get fixed, but let's hear from the ones more experienced in this area.

**Comment by eladh** [comment]
hi @pkozlowski-opensource  ,

$eval parsing behavior is implemented all over angular infrastructure.
i understand the flexibility behind  $parse "expression forgiving policy"  , but is getting more and more problematic in  a large scale application.

the basic thing here that if $parse returning angular.noop as a function , why we should move on as now error occur ? the user specified for a proper function and angular wasn't able to find it ...
 
for example - ng-click also use $parse and the same issue will be happens as mention above.

is there any way to add this as part of "Strict Mode" switch  ?


10x
elad.

**Comment by frfancha** [comment]
Typical html for angular is lot of expressions which will "work" only when some data got by $http is retrieved, including functions which will be defined according to the type of data received in various $http calls.
Therefore the current forgiving behavior must be left untouched.
Of course it doesn't make debugging very easy, and an option to output to log all expressions which had to be "forgiven" could be useful.

**Comment by pkozlowski-opensource** [comment]
@eladh I perfectly understand the pain of silently failing / debugging you are raising here. The problem is, though, that AngularJS expressions were forgiving from the very start (~5 years now) so we can't simply change it as it would be massive breaking change. This would have to be configurable, as a very minimum (or abstracted behind a strategy, as you are proposing).

Having said this forgiving expressions are _very_ handy in many cases (one is raised by @frfancha - this is very common). 

Anyway, let's hear what others have to say, especially people knowing better $parse impl

**Comment by lgalfaso** [comment]
making Angular not forgiving is not an option, the asynchronous nature of an SPA forbids this. Adding things to the log, would just pollute the log more than anything else

**Comment by eladh** [comment]
thanks.
