### ISSUE TITLE
ngResource: If parameter is a function, it is only executed once

### ISSUE THREAD

**Issue by ulilicht** [angular/angular.js#10803]
the Angular-Resource documentation says for parameters: 

> If any of the parameter value is a function, it will be executed every time when a param value needs to be obtained for a request (unless the param was overridden).

Unfortunately this does not work for me, the function is only called once when the resource is initialized. 

**I already asked a Stackoverflow question, got some upvotes and views but no answer - this is why I consider it as a Bug - or is it expected behaviour?**

I created a plunkr as an example. Open the Browsers Debug Console to see that `ApplicationState.getCurrentTime()` is only called once and not every time you click on the button. 

http://plnkr.co/edit/qeoIUuzFCqnQNdnYp5ZX?p=preview

Thanks for your help!

Some more information from Stackoverflow: 
My case: 
I have a global Application state which you can choose on the top navigation of the app. This state affects a query param in most calls. (e.g. the date for which the call is valid). I maintain this global state in a service. 

My Services (model layer) look like this: 

    function($resource, ApplicationState) {
          return $resource('test/:_id', {
            date: ApplicationState.getCurrentTime()
          }, {
            get: {
              method: 'GET'
            }
          });
        }

I'd expect `ApplicationState.getCurrentTime()` to be called on every get call. It is only called once. 

Here the link to the Stackoverflow post: http://stackoverflow.com/questions/27981308/use-dynamic-parameters-in-angular-resource

**Comment by caitp** [comment]
when you define an object literal, expressions are evaluated when the literal is materialized --- sooo, yeah this doesn't really work.

But, we don't have any code to walk through the enumerable object properties and evaluate functions, if the expression evaluated to a function, either. So that's kind of a feature request --- I suggest you go through the [process](https://docs.google.com/document/d/16UhnPdpYG4tvcFHKYCI9hMSCWwD7F0x3wzeCe4YHLKI/edit) and send an Intent-to-Implement email to the list, as described in the document. We'll use that to collect feedback on the idea and figure out how to best do it, or if it's worth doing at all.

[here's an example](https://groups.google.com/forum/#!topic/angular/i5by29Okh48) (still in progress).

**Comment by frfancha** [comment]
@ulilicht 
Yes it is as the doc says, parameters functions are called everytime.
Just provide the function, not the result of one execution of course...
This works in your plunker:
`.factory('TestService', ['$resource', 'ApplicationState',
    function($resource, ApplicationState) {
      return $resource('test/:_id', {date: ApplicationState.getCurrentTime}, {
        get: {
          method: 'GET'
        }
      });
    }`

**Comment by frfancha** [comment]
@caitp I understand the first 2 lines of your comment of course, but the next part not really...

**Comment by ulilicht** [comment]
@frfancha 

Thank you very much for your answer, this did the trick! 
It seems that a deeper understanding of JavaScript is the solution ;-) 

I will post this on stackoverflow as well.
