### ISSUE TITLE
Application Shutdown Event

### ISSUE THREAD

**Issue by ChrisLongo61** [angular/angular.js#10817]
I would be nice if angular had an application shutdown event.

**Comment by lgalfaso** [comment]
There is no real way to destroy an angular application, (well, at least until #8005 or any of the other PRs that aim at this lands), so I am not sure what this issue is aiming for. That said, whenever any of these lands, the way to detect this would be by just listening on `'$destroy'` event on `$rootScope`. I am closing this as making an angular app shutdown friendly is handled in other PRs and the event would be there once any of these lands
