### ISSUE TITLE
AngularJS 1.3.5 : Custom directive link function is not getting registered

### ISSUE THREAD

**Issue by corporatepiyush** [angular/angular.js#10825]
here is the link for detailed description and code snippet

http://stackoverflow.com/questions/28069368/angularjs-custom-directive-link-function-is-not-getting-registered

**Comment by frfancha** [comment]
First delete from your code everything you can delete while the problem still occurs.
When you have a minimal version showing the problem, I will have a look to help you.

**Comment by Narretz** [comment]
Your FooterLink and FooterText directives are inside of the footer directive, but the footer directive has a template, which means its contents are getting replaced with the template. That's why the directives are never called. Anway, this is a support question and we want to keep Github for bugs and features only. So please direct future questions towards Stackoverflow, the mailing list or the IRC
