### ISSUE TITLE
Error: [$parse:syntax] with number keys in associative array

### ISSUE THREAD

**Issue by hapali** [angular/angular.js#10906]
http://errors.angularjs.org/1.3.9/$parse/syntax?p0=.1234.&p1=is%20an%20unexpected%20token&p2=8&p3=myArray.1234.name&p4=.1234.name

Syntax Error: Token '.1234.' is an unexpected token at column 8 of the expression [myArray.1234.name] starting at [.1234.name].

```
app.directive("test", [function() {
    return {
        restrict: "E",
        template : "{{myArray.1234.name}}",
        controller : function($scope){
        	$scope.myArray = {};
        	$scope.myArray["1234"] = {};
        	$scope.myArray["1234"].name = "abc";
        }
    };
}]);

```

This works:
```
app.directive("test", [function() {
    return {
        restrict: "E",
        template : "{{myArray.key.name}}",
        controller : function($scope){
        	$scope.myArray = {};
        	$scope.myArray["key"] = {};
        	$scope.myArray["key"].name = "abc";
        }
    };
}]);
```

**Comment by pkozlowski-opensource** [comment]
It used to be possible to access array elements by a numeric index using the dot notation (ex. `myArray.1234.name`) but in 1.3.x it is no longer possible due to $parse refactoring. We don't want to revert this change as the current expression parsing rules are consistent with JavaScript ones.  You need to change your expressions and write them the same way as you write your JS, that is: `myArray[1234].name`.
