### ISSUE TITLE
ngAssignController directive to facilitate communication with child directive instances

### ISSUE THREAD

**Issue by matthewjh** [angular/angular.js#10924]
At present there is a mechanism for cross-directive communication: certain parent or sibling directives can be 'required' via a directive definition object's `require` property. This passes references to controllers of said directives' instances as arguments to the `link` function of the child/sibling directive.

This makes directive communication 'up' the DOM hierarchy easy enough, but there is no similar mechanism for communication with child directive controllers. E.g. Imagine a directive `myAccountPage` that has the following template, noting the inclusion of the `modal` directive:

```html
<h1>My Account</h1>
<modal title="More info needed">Please fill in your account information</modal>
```

The Angular docs state that by exposing methods on a directive controller, an API can be provided for other directives to use. However, in this example if the `modal` directive's controller exposes intuitive methods such as `open` and `close`, the `myAccountPage` directive cannot utilise them due to the lack of means for acquiring a reference to the modal directive controller instance. [1] This is counter-intuitive and seems adverse to any attempt to use directives to 'componentize' code. Instead a developer may resort to using `$scope.$broadcast` to communicate with child directives.

I feel that an `ngAssignController` directive would be a reasonable solution to this:

```html
<h1>My Account</h1>
<modal title="More info needed" ng-assign-controller="modalCtrl">Please fill in your account information</modal>
```

`ngAssignController` would assign the controller instance corresponding to the element-restricted directive on the element to the surrounding scope. In the above example, the modal directive controller instance would be available to the `myAccountPage` instance via `$scope.modalCtrl` (or `this.modalCtrl` if `controllerAs` is used), enabling the `myAccountPage` instance to communicate with the `modal` directive instance cleanly and directly.

Thoughts? I have an implementation of this that I have been using on my own project.

[1] Actually, a reference can be acquired by traversing the DOM in the `link` function and calling `element.controller`, but this is nasty for something that seems like it should be simple and common.

**Comment by petebacondarwin** [comment]
Hi @matthewjh - thanks for your idea.

This particular use case was much debated in the angular-ui bootstrap library. It was decided that in this case the best option is that the "modal" should not be a directive at all but a service. This service can then be injected into any directive or controller that wishes to use it and can trigger modal boxes to open or close etc. You can see the implementation here: http://angular-ui.github.io/bootstrap/#/modal

Now for the more general use case there are a couple of options.

* The first is similar to the above, which is to move the methods that could be called out into a service that acts as a kind of communication bus:  directives can register to provide a service or consume a service on this bus.
* The second is to create a "container" directive that acts as this communication bus, exposing a controller, which can be "required" by directives that would like to provide or consume a service.

There are troubles with the solution of attaching the controller to the surrounding scope:

* it could cause memory leaks if the child scope is destroyed but the parent scope is not
* it is brittle to someone placing a directive between the inner and outer scopes that creates a new scope - thus preventing the outer directive from accessing the "assigned to" property from the inner directive
* what happens if the consuming and providing directives are actually on cousin scopes that don't have a direct shared scope in which to communicate.

I hope that is enough information to be going on with. I am going to close this now as it is not a feature that we intend to include in core angular.js for the reasons above.  I might have missed something so if I have please do comment again (pinging me) or create a new issue to bring it to my attention.
