### ISSUE TITLE
Define directive "priority" via order directives are defined in.

### ISSUE THREAD

**Issue by lu4** [angular/angular.js#10931]
Hi everyone, although I've faced some resistance on stackoverflow while asking the same question (http://stackoverflow.com/questions/27884027/why-does-angular-define-priority-property-for-directives-that-are-defined-on-t) I still feel that this question should be raised also here. Using directive order as the order directives should be executed, instead of nailing-down-property `priority` seems nice. At least my use-case shows that having an ability to affect priority would be nice, what's your thoughts on this subject?

**Comment by matsko** [comment]
The priority value is mostly there to satisfy transclusion and terminal directives. This basically avoids the DOM for continuing to render itself before or past a certain directive has been evaluated.

I believe that for AngularDart we went the Dependency Injector route (where if directive injects the class that runs another then the injected directive would have a higher priority). This mostly solves the problem of priority for future version. There may be a more sophisticated approach for 2.0 planned as well.

As for 1.3 and 1.4 it we can't really change things around since there is such a high dependency for this to work (for example priority ensures that ngRepeat runs a directive before it is cloned vs running it on all the cloned elements).

Things may get better over future releases. I just wanted you to have a better idea as to why priority is a necessary solution for the time being.

**Comment by lgalfaso** [comment]
It is not possible to use the order the directives are defined as the attributes in an elements have no order
