### ISSUE TITLE
Angular JS + JQuery UI Button for ng-if, ng-show, etc.

### ISSUE THREAD

**Issue by goodseller** [angular/angular.js#10933]
Race condition happened as adding the ng-hide class.

Angular JS will make the button hide with ng-hide class.
Then, JQuery UI will add a ui-state-focus with all its class to the button as the button being clicked and override the ng-hide.

As a result, The button is still there.

Is there any way to handle this? Thanks.

**Comment by VitalyTomilov** [comment]
AngularJS isn't compatible with jQuery UI. That's why all UI frameworks are rewritten with Angular.

The front-runners are: http://angularjs4u.com/frameworks/5-top-angularjs-ui-frameworks/

I personally use Angular + Bootstrap: http://angular-ui.github.io/bootstrap/

There are many other libraries that provide a subset of functionality, like Angular Bootstrap Dialogs: http://codepen.io/m-e-conroy/pen/ALsdF

**Comment by petebacondarwin** [comment]
@goodseller - I am afraid that @VitalyTomilov is correct here.
The best thing you can do is to wrap the buttons/inputs where you are using jQueryUI in a `<div>` and put the angular directives on those instead:

```js
<div ng-hide="xxx">
  <button id="jqui-button">...</button>
</div>
```

Closing as this is not something we are going to be able to support.
