### ISSUE TITLE
$interval

### ISSUE THREAD

**Issue by daniel1985** [angular/angular.js#10930]
The version of 1.2.28 works fine but the 1.3.X version doesn't work in this code

```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
</head>
<body ng-app>
	<div ng-controller='ClockController'>
		<h2>{{time}}</h2>
	</div>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.28/angular.min.js"></script>
	<script>
		function ClockController($scope, $interval){
			var getTime = function(){
				$scope.time = new Date();
			};
			$interval(getTime, 1);
		}
	</script>
</body>
</html>
```

**Comment by daniel1985** [comment]
The code does work fine in version 1.2.28, but in 1.3.X version it does not work.

Can anyone tell me how i can fix this problem?

**Comment by caitp** [comment]
your issue is that in 1.3, by default, you can't use global functions as controllers (see https://github.com/angular/angular.js/commit/3f2232b5a181512fac23775b1df4a6ebda67d018#diff-39f7f76ebd18c5a040b9413a98410197). To work around this, you can enable global controllers via a config method (you would not be able to use an anonymous app to do this), eg http://plnkr.co/edit/KjNgzwJplP0n3xP3WMkp?p=preview --- alternatively, you can explicitly define the controller, like this: http://plnkr.co/edit/s6srm7DE3na3ly2Y9Haa?p=preview
