### ISSUE TITLE
debugInfoEnabled breaking dragNdrop functionality

### ISSUE THREAD

**Issue by Pickra** [angular/angular.js#10938]
We were using [btf-dragon](https://github.com/btford/angular-dragon-drop) for dragNdrop functionality. Upgrading to 1.3  and adding...
```
.config(($compileProvider) ->
  $compileProvider.debugInfoEnabled debugInfoEnabled
)
```
... to our app,  killed the dragon. We are now using [Sortable](https://github.com/RubaXa/Sortable), but the problem remains. Disabling debugInfo stops reporting on DOM elements, but dragNdrop functionality depends on reporting from DOM elements.

If it helps, my colleague has a more specific use case [issue](https://github.com/RubaXa/Sortable/issues/255).
I was hoping you might have some thoughts.

Thanks

**Comment by Narretz** [comment]
This is probably because `debugInfoEnabled = false` does not attach the scope to elements, and that means also the functions `scope()` and `isolateScope()` do not work anymore. This is imo a wontfix - either btf-dragon needs to be rewritten to not rely on scope attachments or you cannot disable debugInfo

**Comment by lgalfaso** [comment]
This is a wontfix. There are two options, keep the debug info or ask the btf-dragon owner not to use `element.scope()` and `element.isolatedScope()`
