### ISSUE TITLE
forms and ng-forms under ng-if directives do not get named field on $scope.

### ISSUE THREAD

**Issue by RobiFerentz** [angular/angular.js#10944]
Not sure if this is intentional or not, but I have plenty of use cases where I need to create an entire form dynamically including the surrounding form or ng-form element/directive. 
When I use ng-hide/ng-show, the $scope gets the usual 'nameoftheform' property on it.
That is however not the case when using ng-if. 
In some cases, I MUST use ng-if so that the form (usually a nested ng-form) needs to be removed from the validation when it's not in view.

**Comment by Narretz** [comment]
This is because `ng-if` creates a new child scope, and if your form is simple like `myForm`, then this will not be set on the parent scope (because of prototypical inheritance). A workaround for this is to handle form names like ng-models - always make them object properties, like `obj.myForm`, where `obj` is defined on your controller. This works because angular handles form names not as names, but rather as paths / expressions.
But I agree that this is unintuitive. I'd prefer `ng-if` to not create a child scope, but I don't know if this is possible.

**Comment by lgalfaso** [comment]
The link is slightly out-of-date, but will help you understand scopes and why this is not an issue
https://github.com/angular/angular.js/wiki/Understanding-Scopes
