### ISSUE TITLE
Is there a performance issue with $asyncValidators vs $validators?

### ISSUE THREAD

**Issue by kentcdodds** [angular/angular.js#10955]
Just a question here. I've written an abstraction on top of the $validators pipeline and right now users have to specify whether their function is async or not. I'm just wondering if there would be a problem with simply wrapping them all in `$q.when` and putting them in the `$asyncValidators` pipeline.

**Comment by matsko** [comment]
The main reason for the split was that async validations are typically on a higher level than regular validations. This means that if a regular validation fails (like minlength or pattern or required) then there is no reason to issue an async validation since the data that would normally go into the async validation is incomplete. If this were to have been implemented in a different way where both validations were combined then we would end up having a messy, object-based approach with ordering and dependencies.

**Comment by kentcdodds** [comment]
Ah, that makes sense. Thank you for the answer :-D
