### ISSUE TITLE
Angular fails to instantiate module ngLocale in tests after upgrade to 1.3.12 

### ISSUE THREAD

**Issue by nadavsinai** [angular/angular.js#10967]
In our CI the tests failed, I tried to reproduce locally and could not until I removed our bower libs and reinstalled. (we were asking for ~1.3).
I played with bower.json angular versions and found that 1.3.11 works and 1.3.12 fails.

the code that breaks our app is found in commit 6ec5946094ee92b820bbacc886fa2367715e60b4

line 2138 in angular-mocks.js

     Error: [$injector:modulerr] Failed to instantiate module ng due to:
      Error: [$injector:modulerr] Failed to instantiate module ngLocale due to:
      TypeError: 'undefined' is not an object (evaluating 'annotatedFunctions.push')
      at /Volumes/OSxData/websites/startapp/portal/public/lib/angular-mocks/angular-mocks.js:2145
      at invoke (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4163)
      at instantiate (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4193)
      at provider (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4028)
      at /Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4020
      at runInvokeQueue (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4091)
      at /Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4099
      at forEach (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:323)
      at loadModules (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4123)
      at /Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4098
      at forEach (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:323)
      at loadModules (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4123)
      at createInjector (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4007)
      at /Volumes/OSxData/websites/startapp/portal/public/lib/sinon-ng/sinon-ng.js:4
      at /Volumes/OSxData/websites/startapp/portal/public/lib/sinon-ng/sinon-ng.js:30

this occurs in angular-mocks therefore relevant only in testing environment

**Reproducable**: always
**Browsers** : Chrome 40, Phantom JS
**Operating system**: OSX 10.10, Ubuntu 14, Fedora 20

**Comment by kuoloneous** [comment]
Also having the same issue.

**Comment by kodypeterson** [comment]
+1 Also seeing the same...

**Comment by donniewa** [comment]
+1

**Comment by ricardocasares** [comment]
+1

**Comment by brianwider** [comment]
+1 here

**Comment by lgalfaso** [comment]
@petebacondarwin would like to revert the commit that caused this regression until we have a better solution. WDYT?

**Comment by petebacondarwin** [comment]
Let's see if we can't fix this but revert before the next release if no joy

**Comment by shahata** [comment]
This seems to be the same issue that @jeffbcross mentioned for an internal test that failed for him. The fix is easy (initialize the variable to an empty array instead of undefined), but I would like to understand first why this happens and see if I can add a test to protect against this. Taking a deeper look.

**Comment by lgalfaso** [comment]
Thanks @shahata !

**Comment by shahata** [comment]
If anyone can post a reproduce it will be very helpful...

**Comment by shahata** [comment]
OK, the reason for this as I suspected before is that someone is creating an injector before the first `beforeEach` in the case of @nadavsinai you can see that the source is sinon-ng which creates an injector immediately on page load in order to get a hold on `$q` and `$timeout` (which sounds like a bad idea to me, but never mind that - see https://github.com/boneskull/sinon-ng/blob/master/sinon-ng.js). Anyway, I'll post a simple PR that fixes this but I'm not sure if I want to add a test for this and do something similar in our test suite. @lgalfaso @petebacondarwin - thoughts?

**Comment by lgalfaso** [comment]
@shahata I think we should add a test to ng-mock to be sure that we do not break this in the future

**Comment by kuoloneous** [comment]
Thanks for getting on this so quickly.  In our case, our source was https://github.com/cabrel/angular-lodash which was causing the issue.

**Comment by shahata** [comment]
Test added. Though I'm not proud of it :)
