### ISSUE TITLE
input type time set Date issue

### ISSUE THREAD

**Issue by ilanbiala** [angular/angular.js#10986]
I have some HTML like this:
```
<input type="time" placeholder="Submission time" required="required" ng-model="newSchedule.submissionTime">
```

When I set `$scope.newSchedule.submissionTime = 9;` to set it to 9:00 AM, I get an error saying that ngModel expects a `Date` object. In a way this makes sense, but it means that I have to manually set the one field and reset all the others from a `new Date()` because I need to work off of a `Date` object. Has this been looked at before?

**Comment by smallg** [comment]
I think you must use date type to init value, like this:
```
$scope.time= new Date(2000, 8, 10, 9,0,0);
```

**Comment by Narretz** [comment]
> I have to manually set the one field and reset all the others from a new Date() because I need to work off of a Date object

Can you clarify what that means?

**Comment by ilanbiala** [comment]
I manually `.setHours(9)`, and then have to set all the others to 0.

**Comment by Narretz** [comment]
@ilanbiala I agree with @smallg, can't you just do `$scope.time= new Date(0, 0, 0, 9,0,0);`? If you're only interested in the time / hours, the other fields shouldn't matter at all, right?

**Comment by Narretz** [comment]
Please feel free reopen this issue if the technique in my previous comment does not fix your problem.

**Comment by ilanbiala** [comment]
@Narretz that fixes the problem, but it seems very inelegant..

**Comment by Narretz** [comment]
There's currently a requirement for `input[date]` to be a Date object. This is because the user input is parsed into a date object. That means your scope variable would end up a Date object anyway - we want to keep that consistent. Maybe we'll introduce automatic conversion in the future, but at the moment this is not gonna change. Personally, I also think a Date object is much clearer in your case than a simple Number.
