### ISSUE TITLE
ngClick issue in IE11

### ISSUE THREAD

**Issue by ajayparsana** [angular/angular.js#10980]
Hi,

We have written customised checkbox which has divs for square and label.

Issue:Checkbox div has ng-click which should only be fired when clicked on square box but it also get fired if I click on Text next to it in IE11 Version 11.0.9600.16428.

Our implementation is working fine in Chrome and Mozilla but gives above issue when executed in IE11.

Sample Code link: (Please run this code in Chrome & IE11)
http://jsbin.com/luzogucasi/5/edit?html,js,output

**Comment by pankajparkar** [comment]
That is only expected behavior, because you used for="k". The for attribute will target the id="k", and whenever you clicked on label it will also fire click event element with id="k"

http://jsbin.com/gikixehazi/1/edit?html,js,output

Remove attribute for="k" will work proper on any browser.

Also take look at.
http://stackoverflow.com/questions/28346733/unwanted-ngclick-gets-fired-in-ie11-browser/28353741#28353741

**Comment by ajayparsana** [comment]
Thanks Pankaj.
