### ISSUE TITLE
$http.notify shortcut method

### ISSUE THREAD

**Issue by mallowigi** [angular/angular.js#11020]
Hi, 

I wonder if it is possible to add a shorthand method `notify` to the `$http` service to trigger notify callbacks? It would be better than doing:

```js
var interval = $interval(myFunction, 10000);

// Before
interval.then(null, null, (data) => console.log(data););

// After
interval.notify(data => console.log(data););
```

**Comment by Narretz** [comment]
I don't get it tbh. What exactly do you want to do? I don't see any $http in your example, I only see $interval.

**Comment by mallowigi** [comment]
Sorry, my bad. I meant something like `.catch` in thenables, but only for the sake of the `notify` operation.

Examples:
```js
$http.notify(function onNotify () { ... }) // instead of $http.then(onSuccess, onFailure, onNotify)
```

**Comment by Narretz** [comment]
This could possibly be very confusing, as notify might be misunderstood as the xhr progress event.

**Comment by pkozlowski-opensource** [comment]
Nope, sorry, it won't happen. Progress notifications as part of promises turned out to be a bad idea. On top of this it seems like the convenience methods (`success` / `error`) are often confused with promises (ex.: #10508) so we don't want to go down this path.

Thnx for the suggestion @mallowigi but we will pass on this one...
