### ISSUE TITLE
Directive isolated scope bindings don't work with scope inhertiance

### ISSUE THREAD

**Issue by mbonacci** [angular/angular.js#11048]
Let's say I have isolated scope two-way binding (eg. scope: {name: '='}), and I use the directive normally (<test-directive name="name"/>). If I change the attribute on directive's isolated scope, the parent scope's attribute is updated.
Bit if there is a child scope in between (which prototipcally inherits from parent scope), like in the case of ng-include directive, then change in directive's scope will not be applied to parent scope. It seems like the attribute is created on directive's scope and becomes unboud from parent attribute.
I have created a plunker to demonstrate this:
http://plnkr.co/edit/vXllzReJMFr0mEim5HzU?p=preview
If you click first button, the change is reflected in both directive's scope.
If you click the seconf button, the change is reflected in parent scope in the other directive.
But if you click the third button, the change is not reflected anywhere, and from now on, clicking other buttons has not effect on this directive instance.

**Comment by Narretz** [comment]
I think that's a "normal" effect of scope inheritance. Like you said, ngInclude creates a new child scope. Since your property is a primitive (string), setting it on a prototypically inherited child scope, will only set it on this child scope, not on the parent scope.
The recommended approach for this is to always use objects for two-way binding, e.g. in your case instead of `name: '=?name'` use `data: '=?data'` and write `name` to this object, see http://plnkr.co/edit/LY0EUoiBhymGkskzaOoF?p=preview

Here's a good explanation: http://stackoverflow.com/questions/14049480/what-are-the-nuances-of-scope-prototypal-prototypical-inheritance-in-angularjs

**Comment by mbonacci** [comment]
Indeed, after reading about JS prototype inheritance, I see what the problem is. But still, this behaviour is very confusing, escpecially if you are authoring reusable components as directives. You have no way  to force the user of the component to use objects and not primitives, you can only hope he/she understands the nuances of JS inheritance. 
I'm wondering isn't there a way to circumvent this shortcoming in Angular itself, e.g. detect primitives during isolated scope binding and create a property on isolated scope that shadows parent property, but set-up a watch on parent and child properties to do the value transfer.
