### ISSUE TITLE
ngVisible

### ISSUE THREAD

**Issue by VitalyTomilov** [angular/angular.js#11115]
Guys, please add ngVisible to 1.3. This is probably the most generic directive still not implemented, even though it is needed in just about every project. And it is 100% core functionality.

Something along these lines, I believe:
````
.directive('ngVisible', function () {
    return function (scope, element, attr) {
        scope.$watch(attr.ngVisible, function (visible) {
            element.css('visibility', visible ? 'visible' : 'hidden');
        });
    };
})
````

**Comment by Narretz** [comment]
Compelling arguments, although personaly, I hardly ever use`visible: hidden`.

**Comment by gkalpak** [comment]
I can't recall ever using `visibility: <anything>`...

**Comment by VitalyTomilov** [comment]
CSS visibility is the key property for maintaining reserved space for invisible objects. There is no substitute in Angular for that, or at least one that would work as reliably as the basic CSS.

From my code example:
````
<p ng-visible="initialized">
       grid summary clause
</p>
<div>
    fixed-size grid
</div>
````
If I do not use ng-visible, then my data grid will jump after initialization, which looks bad. I want to reserve space in the simplest possible way, which is how I do it in my example, coherent with the standard CSS approach.

I do not want to do an Angular work-around for such a basic CSS feature, so I always end up extending my code with ng-visible as shown in my first post.

**Comment by meanJim** [comment]
Front end developers use `visibility` very frequently. I totally agree with @VitalyTomilov here, and would add that designers and interaction designers **don't** want to see their interfaces jump around all over the place. Visibility helps claim visual space for a DOM element to prevent that jumping.

Have a look here at a mockup of **1** of **~40** modals we built with varying heights:

![screen shot 2015-02-20 at 9 51 22 am](https://cloud.githubusercontent.com/assets/310223/6306175/0dbf4450-b8e6-11e4-8ba8-cfff2debe91a.png)

* **The Goal:** Have text appear after some delay inside of this modal without using a fixed height. A fixed height is unacceptable.
* Using `display:none` -> `display:block` forces the modal to adjust to the contents of the modal container element. Will cause a jump. Can make the jump look nice if I want.
* Using `visibility: hidden` -> `visibility: visible` we avoid this problem all together.

Also some CSS transitions with `opacity` declared as `transition: opacity 300ms ease;` do not work with the use of `display: none;` and `display: block;` anyways. I am aware of `ngAnimate` and other work arounds, but having something we always extend built in would be nice.

**Comment by VitalyTomilov** [comment]
@meanJim - thank you!

And I would argue with it set set to "frequency:low", it is a high frequency feature, I dunno how and why it was skipped in the first place, being such a fundamental CSS feature.

**Comment by andrewdc** [comment]
Here here, guys. Both forms of show and hide (display/visibility) are very critical for front end interactivity. Having this feature out of the box would be extremely beneficial. 

+1

**Comment by Narretz** [comment]
Thinking about this some more, this seems like the wrong approach to fix your issues. `ngShow` and `ngHide` simply default to `display: none` but the docs tell you how to override the styles of `ng-hide`. If you add separate classes for visibility / display to your show|hide elements, this should solve your problems.

**Comment by VitalyTomilov** [comment]
@Narretz: show/hide are the properties of "display" css attribute, while "visible" is the property of css "visibility" attribute, with very different result. Trying to mix the two would create the logic against the css standard, which is ill-advised for Angular that's supposed to adhere to the css standard, without reversing or completely altering things.

**Comment by richcsmith** [comment]
@Narretz Overrides add an unnecessary layer of cognitive overhead to your code. An ngVisible directive would be much more explicit and it would make a lot more semantic sense, especially since, as @VitalyTomilov just pointed out, the two properties shouldn't be thought of in an interchangeable way.

**Comment by Narretz** [comment]
I have to disagree. `ngShow` simply toggles between showing and hiding an element and provides the option to customize the way showing and hiding is implemented. Just because `display` is the default, it does not mean that `ngShow` is a display directive. There's also no link between `ngShow` and the values of the display property, in fact all the terms are different.

@richcsmith The advantage of using ngShow with a custom css selector is that it doesn't interfere with your code at all. In your code you only have the semantics of show / hide, while you are free to implement it with CSS as you want.

**Comment by VitalyTomilov** [comment]
@Narretz, i hate to be blunt, but any argument you have against only suggests it comes from someone who spends most of his time developing UI frameworks as opposed to developing end-user UI-s using those frameworks. You need to dive into the latter on the day-to-day basis to see the obvious need for such a directive. And what what you are suggesting will create nothing but confusion for people who know css and are trying to get into Angular.

**Comment by LeonardoBraga** [comment]
I would suggest not to change the CSS classes for ngShow/ngHide because `visibility` causes the browser to compute the dimensions of the DOM elements (and its children) skipping just the paint step, while `display: none` causes the element (and its children) to be entirely skipped from the render tree. Making ngShow/ngHide classes to be based on `visibility` will impact the performance and will change the presentation as can be seen here http://jsfiddle.net/xbtnay5x/ - so sing `visibility: hidden` instead of `display: none` will have many side effects for ngShow/ngHide.

Having said that, I'm against creating a directive for it, since you can easily achieve the desired result with a class like `.invisible { visbility: hidden }` and combining it with `ngClass` like `ng-class="{ invisible: yourFlag }"`.

**Comment by pkozlowski-opensource** [comment]
@VitalyTomilov please refrain from personal comments, especially if you don't know a person you are talking too and trying to imply things about this person. This is violating our code of conduct: https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md

Guys, we are talking about 5 lines of code here, I'm sure we can keep the discussion focused on the technical matters.

**Comment by VitalyTomilov** [comment]
@LeonardoBraga, it is important to keep in mind, this is a convenience feature, not an absolute necessity.

**Comment by LeonardoBraga** [comment]
@VitalyTomilov for sure, I understand your point. From my personal experience, this kind of feature isn't required as frequent to justify adding another directive to the core and having the extra burden of maintaining it, adding more dynamic CSS classes to support it, and increasing the core size. Also, I think that this can set a dangerous precedence where more people might want to add other convenience CSS-related features like ngFloatLeft and ngClearBoth. -1

**Comment by Narretz** [comment]
@LeonardoBraga Excellent suggestion using ngClass. Although I was suggesting something similar using ng-hide:

`
<div ng-hide="myExp" class="invisible"></div>
`
CSS:
`
.ng-hide:not(.ng-hide-animate).invisible {
  visibility: hidden;
}
`

**Comment by VitalyTomilov** [comment]
@LeonardoBraga, I don't think that visibility features that Angular is trying to cover comprehensively are comparable to layouts or or alignments that are not within the scope at all.

**Comment by Narretz** [comment]
@VitalyTomilov Thanks - I appreciate that. I know it's easy to assume every contributor is just working on the framework, but I actually develop applications with it completely independently.

**Comment by matsko** [comment]
Why not just fully defer `ng-visible` to `ng-show` (just make another directive that uses the same internal code). And then set the following CSS code inside of `css/angular.css`:

```css
/* make sure to have `ngVisible` just add the extra CSS class */
.ng-visible.ng-hide:not(.ng-hide-animate) {
  visibility: hidden;
}
```

**Comment by VitalyTomilov** [comment]
People are asking you to finalize Angular's full control over visibility according to CSS, because ngVisible is just the last thing missing, and you guys keep coming at us with suggestions for workarounds. Nobody needs more workarounds here, we already can just continue using the directive as one in the first post.

**Comment by biiiipy** [comment]
Well then, we might as well add directives for all css properties into ng core, just because! ngFontSize, ngTextDecoration etc... /s
Seriously, ng core doesn't need to include everything & kitchen sink. ngVisible just isn't crucial to add it to the core. As you've demonstrated, it is trivial to create directive that does that for you.

**Comment by VitalyTomilov** [comment]
@biiiipy, blithe trolling is what this is. I'm not republishing any of the above arguments, because clearly, you don't care.

**Comment by petebacondarwin** [comment]
@biiiipy - please refrain from personal remarks.

@VitalyTomilov - Thank you for this suggestion. It is difficult to make decisions on features like this.

From a purely architectural point of view, I would generally steer away from setting styles directly on elements. Instead, I would use CSS classes to declare my semantic intention, freeing the designer to choose how this should be interpreted visually. In that case, I would be more likely to use `ngClass` in this situation. Apart from anything else, it also provides much better support for hooking into `ngAnimate`. But for now let's accept that `ngVisible` is a valid use case.

As providers of a framework that is used in many different and differing projects, we must trade off usefulness of features against the impact they have on the code base - both in terms of speed and size.

As we add new features, and often when we fix bugs, the code size keeps increasing. This is a problem if many of those features are not used in the majority of projects. In fact, we have been thinking hard recently about how we can actually slim down the core angular.js file by moving the less used things, such as some of the filters, into separate modules/files.

Given that you are the first person in a number of years of Angular to request this feature it is reasonable to accept that it is not a high frequency feature, although clearly there are at least four developers who have expressed a positive opinion about this.

AngularJS is first and foremost a framework, which can be customised by the application developer to fit their needs, via directives. We do not need to talk about workarounds with `ng-show` and `ng-class` for this feature. As you demonstrated very clearly in your first post, there is an idiomatic AngularJS solution, which is to implement a simple directive to support your use case.

If you look around the AngularJS eco-system you will see literally hundreds of such directives that people have developed and even shared with the rest of the community. This is how AngularJS ought to be used rather than being a huge monolithic library with hundreds of features, of which many are rarely used.

This is not a feature that are going to add to the core angular.js library. It is a simple directive to add to your own projects as needed, if that is useful to you. If you would like to help other developers who might also find this directive useful then I recommend that you package it up and publish it via bower and on websites such as http://ngmodules.org/.

I'm going to close this issue, but we can revisit the concept when we start planning for Angular 1.5. It may be that we can provide a new module that contains various small directives such as this in a way that doesn't impact on the core code size.

**Comment by VitalyTomilov** [comment]
@petebacondarwin,

Angular has a number of modules, but they are all specific. This feature then would fit into a notion of Utils, if it doesn't fit into the Core. If you schedule it for 1.5 instead of just closing, then maybe it will make it into the core eventually.

**Comment by pkozlowski-opensource** [comment]
@VitalyTomilov What @petebacondarwin was saying in regard to 1.5 is that we are going to solicit community feedback on what should go into 1.5 (more announcements to come during `ng-conf` but essentially all the release planning will be happening in public and the community will be deciding on what should go into the next release). So if you deeply care about this going into the core make your friends, family, pets (or whoever else you can get) vote on this issue!

**Comment by glepretre** [comment]
Hi all,

We ran today into the "jump" issue well described by @meanJim :disappointed: 

I might have missed some discussion elsewhere but I do not understand why the community chose `display: none!important` as behavior for `ngHide`? 
Isn't this (at least partially) covered by the `ngIf` directive?

Trying to think about the different use cases:
* You don't want the element to be into the DOM at all when this or that... --> `ngIf`
* You want the element to be into the DOM but hidden, sparing browser paint reflow --> current `ngHide`
* You want the element to be into the DOM but simply hidden --> `visibility: hidden`?

@petebacondarwin I deeply understand your caution before adding more and more new features into the core. And I think all of us developing long-term-support apps know the cost of maintainability inherited by code legacy. 

What I'm saying is that this request does not look completely illegitimate to me.

Waiting for the necessary debate and reflection upon this, we are going to use `ngClass` to handle that, as suggested by @LeonardoBraga :wink:. 
Solution that I find cleaner than overriding `.ng-hide` CSS rule as suggested into the docs :confused:

@pkozlowski-opensource Where will we vote for 1.5 issues/features? Here on GitHub?

**Comment by vitaly-t** [comment]
@glepretre, I'm out of arguments for this feature since I first asked for it, so it will take a good few up-votes to move this unmovable object :)

In the meantime, I find use of the directive (in the initial post) the cleanest and simplest approach ;)

+1

**Comment by LeonardoBraga** [comment]
@glepretre I'm happy you were able to workaround it using `ngClass`, which I also find way cleaner than touching `.ng-hide`, and less susceptible to unknown side effects.

I believe the main issue here is the misconception that `ngIf` and `ngShow` are *always* interchangeable, which unfortunately isn't the case. The first destroys the DOM element when the expression evaluates as `falsy`, and the latter just cases the browser to [skip the element when processing the render tree](http://www.html5rocks.com/en/tutorials/internals/howbrowserswork/) under the same conditions. Depending on your UI, you can positively impact performance by using one or another. Let's say you have a huge and complex block of elements that is only shown occasionally. In this case, you probably will have better performance by controlling it with `ngIf`, since it will remove the heavy DOM from the page when it's not required. Conversely, if you have many small elements that you need to show or hide individually and frequently, you'll probably have better performance using `ngShow`, since the browser won't need to reconstruct the DOM every time the element is displayed.

**Comment by gkalpak** [comment]
i somehow feel many people on this thread didn't pay [@matsko's comment][1] the attention it deserves :)
It is a really "refined" and elegant solution (and very much in the Angular spirit imo). 

[1]: https://github.com/angular/angular.js/issues/11115#issuecomment-75313906
