### ISSUE TITLE
feat(ngModel): add public $setModelValue fn to programmatically update model

### ISSUE THREAD

**Issue by tdakhla** [angular/angular.js#11128]
In regards to my workaround in https://github.com/angular/angular.js/issues/11090#issuecomment-74799429, it would be nice to have a `$setModelValue` fn in `NgModelController` which would programmatically update the model.  Instead of having to inject in `$parse` to my directive, do `$parse(attrs.ngModel).assign(scope, newValue)`, etc, (I've seen code like this in several places, and I've used it a lot in my directives), there should be a public fn to do that work.

The code in NgModelController should be as easy as:

``` js
this.$setModelValue = function(value) {
    ngModelSet($scope, value);
};
```

Or, if all the `$viewChangeListeners` need to get executed, then perhaps open up `this.$$writeModelToScope` by changing it so it accepts a model value param, and rename it to `this.$setModelValue` (and doing the handful of refactors).  I think having `$setModelValue` would be a nice addition to the ngModel API.

**Comment by Narretz** [comment]
Customizing when  / how the model is set to scope is definitely planned. Btw, `$setModelValue` is a bit confusing as there's also the `$modelValue` property on ngModel, and I would expect that this is set from this function.

**Comment by realityking** [comment]
I've got an implementation in #10764, I just haven't had time to adress the last comment.

**Comment by maraisr** [comment]
+1

**Comment by Narretz** [comment]
Setting the scope model from inside the ngModel controller so that it runs the model > view pipeline again is not good practice. There might be edge cases where it is necessary, but I'd rather have devs use parse and assign in this case, then expose a function on the ngModelController that does it.
For the simple case where you need to re-run the formatters on the modelValue, there will be a function in 1.6.7: https://github.com/angular/angular.js/commit/14519488ce9218aa891d34e89fc3271fd4ed0f04
