### ISSUE TITLE
i18n - Finnish localization "fulldate" issue

### ISSUE THREAD

**Issue by branimirborisov** [angular/angular.js#11148]
Hi,
I noticed that in i18n localizations for Finnish in both files
angular-locale_fi.js
angular-locale_fi-fi.js 
the value for the day in "fullDate" is actually using the "cccc" format instead of "EEEE".

On both files line 74:
```javascript
    "fullDate": "cccc d. MMMM y",
```

In all the rest locale files "fullDate" uses "EEEE" format, so basically it does now work only for Finnish.

**Comment by matsko** [comment]
OK minä tarkistan.

**Comment by Sangeethakdass** [comment]
We use AngularJS version 1.2.24.4. When can we expect the fix to be available?

**Comment by rantani** [comment]
We use Angular version 1.3.15 and have this issue. Any update on this?

**Comment by jbnicolai** [comment]
Created a PR to google/closure-library#531.

After this is merged I believe the angular locale files can be updated by running

1. `i18n/update-closure.sh`
2. `i18n/generate.sh`

and committing the chances.

I'm having some issues with the PR to the closure library however, the Travis-CI tests see to fail due to I suspect unrelated changes. If someone could shed some light on this I'd appreciate it.

**Comment by Narretz** [comment]
As noted in the linked PR the data must be updated in the original source.

**Comment by Anirban1989** [comment]
Hi, for fulldate  I am still getting "cccc 26. lokakuuta 2018 18.20.35" for Finnish locale.  For other languages its working fine i.e i am getting Friday. Can anybody help.
