### ISSUE TITLE
Form !$valid and $invalid disagree on async validations.

### ISSUE THREAD

**Issue by Cayan** [angular/angular.js#11167]
I'm using ng-disable with form's submit button and some inputs are validated using $asyncValidators.

When I use:
* 'ng-disabled' => 'form.$invalid'
the button is always disabled while the form is invalid.

* 'ng-disabled' => '!form.$valid'
the button is disabled while the form is invalid and while $q.defer() waits to resolve or reject.

**Comment by gkalpak** [comment]
What would be the expected behaviour ? While the form is in `pending` state (i.e. waiting for `asyncValidators`) it is neither valid nor invalid.

**Comment by Cayan** [comment]
@gkalpak You got a point, the pending state should be handled by the app in it's own way.

But the question here is regarding @valid and @invalid logic, they are expected to be opposite to each other and it seems like they are not, which is confusing.

Note: a couple of hours after this post, they have switched behaviors, now $invalid presents the pending state and @valid has only a true/false state.

**Comment by gkalpak** [comment]
@Cayan, I don't know what version of Angular you are using, but I don't see any difference between `1.4.0-beta.4` and `1.4.0-beta.5` (released a few hours ago).

Basically, this is what happens:

* While there is an async validation "pending":
  - `$valid/$invalid: undefined`
  - `$pending: [object]`
* While there is no async validation "pending" (either because skipped or resolved):
  - `$valid/$invalid: true/false | false/true` (based on validation result)
  - `$pending: undefined`

Here is [a fiddle][1], illustrating the above.

[1]: http://jsfiddle.net/ExpertSystem/yofk7u0L/2/

**Comment by Cayan** [comment]
1.3.14, I'll check it later today.

**Comment by Cayan** [comment]
It worked, sorry to bother you.
I didn't know about the pending state and those undefined.
