### ISSUE TITLE
Error on using nb-bind-html

### ISSUE THREAD

**Issue by cmschulz** [angular/angular.js#11178]
in the actual stable Version (1.3.14), function "$$addBindingInfo" there is the following code:
if (isArray(binding)) {
    bindings = bindings.concat(binding);
} else {
    bindings.push(binding);
}
The question to "if (isArray(..) ..." must be changed to "if (!isArray(...) ..."
You can use array.push only when it´s an Array :)

**Comment by Narretz** [comment]
Can you show an example where this causes an error?

**Comment by cmschulz** [comment]
The error occurs when I use ng-html-binding like <p ng-html-binding="someHTML"></p>.
"someHTML" is a vaiable within my scope.
The code says "use the push method of an array if it´s not an array"

**Comment by Narretz** [comment]
Can you please post an example in a plnkr.co or similar?

**Comment by gkalpak** [comment]
@cmschulz, I think you misread this. It's `binding` that is checked, not `bindings` (note trailing `s`). `bindings` is supposed to always be an array.

If you facing a problem, it is not associated with this code fragment, so posting a live reproduction (using JSFidfle, Plnkr or similar) will help investigate further (as @Narretz already mentioned :smiley:)).

**Comment by cmschulz** [comment]
@gkalpak, you are right, the check is done on `<binding>` but, therefore my first suggestion is wrong, but in my case `<var bindings = $element.data('$binding') || [];>` returns a string (line 6866 in Version 1.3.14 on angular.js, not an array.
I tried to reproduce the problem within a simple example on plnkr, but there everything worked fine.

**Comment by gkalpak** [comment]
@cmschulz, unless you (or some third-party module you are using) are setting `$element.data('$binding')` to something that is not an array, I can't see how a string can be returned.
Angular always sets it to an array and it is even (indirectly) [documented][1].

Since this is not reproducible in a plnkr, I presume it is something that has to do with your setup.

[1]: https://docs.angularjs.org/api/ng/provider/$compileProvider#debugInfoEnabled

**Comment by Narretz** [comment]
Feel free tio reopen the issue if you can provide an reduction. Thanks!
