### ISSUE TITLE
Inconsistent linkFn/$destroy behavior angular 1.3.x

### ISSUE THREAD

**Issue by djabor** [angular/angular.js#11181]
There is an issue with the predictability of a directive's link/destroy cycle in certain cases.

when i use ng-if (or any other destructive switching mechanism) to flip between 2 html snippets
containing the **same** directive.

In some cases the scope.$on('$destroy', cb) event callback gets called on the new directive instead of the actually destroyed directive.

expected behavior when switching:
- mutate DOM
- $destroy event on scope
- link new directive
- $destroy event on jQLite element

actual behavior
- mutate DOM
- a race condition between sope $destroy and new linkFn
- $destroy event on jQLite element 

this can be seen in this plunkr:
http://plnkr.co/edit/6jsTbGsScoROE9WIOJ9P?p=preview

**Comment by wesleycho** [comment]
This does not seem to be happening in your plunker - I added the scope id in the message to give more insight into what exactly is happening: http://plnkr.co/edit/zsy90RzdDJqRQzhrGWSd?p=preview

**Comment by petebacondarwin** [comment]
@wesleycho is right, the callbacks are called on the correct scope/element. What is might be happening, which is confusing matters, is that since these changes are driven by the digest cycle, in which watch handlers can be triggered in an arbitrary order, the creation of one ng-if block may or may not appear before the destruction of the other ng-if block.

**Comment by lgalfaso** [comment]
With the provided information from @wesalvaro I think it is safe to close this issue
