### ISSUE TITLE
Html sanitization [ngSanitize] not working for ng-options

### ISSUE THREAD

**Issue by magiccrafter** [angular/angular.js#11202]
It looks like ngSanitize module cannot bind the select options.
Here is the [Plunkr](http://plnkr.co/edit/FrKKLqxr4gqTcfYWVFBB?p=preview)

**Comment by Narretz** [comment]
`ngOptions` and `ngBindHtml` will not work together, as `ngBindHtml` replaces the element content with the expression in the attribute.
We'd need to introduce a new attribute / microsyntax for ngOptions to make this work, because we currently use `textContent`, but entities need `innerHtml` or something similar. This is complicated by the fact that ngOptions shouldn't have a dependency on `ngSanitize`, so the user needs to make sure the html us sanitized. However, since you cannot put children inside `option` elements, this might not be need anyway.

**Comment by Narretz** [comment]
Actually, I found another issue about this: https://github.com/angular/angular.js/issues/2403 Given this, I think the chances are pretty slim for this to be implemented, as you are not supposed to insert HTML entities into DOM nodes.

**Comment by magiccrafter** [comment]
According to [Html reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option), the permitted content is "Text with eventually escaped characters (like \&eacute;)". The way that ngOptions is implemented right now overrides this rule and the rule is interpreted as: the permitted content is "Text with escaped characters". I don't think it is correct, because that way you decide how the text is going to be shown, not the browser. I believe currently all browsers unescapes in the option tag the reserved html characters:(\&apos;, \&quot;, \&amp;, \&lt;, \&gt;, \&nbsp;)
<br/>Here is the pure html option's usage: [Plunkr](http://plnkr.co/edit/cMv3NYqym8jIrrOCqXTK?p=preview).

**Comment by lgalfaso** [comment]
This issue looks invalid. The labels on the options should follow JavaScript syntax and not HTML. In the case I am missing something, feel free to reopen this issue
