### ISSUE TITLE
Controller is not instantiated for dynamically added directive element

### ISSUE THREAD

**Issue by bikramwp** [angular/angular.js#11210]
This AngularJS script demonstrates that the controller for a dynamically added directive element is not instantiated. Tested in versions v1.3.13 (and v1.4.0-beta.5) .

This script has two directives, `viewsContainer` and `view`. A `viewsContainer` element is meant to contain one or more `view` elements.

If I add the necessary HTML markup (see example code below) on the page and then run the app, the controller for the `viewsContainer` and `view` elements are available via `element.controller()`.

However, if the `viewsContainer` and `view` are added dynamically, the `viewsContainer` controller is available, but the `view` controller is not (it is reported as `undefined`).

Plnkr demonstrating the issue: http://plnkr.co/tnuK4dUKIJ7Re61uvOVh

EDIT: Moved code to Plnkr.

**Comment by Narretz** [comment]
Can you please put the example in a plnkr or similar?

**Comment by bikramwp** [comment]
Thanks @Narretz , I should've done that :) 
Here is the plnkr for it: http://plnkr.co/tnuK4dUKIJ7Re61uvOVh

**Comment by Narretz** [comment]
I think the problem is with this line:
`postLinkFunction = $compile(rawElement.contents())`

`rawElement` starts like this: 
```
        <view name='"+viewName+"''>                                                             \
          <h4>view: "+viewName+"</h4> 
```

If you are using contents, `$compile` does not actually compile the view directive, and so the controller is never instantiated. Note also that the `view` link fn is also never called. You simply need to use `postLinkFunction = $compile(rawElement)`
