### ISSUE TITLE
JQLite prepend method not working for 'BODY' tag.

### ISSUE THREAD

**Issue by mehmetotkun** [angular/angular.js#11217]
I have tried to prepend something inside bodyController. However, I get this error for any case during the controller activating

`TypeError: Cannot read property 'childNodes' of undefined
    at compositeLinkFn...`

**Comment by Narretz** [comment]
Hi, can you please provide an example via plnkr.co or similar?

**Comment by mehmetotkun** [comment]
Hi,
[this is the plunker example](http://plnkr.co/edit/9M8uOQii8jZgiqWWiQP4?p=preview). As I understand, if I tried to prepend something before $compile process complate, I get the compliation error.

Content is prepended but copliation is stopped.

**Comment by gkalpak** [comment]
Without looking too deep into it, it seems to be related to how the compiler "loop" works (as explained in this (very insightful) [article][1]). Basically, prepending elements during compilation is dangerous (as in "don't try this at home").

Also, note:
1. It is not a good idea to change the DOM inside of controllers (in fact this must one of the "frowned-upon"est things in the Angular community :P)
2. Wrapping the prepending code insode of a timeout works as expected.
3. Appending (instead of prepending) works as expected.

[1]: http://www.bennadel.com/blog/2750-injecting-sibling-nodes-during-the-compilation-phase-of-angularjs-directives.htm

**Comment by mehmetotkun** [comment]
I have solved the problem with $timeout.

I just wanted to report the issue, in case of using angular with Jquery there is no problem, but, without Jquery the problem is occured.

**Comment by Narretz** [comment]
FWIW, I can't see a difference between jquery / jqlite in your example: http://plnkr.co/edit/6csEEiLhDcKG44jP1cCo?p=preview

**Comment by mehmetotkun** [comment]
Ooo sorry... I faced with the problem when remove jquery from my project.

And interpolation is in the loading view. Maybe jquery become late in my local project.

Thus: Prepending element to the 'BODY' tag is a bad idea during page compliation :)

**Comment by gkalpak** [comment]
> Thus: Prepending element to the 'BODY' tag is a bad idea during page compliation :)

No, prepending **any** element that is not done compiling is a bad idea.

**Comment by mehmetotkun** [comment]
Thanks everyone, I am closing the issue...
