### ISSUE TITLE
Checkbox/Labels ng-click behaviour

### ISSUE THREAD

**Issue by ggirelli** [angular/angular.js#11252]
Hi. I recently moved from AngularJS v1.2.26 to v1.3.14 on a project I am working on.
I discovered that, after the upgrade, the behaviour of ng-click for input[type=checkbox] placed inside the label (for the same input) changed.

In other words, in the following case:
```
<div ng-app="my-app" ng-controller="myCtrl" ng-model="myCtrl">
	<label for="check">
		<input type="checkbox" id="check" name="check"
			ng-model="status" ng-click="toggle_status()">&nbsp;label for checkbox
	</label>
</div>
```
With the myCtrl as follows
```
function myCtrl($scope) {
	scope.status = false;
	scope.toggle_status = function () { scope.status = !scope.status; };
}
```

In v1.2.26 everything worked smoothly both when clicking on the label or on the checkbox directly.
With the new v1.3.14 `scope.status` is not toggled when you click on the label nor on the checkbox.
This is due to the fact that the function is triggered twice at the same time.
I fixed it by changing the HTML as follows (moving the ng-click to the label):
```
<div ng-app="my-app" ng-controller="myCtrl" ng-model="myCtrl">
	<label for="check" ng-click="toggle_status()">
		<input type="checkbox" id="check" name="check" ng-model="status">&nbsp;label for checkbox
	</label>
</div>
```

Still, this solution is not optimal due to the fact that clicking on the checkbox won't trigger the `toggle_status()` function anymore...

**Comment by Narretz** [comment]
Yes, this changed - I think because the directive priorities changed or the prio behavior itself. The consensus was that you should not rely on the order of these events, as angular does not make any guarantees about this. What should work for you (and is canonical to angular) is to use `ng-change="toggle_status()"` on the checkbox. So any time your model changes, toggle_status will be called.
