### ISSUE TITLE
IE9 : Issue with angular.copy in IE9 as of version 1.3

### ISSUE THREAD

**Issue by WardMe** [angular/angular.js#11283]
Not all data is being copied from the source object to the destination object.

This fiddle uses angular.js 1.2.28, the whole object is being copied:
http://fiddle.jshell.net/drawm/gn2fsuno/

This fiddle uses angular.js 1.3.14 and it's missing the deeper nested objects:
http://fiddle.jshell.net/drawm/gapn6sd7/

All other browsers seem to work as expected.

**Comment by jbedard** [comment]
The data looks the same for me in an IE9 VM...

**Comment by eduardoroyer** [comment]
The same here.

**Comment by jbedard** [comment]
I've actually encountered this issue now as well. It seems like some versions of IE9 have a buggy `hasOwnProperty` method which `angular.copy` uses in 1.3 but not 1.2. If windows has the latest patches the problem seems to be fixed.  This seems to describe it: http://webreflection.blogspot.ca/2014/04/all-ie-objects-are-broken.html

**Comment by hoxu** [comment]
For people coming from Google, I could reproduce this using MSIE9 image from here: http://osxdaily.com/2011/09/04/internet-explorer-for-mac-ie7-ie8-ie-9-free/

One workaround is to use lodash `deepClone`, which seems to work with MSIE9.

**Comment by Narretz** [comment]
If it's a bug in an unpatched version of IE, then we cannot realistically do anything about it. Good to know that there's an easy workaround, though!
