### ISSUE TITLE
Bug. Select ng-options with multiple doesn't work IE10/11 when next to each other.

### ISSUE THREAD

**Issue by wawyed** [angular/angular.js#11314]
There seems to be an issue in IE10/11 using select with multiple attribute. The issue only seems to be happening when you have more than one select in a page. The unexpected behaviour renders all of the selects unresponsive minus the last one. It would appear to be a rendering issue, since if you toggle the visibility of the element it works as intended.

Here is a plnkr to reproduce the issue: http://plnkr.co/edit/E1asWesEj90OqAf5RIt2?p=preview

**Comment by Narretz** [comment]
That was difficult to debug ...
Turns out IE(11) has a problem with this line where the label property is assigned:https://github.com/angular/angular.js/blob/v1.4.0-beta.6/src/ng/directive/ngOptions.js#L513

Previously, the whole template cloning / assigning was wrapped in jqlite. I guess we cannot simply skip the label assignment - theoretically it should be set to the text always, but I don't know if that works in all browsers.

**Comment by Narretz** [comment]
This is a crazy bug. It only happens if the first select is wrapped in an element with `display: block`or `display: inline-block` (possibly others).
It's also not possible to test this in a unit test with browserTrigger. I assume because the select is completely blocked to any user interaction, but browserTrigger dispatches the event directly from the DOM.

**Comment by Narretz** [comment]
The bug also appear in IE Edge. Here are two plnkrs that show how to repro the bug without angular, and two workarounds. Setting the option.label before the value is tested to work in IE9, too and will land in core.
- http://plnkr.co/edit/b1nUJdRaZ4e5JHBA5THB?p=preview
- http://plnkr.co/edit/vT3dCoSnL0vPlsZnV5Ag?p=preview

**Comment by apurbamandal** [comment]
I have a working fix for the IE picklist issue.
 before Fix:[](http://plnkr.co/edit/NGwG1LUVk3ctGOsX15KI?p=preview) 
After Fix:[](http://plnkr.co/edit/a7CGJavo2m2Tc73VR28i?p=preview)
`$("select").click(function(){ 
  $(this).append('<option></option>');  
  $(this).find('option:last').remove(); 
 });
`
I just added dummy option for the dom to rerender the select and removed it.
 let me know it works for you

**Comment by petebacondarwin** [comment]
@apurbamandal - is that a fix or a workaround?

**Comment by Narretz** [comment]
This has been fixed in https://github.com/angular/angular.js/commit/42c97c5db5921e9e5447fb32bdae1f48da42844f and I just tested that it still works in 1.6.6 (it's not automatically testable unfortunately)

**Comment by apurbamandal** [comment]
Hi pete, First of all correct me if i am wrong. This is a issue with ie particularly. Irrespective of angular. I have faced it with a very old gwt code. Second, pardon me its not a fix its an workaround. As i faced this which wasn't in angular. Hence i couldn't verify that. But i am sure that the workaround work with angular too. People from different frameworks land in this page for the same issue. So i thought it might help. I am pretty sure you have Please suggest me any better way to fix it with normal Jquery. I would be very thankfull to you. On 25 Sep 2017 8:35 p.m., Pete Bacon Darwin <notifications@github.com> wrote:@apurbamandal - is that a fix or a workaround?

**Comment by Narretz** [comment]
@apurbamandal You are right, this issue is not exclusive to AngularJS, but happens under specific circumstances when select options are added or manipulated with Javascript. In our case, it was caused by a combination of reading the option.value before setting it, and updating the option.label afterwards. It's not conclusive what this causes unfortunately.
Your solution is more of a workaround as, adding and removing an option element triggers a re-render of the select which unfreezes it. If this issue shows up when people google the problem it's ok to have it here, it's just important to point out that this is not a problem in AngularJS anymore.
