### ISSUE TITLE
right-click triggers ng-mouseleave?

### ISSUE THREAD

**Issue by dgtlmonk** [angular/angular.js#11331]
Hi, 

Looks like angular has an issue with Chrome 41.x.x firing ng-mouseleave on right-clicking the div that's involve. In the angular example https://docs.angularjs.org/api/ng/directive/ngMouseleave ... try to right click the button and see how the mouse-leave counter increment even if the mouse is inside the button. 

This made a critical bug on divs/layers that's been hidden/shown using ng-mouseleave/ng-mouseenter ..

**Comment by dgtlmonk** [comment]
same behavior on Firefox 35.0.1. 

Note that this bug was fine with Chrome 40.x.x

**Comment by jaysondaquer** [comment]
I think this is related to this: 
https://code.google.com/p/chromium/issues/detail?id=450138

quote from a comment on the said link:
using http://www.rbyers.net/eventTest.html by right-clicking on the purple box.

Previously we'd get: 
mousedown, mouseup, contextmenu, mousemove, mousemove (hover still active)

Now we get: 
mousedown, mouseup, contextmenu, mousemove, mouseleave, mouseout (no hover)

This reproduces only on Windows for me (not Mac) which makes sense because Windows is the only platform where the context menu is shown on mouseup (the others show it on mousedown).

**Comment by Narretz** [comment]
This looks like a Chrome bug. Hopefully it gets fixed soon.
@dgtlmonk The behavior is correct on Firefox as far as I can see.

**Comment by Narretz** [comment]
Works now in Version 45.0.2429.0 canary
