### ISSUE TITLE
<input> element loses focus after pressing space with ngAria

### ISSUE THREAD

**Issue by jelbourn** [angular/angular.js#11356]
(filing on behalf of a user)

Reproduction: http://jsbin.com/purara/2/edit?html,js,output

Click on the 'Edit' button and start typing into the input. After pressing a space, the input loses focus on the next keypress.

**Comment by andrewaustin** [comment]
This is not an issue with ngAria, but a bug in your template.

An event handler for keypress is being attached by ngAria to div.nav-item because it has an ng-click attribute. When a user triggers a keypress event, that event bubbles up from the <input> field to your div.nav-item which causes ngAria to fire its keypress event (as designed).

Your current template for navItem() has:

```
'<input ng-show="$index == editIndex" ng-click="$event.stopPropagation()" ng-model="item.value">' 
```

You already stop propagation for click events, but you must also do this for keypress events to keep the event from bubbling. To fix your issue simply change the above line to:

```
'<input ng-show="$index == editIndex" ng-click="$event.stopPropagation()" ng-keypress="$event.stopPropagation()" ng-model="item.value">' +
```

You can see a working example here: http://jsbin.com/casaqucufo/1/edit?html,js,output

**Comment by TEHEK** [comment]
I think the original intent was to make ng-clicks accessible via keyboard. However, if the element is not the target of the keyboard event, I think it shouldn't trigger clicks...

```
<div ng-click="doSomething()">
  <div ng-click="doSomethingElse()">
     <input>
  </div>
</div>
```

Having this kind of pitfall would cause users to not adopt $aria...

I can send a PR if you reconsider :)

**Comment by marcysutton** [comment]
I am just seeing this issue now. Do you think ngAria needs to check for `$event.currentTarget` to prevent bubbling?

**Comment by TEHEK** [comment]
I think so. I made a small patch, but turns out writing a unit test for that is a bit of a problem because jqLite doesn't support .trigger() function and .triggerHandler() doens't propagate events. And this issue is still considered closed -_-...
