### ISSUE TITLE
ng-repeat cannot pass value to custom directive

### ISSUE THREAD

**Issue by zishanj** [angular/angular.js#11391]
I am using custom directive inside nested `ng-repeat` like this:

    <tbody ng-repeat="item1 in data1 track by item1.id">
     <tr ng-repeat="item2 in data2 track by item2.id">
      <my-dir current-item="item2" previous-item="item1"/>
     </tr>
    </tbody>

But I am always getting undefined for `scope.currentItem` and `scope.previousItem` inside my directive. If I pass `data1` or `data2` without `ng-repeat` then it works. Whats the issue?

I am using AngularJS 1.3.14.

**Comment by wesleycho** [comment]
Can you reproduce this in a [Plunker](http://plnkr.co/)?

**Comment by zishanj** [comment]
I have seen that this is happening because I am using custom directive inside a table which doesn't conforms as a valid element for the table. As a result it rejects my entire directive.

**Comment by gkalpak** [comment]
@zishanj: The directive is not actually ignored. It is moved outside of the table (by the browser itself, not by Angular), because there are only certain elements that are allowed as childs of `table`, `tbody`, `tr`, etc.

In such cases, you can usually work round the issue, by allowing your directive to be an attribute directive, e.g.:

```html
<!-- NOT ALLOWED -->
<table><tr><custom-td ...></custom-td></tr></table>
<!-- will become: -->
<custom-td ...></custom-td>
<table><tr></tr></table>

<!-- WORKS FINE
<table><tr><td custom-td ...></td></tr></table>
```

**Comment by pkozlowski-opensource** [comment]
@gkalpak explanation is spot on!
