### ISSUE TITLE
Is there a way to format currencies by their ISO codes?

### ISSUE THREAD

**Issue by moneytree-doug** [angular/angular.js#11456]
My application shows different currencies, but it still needs to be in a given language such as English. I know you can set the entire application to a certain locale, but I couldn't find a way to just format the currency alone.

**Comment by lgalfaso** [comment]
There is no easy way. You will need to specify the currency symbol whenever you are using the `currency` filter.

**Comment by pkozlowski-opensource** [comment]
@lgalfaso but the symbol is only part of the problem, right? We still need to format a number correctly and stick the symbol at the "right" place.

**Comment by lgalfaso** [comment]
this might be somehow off-topic, but if a page is language X, then I would expect that money amounts to be formatted using language X currency format (regardless of the currency being used).

**Comment by moneytree-doug** [comment]
@lgalfaso You aren't wrong, but there is also the common use case in finance where there are always multiple currencies shown on a given page. Bank accounts are a good example.

**Comment by lgalfaso** [comment]
If at the same time, you need to display multiple currencies, then
specifying the currency symbol is a must. Btw, the current symbol can be an
expression

**Comment by moneytree-doug** [comment]
@lgalfaso Aside from the symbol, what about the precision as in the significant digits? Then there's other localisation factors such as ``$400k`` which would be ``40万円``. Are there future plans for these things?

**Comment by lgalfaso** [comment]
> @lgalfaso <https://github.com/lgalfaso> Aside from the symbol, what about
> the precision as in the significant digits? Then there's other localisation
> factors such as $400k which would be 40万円. Are there future plans for
> these things?
>

Not that I am aware of, I would look for a third party module if this is a
requirement

**Comment by realityking** [comment]
Only slightly off topic: How about reimplementing the filters (currency, number, maybe date) based on the [ECMAScript Internationalization API](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Intl)

[Browser support](http://caniuse.com/#feat=internationalization) is decent but not great. There's a [polyfill](https://github.com/andyearnshaw/Intl.js), however it's not load and forget as you have to actually load the data you need.

If this is intresting, I'd be happy to create a pull request. Or maybe this should be a separate repository, due to the polyfill?

**Comment by eseceve** [comment]
https://github.com/zwacky/isoCurrency
