### ISSUE TITLE
Expose getter for per-element $animate enable state

### ISSUE THREAD

**Issue by chrisirhc** [angular/angular.js#11458]
Right now there's only a getter for the global animations enable flag through `$animate.enabled()`. However, it would be helpful for directives to know when animations are enabled for the directive's element.
This should probably expose `animationsDisabled()` method already in `ngAnimate`. The directive could use this information to skip preparation for animations or to avoid attaching events that won't be useful.

**Comment by matsko** [comment]
In 1.4 on master we can do this now since the args have been flipped:

BREAKING CHANGE: The function params for `$animate.enabled()` when an
element is used are now flipped. This fix allows the function to act as
a getter when a single element param is provided.

```js
// < 1.4
$animate.enabled(false, element);

// 1.4+
$animate.enabled(element, false);
```

Is this what you were looking for?

**Comment by chrisirhc** [comment]
Yep indeed, that's what I was referring to. Heh, saw your release a few days after this was posted. :+1:
