### ISSUE TITLE
ngCsp example doesn't work

### ISSUE THREAD

**Issue by ottens** [angular/angular.js#11465]
Hi,

I'm looking into ngCsp to secure an app I'm working on, but could not get it to reject anything that was supposedly bad. So I went back to the example in the documentation, but that one seemingly doesn't work either. The eval in the example evaluates nicely instead of throwing an error. This goes for 1.4, 1.3 and 1.2.28 on my local setup. Am I missing something obvious? Tried latest chrome, firefox and safari on yosemite mac.

Try and click the evil button in the example. I'm getting no response and can log the eval outcome. 

https://docs.angularjs.org/api/ng/directive/ngCsp

Thanks,
Maarten

**Comment by Expyron** [comment]
Hi ottens,

My understanding is that the *ngCsp* directive will prevent angular from using features forbidden by CSP (e.g. *eval*), in its internals. However, angular will not prevent you from using these features in your own code. If anything is forbidden, it will be at the browser level and not by angular.

As for the example, CSP isn't enabled on usual webpages, so the browser doesn't throw an error when *eval* is used. I do agree that the example is not optimal since CSP is not enabled, and thus nothing happens when you press the Evil button.

The same thing happens with your app. CSP is not enabled in the environment you are testing in. I don't know what your environment is, but if everything is allowed in it, you don't have to worry about CSP at all.

**Comment by ottens** [comment]
Thanks for the answer. The example threw me off quite a bit, but I seems to have a better grasp now.

When I add ng-csp it indeed prevents Angular from doing some things that a CSP would not allow, e.g. injecting inline CSS. So that part works (and would perhaps be a better example, e.g. ng-show doesn't work because it relies on inline css, easy to demonstrate with ng-csp). To prevent things like eval and different origin script loading prevention, I need to set the CSP in the headers of the responses, on the server. That I got working too. In the end I now understand ng-csps main function is to prevent a harmless error from popping up. It has nothing inherently to do with Content Security Policies, just forces Angular in the CSP compatible mode before the auto detection finds it.

Thanks again, much appreciated.

**Comment by gkalpak** [comment]
Just a heads-up:
There are directives (like `ngShow/Hide`, `ngCloak` etc) which rely on CSS. In CSP mode, Angular can't inline stylesheet rules, so in order for them to work, you have to include a CSS file "manually".
Other than that (and performance aside), everything should work the same (as far as Angular itelf is concerned).

From the docs:

>CSP forbids JavaScript to inline stylesheet rules. In non CSP mode Angular automatically includes some CSS rules (e.g. `ngCloak`). To make those directives work in CSP mode, include the `angular-csp.css` manually.
