### ISSUE TITLE
bower file has the wrong "main" javascript

### ISSUE THREAD

**Issue by lilicaway** [angular/angular.js#11467]
The bower.js file that I get when I install angular like this:
`bower install angular#1.3.15`

has a `"main"` that points to `"./angular.js"` and should point to `"./index.js"`

This is the bower.js file content:
``` json
{
  "name": "angular",
  "version": "1.3.15",
  "main": "./angular.js",
  "ignore": [],
  "dependencies": {
  }
}
```

And it should be:
``` json
{
  "name": "angular",
  "version": "1.3.15",
  "main": "./index.js",
  "ignore": [],
  "dependencies": {
  }
}
```

The `"main"` is set correctly in the npm package.

Without this, using bower with browserify doesn't work.
As pointed out by this page: https://www.npmjs.com/package/debowerify#notes

> The transform depends on the "main" entry in bower.json to be correct.
> 
> Some bower components may not have this set, or have it set incorrectly. In this case, either manually update the bower.json file yourself, of just do a require to the relevant full path of the bower javascript file - and then complain to the bower component repo owner! :-)

I am just a messenger :)

**Comment by linclark** [comment]
You shouldn't need to install angular with bower and debowerify it. Angular is published to npm, and it can be used with Browserify directly. You can read more here: blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support

**Comment by lilicaway** [comment]
I understand your point but still I believe it needs to be compliant for bower.

**Comment by petebacondarwin** [comment]
@linclark is correct here. Browserify is designed to work with node modules published on npm, which is why we have setup and are deploying all versions of angular via npm. Debowerify is for cases where the library developer has not provided an npm implementation.

I understand that you wish to have a system where you get all your dependencies via bower and then use browserify but this is not the intention of browserify and debowerify is a hack to get around specific situation where you cannot get modules from npm.

Unfortunately, on the other side of the equation, bower explicitly states that the `main` property of bower.json should point to the main file for the package, which in our case is indeed `angular.js`, since bower does not care for commonjs or amd style module packaging.

Therefore we are doing the right thing by bower in setting `main: './angular.js'` and the right thing by browserify by publishing to npm with `main: `./index.js` there.
