### ISSUE TITLE
option to autocast strings as numbers

### ISSUE THREAD

**Issue by rizen** [angular/angular.js#11464]
There needs to be a way to cast strings as numbers from the model. Angular is used in all sorts of systems where you don't have access to the backend that generates the JSON that populates a field. So if I set a field like this:

&lt;input type="number" ng-model="some_value"&gt;

Then angular should trust me when I say that some_value is a number, and run Number() on it. 

I know you guys have considered this before, as you did in this ticket: https://github.com/angular/angular.js/issues/6683

And I know you've rejected the premise. However, that's just a terrible way to do things. We need a way to at least optionally change a config setting to change this behavior. If you don't, I'm forced to either set the field as "text", which is semantically wrong, or I'm force to loop over all the results as they come in and manually run Number() on them, which adds a lot of code for something that should be automatic. Please reconsider.

**Comment by Narretz** [comment]
I'll think it's worth reconsidering this. Here's some thoughts:
* the reason for this was that you will overwrite your non-number / string with a number once the user changes the input. You may not want this. Likewise, on init the model and view are inconsistent - one is a string , one is a number (which might be problematic for validation)
* You can use a custom formatter that runs before the built-in formatter and formats your string to a number. No looping required.

**Comment by rizen** [comment]
That's why I said to make it an option. It may not be right to turn this on for everybody, but it's certainly good for people that explicitly want that behavior. 

Could you link to an example of how to build a custom formatter? I've never heard of such a thing. Unless you mean a custom filter? If that's what you mean I can't apply the filter to the field because I've attached the model directly to the input field, so I can't do {{some_value | number}}.  Please show me the error of my ways.

**Comment by rizen** [comment]
After a few hours of searching and reading, I finally figured out what an angular formatter is and how to apply it to this situation. For people seeing this going forward, I applied @Narretz advice and came up with this:

myApp.directive('input', [function() {
    return {
        restrict: 'E',
        require: '?ngModel',
        link: function(scope, element, attrs, ngModel) {
            if (
                   'undefined' !== typeof attrs.type
                && 'number' === attrs.type
                && ngModel
            ) {
                ngModel.$formatters.push(function(modelValue) {
                    return parseInt(modelValue);
                });

                ngModel.$parsers.push(function(viewValue) {
                    return parseInt(viewValue);
                });
            }
        }
    }
}]);

**Comment by Narretz** [comment]
Hey @rizen if you want to give a PR a shot that allows non-Number numbers, that'd be great. Here's a list of things that'd be needed:

1. add an option to ngModelOptions: `numberAutocast` or similar
2. change the input[number] formatter to read this option and allow non-numbers in that case
3. Update the docs.

**Comment by adamreisnz** [comment]
I am also in favour of this, due to the following use case:

I am actually in control of the input, and I am calculating some numbers that I need to put in the model. However, these numbers are currency values, and as such I would like to have them formatted as such, e.g. with 2 decimal spaces, even if the value is `12.5`, it should display as `12.50` in the input field.

A user can input `12.50` in the input[number] field without problems. We should be able to "input" that into the input field through the model value as well. 

Currently, this is not possible, because if I run the value through the `number` filter for example, it converts into a string and then Angular throws the `ngModel:numfmt` error.

So I have no way of pre-populating the number field with valid numbers at this stage, other than changing the input field to free text, which of course is not what I'd want to do.

**Comment by frederikprijck** [comment]
@Narretz If this is still something you'd like to have in the core, i'd be happy to create a PR for it. After looking into https://github.com/angular/angular.js/issues/16080 it looks like we might benefit from adding it in the core.

**Comment by gkalpak** [comment]
As already discussed, a formatter is the way to go. Formatters essentially provide a way for developers to implement their own "switches" to turn features on, either on specific inputs (e.g. with a custom selector that you have to explicitly apply to the inputs) or for all input of a type (e.g. using `input` as the selector and checking for the type).

Finally, as a very last resort, it is even possible to remove or replace the built-in formatters.

##
Additionally, in latest versions it is even possible (even if not well documented) to get hold of the `ngModelOptions` [options][1] and implement this as an `ng-model-options` property (if one wants to).
(There would still need to be a custom directive or decorating one of the existing ones.)

##
Personally, I would close this as _won't fix_, because what you want it already possible (without any changes to core), can be applied granularly and there is no intention (afaict) to change the default behavior atm (as this would be a breaking change of something that is useful in most cases).

I'll leave the final call to @Narretz :smiley:

[1]: https://docs.angularjs.org/api/ng/type/ModelOptions

**Comment by adamreisnz** [comment]
I don't think I agree. See the discussion in #16080 and this Plunkr: https://plnkr.co/edit/8XhP9xLhgNgx6RdAz9ZJ?p=preview

The `input[type=number]` actually _accepts_ valid numerical String values _natively_ as demonstrated by the Plunkr. E.g. something like this:

```
document.getElementById('input1').value = '2.50';
```

This sets the proper value for that input to `2.50`, trailing zero included.

So Angular's behaviour actually _limits_ us, preventing us from utilizing the native capabilities of the `input[type=number]`. That I think is a problem with the framework, and should not be solved in userland by custom formatters or 

The simplest way to fix this in Angular core would be to mimic the native behaviour, and instead of just type checking if a `Number` is passed, it could check a `String` to be of a valid numeric format and put that in as is without casting it to a `Number`. This could be implemented with an optional additional flag, if you're worried about breaking changes, although personally I don't see it breaking many things.

Do you know if Angular 2 has the same behaviour?

**Comment by adamreisnz** [comment]
Looking at the source code, there already is a regex in place to check for valid numbers:

https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L28

All that would realistically need to change imo, is these lines:

https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L1519-L1521

Replace the `isNumber()` check in the formatter with the same regex check as is used a few lines above in the parser, and change the error message.

**Comment by adamreisnz** [comment]
I have tested this in our own project by creating this directive and it seems to work ok;

```js
/**
 * Module definition and dependencies
 */
angular.module('Shared.Input.Directive', [])

/**
 * Directive
 */
.directive('input', function() {
  return {
    require: [
      '?ngModel',
    ],
    link(scope, element, attrs, ngModel) {

      //Array?
      if (angular.isArray(ngModel)) {
        ngModel = ngModel[0];
      }

      //Number regex
      const NUMBER_REGEXP = /^\s*(-|\+)?(\d+|(\d*(\.\d*)))([eE][+-]?\d+)?\s*$/;

      /**
       * Helper to apply number handling
       */
      function applyNumberHandling() {

        //Remove existing formatter
        ngModel.$formatters.pop();

        //Roll our own
        ngModel.$formatters.push(function(value) {
          if (!ngModel.$isEmpty(value)) {
            if (!NUMBER_REGEXP.test(value)) {
              throw Error('Expected `' + value + '` to be a number');
            }
            value = value.toString();
          }
          return value;
        });
      }

      //Apply better number validation
      if (ngModel && attrs.type === 'number') {
        applyNumberHandling();
      }
    },
  };
});
```

**Comment by frederikprijck** [comment]
@adamreisnz I had a chat offline with @gkalpak and it makes perfectly sense as, in AngularJS, we have a seperation of ViewValue and ModelValue. When working with an API that expects a number, we want to ensure it's a number type (not a numeric value) hence there's no need to pass in a string. We could argue that we could pass in '2.50' and parse it to a number before doing numerical operations, but we'll again lose the trailing `0`.

If you have the need to visualize the value differently from the model (visualize it as a string, while the model is a number) you can make use of an simple formatter like so: http://plnkr.co/edit/NJSUppF28ZPKsrWisXZF?p=preview

Even tho I understand your point, I also understand @gkalpak's point of view with regards to api usage.
I also think it's going to be more complex than only allowing strings (depending on the numeric API usage internally).

**Comment by adamreisnz** [comment]
Ok, thanks for looking into it. I think I will stick to my directive, essentially overwriting the behaviour of all Number inputs, because I feel it's something that should work on all input fields of type number, but thanks for posting your suggestion. It's also a good approach.

Not sure if it would be more complex, as the regex is already there, and all I did was basically replace the `isNumber` check with the regex check. You use the same check in the parser, so it should be ok.

**Comment by gkalpak** [comment]
It seems we have come to some sort of consensus :smiley: 
Still, here is a quick summary of my thoughts:

The question is not whether we can implement this (we obviously can :smiley:), but whether this is the right thing to do (imo it is not :smiley:).

What the browser does (i.e. accepting any string that is a valid representation of a number as `value`) is not really relevant, because AngularJS enhances the browser's capabilities and does better than the browser 😛

In AngularJS, there is a clear separation between the model (actual data) and the view (the visual representation of that data). `NgModelController` provides parsers and formatters (validators are not related here btw) for the exact purpose of giving the developer full control over how the data is presented to the user and how the user's input is translated to the model representation.

Using formatters for their intended purpose (i.e. formatting the model data for visual representation in the view) is not a hack or work around. It is normal and common practice (in fact AngularJS itself uses these APIs under the hood for all supported input types).

##
Now, specifically regarding the number input type, there is a contract in AngularJS that the model data bound to such an input is a number (which makes perfect sense imo, since the input is supposed to offer an interface for interacting with numbers). This guarantee allows AngularJS, 3rd-party libraries and app developers operate on a common assumption that will always hold true: The model value (if not empty) will be of type `number`. (The same is true for other types of inputs, such as `date` etc.)

Changing this would leave us in a position were we can't be sure of the type of the model data. This would affect several `ngModel` APIs (e.g. parsers, validators, formatters) - both in AngularJS itself and 3rd-party libraries - as well as any app-specific logic (methods, filters etc) that takes such data as input (and naturally expects to operate on numbers).

Furthermore, allowing this, would create another inconsistency which makes `ngModel`-bound inputs harder to reason about: You can't be sure what model data a specific input corresponds to (or even what is the type of model data).
(BTW, saying that we will immediately update the model data to be a number would break another `ngModel` contract: As long as the input's validity hasn't changed, there can be no change in the model value, unless the user initiated that change (or the model value has been programmatically updated)).

##
In a nutshell, by implementing the requested change (and hiding it behind a flag in order to avoid a breaking change) we would be breaking some contracts that make `ngModel` easier to reason about and introducing undeterministic behavior.

These are obvious downsides. What would we gain in exchange?

AFAICT, the only tangible upside is to be able to display a value in a specific format. But (as discussed earlier) this is exactly what formatters are for. In addition, using formatters has the following advantages:

- They are more flexible (every app can customize them for its specific usecase).
- They are composable (you can add other formatters in the pipe in arbitrary locations).
- They can be applied selectively (on specific inputs) or app-wide (all number inputs). Or you can even apply them app-wide, but have certain inputs opt-out.

##
Even if the `ngModel` API is far from perfect, a considerable amount of work has been put into making it powerful and extensible. This is a great thing that should be utilized more imo. It allows developers to have their highly customized inputs, but without bloating the framework with code and logic that is not useful to all users.

And given how easy it is to re-use logic in AngularJS apps, I really see no reason for not solving this via formatters :grin:

**Comment by adamreisnz** [comment]
Ok let's close this issue then 👍
