### ISSUE TITLE
ngDisabled Delay

### ISSUE THREAD

**Issue by jacobscarter** [angular/angular.js#11501]
I have a function that flips a boolean which removes the ngDisaled, i.e.

    //js
    $scope.removeDisabled = function(){
        $scope.disabledBoolean = false;
        angular.element('#myInput').focus()
    };

    //html
    <button ng-click="removeDisabled()">Click Me</button>
    <input ng-disabled="disabledBoolean" id="myInput">

The function also puts the input in focus

The problem that I run into is that the input will only go into focus if I wrap the function in a $timeout, even if the delay on that timeout is 0. My conclusion was that the disabled is not removed quick enough for the input to be allowed to be put in focus. Is there any documentation on this sort of issue?

My solution feels hacky and I figured someone smarter than me has solved this already. Also perhaps this is a JavaScript question not an Angular one so I apologize in advance if I shouldn't be posting this here.

**Comment by gkalpak** [comment]
It is expected that the input is not enabled **the moment** `$scope.disabledBoolean` is set to false.
This will happen at a later time, when during the $digest loop, when Angular's change-detection kicks in and the `ngDisabled` directive picks up the change and enabled the input.
And since JavaScript is (mostly) single-threeaded, the call to `angular.element('#myInput').focus()` will happen right after setting `disabledBoolean` to false and **before** the rest of the $digest loop.

Wrapping something in a `$timeout` (even with a 0 delay), ensures that it is executed **after** the next rendering phase, meaning the $digest loop is guaranteed to have been completed and thus all DOM elements updated. In this case, you wouldn't even need a new $digest cycle, so you could use `$timeout(..., 0, false)` to avoid the extra overhead.

I say `wouldn't`, because you shouldn't be doing what you are doing in the first place. Directly accessing DOM elements in a controller is an anti-pattern in Angular; it is a directive's job to do that.

--
Having said that, this is a general support question and should be directed to the [appropriate channels][1].
GitHub is reserved for bug reports and feature requests.

I am closing this now, but feel free to reopen if it turns out to be a bug in Angular.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
