### ISSUE TITLE
Automatic update of $scope variable

### ISSUE THREAD

**Issue by mishavetl** [angular/angular.js#11514]
If i use `{{ foo }}` in template and in controller
`$scope.foo = 'bar';`

It does not update automaticly.
I know that i can do as following:

    $scope.get_foo = function (){
        return $scope.foo;
    }

But it will increase an amount of lines in my code.

Can it be fixed or is there some issues?

**Comment by Stephn-R** [comment]
There are generally two ways to perform this:

**1. $watch**:

```js
$scope.$watch($scope.foo, function(e) { $scope.bar = $scope.foo; });
```

**2. Function (as you provided)**

**Comment by wesleycho** [comment]
Likely what is happening is that the code that sets `$scope.foo = 'bar';` is outside the Angular context, and so the fix is likely to execute `$scope.$apply()` at the end of that block.

Another common issue is that you are using directives that create new `$scope` - I recommending reading [this entry on $scope](https://github.com/angular/angular.js/wiki/Understanding-Scopes), and setting this property to an object on `$scope`, i.e. `$scope.foo.bar = 'baz'`.

**Comment by Narretz** [comment]
I think there's information missing here to resolve this issue. Either way, support questions are better asked on Stackoverflow, the Google Groups, or the IRC. You'll also increase your chances of getting an answer by including a minimal example of your problem in a plnkr.co or similar. Most likely thugh, it's a scope inheritance issue as @wesleycho said.
