### ISSUE TITLE
bug($q): finally is a ES5 reserved keyword - jslint/jshint invalidates the code

### ISSUE THREAD

**Issue by dragosrususv** [angular/angular.js#11511]
"finally" keyword is used in AngularJS promises but seems to be a reserved keyword in ES5. 
Therefore validation tools like JSLint and JSHint are failing on this keyword. Moreover, for people who use this on a daily basis via Grunt, they won't get their files compiled because validation engines fail.

Any chance some alias of "finally" is added in 1.4? May it be always (https://api.jquery.com/deferred.always/) or whatever that might be.

Thanks in advance.

**Comment by realityking** [comment]
The same is true for catch. Since ES5 reserved keyword can be used as methods. AFAIK the only supported browser which has issues with this is Android < 4. I don't think it's worth changing this at this point.

You can configure JSHint to now check this rule, or, if you need Android 2 compatibility use the dynamic syntax:

    promise['finally']()

**Comment by dragosrususv** [comment]
I'm already using the dynamic syntax, but it just doesn't seem right.
I understand the background "noise" of old browsers, but the problem is that ES6 passes theses reserved keywords along so automatic validation tools will encounter this more often. 

Might be something to be systematically addressed in AngularJS 2 at least.
JSHint: https://github.com/jshint/jshint/issues/1646

**Comment by Narretz** [comment]
angular 1 also uses jshint for code validation, and there are no errors. I assume it's a specific config value that must be set. I expect that projects using angular can also adjust the config this way.

**Comment by dragosrususv** [comment]
@Narretz : seems es5 reserved keywords is not disabled on angularjs ( https://github.com/angular/angular.js/blob/master/.jshintrc-base ) but then again .finally is not used anywhere in angularjs from promise (only finally from try/catch mechanism). So it's not a config issue, it's an API that is given by AngularJS and if it's used, we get in trouble with JSHint/JSLint type of tools.

Not sure what a solution would look like here. I would suggest some alias of the finally into something that is not a reserved keyword.

**Comment by dragosrususv** [comment]
@Narretz : ca we remove the needs more info label?

**Comment by Narretz** [comment]
I think this is really a wontfix, as we've specifically changed `always` to `finally` to be consistent with most promise specs.
Further, the current version of jshint (since 2.0 (?)) already sets `es5`to `true`. To see the invalidation behavior, you'll explicitly have to set `es3`to `true`. So it is configurable, and actually works by default. The same should be true for jslint.
Also, you can use the bracket notation if you have to support browsers that actually break on using reserved keywords.

**Comment by dragosrususv** [comment]
es5: true will actually show that error... you have to manually put FALSE to avoid it!
https://jslinterrors.com/es5-option-is-now-set-per-default

**Comment by caitp** [comment]
per-spec, reserved words can't match Identifiers, but can match IdentifierNames, which are the productions used for PropertyNames in both ES5 and ES6. This was fixed at some point in ancient history in JSHint, so maybe don't use jslint?
