### ISSUE TITLE
DOM not updated when changing associated data.

### ISSUE THREAD

**Issue by kamijean47** [angular/angular.js#11530]
i have this:

```
<div ng-app="myApp" ng-controller="personCtrl">
  <p> {{firstName}} </p>
  <p ng-hide="myVar">
  First Name: <input type=text ng-model="firstName"><br>
  Last Name: <input type=text ng-model="lastName"><br><br>
  Full Name: {{firstName + " " + lastName}}
  </p>
</div>

<script>
var app = angular.module('myApp', []);
app.controller('personCtrl', function($scope) {
    $scope.firstName = "John",
    $scope.lastName = "Doe"
    $scope.myVar = false;
    $scope.toggle = function() {
        $scope.myVar = !$scope.myVar;
    }

   // setting delay before changing value of myVar and firstName to see if the DOM will be updated
   setTimeout(function(){
        $scope.myVar = true;
        $scope.firstName = "Jean";
       console.log($scope);
     }, 3000)
   });
</script> 
```

after 3s, the {{`firstName`}} in the html must be 'Jean', and the text inputs must be hidden because `myVar` will be set to true.
my issue is changing data programmatically doesnt trigger change in the DOM,
but it will be updated once i write something inside the text inputs.

**Comment by frfancha** [comment]
I think reading an introduction to Angular is necessary.
Anyway, the answer to your problem is that there is no magic in angular: it only knows that things have changed if it triggers the change itself.
Here the change is not triggered by angular (it comes from the browser setTimeout execution), therefore you must either in the setTimeout calls $apply to let angular apply your changes, or use the angular service $timeout instead of setTimeout.
And this is not a bug at all, you should ask this kind of questions on the list and not as a bug report.

**Comment by pkozlowski-opensource** [comment]
@frfancha thnx so much for stepping in and helping out with issues - much appreciated!

@kamijean47 this is indeed a support question and as such should be asked on a dedicated support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by kamijean47** [comment]
@frfancha thanks for informing me, i think i mislead myself in the concept of two-way data binding and i really need to read more about Angular. And using $apply/$timeout works! Thanks.

@pkozlowski-opensource sorry, my bad for reporting it here.
