### ISSUE TITLE
cannot load angular.mode in IE 11

### ISSUE THREAD

**Issue by brendonco** [angular/angular.js#11553]
Hi,

I cant load the module in IE 11. below script works on Chrome and firefox but not in IE. I'm using Angular 1.4.

var app = angular.module("myApp", ["windowFrameModule", "utilService"]);

Object doesn't support property or method 'module'.

**Comment by pkozlowski-opensource** [comment]
@brendonco it sounds very odd, I think that there is something wrong going on with one of your modules. Do you see the same error if you do `var app = angular.module("myApp", []);`?

We will need a minimal reproduce scenario to progress on this one. Could you please prepare one using pluker, jsbin or similar? Otherwise it is next to impossible to help here...

**Comment by brendonco** [comment]
Hi,
it seems that the angular.js that I downloaded seems corrupted.  I download again and it is working now in IE.
