### ISSUE TITLE
angular.element.css() method has undocumented inconsistentcy with jQuery api

### ISSUE THREAD

**Issue by adam77** [angular/angular.js#11626]
"When a number is passed as the value, jQuery will convert it to a string and add px to the end of that string."
http://api.jquery.com/css/#css2

jqLite does not appear to do this.

Can result in some nasty subtle bugs which only show up when jqLite in use.

**Comment by petebacondarwin** [comment]
@mzgol can you take a look at this?

**Comment by mzgol** [comment]
I wish jQuery didn't do it. :) This basically means any new CSS property that might accept plain numbers as values needs to be added to a whitelist that we maintain; we've recently had to add flexbox-related properties to the list.

A current list can be viewed at http://api.jquery.com/jQuery.cssNumber/, we've made this object public recently.

jqLite diverges from jQuery in many places but in this case. That said, we haven't removed this mechanism exactly because it might broke a lot of code and it won't throw errors but just won't apply some CSS rules so it might, indeed, be hard to debug. This would be pretty trivial to add to jqLite, maybe we should do it for compat with jQuery.

This would be a breaking change for jqLite, though so we shouldn't touch it in 1.3 IMO.

**Comment by petebacondarwin** [comment]
Let's add it as a candidate for 1.5 and just merge the doc update (#11614) for now.

**Comment by mzgol** [comment]
Makes sense, this API requires one to react to new CSS properties so it adds responsibility for jqLite maintenance if we do want to match this jQuery design mistake. ;)

**Comment by adam77** [comment]
jQuery reference:
* [convert parameters of type number] (https://github.com/jquery/jquery/blob/master/src/css.js#L287)
* [list of props not to add 'px' to ('possibly unitless')] (https://github.com/jquery/jquery/blob/master/src/css.js#L230)

**Comment by mzgol** [comment]
@adam77 No need to link to source, it's officially documented under http://api.jquery.com/jQuery.cssNumber/ with more info than in the code as I mentioned in my comment https://github.com/angular/angular.js/issues/11626#issuecomment-96643955

**Comment by mgol** [comment]
We'll be removing this logic in jQuery 4.0, just with a closed whitelist of properties to which we'll still append `px` just for back compat reasons. Because of that, adding it in jqLite doesn't make sense. Closing.
