### ISSUE TITLE
ngMock - why does $httpBackend match the first and not the last mock definition?

### ISSUE THREAD

**Issue by szimek** [angular/angular.js#11637]
Is there any reason why `$httpBackend` matches the first and not the last mock definition? If it worked the other way around (i.e. `$httpBackend.when` added new mock definitions to the beginning of `definitions` array instead of the end of it) it would be much easier to overwrite already mocked requests.

I've got some default mock definitions common for almost all tests that are loaded before each test and would like to be able to easily overwrite them in some specific tests.

I wanted to prepare PR that changes this, but there's even a [unit test](https://github.com/angular/angular.js/blob/master/test/ngMock/angular-mocksSpec.js#L960) that explicitly checks for this behavior.

EDIT: In ngMock module unit tests like [`should match headers if specified`](https://github.com/angular/angular.js/blob/master/test/ngMock/angular-mocksSpec.js#L1011-L1013) or [`should match data if specified`](https://github.com/angular/angular.js/blob/master/test/ngMock/angular-mocksSpec.js#L1035-L1036), the first mocks are more specific than the later ones. In a real app, I'd expect something opposite - one would create general mocks for most tests and then define more specific ones in selected tests.

**Comment by petebacondarwin** [comment]
I think this sounds like a good idea, but of course it would be quite a breaking change to applications.
Let's see if the rest of the team agrees and if so then aim to put it into 1.5

**Comment by drewzh** [comment]
This is actually a really annoying feature when it comes to E2E testing with Protactor, as currently there's no module available that will allow you to keep reference the promise returned by the mock httpBackend to re-purpose the redirect after it's already been set.

So essentially, it's impossible to test a success response and then immediately test a failure without having to do a full browser refresh with browser.get('blah').

Allowing the option of matching the last added regex instead of the first would make this kind of testing trivial. But essentially for me at the moment, integrating Protractor into my tests is impossible due to the high number of tests that can't be changed easily.

**Comment by szimek** [comment]
@petebacondarwin Are there still any chances this could land in 1.5, as there already were 2 beta releases? 
How does it work in Angular 2? Is there the same problem?

**Comment by yogeshgadge** [comment]
Why don't we just add something like resetDefinitions() along the lines of resetExpectations() ? This will at-least help in setting new definitions.

**Comment by szimek** [comment]
You could also add it as an option that would default to the current code, so it would be backwards compatible. It's really just a matter of changing `push` to `unshift` in one place (which we do ourselves after every release of Angular 1.x 😉 )

**Comment by yogeshgadge** [comment]
Am I reading this correctly - I see `return;` statement inside that while loop so then what purpose does holding on to several definitions of same {METHOD, URL} definition is served. 
If we are going to return this loop on the first match then why even bother to push - perhaps it should be a map since there can be only one response. 

```
    var i = -1, definition;
    while ((definition = definitions[++i])) {
      if (definition.match(method, url, data, headers || {})) {
        if (definition.response) {
          // if $browser specified, we do auto flush all requests
          ($browser ? $browser.defer : responsesPush)(wrapResponse(definition));
        } else if (definition.passThrough) {
          $delegate(method, url, data, callback, headers, timeout, withCredentials, responseType, eventHandlers, uploadEventHandlers);
        } else throw new Error('No response defined !');
        return;//why are we returning
      }
    }
```

**Comment by Narretz** [comment]
I was also thinking of making this configurable. In any case, a PoC PR is very welcome.

**Comment by petebacondarwin** [comment]
We are happy to merge a PR that implements a non-breaking change form of this feature. It looks like something along the lines of `resetDefinitions` would be best - or perhaps something like `whenOverride`?

**Comment by szimek** [comment]
Personally, I'd prefer `whenOverride`, because this would allow me to keep my generic mocks for most requests and override just the ones I need in a given test. I'll try to find some time to come up with a PR.
