### ISSUE TITLE
interpolation fails when using dynamic form fields inside ng-repeat

### ISSUE THREAD

**Issue by p09** [angular/angular.js#11662]
I have been trying to generate a form dynamically using json data and applying validation on it. For applying validation i used the validation framework provided by https://github.com/ghiscoding/angular-validation.
here is the link to the plunker i created 
http://plnkr.co/edit/RqOfvR5CECya86eCYidL?p=info
on clicking the validate button the validation summary is shown which relects the form field name and corresponding error. However, i only get the error for the form field which was there in the html. For the form fields generated by json data the name displayed is the non-iterpolated one.
![interpolationfailed](https://cloud.githubusercontent.com/assets/11771194/7246408/86a3c658-e81a-11e4-9950-9331510ee072.png)

First i thought this was an issue related to the validation framework but now i think its an angular issue.
For dynamic fields inside ng-repeat the interpolation fails.
Also when i add a directive to the dynamic fields generated by directive which links the name to the element and then compiles it the issue is resolved

As suggested by http://stackoverflow.com/questions/21455695/angularjs-dynamic-form-field-validation/21457121#21457121

app.directive("dynamicName",function($compile){
  return {
      restrict:"A",
      link:function(scope,element,attrs){
          element.attr('name', scope.$eval(attrs.dynamicName));
          element.removeAttr("dynamic-name");
          $compile(element)(scope);
      }
   };
});
 
What i still don't get is that if interpolation fails then why am i able to see the name in the html markup when i inspect the element

**Comment by pkozlowski-opensource** [comment]
@p09 Thnx for reporting and providing a plunk but there is a _lot_ of code in your sample.... Could you please reduce it to the minimal scenario, removing all 3rd party dependencies (you are saying that you believe that it is AngularJS issue, it should be reproducible without 3rd parties). Otherwise it is rather hard to see what is going on and we might be obliged to close this one as a general support question that is better asked on the dedicated support channel (https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question)

**Comment by gkalpak** [comment]
It is indeed a bug/unsupported feature of the [angular-validation][1] module, which can't handle that kind of dynamic names (it could, but it isn't).
<sub>Without looking too deep into it, it is using `element.attr('name')` instead of `attrs.name` at a point in time that the element's `name` attribute has not yet been updated with the result of the interpolation, whereas the `attrs` `name` property has.</sub>

--
I could make your example work by adding something like `element.attr('name', attrs.name)` somewhere: [Updated Plnkr][2].

So, the point is that this is not related to Angular core.

[1]: https://github.com/ghiscoding/angular-validation
[2]: http://plnkr.co/edit/WTYfLQreSHfwfKi0DoPP?p=preview
