### ISSUE TITLE
Execute a function all the time

### ISSUE THREAD

**Issue by MartelBenjamin** [angular/angular.js#11738]
Hi, i have a question that i can't find the answer.

How can i do to execute a function all the time ?
I have a function who modify the menu and i would it to be executed every scrolls, clicks on button , etc ...
In fact i would change the menu to appear/disappear submenu in function of the position on the page like the following site : http://getbootstrap.com/components/#glyphicons.
If you scrolls the menu changes automaticaly.

Thanks :)
Ben

**Comment by pkozlowski-opensource** [comment]
Not sure what you mean by "all the time" but you can surely execute a function on each $digest look by doing `$scope.$watch(function() { ... })`. Based on your description, though, this might not be what you are looking for since your use case more suggest executing sth in response to DOM events. In this case you can write a custom directive, register DOM even listener and call a function in a listener.

Anyway, this is a general support question and as such should be asked elsewhere: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by MartelBenjamin** [comment]
Ok thanks
