### ISSUE TITLE
Bindtocontroller should be deprecated. Isolate scope should be available to the locals that can be injected.

### ISSUE THREAD

**Issue by SanderElias** [angular/angular.js#11731]
Somehow this one slipped trough. 
Is there an technical reason that makes isolate scope so special that it needs it's own property on a directive definition object?
It makes much more sense API wise to make it available to the locals, so it can be injected explicitly.

**Comment by gkalpak** [comment]
Mind to clarify what you mean ? I don't get. Why deprecate `bindToController` (especially now that it also supports non-isolate objects). And how would you specify the type of scope if you remove the DDO attribute ?

**Comment by SanderElias** [comment]
Sure, I should have added an example. I will think one up, and try to add that on thuesday, when I'm back at the office.
I want to remove the attribute `bindToController` not the `scope` attribute. (I think that should be removed/renamed too, but that's a bridge too far), so the way you define what kind of scope you want does not change.
First of all, (not a proposal, we can't change it anymore..) isolateScope should have been called ParsedDataFromAttributes. It would be way less messy at what we have now. 

It will help with migrating to 2.0 if we put way less attention to scope, and more to controllers. There are a number of steps that can help here, but as a first step, this is as good as any other.

Also, hooking up isolate scope data to the `this` of a controller feels like a hack. And as a source of confusion for starters. We have an excellent $injector available, why not use that to inject the $isolateScope  into the directives controller? And while we are at. why not make it like this:

```
function SomeDirectiveController($parsedAttribs,$directiveLocalData) {
  // $parsedAttribs // former isolate scope, the part that holds the parsed attrs
  // $directiveLocalData  // former isolate scope without above. Perhaps better called $ElementLocalData
}
``` 
We might use $isolateScope, but while we are working on it.....

So, I want to deprecate `bindToController`, not because it's an bad idea, but because it not belongs on the DDO. There is an `$injector` that can provide the exact same thing.
Does this makes sense to you?

**Comment by gkalpak** [comment]
To be honest, it's still not 100% sure what you are proposing (with `$parsedAttribs` and `$directiveLocalData`) and how it is different from what we have now (apart from renaming stuff and removing `bindToController`), but:

* What (I think) you propose is already possible, by omitting `bindToController` and injecting `$scope` into the controller.

* The convenience of `bindToController` is that it attaches the (isolate or not) scope properties onto the controller's `this`, which saves you the troublt of having to do it yourself in every controller (in order to make it availalable wherever the controller instance is used; e.g. the view, the linking functions, other requiring directives etc).

**Comment by SanderElias** [comment]
@galpak you first point is correct, but not $scope, $isolateScope in stead. $scope is already available to the injector.
To you second point. That is exactly the problem. It should be provided by the $injector, not by some extra functionality hooked up to the DDO.

**Comment by gkalpak** [comment]
In a sense, `$isolateScope` is already available to the `$injector`: it is the `$scope` you get injected on isolate-scope directives.

Regarding the 2nd point, do you mean that the `$injector` should bind the properties on the controller instance ? Why is that the `$injector`'s job ? It's not the injector that instantiates the controller.
Besides that, it is (imo) part of the definition of the directive what properties you want to bind where (because the directive (not the `$injector`) knows where it wants to reference them).

**Comment by Narretz** [comment]
I think it's too late in Angular 1.x lifecycle to make such drastic changes. Imo, bindToController is now a well known and tested mechanism. With the new component helper, we are also hiding much of the implementation. Imo, in Angular 1, there will always be a certain clash between the injector and other mechanisms.
