### ISSUE TITLE
Potential issue in the documentation

### ISSUE THREAD

**Issue by gcoutable** [angular/angular.js#11768]
Hi,

I was looking for some documentation about ngOption and I found this potential issue.

Here is a caution that warns us to do not use 'as' and 'track by' in the same expression :
https://github.com/angular/angular.js/blob/master/src/ng/directive/ngOptions.js#L61

But the next example, uses 'as' and 'track by' in the same expression :
https://github.com/angular/angular.js/blob/master/src/ng/directive/ngOptions.js#L67

Is that normal?

Regards,

Guillaume

**Comment by gkalpak** [comment]
@gcoutable, it's an _"anti-example"_. It basically showcases what you **shouldn't** do and explains why it's not possible. In that sense, it's _OK-ish_.

Reading the explanation though, it seems that - while `item.a as item.b for item in items track by item.c` is not possible - using `item as item.b for item in items track by item.c` **should** be possible.

@petebacondarwin, should the documentation be updated (since the later is the most common usecase imo). I can't think of a good way to describe that when using `track by` and `select as` the `select` part should be the item itself.

**Comment by petebacondarwin** [comment]
The documentation should indeed be improved. I will take a look today as I am messing with `ngOptions` anyway.

**Comment by petebacondarwin** [comment]
I don't have time to do this. Would anyone else like to provide a PR?

**Comment by ryanhart2** [comment]
I submitted pull request #12999 to address this.

**Comment by Narretz** [comment]
The PR has been merged IIRC
