### ISSUE TITLE
ng-jq only works on html tag

### ISSUE THREAD

**Issue by TheBelgarion** [angular/angular.js#11779]
I tried the new tag 'ng-jq' to disable trying to use my very old jQuery lib

<div  ng-jq ng-app="myApp"> (not working)

<html ng-jq ...> (working)

In my case I tried to improve a small module in a very old Joomla page so changing the layout template is not really a nice way to do it - would be better if I could use ng-jq on the app tag too)

AT least the description stated it not madatory to do it in the <html> tag

tried with: 1.4.0-rc.1

**Comment by kentcdodds** [comment]
I'm guessing this is your issue. Compare [this jsbin (not working)](http://jsbin.com/vobilo/edit?html,js,output) to [this jsbin (working)](http://jsbin.com/firaju/edit?html,js,output). The difference is where angular is being loaded. I'm guessing that you're placing the `angular` script on the page BEFORE the element with the `ng-jq` tag. I'm guessing that the issue is that at the time `angular` loads, it will look in the DOM and try to find `ng-jq`. Because that part of the DOM hasn't been loaded yet, angular doesn't find it.

So your solution is to make sure that the element with `ng-jq` appears BEFORE the script tag that loads angular.

Perhaps I'll make a PR to update the docs to point out this issue. Good luck!

**Comment by caitp** [comment]
That's right. Unfortunately this info needs to be known before the document is ready, so it needs to be an early element

**Comment by kentcdodds** [comment]
Ah, and another alternative would be to simply place the jQuery script AFTER the angular script. You wouldn't need the `ng-jq` script on the page at all for this solution.

**Comment by TheBelgarion** [comment]
Ha, yes that makes sense, was somehow thinking it inits after domread but guess it need to run earlier for all the gimmicks ..

@kentcdodds I think there was some talk why loading jQuery after angularJS doesnt work in all cases
e.g. some code simple uses  <pre>if (!jQuery) {...} else {jQlite}</pre>  

issue relates to #11647 ( just found that now)
