### ISSUE TITLE
 filterFilter doesn't work with Array like objects anymore

### ISSUE THREAD

**Issue by superasn** [angular/angular.js#11782]
*filterFilter* also doesn't work with Array like objects anymore, like it used to before.

Please take a look at this fiddle:

Works like it should with previous version of Angular (v1.2):
https://jsfiddle.net/superasn/gznzjgmb/ 

Breaks with newer versions of Angular (v1.3 and above):
https://jsfiddle.net/superasn/c15yvq6g/

**Comment by petebacondarwin** [comment]
@gkalpak can you take a look at this one?

**Comment by gkalpak** [comment]
Will do.

**Comment by gkalpak** [comment]
A little background: 

* This was/is **not** working on 1.2.x. In fact, "array-like" objects have not been supported since `v1.1.3`.
* In this context, "array-like" objects are objects prototypally inheriting from Array (so **not** what Angular internally refers to as "array-like" (i.e. objects for which `isArrayLike()` returns true)).
* Pre v1.1.3, `filterFilter` was checking whether `array instanceof Array` (which included "subclasses" of Array). Then is switched to `Object.prototype.toString.call(array) === '[object Array]'` and later to `Array.isArray(array)`.

--
That said, I don't see why we couldn't support array-like objects (in the internal Angular sense). It seems to be a trivial change.

@gonzaloruizdevilla has already submitted a PR (#11787) we can work on, so let's move the discussion there.

**Comment by caitp** [comment]
isArrayLike is basically, you have an integer-valued "length" property. Prototypically inheriting from Array won't give you magic "length" behaviour, so unless you override it manually, your length is 0. For proper subclasses, Array.isArray() returns true, so it's a moot point

**Comment by petebacondarwin** [comment]
One can ducktype an array for one's own purposes without it being a proper subclass and still like Angular to treat it like a collection in some cases.

**Comment by caitp** [comment]
I don't think you understand, this already works. All they need to do is set the length property to what they want.

**Comment by caitp** [comment]
The one fix I'd suggest is getting rid of this `length > 0 && (length - 1) in obj` crap, which is nonsense

**Comment by caitp** [comment]
https://jsfiddle.net/dzkgxa68/ here's a proper version of the 1.3 repro posted above which works correctly, by subclassing the array "properly"

**Comment by caitp** [comment]
Sorry, to expand on what I was saying above, I mean "the one fix" reguarding what constitutes an array-like object. But yes, the "isArray()" test is crap in filterFilter

**Comment by gkalpak** [comment]
@caitp, still not sure what you suggest :)

This doesn't work as is (because of the `isArray(array)` check and `array.filter`).
I suggested replacing `isArray` with `isArrayLike` and `array.filter(...)` with `isArray(array) ? array.filter(...) : Array.prototype.filter.call(array, ...)`.

Are you saying something different ?

--
Regarding the `length > 0 && (length - 1) in obj` check in `isArrayLike`, I agree it is useless, but doesn't hurt either (other than slowing it down). I would be fine removing it.

**Comment by caitp** [comment]
> but yes, filterFilter should replace isArray() with isArrayLike(), I guess.

**Comment by gonzaloruizdevilla** [comment]
@gkalpak I don't think the `typeof length === 'number' && length > 0 && (length - 1) in obj` part is useless.
Actually, my PR #1938 with the first `isArrayLike` implementation was meant to distinguish between arrayLike objects and other objects with a numeric `length` property.

It's funny to see how today's implementation is so similar to the one I PR those days. @IgorMinar had to make a difficult implementation due to IE8 support in those versions (ec54712)
