### ISSUE TITLE
ngPluralize setting when property via directives link function causes rules to not be detected

### ISSUE THREAD

**Issue by MikaAK** [angular/angular.js#11792]
While in a directive, If you try to set ng-pluralize's `when` via an object defined in the `link` function it will throw `ngPluralize: no rule defined for other`. However if you use the `controller` it will work perfectly fine. 

I've created a  [Plunker Example](http://plnkr.co/edit/6rX8nmAOcP9QQpO4em0J)  demoing this behavior.

**Comment by gkalpak** [comment]
This is expected behaviour (imo), since the controller is instantiated before the child-directive's post-linking, while `link: fn` (which is short for `link: {post: fn}`) is executed **after** the child-directive post-linking phase.

If (for whatever reason) you don't want to use a controller, you can use the parent directive's pre-linking phase:

```js
return {
  ...
  link: {
    pre: function (scope) {
      ...
      scope.postItem = {...};
    }
  }
};
```

**Comment by Narretz** [comment]
@gkalpak is right!
