### ISSUE TITLE
Need Intellisense like $scope.$watch or $scope.$on etc.

### ISSUE THREAD

**Issue by rdpatelcygnet** [angular/angular.js#11799]
Hi,

We use AngularJs extremely in our product development and we need full IntelliSense support.
Can you provide IntelliSense support in you next release like If I want to use $watch with $scope then $watch gets populated in IntelliSense list.Can you provide IntelliSense for $on , $broadcast  and so on.

**Comment by matthiasg** [comment]
who exactly should provide intellisense ?

angular is just a library not an editor. they only thing they could do is potentially offer typescript definition files which would allow tools to show intellisense-like information, but thats what  angular 2.0 is doing anyway you might look there but 2.0 is far from production ready.
 
since i do not expect nor want angular 1.x to be rewritten in typescript though i think this will not happen in 1.x.

**Comment by kentcdodds** [comment]
You might look into the [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) project with [angularjs definitions](https://github.com/borisyankov/DefinitelyTyped/tree/master/angularjs). I've not used it, but, depending on your editor, you should be able to point your editor to those definitions and get intellisense support.

**Comment by petebacondarwin** [comment]
@matthiasg is to be right here. I don't quite understand what you want @rdpatelcygnet - it might be that you would be better contacting your editor/IDE manufacturer to ask them to implement this support. But as @kentcdodds points out the best we could probably do to support such a feature is to provide better type information. Unfortunately, things like $scope are almost impossible to type in the current version of Angular 1.x so this is not likely to happen here.

**Comment by martinmcwhorter** [comment]
Using TypeScript with the DefinitelyTyped angular type definitions gives you intellisence.

**Comment by Narretz** [comment]
I'm closing this. It's not clear what the request was, and there has been no feedback.
