### ISSUE TITLE
Poorly specified API for linking a directive multiple times

### ISSUE THREAD

**Issue by bcherny** [angular/angular.js#11824]
When I link a directive, the behavior is different depending on whether I pass in a [`cloneConnectFn`](https://github.com/angular/angular.js/blob/master/src/ng/compile.js#L1267) or not. If I do pass in a function (even if the fn doesn't do anything), I can then consume the cloned node synchronously or asynchronously. Otherwise, I can only consume the original node.

The sync and async return values are *the same*, so there is no reason to expose an async API at all.

The, #link should always return the node synchronously, and accept a `doClone: Boolean` flag to control whether or not the node should be a clone or the original.

Plunkr: http://plnkr.co/edit/M6kuPSTHKEwodO4JJ0J8
SO post: http://stackoverflow.com/questions/29958723/speeding-up-angular-compile-function

**Comment by gkalpak** [comment]
As pointed out in the [SO question][1] there is no synchronous vs asynchronous behaviour.
The call to `cloneConnectFn()` is synchronous as well.

I suspect that the function has to be passed in as a callback (instead of just a `doClone` boolean), because `cloneConnectFn()` should be called **before** calling [`compositeLinkFn()`][2].
But, I am just guessing here, so someone with more insight on the compiler internals could confirm.

[1]: http://stackoverflow.com/questions/29958723/speeding-up-angular-compile-function#comment-48291146
[2]: https://github.com/angular/angular.js/blob/master/src/ng/compile.js#L1313

**Comment by petebacondarwin** [comment]
@gkalpak is correct here. It is all sync and the callback needs to occur at a specific point:

* In the case where we do not clone the node, we just simply link the original compiled node to the scope (using the `compositeLinkFn`). We then return the original node to be nice :-)

* In the case where we do want a clone of the node, we need to attach this new clone to the DOM before we link it to the scope (using the `compositeLinkFn`). We then return the newly cloned node, again to be nice :-)

In both cases we could have not returned anything from the `publicLinkFn`, since you could get it either from the node that you compiled or from the `cloneAttachFn`.

It may be that the docs for the linking function could be made clearer on this but otherwise I am closing as invalid.

**Comment by bcherny** [comment]
Makes sense, thank you for the explanations!
