### ISSUE TITLE
ng-repeat not functioning if ng-init contains repeated values

### ISSUE THREAD

**Issue by surezram** [angular/angular.js#11827]
Below code is not working

```html
<div ng-app="" ng-init="names=[1,2,3,4,1]">
  <p>Looping with objects:</p>
  <ul>
    <li ng-repeat="x in names">
      {{ x }}
    </li>
  </ul>
</div>
```

**Comment by gkalpak** [comment]
This works as expected. It throws an error, because `ngRepeat` can't handle duplicate objects, unless you exlicitly tell it how to distinguish between them (read more about it in [the docs][1]).

E.g. you could change it to `ng-repeat="x in names track by $index"` and it will [work as expected][2].

--
That said, this is a general support question. In the future, please direct such question to the [appropriate channels][3]. GitHub is reserved for bug reports and feature requests.

[1]: https://docs.angularjs.org/api/ng/directive/ngRepeat#tracking-and-duplicates
[2]: http://codepen.io/ExpertSystem/pen/MwaZLr
[3]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by surezram** [comment]
Thanks.
