### ISSUE TITLE
Send event only to targeted directive

### ISSUE THREAD

**Issue by junajan** [angular/angular.js#11864]
It would be great to have some tool to send events only to specific directive, something like:
```javascript
 $directive("timeAgo").$event("hearthbeat", new Date().getTime());
```
Usecase example: I have one service, which translates dates to more human readable format like "one second ago". In view, there is directive which is calling this service for translation but if I want to update translations in time I have to use $interval in each instance of directive or $broadcast hearthbeat to rootScope and listen on it with directives..

**Comment by shahata** [comment]
what about something like this instead: http://plnkr.co/edit/DEJvpPxq7DH7rrxBTzDP?p=preview

**Comment by junajan** [comment]
But it would perform computation (selecting translation code based on timediff) every digest cycle.. 

Finally I managed it with service which $emits each 10 000ms hearthbeat event to $rootScope and directives that are listening on this and in case of destruction removes its listeners. But it is messing $rootScope and filter approach would be much prettier..

**Comment by shahata** [comment]
I would go with the filter approach, calculating those strings on digest doesn't sounds too expensive plus you could optimize using memoization/debouncing if it is very important. Anyway, I'm closing this since I don't see additional value in broadcasting to specific directives over broadcasting to rootScope.
