### ISSUE TITLE
asynchronous $parsers

### ISSUE THREAD

**Issue by nikoudel** [angular/angular.js#11918]
I'm missing something like $asyncParsers. Tried to [ask](http://stackoverflow.com/questions/30352106/converting-viewvalue-with-an-async-function-call) this on SO but no replies so far.

In my case user input (localized datetime) needs to be parsed on the server side and the result (a javascript Date object) should then replace the current model.

$asyncValidators can handle the validation part but what about model modification, is there some way to handle that?

**Comment by jminuscula** [comment]
I've asked a [similar question](http://stackoverflow.com/questions/32789172/angular-directive-with-async-parser-getting-modelvalue-from-api) too. What is the current recommended way to get around this?

**Comment by afreeland** [comment]
Any love for this yet?

**Comment by gkalpak** [comment]
Nope :smiley:

Supporting this, would require significant changes to the already complex `ngModel` pipeline (which includes parses, formaters, sync and async validators, debouncing etc). 
Since there hasn't been much interest around it, I don't see it happening any time soon, but if anyone wants to give it a go and submit a PR, we would be glad to take a look and consider it (no promises though).

**Comment by afreeland** [comment]
@gkalpak  I figured so, with such low interest but thanks for the quick response.  I actually just stumbled upon the $parses and $formatters  parts of the pipeline will definitely add them to the tool set =)
