### ISSUE TITLE
$sceDelegate is too grabby on src attributes

### ISSUE THREAD

**Issue by royaldark** [angular/angular.js#11931]
I ran into a counterintuitive issue today with `$sceDelegate` and `src` attributes. It seems `$sceDelegate` will block what it considers insecure interpolations on any attribute named `src` on any directive - even custom ones. Here's the scenario:

We have a lazy image loading directive called `kbLazyImg`. It utilizes a jQuery-based lazy loading library, and has been working great. A typical use looks like this:
`<kb-lazy-img src="{{ url }}" width="40" height="40"></kb-lazy-img>`

The directive expands to a plain `<img>` tag like this:
`<img data-original="{{ src }}" width="{{ width }}" height="{{ height }}" />`

This has been working great for us for several months. Today, however, I updated many of our image assets to serve over HTTPS rather than plain HTTP. As soon as I did, `$sceDelegate` began throwing `insecurl` errors: 
```
11:43:43.416 Error: [$interpolate:interr] Can't interpolate: {{ user.avatar }}
Error: [$sce:insecurl] Blocked loading resource from url not allowed by $sceDelegate policy.  URL: https://s3.amazonaws.com/our-bucket/image.png
```

The `insecurl` error seems very odd, since the presence of the `src` attribute on `kb-lazy-img` should not make the browser load any remote resources. In fact, that image shouldn't be touched by Angular at all. The `src` attribute is just a string, which happens to contain a secure URL, and our jQuery lazy load library should be the one actually requesting the image. 

Changing `src` to another name like `kb-src` makes everything work as expected, so it is obviously the presence of the `src` attribute that causes issues.

Does `$sceDelegate` block all interpolations of (non-whitelisted) HTTPS URLs on `src` attributes on all directives? That appears to be what is occurring, and I would consider that overzealous.

**Comment by Narretz** [comment]
Here's why: https://github.com/angular/angular.js/commit/38deedd6e3d806eb8262bb43f26d47245f6c2739. It's a security mechanism that prevents iframe, object etc. src attributes from being made up of more than one expression, which can more easily casue XSS. A side effect of this is that the interpolation result gets matched against the allowedUrl whitelist.
I'm not sure if the condition for this could be hardened to explicitly include `object`, `iframe` and anything else that can load resources via `src`, or if there was a reason to do it like this.
Since a) the workaround is pretty easy, and b) it's recommended to use prefixes for your own directives anyway, and c) replace is deprecated I'd say it's pretty low priority. But PRs are welcome.

**Comment by gkalpak** [comment]
I agree with @Narretz. Relaxing the policy would make me feel uneasy.
Considering it is a rather uncommon issue and it is pretty easy to work-around this, we shouldn't make any changes that might have security implications.

You should either prefix/use a different name for your directive's attribute or explcitly trust the values as RESOURCE_URL (either per value via `$sce.trustAsResourceUrl` or using `$sceDelegateProvider.resourceUrlWhiteList`).

I'm going to close this as we are unlikely to make any change, but if someone feels strongly about it, feel free to submit a PR and continue the discussion there.
