### ISSUE TITLE
ng-repeat-start and track by $index weird order behaviour

### ISSUE THREAD

**Issue by Devqon** [angular/angular.js#11951]
When using an ng-repeat-start (or just ng-repeat) in combination with a `track by $index` and an `unshift()` action on the collection, the new element is inserted **after** the first one (when a 'bot' message is inserted after another).

See [this jsfiddle](http://jsfiddle.net/t6x3a1zj/13/)

The css says that the first element needs to be animated when `ng-enter` is applied, but it doesn't when the `track by $index` is used (first example). After deleting the `track by $index` (second example) it correctly inserts the element as the first item of the unordered list.

**Comment by gkalpak** [comment]
I don't really get what the fiddle is supposed to do, but it sounds like it's working as expected (because of how `$track by $index` works.

`$track by $index` will "reuse" the same DOM elements, because it is tracking them by `$index` (and an element for the same `$index` already exists). Thus it will only update the contents o the element, but will not remove it and create a new one (thus no `ng-leave/ng-enter`) operations).

So, if you don't want that behaviour, don't `$track` by `$index` ?

**Comment by lgalfaso** [comment]
Agree with @gkalpak this is working as expected.

**Comment by Devqon** [comment]
Okay my mistake then. Thanks for the explanations! I misassumed that `track by $index` was for tracking by index of the **array**.

This issue then can be closed :)
