### ISSUE TITLE
XSRF mechanism is problematic on shared domains

### ISSUE THREAD

**Issue by mkowalchuk** [angular/angular.js#11999]
Angular's built-in XSRF protection mechanism seems to break down if you have multiple 'XSRF-TOKEN' cookies, because Angular's $http service only sends the first one it finds to the server, and that's not guaranteed to be the right one.

This can happen in shared-domain hosting environments, where multiple sites are hosted in different subdomains of the same domain.  For example, suppose that 'test.com' offered subdomains to the world, and you were running an Angular site on 'a.test.com', using cookies named 'XSRF-TOKEN' that were scoped for '.a.test.com'.  'b.test.com' could come along and issue its own 'XSRF-TOKEN' cookie to all of '.test.com', and then any user who had visited both 'a.test.com' and 'b.test.com' would have two 'XSRF-TOKEN' cookies.

We fixed this in my project by disabling Angular's built-in XSRF token mechanism and replacing it with a custom one that expects multiple 'XSRF-TOKEN' cookies, and pushes them all to the server as a single HTTP header. Our server-side XSRF token processor had to be updated to expect multiple values in the HTTP header, and to accept requests that have at least one valid token Perhaps Angular's built-in XSRF token forwarder could do the same thing.

**Comment by gkalpak** [comment]
What I do in such cases is changing the default `xsrfCookieName`/`xsrfHeaderName` per app (see [`$httpProvider.defaults`][1]). Besides being much easier to impement (as it's builti into Angular), it should be more secure than accepting any valid token (if I understand the usecase correctly) ?

[1]: https://docs.angularjs.org/api/ng/provider/$httpProvider#defaults

**Comment by mkowalchuk** [comment]
That should protect you from accidental collisions (assuming you choose a distinct enough cookie name), but there's still some risk from malicious/intentional collisions.

**Comment by gkalpak** [comment]
Truth is I do it on domains I have full control over, so no malicious collisions for me :)
But how does sending all tokens protect you from that ?

**Comment by mkowalchuk** [comment]
Suppose that these are your cookies:
'.test.com' -> '(malicious cookie)',
'.a.test.com' -> '(my valid cookie)'

Currently, Angular will send $http requests with 'X-XSRF-TOKEN' set to '(malicious cookie)'. At least, it seems to do that in Chrome and Firefox.

If Angular sent both '(malicious cookie)' and '(my valid cookie)', your server-side filter would have a chance to inspect both and see that one of them was valid. It'd have to send both because the client can't tell which one is valid -- JavaScript can't even see the 'domain' property on the cookies.

Anyway, I don't mean to say that sending two cookies is the *only* way to handle this scenario (e.g., you can pass the token in your initial HTML page, or in an HTTP response header), it's just the most backwards-compatible way that I could think of.

**Comment by mprobst** [comment]
Just to be clear, the malicious scenario would allow an attacker who controls an app on a domain that your code runs under, or a sibling domain, to DoS your app, prevent AJAX requests from succeeding. There is no ability to tamper with or steal data.

**Comment by gkalpak** [comment]
@mprobst: Why not ? Doesn't it depend on your implementation ?

The way I understand it, the problem is that the malicious website could send requests to your app which look as coming from your wepsite (because it has access to your token). What is the result of these requests is up to your implementations (it could be anything from stealing data, to performing actions etc).

--
@mkowalchuk, the greatest danger with a milicious website on the same domain, is not preventing your app from properly recognizing the valid requests as valid, but not being able to recognize invalid requests (as described above).
And accepting any valid token, does not prevent the latter.

DISCLAIMER: I don't know much about XSRF.

**Comment by mprobst** [comment]
@gkalpak if you restrict your cookie to your full domain name, it won't be sent to the attacker's domain. The only thing that's possible is that an attacker injects their own XSRF token into your requests, which at worst invalidates requests.

**Comment by gkalpak** [comment]
@mprobst, is (naturally) right :smile: Sorry, for the noise :disappointed: 
(I just realized I was talking more about cases where the domain is the same and you are serving a different app on different paths.)

**Comment by IgorMinar** [comment]
The impact of this issue can be categorized into two groups:

1. as @mprobst and @gkalpak mentioned, an attacker could use this issue to create a DoS for an app. But it would not be possible to use this issue for information theft. 
2. two or more apps sharing a domain could interfere with each other if at least one of them publishes XSRF cookie on the shared domain.

As proposed, sending all the possible XSRF cookie values is an option. Especially since there is no way for us to determine which cookie is more specific -  we can't retrieve information about domains or paths a cookie is associated with or infer the specificity of the cookie from the order in the cookie string (see the [cookie spec](http://www.ietf.org/rfc/rfc2965.txt) which explicitly states that order of key-value pairs is undefined for cookies with the same key but different domain).

On the other hand even if we were to send all possible tokens, an attacker could flood the cookie storage with bogus cookies and prevent the XSFR cookie to be stored in the first place (the cookie storage is limited to a small number of bytes/key-value pairs per domain). This would lead to the very same DoS using an attack vector that we have no way of dealing with on the client.

This makes me believe that the proposed solution to send all the cookies would not solve the first (DoS) aspect of the issue. And considering the browser cookie api, I don't think that Angular should even try to solve this problem.

The second aspect - accidental collisions - can be solved by requiring each app on the shared domain to use custom `xsrfCookieName` as @gkalpak pointed out early on.

Depending on the organization, the enforcement of this might be hard, but that's not such a big deal, because the apps that do use custom cookie name, can't be interfered with by accident.

Am I missing anything else?

**Comment by mprobst** [comment]
@IgorMinar it might be worth mentioning as we discussed that implementing something like sending *all* cookies would allow recognizing and fixing the problem on the server side, but of course require server side changes for apps. At that point it might be easier to just change the cookie name, which is also a server & client side change, but likely less invasive.

With that in mind, even fixing this by sending all cookies doesn't seem worth the effort. The best approach is probably to track down whoever is *'poisoning'* your shared environment, and getting them to stop it (assuming all the apps underneath a shared domain are indeed from one organization, which I assume is likely).

**Comment by mkowalchuk** [comment]
@IgorMinar, good point - I didn't realize that the cookie storage could be flooded. It sounds like intentional cookie interference could occur just as easily with other cookies, e.g., session cookies, so the generalized problem isn't really AngularJS-specific. I guess there really does need to be a degree of trust in shared-domain environments.

**Comment by IgorMinar** [comment]
@mkowalchuk yeah, I think so too.
