### ISSUE TITLE
ngAnimate disrupts correct validation of input type email

### ISSUE THREAD

**Issue by JPtenBerge** [angular/angular.js#12007]
Hi there,

With the newest version (1.4.0) it seems that email validation does not fully work correctly when the ngAnimate module gets included. Check out this Plnkr: http://plnkr.co/edit/mRvFhnpgZCKTI1YPWqkT?p=preview.

Try entering a value like '@@@', '|||' or 'qqq'. The model value only gets updated when a true valid value is entered, but the ng-valid/ng-invalid classes get applied wrongly. Removing the ngAnimate module as a dependency and the ng-valid/invalid classes work just fine.

I'm experiencing this on Windows 7 and 8, in IE as well as Chrome and Firefox.

JP

**Comment by Narretz** [comment]
@matsko Wasn't there a similar bug that was already fixed? Or is this the same problem?

**Comment by Narretz** [comment]
This seems to be the same issue: https://github.com/angular/angular.js/issues/11652

**Comment by gkalpak** [comment]
It is quite similar, but I don't think it is the same issue, because #11652 has been fixed ([demo][1]), but this one is still [reproducible on master][2].

Also, the wrong behaviour is different: This one seems to incorrectly apply the valida classes every 3 keystrokes, even if the value is invalid. Weird and interesting :)

[1]: http://jsbin.com/tiwijowiza/3/edit
[2]: http://plnkr.co/edit/3YyAnVQWT5E7NImPdB2e?p=preview

**Comment by matsko** [comment]
This is now fixed in master courtesy of @sreeramu.

**Comment by matsko** [comment]
1.4.4 will land next week as well.
