### ISSUE TITLE
Cancelling *chained* animations does not really work in 1.4.0

### ISSUE THREAD

**Issue by dmitri777** [angular/angular.js#12039]
the command $animate.enabled(false) is not preventing promise function specified in ".then" part of animation statement from being executed. It starts eternal loop of successive calls.

Here is my simple Plunker:

http://plnkr.co/edit/MmEJfAfJ3k0cbImfD2qa?p=preview

First, you start chained animations by clicking a button. So far all runs fine.

Then you try to stop it ( $animate.enabled(false) ), and it goes totally crazy... Just see the Plunker!

**Comment by matsko** [comment]
So it turns out that this works as expected. The reasoning is that even if animations are disabled, the trailing `then` callback is always handled. This is to allow directives to issue code to run after the animations are all over even if nothing runs or is detected.

So in this situation, the disabled state just skips the animation from running at all which then calls the then callback which then repeats the whole process.

If you want your code to not continue animating then you'll need to have an if statement check `$animate.enabled()` to see if it's allowed before recursively continuing.

**Comment by dmitri777** [comment]
Thanks Matias for your explanation! I still have two questions related to this topic:

1) is there a way to freeze the animation that is currently underway, like, when it is 50% done? In my Plunker, as you can see, freezing is not taking place, and putting "if" into "then" block will obviously not change anything. JQuery, for example, has "stop" method that has corresponding flags to control it.

2) what is correct, kosher way of resuming chained animations? If I just start $animate.animate(..) again, I - sometimes - get eternal loop, even with "if" in "then" block correctly used as you suggested...
