### ISSUE TITLE
Error at Angular 1.2 Copy

### ISSUE THREAD

**Issue by San4oPanso** [angular/angular.js#12034]
Warning: 
Attr child nodes are deprecated and will be removed in M45, around August 2015. Please use 'Attr.value' instead.
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/4Hg0l42QHH0/H59LyoiJlI4J

angular.copy -> line: result = copy(source[key], null, stackSource, stackDest);
And error which i haven't seen before there
Error: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('checkbox') does not support selection.

Angular v1.2.28; Chrome v43

**Comment by caitp** [comment]
You won't be able to use `copy()` for DOM objects in Chrome in general anymore once M44 or M45 is reached, because they've fixed the bug of making IDL attributes own properties.

You should not be relying on `copy()` for anything DOM-related, it won't do what you want it to do, and is potentially unsafe.

**Comment by caitp** [comment]
I would say we should throw an error, but there are so many DOM interfaces, and it's an ever-growing, hard-to-maintain list. So realistically all we can do is remind people not to do the wrong thing.
