### ISSUE TITLE
loading jquery after angular.js

### ISSUE THREAD

**Issue by parliament718** [angular/angular.js#12033]
I'm experiencing an issue with ngDraggable library that is immediately solved by loading jquery.js AFTER angular.js. This issue: fatlinesofcode/ngDraggable#119 (comment)

Although doing so fixes all the issues with that library, is then breaks my entire code base (tons of console errors including a [Error: jqLite:nosel]).

Does the angular community have any insight into why this may be happening? Could it be that angular.js is overwriting or hidding funtionality in jquery, such that loading it after jquery causes ngDraggable to break?

**Comment by gkalpak** [comment]
Angular comes with a tiny subset implementation of jQuery, jqLite. If jQuery is loaded when Angular bootstraps, it will use that instead of jqLite. `angular.element` will then be an alias for `jQuery` (instead of `jqLite`).

jqLite tries to stay close, but it's not 100% API compatible with jQuery (and ad already mentioned it's a smaller subset of methods).

According to the issue yoy link too, latest vrrsions of `ngDraggable` seem to not be jQuery compatible (which is kind of strange, but...), so it needs jqLite in order to work properly.
Othet stuff on your app, though, seem to need jQuery in order to work properly and thus break if you load jQuery after Angular (which forces Angular use jqLite).

It sounds like something to be addresses on the `ngDraggable` side.

I will close this for now, ad there is nothing actionable, but feel free to reopen (or open a new issue) if it turns out to be an issue with Angular core.
