### ISSUE TITLE
ngClass wrong evaluation of function call

### ISSUE THREAD

**Issue by Fidel90** [angular/angular.js#12093]
I am using a function from a controller to evaluate a class for my button. The function evaluates expressions like `true && !true` correctly to `false` and returns that. Anyway my ngClass on the button evaluates to `.btn-succes` though the expression inside the button shows `false`. I'm on angular 1.3.13 at the moment and have used this pattern many times around my application without any issue.

`<button type="button" class="btn" ng-class="UserMode.Status.isSoftware() ? 'btn-success' : 'btn-danger'">
            {{UserMode.Status.isSoftware()}}
        </button>`

I tried other ngClass patterns (`ng-class="{true:'btn-success', false:'btn-danger'}[UserMode.isSoftware()]"`) as well but without any effect.

**Comment by Fidel90** [comment]
Further description: http://stackoverflow.com/q/30775365/2577116

**Comment by gkalpak** [comment]
@Fidel90, I can't reproduce the problem (not even with the info provided on the StackOverflow question). Everything seems to work as expected.

Feel free to re-open (providing a clear reproduction path), if it turns out to be a bug in Angular.
(Note that general support questions should be directed to the [appropriate channels][1]. GitHub is reserved for bug reports and feature requests.)

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by Fidel90** [comment]
@gkalpak, thanks for your fast response. I just have downloaded the new 1.4.0 and tried it again. With success. It seems like something has been changed between versions though I could not find something related in the changelogs. Anyway I'm happy that I have not made any mistake and it works fine now. Sorry for posting in the worng section as I'm new to GitHub :)
