### ISSUE TITLE
$viewChangeListeners causing equals binding to toggle incorrectly

### ISSUE THREAD

**Issue by kirschre** [angular/angular.js#12136]
[Reproducer](http://plnkr.co/edit/y150DGOb9JZIWU7HGMoW)

In this plunkr, I have a child directive that uses ngModel and has a two-way (=) bound attribute on its isolate scope. It uses an ngModel `$viewChangeListener` to set the value of the binding to false any time the model changes.

There is also a parent directive that consumes the child directive via its template. The parent directive grabs the child's ngModelController in order to add its own `$viewChangeListener`, which sets the value of the equals binding on the child to true whenever the model is changed.

When the button is clicked, it updates the ngModel, which fires the `$viewChangeListeners`. However, clicking the button multiple times shows that the attribute value is being toggled between true and false, instead of staying at the value true.

From the console output, we see that the parent's `$viewChangeListener` is registered after the child's, which is expected. Additionally, when we click on the button, the `$viewChangeListeners` are run in the order we expect, as the parent listener fires after the child listener in the order they were registered. However, only one of the listeners, whichever one toggles the value this digest cycle, is respected.

In most situations, replacing the parent's listener with a `scope.$watch` would be an acceptable workaround. However, in my use case, there are many of the child directives in the parent directive at the same time, so registering watchers for each of them could incur a sizable performance penalty over using the listeners. At the same time, it seems reasonable that both the parent and the child would use `$viewChangeListeners` to mutate a binding like this.

Is this behavior expected given this setup? If so, is there a better pattern that avoids having to watch the model value myself in order for the parent's effect on this binding to be properly respected? I was able to work around this issue by removing the equals binding in the child, and manually using `$parse` instead, but this does not seem to be a very clean solution.

**Comment by Narretz** [comment]
I think this can be explained by prototype inheritance, which is used by the scope tree. This introduces one big "gotcha", into angular, you are maybe familiar with it: if you are using primitives in child scopes, they are not set on the parent scope, instead they "shadow" the parent scope property. That is why you should always use objects for your data / models, because with them shadowing does not apply. That, and the way the two-way bindings are updated cause this problem.

So in your example, what happens is roughly as follows:

The first click sets attr to `false` on the child scope, and `true` on the parent scope. Since the last (initial) value on the parent is `undefined`, the bindings watcher sees that the parent scope value has changed. Since this takes precendence over a child change, the child value is overwritten with the parent value, and the result is as expected.

The second click also sets attr to `false` on the child scope, and `true` on the parent scope. Since the last value on the parent is already `true`, there's no need to update the child value. However, since the child value is `false`, the binding updater detects a change and updates the parent value with the child value.

The easiest solution for you is now to use an object for your binding instead of a primitive (string): http://plnkr.co/edit/gGXsQ7MmrW6mzPTYbi4U?p=preview

If you have any question, feel free to reopen this issue.
