### ISSUE TITLE
$watch not triggering the second time scrollHeight changes

### ISSUE THREAD

**Issue by natcohen** [angular/angular.js#12157]
I'm trying to `$watch` the `scrollHeight` of an element (hidden inside two tables) in a directive. The behavior is very strange; the first time the value changes, it triggers my function. The second time it doesn't and then it works for good...

The `scrollHeight` I'm watching is inside a double table:

    <table> 
      <tbody>
        <tr>
          <td ng-click="show()" style="cursor:pointer">Show Row</td>
        </tr>
        <tr>
          <td>
            <table ng-show="showRow"> 
              <tbody>
                <tr>
                  <td ng-click="showTD()" style="cursor:pointer">Show Cell</td>
                </tr> 
                <tr ng-show="showCell">
                  <td id="tracker" tracker=""> Watch that</td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </tbody>
    </table>

And my directive to watch it:

    myApp.directive('tracker', function() {
       return {
         compile : function(elem, attr, linker) {
           return function(scope, elm, attrs) {
              scope.$watch(function(){ return elm[0].scrollHeight }, function(){
                 console.log(elm[0].scrollHeight);
              });
           };
         }
       }
    });

I made a [plunker][1] to illustrate this behavior. If you open the console, you will see the following:

 - My watched cell is getting initialized and you get the first `scrollHeight` (29)
 - You click on 'Show row' and the element in your console gets displayed (so you can check the `scrollHeight` value) and the `$watch` gets triggered and displays the updated value (0) - This is correct, the element's `scrollHeight` is 0
 - Now you click on 'Show cell' and you get the element (`scrollHeight` has changed (29)) but the $watch doesn't trigger the function!?! - It's only when you click again on 'Show cell' that it gets triggered and display the wrong value of 29!

I'm sure both bugs are related (returning the wrong value and not triggering the second time...)

  [1]: http://plnkr.co/edit/C89Xqtap45Nuroz5AiLP?p=preview

**Comment by Narretz** [comment]
Definitely weird. That said, watching DOM properties is not something that is recommended, as it slows down the digest cycle. I also suspect that there's some sort of timing problem involved here that causes this behavior.

**Comment by gkalpak** [comment]
It's not all that weird (if you are aware of a couple of (documented) implementation details) :smiley:

--
#### Background:

1. `ngHide` uses `$animate.addClass/removeClass` in order to add/remove the `ng-hide` class (which is what causes the element to be hidden).
    From the docs:  
    > **Animations**
    > addClass: .ng-hide - happens after the ngHide expression evaluates to a non truthy value and just before the contents are set to visible

2. In the [docs for `$animate`][1] (both `ngAnimate`'s service and the minimal, built-in `$animate` stub) we read that:
    > the addClass/removeClass operation will only be handled after the next digest

--
#### What's really going on

Here is what is actually going on (and how it explains the observed behaviour):

1. Angular has not taken over yet, so everything looks as the raw HTML prescribes.
    `#tracker.scrollHeight: 29`

2. Angular kicks in and starts a digest loop.

3. At some point `ngHide`'s expressions evaluate to false, which results in calling `$animate.addClass('ng-hide')` on the respective elements (including #tracker's parent).
    `#tracker.scrollHeight: 29`
   (Remember that the actual DOM operation (i.e. class manipulation) will happen **after** the current digest.)

4. The watcher on #tracker's `scrollHeight` runs and determines that `#tracker.scrollHeight === 29`.
    Since it's the 1st time the watch-function is run, the watch-action is executed (and logs `29` to the console).

5. Once the digest loop is over, `ng-hide` is added to #tracker's parent, which results in `#tracker.scrollHeight` becoming 0.
    (Note that this will not trigger a digest, since it's not related to Angular. Angular still thinks that `#tracker.scrollHeight` is 29.)

6. The user clicks on "Show Row" and triggers a digest. The `scrollHeight` is still 0, but because the last value knows to Angular was 29, the watch-action is triggered again (this time storing the correct `0` as the last known value for `scrollHeght`).

7. The user clicks on "Show Cell" and triggers a digest. `ngHide`'s expression for #tracker's parent evaluates to false (resulting in `$animate.removeClass('ng-hide')`), but remeber that class manipulation happens in the post-digest phase.

8. By the time the watch-function attempts to evaluate `#tracker.scrollHeight`, the `ng-hide` class has **not** been removed yet, thus `scrollHeight` is (still) 0. No change detected ==> no running the watch-action function ==> no logging to the console.

--
Clear enough, right !

So, this only stresses @Narretz's point that _"watching DOM properties is not something that is recommended"_ (and not only for performance-related reasons) :smiley:

--
<sub>That said, if you really want to make it work, there are ways to do it. But it's still not recommended and it's outside of the scope of this answer :)</sub>

[1]: https://docs.angularjs.org/api/ng/service/$animate#addClass

**Comment by gkalpak** [comment]
I will go ahead and close this, since the observed behaviour seems to be both expected (even if not intuitive) and documented.

Feel free to reopen if there is any indication of some bug being involved (that I have missed).

**Comment by natcohen** [comment]
@gkalpak Thank you very much for the clear explanation! Do you have any workaround or best practice for such case?

**Comment by gkalpak** [comment]
@natcohen, I don't have a best practice for logging a changed `scrollHeight` to the console (i.e. it is not clear what you are trying to achieve in order to suggest a better way).

If you are trying to detect when the element is shown/hidden, I would probably use the same Angular expressions used on the `ngShow`s (or expand the logic to make it easy.
<sub>(If you absolutely have to detect the change on the `scrollHeight`, a `$timeout()` (possibly without invoking `$apply`) might be a work-around, but it's hardly recommended not a best practice.)</sub>
