### ISSUE TITLE
ng-script

### ISSUE THREAD

**Issue by dimrsilva** [angular/angular.js#12170]
Could we have a ngScript directive?

The script directive works greatful for define templates. The problem is that sometimes it generates wrong output when trying to put one template inside another, I think it is because the browser does not accept script node inside another script.

http://plnkr.co/edit/kUjVeCCy5FYGkCgeDLjV?p=preview

In the plunk above there is an example of an error and a simple directive (a simple copy of scriptDirective) to solve this issue. I am actually using it in a project.

```javascript
    angular.module('app').directive('ngScript', ngScriptDirective);

    ngScriptDirective.$inject = ['$templateCache'];
    function ngScriptDirective($templateCache) {
        return {
            restrict: 'E',
            terminal: true,
            compile: function(element, attr) {
                if (attr.type == 'text/ng-template') {
                    var templateUrl = attr.id,
                    text = element.html();
                    $templateCache.put(templateUrl, text);
                    element.detach();
                }
            }
        };
    }
```

**Comment by Narretz** [comment]
Why do you need nested ng-templates? I don't think this use case is very common.

**Comment by dimrsilva** [comment]
It's not really a common usecase, and probably a bad design of my part. I am starting Angular in an existent project.
I needed it cause I did a page with a popup, the page template defines the popup template.
I think it worth at least a reminder on docs of `script` directive.

```html
<script type="text/ng-template" id="mypage.html">
  <button ng-click="vm.openPopup()">Open Popup</button>
  <script type="text/ng-template" id="mypage-popup.html">
    <h1>Hello World!</h1>
  </script>
</script>
```
Something like it.

**Comment by Narretz** [comment]
Is there a reason why the popup template can't be a top level template?

**Comment by dimrsilva** [comment]
Not a good reason, there is a bad design on my code. I run into this problem cause I am adapting some code to Angular.
I am using Laravel Blade templates.

```html
<div ng-include="'page.html'"></div>
<script type="text/ng-template" id="page.html">
@yield('page_template')
</ng-script>
```

I could put the script tag inside of each page_template, but it will demand much work.
I did the ngScript directive to solve my problem. It was really very specific.

That's why I changed my mind about creating the directive, but I still think it worth a reminder on docs.

**Comment by dlmiles** [comment]
No this is a good idea if I understand it correctly.

I am looking for a ngScriptTemplate attribute that can be on any element and causes the child elements inside it to be added as a cached template AS WELL AS the browser to simply render the inline contents as well.

Maybe your idea of using an elements works just as well (or better) but for me a <div ng-script-template="{id:'/partial/homepage.html', param:'paramValue'}"> which a shorter form of <div ng-script-template="/partial/homepage.html"> is what I had in mind.

The common use pattern is to serve up the view template inline, so the browser simply renders it as-is, but the content are added to the cache as well (so a 2nd HTTP request is not made).

When $routeProvider looks at the state, ideally, it should not reload the contents with the cache either (if that would cause flicking, extra state changes, etc..).

The reason is because the <script> method is ignored by things that do not understand the content type (this is intended) but that also means it is ignored for the purpose of rendering it inline too, when JavaScript does not run.  For example search engine robots and other simple screen scraper applications.

So to be clear here, I am not after nested templates myself, I am after a custom attribute (or element) whichever works better, that a browser that does not fully understand angular will simply render inline.  SO this would be an alternative to the existing <script type="test/ng-template"> method but using a standard HTML element for demarcation.

**Comment by lgalfaso** [comment]
This looks as a bad idea. Mixing inert an live DOM should never be done. We are going to pass on this one. Closing

**Comment by dlmiles** [comment]
Well the obvious solution is to allow both like this:

`<div ng-view>
 <div ng-script-template="/partial/homepage.html">Welcome to the website!</div>
</div>
<script id="/partial/homepage.html" type="test/ng-template">
 <div ng-script-template="/partial/homepage.html">Welcome to the website!</div>
</script>
`

With the <script> always taking priority on populating $templateCache if it exists in the markup with the same id.  Serving the additional duplicate HTML payload is still better performing than an additional HTTP request to get it.

**Comment by lgalfaso** [comment]
You can do
```html
<! -- untested -->
 <div ng-include="/partial/homepage.html"></div>
<script id="/partial/homepage.html" type="text/ng-template">
 Welcome to the website!
</script>
```

and the same content will not be sent twice

**Comment by dlmiles** [comment]
But things that do not understand `<script type="text/ng-template">` will exclude the content because they know enough about markup to know to ignore script elements they do not understand.

And this is the point of using `<ANY ng-script-template="">` as a replacement for.

Sending the content twice is not such a major issue, it ranks in the nice-to-have feature.  So I don't need a solution for this part since that solution is irrelevant when the main point is not satisfied.

Basically the page can be rendered by the server complete, the page has `ng-view`.  Each URL can also be rendered complete (with its appropriate template already inline).

Now how to make angular more efficient:
 * The inline template can not be wrapped by `<script>` elements.  Since it is ignored by the systems we need to treat the contents as regular markup.  THIS IS THE MAIN POINT.
 * We don't want it to perform another HTTP request for the template partial (ok if I understand, I just need to populate $templateCache)
 * We don't want browser to process things twice on the initial load, i.e. no flicker, performance as best as possible (nice to have feature, maybe it is a non-issue anyway)
 * Using an angular `<script>` elements in the same page AS WELL AS would be alright, but if we can perform the same function of the `<script>` tag so we don't send the partial twice that would be a nice to have feature.

If I guess your concern (since you did not specify only talked of "this looks a bad idea" without qualifying it technically).  I guess is that the inline elements might be transformed in someway before $templateCache gets to store the content.  If this is the case then duplicating the partial (by having a `<script>`) in the HTML is a perfectly acceptable trade to me.  If transformation before $templateCache loading can happen then the last twe points above can be scrubbed from the requirements on the basis of being considered/tried but not being technically possible to do.

**Comment by lgalfaso** [comment]
> But things that do not understand <script type="text/ng-template"> will exclude the content because they know enough about markup to know to ignore script elements they do not understand.

Would it be possible to get the name and version of one supported browser that does not understand `<script type="text/ng-template">` and will execute the content.

**Comment by dlmiles** [comment]
Hmm... have I not been clear enough that the content (of `<script type='unknown/things'>` is ignored (therefore will not be executed).  So how it your question relevant ?

Also any reference to the term `browser` I use doesn't only cover that obvious desktop/mobile implementations, but I use the term as any HTTP client content consumer, things like screen scrapers (you can think of these like a search engine robot that does not execute any scripts).
