### ISSUE TITLE
Support the [property] / bind-property syntax in AngularJS

### ISSUE THREAD

**Issue by mhevery** [angular/angular.js#12198]
# Goal

In order to support the [ng2migration](https://docs.google.com/document/d/19NpH_Fzr-omI_Qm6lUt4mZW0L_f6Ksil4pTTp47AhYk/edit#) effort the AngularJS needs to learn how to process the Angular 2 property binding syntax

# Syntax Variants

* `[property]`
* `bind-property`

# Semantics

AngularJS should set up a watch on the expression and write the value of the expression to the `Attributes` class which sits on Node Element. This will allow the `ng2migration.js` to `$observe` changes not the `Attributes` and pass them onto the component controller.

NOTE: by writing the value to the `Attribute` this in essence means that AngularJS will not differentiate between the attributes / properties which Angular 2 does. Given that AngularJS semantics are to write to attributes and that it does not support WebComponents this is a reasonable approximation.

**Comment by lgalfaso** [comment]
Does Angular2 have a security model defined for expressions?

**Comment by mhevery** [comment]
@lgalfaso not yet, but we should. Would you like to work on that?

**Comment by lgalfaso** [comment]
@mhevery I am interested in working on that

**Comment by IgorMinar** [comment]
per discussion in https://docs.google.com/document/d/1xvBZoFuNq9hsgRhPPZOJC-Z48AHEbIBPlOCBTSD8m0Y/edit# I'm going to close this issue for now so that we don't give wrong impression as to what is actually going to happen. The main problem with adding this syntax into Angular 1 core is that it fragments the api/docs/etc and exposes large api surface that we'd need to maintain - which is especially challenging because of the semantical differences between Angular 1 and 2.

We can reopen this issue in the future if needed.
