### ISSUE TITLE
Support the (event) / on-event syntax in AngularJS

### ISSUE THREAD

**Issue by mhevery** [angular/angular.js#12197]
# Goal

In order to support the [ng2migration](https://docs.google.com/document/d/19NpH_Fzr-omI_Qm6lUt4mZW0L_f6Ksil4pTTp47AhYk/edit#) effort the AngularJS needs to learn how to process the Angular 2 event binding syntax

# Syntax Variants

* `(event)` / `(^event)`
* `on-event` / `onbubble-event`

# Semantics

Angular should process this markup directly in the compiler by attaching the appropriate event to the DOM without any need for a directive.

**Comment by IgorMinar** [comment]
per discussion in https://docs.google.com/document/d/1xvBZoFuNq9hsgRhPPZOJC-Z48AHEbIBPlOCBTSD8m0Y/edit# I'm going to close this issue for now so that we don't give wrong impression as to what is actually going to happen. The main problem with adding this syntax into Angular 1 core is that it fragments the api/docs/etc and exposes large api surface that we'd need to maintain - which is especially challenging because of the semantical differences between Angular 1 and 2.

We can reopen this issue in the future if needed.
