### ISSUE TITLE
Changing only part of date (input) does not change form's pristine state (Chrome)

### ISSUE THREAD

**Issue by fracz** [angular/angular.js#12207]
Have a look at this [plnkr](http://plnkr.co/edit/83JJFAL34claqrSGoqz6?p=preview).

When (in Chrome) I click the year and type something - say 2015 - and blur the field, model value does not change.

![image](https://cloud.githubusercontent.com/assets/3918865/8340254/a5532af0-1abd-11e5-807e-3a6b93ab4c79.png)

However, when I select the date from calendar and then I delete the year value (select it and hit backspace), then field & form error are set as expected:

![image](https://cloud.githubusercontent.com/assets/3918865/8340246/9362c350-1abd-11e5-82e6-a74462b3acb4.png)

Not sure if Angular's or Chrome's issue as in Firefox it is working fine (although [there is no date picker](http://caniuse.com/#feat=input-datetime)).

**Comment by wesleycho** [comment]
I did a little looking into here, it looks like if you type all of the date values (mm/dd/yyyy, say 03/14/2015), validation does occur.

This may have to do with how partial date entry is validated - I suspect it has to do with either the fact that it is an input of type date.

**Comment by TimoPot** [comment]
I've noted this issue also. Looking into angular.js I notices that validators are not trigger when a part of the date is changed or cleared.

I've als noticed that clearing the complete date (by using backspace in each part) does not trigger any validator.

**Comment by gkalpak** [comment]
As explained in https://github.com/angular/angular.js/issues/11622#issuecomment-109571015, I think this is due to the fact that an invalid or partial date sets the input's value to an empty string.
(Further edits on the already invalid date, will not have an effect on the input's value (it will remain empty), until a valid date is picked.)

It is related to how the browser does/doesn't emit input events upon partial input.
Responding to `keydown` on date inputs (as suggested by @Narretz), sounds like a viable solution.

**Comment by gkalpak** [comment]
A [quick POV][1] showed that the problem is not only the lack of firing input events.
Off the top of my head, another part of the problem must be the fact that once the input is an empty string, further (invalid) edits do not impose a change in the value (`$viewValue`), thus no validation is triggered (this.just a speculation though).

[1]: http://plnkr.co/edit/sjUzVkUw9K09ztsWtzLg?p=preview

**Comment by Narretz** [comment]
@gkalpak  There's a condition inside $commitViewValue that forces validation etc. when the input has a native validator, even if the viewValue is empty: https://github.com/angular/angular.js/blob/master/src/ng/directive/ngModel.js#L652

The problem is that there's no change event in the following cases, because the browser does not register a change in the input's value (as gkalpak has pointed out)
- when adding data into the input, the change event is only fired after all field (day, month, year) have been filled.
- when removing data from the input, the change event is fired as soon as the date becomes invalid, but not when all data is cleared.



I think

**Comment by gkalpak** [comment]
@Narretz, I thought there was another issue, because my original POC (see https://github.com/angular/angular.js/issues/12207#issuecomment-137675456) didn't work. It turned out to be a timing issue.

So, triggering `input` on `keyup`, seems to [solve the issue][1]. 
The real problem is more related to how browsers fire input events on date inputs though (as described previously), so Angular might have to work around that.

@Narretz, wdyt about imulating `input` on `keyup` (or something) for date-family inputs ? 

[1]: http://plnkr.co/edit/FmmlZY10XL53mnlwbNWo?p=preview

**Comment by Narretz** [comment]
@gkalpak Yeah, let's give it a shot. Do you want to open a PR? And I wonder if we should restrict it to Chrome, because FF and IE don't have datepickers (at least on desktop)

**Comment by gkalpak** [comment]
@Narretz, sure, PR is on the way.
Good idea restricting it to browsers that support `input[type="date/..."]` (currently Chrome and Edge - hopefully more in the future). Date inputs report `type === 'text'` in non-supporting browsers.

**Comment by TimoPot** [comment]
@gkalpak to add to your comment of 11 Sep 2015 you said:

when adding data into the input, the change event is only fired after all field (day, month, year) have been filled.

This is partially true, it depends which keys you use to edit the date. If I type the following (wrong) date in one flow then no validator is triggered: 31112015. Even if I leave the field it is still not triggered. When I return to the field and change the year it is not triggered. When I change the day or month the it gets striggered.

**Comment by gkalpak** [comment]
@TimoPot, indeed, I was referring to filling the fields with _valid_ data. If not, the input remains empty (aka unchanged).

**Comment by TimoPot** [comment]
Ah missed that. Well actually the input is not empty after all I've just entered a value ;-)

am I correct to notice that this issue is not solved yet?

**Comment by TimoPot** [comment]
Also manually invoke $validate() or $setTouched() or $setDirty() on the date field does not help to get the date validated. Is there a known workaround?

**Comment by Narretz** [comment]
@TimoPot The problem is that for Angular the input is actually empty, because the browser does not set the value property of the input when invalid data is entered (for date and number). This is pretty stupid imo, but that's the way it is.

I think we need to listen to key events in addition to the input / change event. I believe @gkalpak worked on a PR for this, we should try to get it in after 1.5.

**Comment by gkalpak** [comment]
The workaround I've used (and is more or less what is included in the PR) is to trigger an `input` event, whenever a `keyup` event is fired on date fields. [Demo pen]

I'll resume work on the PR, so we can get this fixed soon.

[1]: https://codepen.io/ExpertSystem/pen/ZQvaVr?editors=001

**Comment by TimoPot** [comment]
Oke. I assume the Demo pen will follow.
Thanks.

**Comment by gkalpak** [comment]
@TimoPot, btw, it's not a proper solution, because one needs to take into account keys that do not change the input (e.g. modifiers etc) and possibly other stuff. But it's good enough for a quick workaround.
