### ISSUE TITLE
Compiler Rewrite Hook

### ISSUE THREAD

**Issue by mhevery** [angular/angular.js#12208]
# Goal

In order to support the [ng2migration](https://docs.google.com/document/d/19NpH_Fzr-omI_Qm6lUt4mZW0L_f6Ksil4pTTp47AhYk/edit#) effort the AngularJS needs to provide a mechanism which would allow a separate library to hook into a compilation process and allow the library to rewrite / replace the elements / attributes before the compiler process them. 

This would allow the templates to be expressed in Angular 2 while executed as rewritten AngularJS 1 directives.

## Changes

- The compiler would inject `$DomRewriter`. (Third party libraries would be allowed to override the default no-op implementation with their own rules.)
- As the compiler would descend into the children it would invoke `currentNode = domRewriter(currentNode)` before it would look for directives. This would give the `DomRewriter` a chance to change the attributes to match the Angular 2 / AngularJS 1 semantics.

**Comment by IgorMinar** [comment]
per discussion in https://docs.google.com/document/d/1xvBZoFuNq9hsgRhPPZOJC-Z48AHEbIBPlOCBTSD8m0Y/edit# I'm going to close this issue for now so that we don't give wrong impression as to what is actually going to happen. The main problem with adding this syntax into Angular 1 core is that it fragments the api/docs/etc and exposes large api surface that we'd need to maintain - which is especially challenging because of the semantical differences between Angular 1 and 2.

We can reopen this issue in the future if needed.
