### ISSUE TITLE
Isolate scope weird behavior based on directive's name.

### ISSUE THREAD

**Issue by tosdan** [angular/angular.js#12215]
I have 2 directives on the same element. One has isolate scope (scope: {}), the other one inherits scope from parent (scope: true). Angular version 1.3.16 (and even 1.4).

This should throw an exception, but it doesn't if my directive's name starts with letter "o" or any following letter in the alphabet.

See for your self in the following plunk by simply changing the directive's name first letter:
http://plnkr.co/edit/oL1WLw

**Comment by gkalpak** [comment]
Without looking deep into, it has clearly to do with directive priorities.
Since all involved directives have equals (=default) priority, their relative priority is determined by alphabetic order (so the `o` is coming from `otherDirective` - e.g. if you rename it to `zOtherDirective` then both `myDirective` and `oyDirective` will throw).

The order of processing its directive changes the outcome, because (for some reason) the check about isolate+new scope is [skipped when there is a `templateUrl`][1] with the following comment:

> //skip the check for directives with async templates, we'll check the derived sync
   // directive when the template arrives

I am not sure if we ever do check when the template arrives (or if we check properly).

[1]: https://github.com/angular/angular.js/blob/8a1eb1625c080445ce1e519762e1f2d4fd842b72/src/ng/compile.js#L1694

**Comment by gkalpak** [comment]
A little more context (Angular internals stuff - for source-viewer only :P):

We indeed fail to properly check, because the `newScopeDirective` is not preserved in the `previousCompileContext` when calling `compileTemplateUrl()` ([compile.js#L1820][1]).

As a result, we (accidentally ?) allow directives that request a new normal scope and a new isolate scope on the same element (as long as the isolate-scope-requesting directive specifies `templateUrl`).

[1]: https://github.com/angular/angular.js/blob/8a1eb1625c080445ce1e519762e1f2d4fd842b72/src/ng/compile.js#L1820
