### ISSUE TITLE
Warn in console if using multiple ng-class directive

### ISSUE THREAD

**Issue by marcalj** [angular/angular.js#12261]
We cannot use multiple ```ng-class``` directive in one element, but there no warning or error to be aware of this limitation.

Thanks.

PD: Using v1.4.1.

**Comment by pkozlowski-opensource** [comment]
I'm afraid that we can't do this... The problem is not only ng-class but any duplicated attribute. Browsers will "auto-correct" such duplicate attributes and will leave only one of them in the DOM. This happens before AngularJS has even a chance of seeing DOM with double attributes.

I understand that it can be a problem, but there is not much we can do about it....

**Comment by marcalj** [comment]
Ok, I'll keep in mind! Could be a headache in some circumstances! Thanks.
