### ISSUE TITLE
step 6 experiments, no different between ng-src, ng-href and normal src and href

### ISSUE THREAD

**Issue by duongphuhiep** [angular/angular.js#12295]
https://docs.angularjs.org/tutorial/step_06

the step 6 experiments said that replacing ng-src by src will break the image, but it is not true, I got no problem with src="{{phone.imageUrl}}", no need to use ng-src

**Comment by gkalpak** [comment]
It doesn't say that it will break the image.

The issue is that it will _initiate a request to invalid URL http://localhost:8000/app/{{phone.imageUrl}}_.
I.e., before Angular has a chance to replace `{{phone.imageUrl}}` with the actual string, the browser will try to fetch an image from an invalid URL. In the end, Angular will update the `src` attribute and the image will be fetched from the correct URL.

As mentioned in the tutorial, using the `ngSrc` directive prevents the browser from making an **extra**, **unnecessary** HTTP request to an invalid location.
