### ISSUE TITLE
Unable to set style in IE11 for direct that uses replace: true and ngStyle

### ISSUE THREAD

**Issue by langdonx** [angular/angular.js#12324]
Using interpolation on the style attribute fails in IE11.

```
<div style="font-weight: {{weight}};">this is never bold in IE11, but it is in Chrome/Firefox</div>
```

The typical resolution to this is to use `ngStyle`, but I can't because the directive I'm using uses `ngStyle` and is a `replace: true` directive.

The fiddle illustrates it better:
- http://jsfiddle.net/8no0atrx/1/

Also, through the course of my discovery, there are some other ~strange behaviors illustrated here:
- http://jsfiddle.net/zn1p3yw0/8/

**Comment by lgalfaso** [comment]
I will leave this open, but this touches two things, one deprecated and the other unsupported. The first being `replace: true` the second having top level `transclude: 'element'`in a directive template.

Fixing this would imply a relatively big refactor on how compilation works, and there is a reasonable chance that it will not be fixed soon.

**Comment by Narretz** [comment]
This basically touches on 2 known issues:
- IE doesn't support interpolation in style attributes (this needs a browser fix which won't come anymore, so it's wontfix)
- AngularJS does not merge expressions correctly (https://github.com/angular/angular.js/issues/5695) (also 99% wontfix due to replace deprecation)
