### ISSUE TITLE
Weird behaviour of angular.toJson on Date object.

### ISSUE THREAD

**Issue by mjasinski5** [angular/angular.js#12360]
Hello!

I have an issue which I dont know if its a good feature or a bug .. :)

Just try those 2 lines of code (angular included ofc)
```
console.log(angular.toJson(new Date()));  // ""2015-07-16T10:32:35.762Z""
console.log(new Date()); // Thu Jul 16 2015 12:32:37 GMT+0200 (CEST)
```
I would expect that date will be this same but... In first case its my local (GMT + 2), in second case its just  'jsonized'... but GMT! In my case  -2 hours. Its a problem for me cause I compare dates. So what's an issue here ?:(

**Comment by pkozlowski-opensource** [comment]
This has nothing to do with AngularJS, just run this in regular JS:

```javascript
var d = new Date();

console.log(d.toString());
console.log(JSON.stringify(d));
```

Those are just 2 different methods of serializing Date objects to string. It just happens that those methods use 2 different _string_ representation of the same objects (btw, both string represent the _same_ date value).

>  Its a problem for me cause I compare dates. So what's an issue here ?:(

The issue is that you are trying to compare string representation of dates, instead of date objects. 

Anyway, this has nothing to do with angular and is general support question, so this discussion doesn't belong here, really: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
