### ISSUE TITLE
attrs defining properties that are not existent in 1.4

### ISSUE THREAD

**Issue by matthiasg** [angular/angular.js#12370]
in <=1.3 the directives attrs object only contained those attributes that are actually defined on an element. with 1.4 the attrs contains them even when they are not defined (seems to me it looks in scope or so, but havent looked into that). 

previously we could write if(attrs.myAttr){} now we have to check for undefined.

**Comment by gkalpak** [comment]
Writing `if (attrs.myAttr)` isn't enough, because it does an empty string still evaluates to false (i.e. the attribute may be present but you won't detect it using `if (attrs.myAttr)` if it has an empty value.
So, if you were using `if (attrs.myAttr)` then setting non-present properties to `undefined` does **not** affect your usecase.

A more consistent way to check for whether an attribute is present or not, is `if (attrs.hasOwnProperty('myAttr'))` (and this would indeed be affected by the new behaviour you described).

--
Anyway, I think this issue has been fixed recently, so could you try if it still happens on 1.4.3 ?
If it does, it would be better to post a live demo, so people can identify (and solve) the problem sooner.

**Comment by matthiasg** [comment]
Sorry we also used ownproperty but thanks I will restest

-----Original Message-----

**Comment by caitp** [comment]
`if (attrs.hasOwnProperty('myAttr'))` this isn't super good, because there are cases where the attribute is shadowed but uninitialized. You also want to tack a `&& attrs.myAttr !== void 0` test, for reliability.

IIRC this is fixed (at least marginally) in one of my recent prs, but I don't think it's landed yet.

**Comment by matthiasg** [comment]
Thanks ! Will keep an eye out.


-----Original Message-----

**Comment by gkalpak** [comment]
It used to work (without the `void 0` part), but then it broke and the it was fixed, but then the fix was reverted again (because it broke `ngMaterial`) and then I thought it was fixed again (by @caitp's PR), but I am not 100% sure it has been merged. Fun stuff :smiley:

**Comment by caitp** [comment]
yeah i'm pretty sure we never merged it

**Comment by caitp** [comment]
https://github.com/angular/angular.js/pull/12290 still open and waiting

**Comment by Narretz** [comment]
I am gonna close this as a duplicate. I am pretty confident #12290 will land this or next week.

**Comment by matthiasg** [comment]
our workaround right now is

```
function hasAttr(element, attributeName){
  return element.filter(`[${attributeName}]`).length > 0;
}
```
