### ISSUE TITLE
module.decorator() requires explicit order of operations. 

### ISSUE THREAD

**Issue by bennadel** [angular/angular.js#12382]
All of the other module-level API methods - service, factory, run, config, etc - can execute in any arbitrary order. However, the new .decorator() method *has to run* after the target service is defined. This is because the feature has been merely piped into the $provide.decorator() method, which used to be required to run in the configuration phase, after all services have been defined. Now that it can be called at any time, the necessary $get() method doesn't always exist. 

As such, this fails:

angular.module( "Foo" ).decorator( "greet", fn ); // error, greetProvider cannot be found.
angular.module( "Foo" ).service( "greet", fn );

... but this works:

angular.module( "Foo" ).service( "greet", fn );
angular.module( "Foo" ).decorator( "greet", fn );

If you could just queue up the .decorator() calls and run them as the first part of the config-queue-flush, I think this would solve the dependency on order-of-operations.

I don't know much about contributing to Angular, so in the future, hopefully I can submit this as part of a PR.

**Comment by Narretz** [comment]
Hi @bennadel feel free to send a PR. There are a few guidelines here: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submitting-a-pull-request

**Comment by mchlbrnd** [comment]
Hi @bennadel,

Regarding your proposed fix of moving .decorator() up the queue; I tried decorating a provider which got injected into the config block without the decoration. See http://plnkr.co/edit/d7wMrcv8cwxQfwo6C0SC?p=preview. Line 22 in scripts.js throws because the decorator (added function to FooProvider) can't be found.

Not sure whether moving .decorator() up like you proposed will also solve the issue for providers. Can you elaborate on this, and (hopefully) on its status? :)

If you need help, do let me know!

**Comment by robertmirro** [comment]
@bennadel 

Another issue with the `module.decorator()` order of operations seems to be related to multiple, same-named providers (potentially an issue when mocks are used) where Angular uses the last/final declared provider.

For example, Angular uses `theOtherProviderFn` when injecting `'theProvider'`, however it is not decorated because `.decorator()` is declared first:

```javascript
angular
    .module('theApp', [])
    .provider('theProvider', theProviderFn)
    .decorator('theProvider', theProviderDecoratorFn)
    .provider('theProvider', theOtherProviderFn);
```
However, decoration would occur as expected when `.decorator()` is declared after all providers:
```javascript
angular
    .module('theApp', [])
    .provider('theProvider', theProviderFn)
    .provider('theProvider', theOtherProviderFn)
    .decorator('theProvider', theProviderDecoratorFn);
```
