### ISSUE TITLE
scope variable is deleted with ng-model-options when $validators return false

### ISSUE THREAD

**Issue by Gregoirevda** [angular/angular.js#12426]
I made a very simple plunker: 
http://plnkr.co/edit/5diCIhFoWX8FneSSBkfA?p=preview

Please, change one input and trigger the blur event.
Is there something I shouldn't do?

**Comment by Gregoirevda** [comment]
Know, I thought it had to be inside an ng-repeat. But it is not the case.
Here is a new one: 
http://plnkr.co/edit/5diCIhFoWX8FneSSBkfA?p=preview

As you can see, when deleting one letter: $validators returns true and everything's fine, but when you type anything else... the scope dissapears

**Comment by sreeramu** [comment]
@Gregoirevda please correct me if i am not correct, The scope which you had mentioned in your issue is the value which you are displaying below the inputbox.?

**Comment by m-amr** [comment]
@sreeramu  i think that you are right that was written in angular documentation 
https://docs.angularjs.org/api/ng/directive/ngModelOptions

allowInvalid: boolean value which indicates that the model can be set with values that did not validate correctly instead of the default behavior of setting the model to undefined.

@Gregoirevda  so angular default behavior is to set the value of the model for the invalid case to undefined.
but you can set allowInvalid to true so model can be set with value from the input in the invalid case
ng-model-options="{allowInvalid: true }"

**Comment by Gregoirevda** [comment]
Thank you both for your answears. I've figured that out thanks to stackoverflow. 

I do not realy understand the logic of setting the default to false, but I will close this issue, since it isn't one.
