### ISSUE TITLE
Don't throw an exception at bootstrap

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular.js#1248]
can we get rid off the try catch (exception) while loading locale module ?
https://github.com/angular/angular.js/blob/master/src/AngularPublic.js#L55

Why ?
- when debugging in Safari, Opera or PS3, every exception requires resuming (typing some cmd on PS3)
- I don't like using exceptions for controlling the flow

I think there is only one corner case when we need this exception. When loading stuff asynchronously and specific locale happens to be loaded before angular, which might override it afterwards. (+ it allows people to include the locale file both before/after angular). Please correct me, if I'm wrong.

Unfortunately, I can't think of better solution then adding API that would tell, whether particular module is already defined.

Or how about having the locale in a special module. "ng" module would provide default implementation of $locale service, and if you use other locales, your app would have to specify the locale module:
angular.module('superApp', ['locale']);

**Comment by srigi** [comment]
This issue is very unpleasant since there is neat feature in chrome's webinspector -  Pause on caught exceptions. Our team is using this feature extensively and we are forced to click that little play button on every browser reload. Solution would be very appreciated.

![screen shot](https://cloud.githubusercontent.com/assets/295197/5755635/21cb7ece-9ca7-11e4-8605-cf3551242b32.png)

**Comment by petebacondarwin** [comment]
I think this is now fixed, right?

**Comment by petebacondarwin** [comment]
https://github.com/angular/angular.js/commit/7b8a16b238fa3a011e502515ac0042fe4dbc421a
