### ISSUE TITLE
$injector cannot instantiate ES6 classes

### ISSUE THREAD

**Issue by mprobst** [angular/angular.js#12597]
This code (paraphrasing) fails with `TypeError: Class constructors cannot be invoked without 'new'`:

```js
class Foo { constructor() { } }
var foo = $injector.instantiate(Foo);
```

The reason is that ES6 disallows using `fn.apply` on class constructors.

**Comment by stefan--** [comment]
+1

**Comment by bisubus** [comment]
@mprobst I've encountered the similar issue before and ended by splitting the solution into separate extension, [ng-classified](https://github.com/ex-machine/ng-classified).

Just have checked #12598, I have a feeling that patching up `instantiate` is halfhearted job, it will just affect performance by propagating `new` everywhere and not targeting the classes. And other things that could benefit from classes will still get their TypeErrors (the world is bigger than controllers).

It is evident that I've managed it more drastically, it is `$injector.invoke` which is primarily responsible for calling class constructors directly. And I consider it the right idea because it is a great opportunity to pull up mature 1.x to fit contemporary expectations (particularly excited by Angular 2) by using DI-enabled classes everywhere where 1.x would expect constructor functions, without breaking anything.

It's not that simple, what's good for extension, is bad for framework. Due to the fact that only Chrome/V8 native class implementation can be easily detected (even FF native classes appear as functions for now), I've had to introduce some conventions and [add flag checks](https://github.com/ex-machine/ng-classified/blob/1.0.0/src/ng-classified.js#L57) to avoid trying-catching TypeErrors on every invoke.

Is it acceptable to make `$injector` configurable on framework level? I'm not sure at all. But I think it is inevitable to provide some degree of configurability to deal with classes in future-proof manner while keeping the performance high for classless apps.
