### ISSUE TITLE
Animation staggering issue in 1.4.4

### ISSUE THREAD

**Issue by serjrd** [angular/angular.js#12594]
Here's a plunker snippet that illustrates the issue: http://plnkr.co/edit/PSuu2IOG03fv2ifNTTwQ?p=preview

With the version 1.4.4 there's no staggering.
But If you change the included angular version to 1.4.3 - staggering works fine.

This is under Ubuntu / Chrome Version 44.0.2403.125 (64-bit).

**Comment by datnordstrom** [comment]
1+

I've experienced this as well.

**Comment by ordinaryAmsel** [comment]
+1

**Comment by Narretz** [comment]
@matsko can you take a look?

**Comment by matsko** [comment]
This isn't entirely broken. You can still get the stagger to work by adding `transition-duration: 0s` into the stagger CSS selector.

http://plnkr.co/edit/PSuu2IOG03fv2ifNTTwQ?p=preview
By the way there is no need to define the -webkit- properties for transitions anymore.

This was mentioned in the stagger docs:
https://docs.angularjs.org/api/ngAnimate#css-staggering-animations

Unfortunately with 1.4.4 and onwards this is **always** the case. You must always define the duration value as 0s since we changed the way the ng-EVENT classes are applied. I completely missed making note of this in the CHANGELOG as a breaking change. I will make sure it shows up in the 1.4.5 release notes.

**Comment by matsko** [comment]
This PR contains a fix to the docs: https://github.com/angular/angular.js/pull/12637

**Comment by serjrd** [comment]
Thanks, that helped for the transition animation.

And what about the keyframes animation? I tried it with the 'animation-duration: 0s' property, but it didn't help.
Same code works fine under the 1.4.3 version.
See the example: http://plnkr.co/edit/uAFFOhZ32mDYQVp4Fcco?p=preview

**Comment by abruzzihraig** [comment]
I met the issue like @serjrd, the 1.4.4 version still has a bug in keyframes when use stagger.

And my code like below:

**Comment by abruzzihraig** [comment]
I met the issue like @serjrd too, the 1.4.4 version still has a bug in keyframes when use stagger.

And my code like below:
http://codepen.io/abruzzi/pen/VLodOK

when you choose 1.4.3 version, the code works fine.

Another thing I have noticed that when you write 'transition-duration: 0' without 's', the stagger not performed like we expected, but in 1.4.3, it works.

**Comment by matsko** [comment]
There is a fix in place for 1.4.5 that fixes both: http://plnkr.co/edit/SkKZaH6qQmgX5w6YoGk9?p=preview

**Comment by abruzzihraig** [comment]
@matsko It works fine, thank you!
