### ISSUE TITLE
ng-model does not update when sending a value to an input field

### ISSUE THREAD

**Issue by jetta20162** [angular/angular.js#12622]
example: i have 3 input fields. The values from the first and second input field get's calculated and the result is shown in the third inputbox.

```javascript
var1 = parseFloat($("#input1").val();
var2 = parseFloat($("#input2").val();
result = var1 + var2;

$("#input3").val(result);
```
`<input type="number" id="input3" name="input3" ng-model="editForm.input3" ng-currency class="form-control input-sm" placeholder="input3">`

i can see the result on the form in input3, but how can i get the model updated?

**Comment by bcherny** [comment]
try this-

```js
$("#input3")
  .val(result)
  .trigger('change')
```

**Comment by gkalpak** [comment]
Actually, this doesn't feel like Angular code. In Angular, it is the other way around: You update the model and the change is reflected in the view. (The model is the single source of truth.)

So, instead of trying to set the value and expect the model to be updated, you should update the model (`editForm.input3`) and the element's value would be updated as a result.

--
That said, this is a general support question and should be directed to the [appropriate channels][1].
GitHub issues are reserved for bug reports and feature requests.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by irufus** [comment]
This came handy for my typeahead+bloodhound integration with angularJS
