### ISSUE TITLE
[Guide] 'User Input' Final Code

### ISSUE THREAD

**Issue by KapuzenSohn** [angular/angular.js#12624]
I just did the Guide and found in the third Guide 'User Input' in the Final Code example a small typo.

In line 18 ```directives: [NgFor, NIf]```
it has to be ```NgIf``` and not ```NIf```

**Comment by gkalpak** [comment]
This should probably be reported to the [Angular 2][1] repo.
This repo is for "Angular 1" (AngularJS).

[1]: https://github.com/angular/angular.

**Comment by KapuzenSohn** [comment]
Sorry, the angular.io page navigated me to this repo

**Comment by gkalpak** [comment]
@KapuzenSohn, np !
[angular.io][1] mentions both ng1 and ng2 (among other things), but the documentation primarily refers to ng2 (for the time being at least).

Where exactly on [angular.io][1] where you directed to this repo ?
(I'm asking, because it might be a _bug_ in [angular.io][1] that needs fixing.)

[1]: https://angular.io

**Comment by KapuzenSohn** [comment]
I clicked on 
'Contribute' -> 'Contribute to Angular for JS' then I was in the Contribution guide of this repository ```https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md```

**Comment by gkalpak** [comment]
@KapuzenSohn, it is indeed confusing. Thx for pointing it out.

The issue has been reported here: https://github.com/angular/angular.io/issues/191

**Comment by KapuzenSohn** [comment]
No problem, I reported the other one in the right repo :)
