### ISSUE TITLE
ngHide/ng-show directive don't  animate in ng 1.4.4

### ISSUE THREAD

**Issue by e-cloud** [angular/angular.js#12631]
when i update to angular 1.4.4, there is a strange thing -- some animation i define for the element with ng-hide directive doesn't seem to work. Then i check the api docs. Ok, [the 1.4.4 version docs of ng-show] (https://code.angularjs.org/1.4.4/docs/api/ng/directive/ngShow)'s [example plunkr](https://code.angularjs.org/1.4.4/docs/api/ng/directive/ngShow#example) seems to have no animation too.

**Does Angular have enough tests before the new version is about to release?**

**Comment by Narretz** [comment]
Can you please provide a demo of the problem? Otherwise, we cannot do anything to fix the problem.

**Comment by A11oW** [comment]
Just look how work [https://code.angularjs.org/1.4.4/docs/api/ng/directive/ngShow#example](example ) or [http://plnkr.co/edit/y2JZH3xTB9MI6VXZ0o4b?p=preview](plunker)
when check labels angular don't add intermediates classes:
```
.ng-hide-add
.ng-hide-add-active,
.ng-hide-remove
.ng-hide-remove-active
```

**Comment by A11oW** [comment]
I think that proble related with #12612, #12583

**Comment by Narretz** [comment]
Ok, I see now. @matsko can you take a look at this? It seems pretty bad if even the "official" ng-hide animations aren't working.

**Comment by matsko** [comment]
Turns out that the API docs example code is incorrect. Transitions always need to be applied to the non active CSS class:
http://plnkr.co/edit/JzI0NnxtPdySR2sMcGeW?p=preview

Or on the class that is being added or removed:
http://plnkr.co/edit/EdhLQkurZRRYjhmSUrrX?p=preview

Or on a shared CSS class that is always there:
http://plnkr.co/edit/HX9BQwtwJ5WvylbWVOa3?p=preview

Placing it on the active CSS classes may have worked before, and I will look into making the fix properly for 1.4.5. Here is an issue to keep note of that:
https://github.com/angular/angular.js/issues/12638

In the meantime here is a commit that will clean up the example in the docs a bit so nobody else comes across this issue:
https://github.com/angular/angular.js/pull/12637

**Comment by matsko** [comment]
OK 1.4.5 will fix this entirely: http://plnkr.co/edit/y2JZH3xTB9MI6VXZ0o4b?p=preview

**Comment by matsko** [comment]
Sorry I provided the wrong link earlier. Here is a patched version of angular.js that fixes the issue: http://plnkr.co/edit/YLTe1SObEAaQn99iOiNv?p=preview

This patch will debut in 1.4.5

**Comment by A11oW** [comment]
thx! =)
