### ISSUE TITLE
1.3.18 -  [jqLite:onargs] jqLite#on() does not support the `selector` or `eventData` parameters

### ISSUE THREAD

**Issue by nicolabortignon** [angular/angular.js#12679]
Hi, I'm using Angular 1.3.18.

I haven't build my project in a while. Today when i started the production pipeline, I saw that there is an error after i concatenate angular with all the other js file. When the files are not concatenated but just used like in developing stage it does work.

It's a long shot, but let see if you have any suggestions here:

It is basically a 

Error: [jqLite:onargs] jqLite#on() does not support the `selector` or `eventData` parameters
http://errors.angularjs.org/1.3.18/jqLite/onargs

With a stack trace of:
```
    at REGEX_STRING_REGEXP (http://localhost:9000/js/app.min.js:63:12)
    at jqLiteOn (http://localhost:9000/js/app.min.js:3067:39)
    at Object.JQLite.(anonymous function) (http://localhost:9000/js/app.min.js:3285:17)
    at link (http://localhost:9000/js/app.min.js:49514:12)
    at invokeLinkFn (http://localhost:9000/js/app.min.js:8290:9)
    at nodeLinkFn (http://localhost:9000/js/app.min.js:7800:11)
    at compositeLinkFn (http://localhost:9000/js/app.min.js:7149:13)
    at compositeLinkFn (http://localhost:9000/js/app.min.js:7152:13)
    at compositeLinkFn (http://localhost:9000/js/app.min.js:7152:13)
    at publicLinkFn (http://localhost:9000/js/app.min.js:7028:30) <nav ui-nav="" class="navi clearfix">
```

The starting error, the tag mentioned at the bottom of the stack, is this tag: 

    
    <nav ui-nav class="navi clearfix" ng-include="'tpl/blocks/nav.html'"></nav>
    

That is some UI code for the navigation menu of my site.
uiNav is this directive:  https://github.com/TracklistMe/client/blame/master/src/js/directives/ui-nav.js

Now, if instead of declaring the directive in that way, i do something like: 

    <ui-nav class="navi clearfix"  ng-include="'tpl/blocks/nav.html'"></ui-nav>

It works.

**Comment by gkalpak** [comment]
When using the element form (`<ui-nav ...></ui-nav>`), it still doesn't work, because the directive is restricted to attribute and class selector (`restrict: 'AC'`).

So using it as an element, it doesn't get recognized as a directive => it doesn't get compiled/linked by Angular => it's `link` function is never called => you don't get the error.
(But it doesn't work either.)

--
It is next to impossible to provide a definitive answer with the info (not) provided, but based on the error you get, this seems a possible explanation (still a stab in the dark):

- The directive uses `.on(<EVENT>, <SELECTOR>, <CALLBACK>)`.
- This syntax is [not supported][1] by `jqLite` (Angular built-in, stripped-down version of `jQuery`).
- Since you say that it works with the unconcatenated files, I presume you have `jQuery` loaded.
- In order for Angular to use `jQuery` (instead of it's `jqLite`), the former has to be loaded **before** Angular.
- A possible cause is that in the concatenated file, `jQuery` is placed **after** Angular, thus force Angular to fall back to `jqLite`.

---
That said, this is a general support question and would be better suited for one of the [suport channels][2].
GitHub issues are reserved for bug reports and feature requests.

I am closing this (since it's not actionable on our part).
Feel free to reopen if you have any indication there is a bug in Angular core that causes the issue.

[1]: https://docs.angularjs.org/api/ng/function/angular.element
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
