### ISSUE TITLE
Isolate scope does not 'isolate' for multiple directives 

### ISSUE THREAD

**Issue by nsang92** [angular/angular.js#12686]
See plunker: http://plnkr.co/edit/YhR39jDt9Zfefx0Dovdm?p=preview

Setting the scope of "myCustomer" to true, effectively separates the scope. Isolating the scope of "myCustomer" with {}, does not separate the scope.

**Comment by gkalpak** [comment]
The `template-one` and `template-two` directives do not request a scope, thus they share the normal (non-isolate) scope of the elements (possibly inherited by an ancestor).
They can't see an isolate scope requested by another directive (even on the same element), because, you can't have more than one directive share an isolate scope.

(There are other ways to make your directives communicate/augment each other, usually involving one directive requiring the other directive's controller.)

--
That said, this is a general support question and would be better suited for one of the [support channels][1].
GitHub issues are reserved for bug reports and feature requests.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
