### ISSUE TITLE
did not find the answers everywhere

### ISSUE THREAD

**Issue by pavel06081991** [angular/angular.js#12694]
Hi. I was looking for answers on my questions on google, on stackoverflow, on some forums, on official documentation but did not find them. Could you please answer me?

1) When we use $watch, we can get new and old values of any scope property. Is it possible to get old value of scope property not using $watch? Are there any methods to get old values?

2) We can watch scope property by reference and by value. It depends on third param of $watch function. But what should I do if I want to watch scope property by reference and value at the same time? I can make two watchers, one for watching by reference and 
one for watching by value, but it is not comfortable. There is watchCollection method, but it does not watch deeply. Maybe there is a solution?

3) Could you tell me please: imagine that we have directive "myDirective" which is set on div element:
<div myDirective>
</div>

This directive has some watchers:

scope.$watch('...', function() {...});

when we remove this div from DOM will angular remove directive scope and its watchers or I have to do this by myself?:
element.on('$destroy', function() {
	scope.$destroy();
});

Thanks.

**Comment by wawyed** [comment]
1) No.

2) Not sure why would you want to do that? Could you give an example.

3) Depends, if your directive creates it's own scope all watches will get removed when the element that is associated to the directive is removed from the DOM. Otherwise the watches will stay until the element that created that scope gets removed or $destroy is called on that scope.

**Comment by benjaminapetersen** [comment]
I'm finding the title 'did not find the answers everywhere' somewhat humorous :smile:

**Comment by pkozlowski-opensource** [comment]
@pavel06081991 you didn't get answers to your questions since you are trying to mix too many different topics. Start by asking one question at the time and give people more context - ideally your _functional_ problem plus what you've attempted so far in code.  

I think that @wawyed has best answers given info in your questions. Usually people are keen on helping provide that you can state your problem clearly providing all the necessary context and code examples. If you are not getting answers it can either mean that you are not clear in your question or it might happen that no one knows the answer :-) In this case you need to dive to the code, I'm afraid.

I'm sorry but I need to close this issue as it _is_ a support request and those need to go to the support channel. I can't provide you with more answers here since there is not enough info / context in your question and @wawyed did his best to provide answers.
