### ISSUE TITLE
ngOptions added in compileFn of Directive did not resolve scope variable

### ISSUE THREAD

**Issue by beautifulinda** [angular/angular.js#12714]
This **ngOptions** problem occurs when **ngOptions attribute is added in compile function of directive** and using return link function to give scope variable (an array used in ngOptions).

The rendered HTML: 

    <select ng-model="selectedMonth" ng-options="month for month in months">
    <option value="? number:3 ?"></option>
    </select>

It's not a normal select element.

I've read [1.4.0-beta.0 photonic-umbrakinesis (2015-01-13)](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#140-beta0-photonic-umbrakinesis-2015-01-13 "1.4.0-beta.0 photonic-umbrakinesis (2015-01-13)") about the Breaking Changes, and still don't know why **ngOptions** breaks.

Here is the [forked one example](https://jsfiddle.net/butylinda/2etb78ay/ "forked example") works fine with version 1.2.18.

And I [copy one](https://jsfiddle.net/butylinda/4ss9ojmh/ "copy one") to test with version 1.4.0.

Please help, thank you.

**Comment by Narretz** [comment]
`ngOptions` is now a standalone directive, that's why adding it inside the compile function does not work anymore. Previously, it was an attribute read by the selectDirective. This hasn't made it to the upgrade guide / changelog unfortunately.
This means you cannot use your directive like this anymore. You should use a directive that has a template which already has all the directives needed on the element. Or one that simply sets your scope values, while you put the options expression directly inside your template.

**Comment by beautifulinda** [comment]
Maybe I should try to use *angular.foreach* to add option elements as a alternative, thank you for paying attention to my question.
