### ISSUE TITLE
angularjs recursive template ng-class can not convertion issue

### ISSUE THREAD

**Issue by bayramucuncu** [angular/angular.js#12750]
Angularjs (v1.2.18) does not convert conditional ng-class in recursive template . This is the original question: (http://stackoverflow.com/questions/32371475/angularjs-recursive-template-maximum-call-stack-size-error-with-third-party-obje?noredirect=1#comment52622895_32371475).

**Comment by Narretz** [comment]
This happens because angular evaluates the ngClass expression during the digest and evaluates until the expression is stable. Since you are using `new OpenLayers()` in your tree, in every digest, a new object is created, and angular compares it to the old object, finding that is not the same, even though its properties are, so it digests again, until the stack is full (or 10 digests are reached). So using !! is the way to go, because it converts the object into a boolean expression which compares easily.
