### ISSUE TITLE
5 Minute Quickstart

### ISSUE THREAD

**Issue by peterennis** [angular/angular.js#12752]
Windows 7 Pro
Installing tsd

Following this: https://angular.io/docs/js/latest/quickstart.html

PS C:\ae\aetsang> npm install -g tsd@^0.6.0
npm WARN engine joi-assert@0.0.3: wanted: {"node":">= 0.10.0 <= 0.11.0"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN peerDependencies The peer dependency minichain@~0.0.1 included from minitable will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

Not  sure what this means. The rest of the install had no warnings.

**Comment by gkalpak** [comment]
This repo is for AngularJS. Issues regarding the [angular.io][1] website should be filed at https://github.com/angular/angular.io.

--
<sub>That said, I don't think the warning you see is angular or angular.io specific.
It's "normal" node/npm stuff (and more or less self-explanatory).</sub>

<sub>Even so, since it is a warning not an error, there is a good chance everything still works fine.</sub>

[1]: https://angular.io
