### ISSUE TITLE
Feature request: use track by in ng-repeat to watch for changes

### ISSUE THREAD

**Issue by olegskl** [angular/angular.js#12764]
This has been discussed in #12506, but I guess there wasn't any follow up.

I'm expecting that the following should work:

```js
ctrl.getItems = function () {
  return [{id: 0}, {id: 1}, {id: 2}];
};
```
```html
<a ng-repeat="item in ctrl.getItems() track by item.id">{{ item.id }}</a>
```

But it doesn't and results in not-very-informative "10 $digest() iterations reached. Aborting!".
It would be great if `track by` would do as it says, i.e. "track" items.

As @coli nailed it:
> I thought the whole point of `track by` was to handle the case where the function returns a new collection/object in the first place

**Comment by frfancha** [comment]
Initialyze your array in your scope. Then replace the items in the array and track by id will work

**Comment by Narretz** [comment]
Track by makes it easier for repeat to "keep track" of the items in a collection. By default, it compares the complete object, with track by it uses the defined unique identifier. The 10 digests error is because on each digest the fn returns a new array. Imo these are two different problems.

**Comment by olegskl** [comment]
Why can't `track by` use that unique identifier to compare objects in the new array?

**Comment by frfancha** [comment]
@olegskl For the quite common scenario when you have a collection of records, each identifed by an id, and you "refresh" one of them by getting new info from backend and replaces this specific record in the collection.
The track by id is used by angular to know that only this item that must be changed, but as the record is a new object the display is refreshed.
Otherwise track by id could only be used for frozen record.
You have to change your design to avoid to build a new array each time you run getItems.
And even if it would work, returning a new array of items each time is a bad idea because you create objects at each digest loop which is impacting performance.

**Comment by Narretz** [comment]
@olegskl frfancha is right. You use the `track by` expression to identify an item in the collection uniquely, so that you can update it more efficiently. You are basically asking for a way to tell the digest cycle that the collections you return from a fn are the same. I personally don't think that is possible or worth the effort, but you can open a feature request for that. If you think the track by docs should be more explicit, feel free to open a PR.
