### ISSUE TITLE
$parent.$index lost when using ng-if

### ISSUE THREAD

**Issue by kishanmundha** [angular/angular.js#12809]
My HTML Code
<pre>
&lt;div&gt;
  &lt;ul&gt;
    &lt;li ng-repeat='parentItem in arr1'&gt;
      &lt;div ng-repeat='childItem in arr2'&gt;
        {{ $parent.$index }} , {{ $index }}
      &lt;/div&gt;
    &lt;/li&gt;
  &lt;/ul&gt;
&lt;/div&gt;
</pre>
Javascript code inside controller
<pre>
$scope.arr1 = [1,2];
$scope.arr2 = [1,2];
</pre>

This code giveing me correct answer
<pre>
0, 0
0, 1
1, 0,
1, 1
</pre>

But if I use <code>ng-if="true"</code> in child loop then it giving me wrong answer
<pre>
&lt;div&gt;
  &lt;ul&gt;
    &lt;li ng-repeat='parentItem in arr1'&gt;
      &lt;div ng-repeat='childItem in arr2' ng-if="true"&gt;
        {{ $parent.$index }} , {{ $index }}
      &lt;/div&gt;
    &lt;/li&gt;
  &lt;/ul&gt;
&lt;/div&gt;
</pre>
<pre>
0, 0
1, 1
0, 0
1, 1
</pre>

This was wrong. It change parent index to child index

Please fix this issue

**Comment by gkalpak** [comment]
This is not an issue in Angular. This happens ([as documented][1]), because `ngIf` creates a new scope, so `$parent` does not refer to the scope of the outer `ngRepeat`.

That is why using `$parent` is not a good practice here. You could/should use [`ngInit`][2] to create an alias of the parent index, like this:

```html
<li ng-repeat="parentItem in arr1" ng-init="parentIdx = $index">
  <div ng-repeat="childItem in arr2" ng-if="true">
    {{ parentIdx }} , {{ $index }}
  </div>
</li>
```

[Demo][3]

[1]: https://docs.angularjs.org/api/ng/directive/ngIf
[2]: https://docs.angularjs.org/api/ng/directive/ngInit
[3]: http://codepen.io/ExpertSystem/pen/EVVyXp?editors=100

**Comment by gkalpak** [comment]
BTW, this is a general support question. Such questions should better be directed to the [appropriate channels][1].
GitHub issues are reserved for bug reports and feature requests.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by kishanmundha** [comment]
Thanks,

I can use this by ng-init
