### ISSUE TITLE
Using class and ng-class together 

### ISSUE THREAD

**Issue by ManjushaMGlobant** [angular/angular.js#12869]
Hello,
     Here I am facing a problem when applying regular element class and ng-class together. In my code ng-class css property depends upon a controller variable whose value changes for every iteration in ng-repeat. The main issue is that for two or more values of  'dependent' variable appearing successively,  ng-class property doesn't applies to first value. 

<html>
<head>
	
	<style type="text/css">
	
		.simpleCss{
			font-size: 14px;
		}
		.changeToRed{
			color : red;
		}
		.changeToBlue{
			color : blue;
		}

	</style>

        <script src= "http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>

       <script type="text/javascript">
	      angular.module('test-app', []).controller('testAppCntrl', function($scope){

		var objects = [
			{id : 1, start : 10, end : 15},//current = 18
			{id : 2, start : 10, end : 11},
			{id : 3, start : 10, end : 20},
			{id : 4, start : 10, end : 23},
			{id : 5, start : 10, end : 25},
			{id : 6, start : 10, end : 14},
			{id : 7, start : 10, end : 13},
			{id : 8, start : 10, end : 12},
			{id : 9, start : 10, end : 20},
			{id : 10, start : 10, end : 28}
			];
		$scope.objects = objects;

		$scope.calculate = function(start, end, current){//start, end, current
			if(current<end)
			{
				$scope.dependent = ((current-start)/(end-start)) * 100;
			}
			else
				$scope.dependent = 100;

			return $scope.dependent;
		}

	});

</script>
</head>

<body ng-app='test-app' ng-controller='testAppCntrl'>

	<div ng-repeat="obj in objects">
		<h6 class="simpleCss" ng-class="{{dependent < 100}} ? 'changeToBlue' : 'changeToRed'" > {{calculate(obj.start,obj.end,18)}}</h6>
	</div>

</body>
</html>

Here is an output of above code.
![output](https://cloud.githubusercontent.com/assets/13828171/9898029/5c1ed456-5c6c-11e5-8705-3eb65781ec80.png)

Hope for the best solution!
Thank you.

**Comment by gkalpak** [comment]
It's not clear what the issue is. AFAICT, it [works as expected][1].

This sounds like a general support question (in which case it should bedirected to one of the [appropriate support channels][2] - with a clear description of the actual vs expected behaviour).
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Feel free to open a new issue if you think you found a bug in Angular itself.

Thx !

[1]: http://codepen.io/ExpertSystem/pen/JYGVbz?editors=101
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by pkozlowski-opensource** [comment]
One thing that looks wrong with the example provided is the syntax used by ngClass: `ng-class="{{dependent < 100}} ? 'changeToBlue' : 'changeToRed'" >` - ngClass takes an expression and not interpolation, so it means that you shouldn't have any `{{}}` in there

**Comment by gkalpak** [comment]
@pkozlowski-opensource, I too thought it was wrong at first, but it turns out to work (because interpolation kicks in before directive linking).
Thus, `ng-class="{{expr}} ? 'class1' : 'class2'"` turns to `ng-class="true/false ? 'class1' : 'class2'"` which is an expression !?! :smile:

**Comment by pkozlowski-opensource** [comment]
@gkalpak the fact that it "workish" doesn't mean that it is what people should do :-)
This usage looks weired and is far from being the simplest one.

**Comment by gkalpak** [comment]
I definitely agree !

I didn't mean to "promote" it in any case :smiley: - I just wanted to point out that it works (so it's not related to the problem per se).
It definitely looks odd and I wouldn't recommend it (especially since the "normal" way is more concise and readable: `ng-class="dependent < 100 ? 'changeToBlue' : 'changeToRed'"`).
