### ISSUE TITLE
Improve $scope documenations

### ISSUE THREAD

**Issue by m-amr** [angular/angular.js#12886]
If we have a parentController $scope.username = 'name-1';
and we have a childController $scope.username will be copied by value from the parenScope and any change in the child scope will not affect the parent scope

but if we have an object  
If we have a parentController $scope.customer.username = 'name-1';
and we have a childController $scope.customer.username will be copied by reference from the parenScope and any change in the child scope will affect the parent scope.

I think that this point should be added to the documentation of the $scope  so developers can know
when $scope is copied be value and when it is copied by reference .

Does anyone think it will be useful ?

**Comment by gkalpak** [comment]
This basically (plain old) JS prototypal inheritance - nothing particular to Angular os Scopes.
It is explained in detail in this wiki article: https://github.com/angular/angular.js/wiki/Understanding-Scopes

I think there are some thoughts about somehow integrating the wiki content into the docs, or maybe we could add a link to the article.

**Comment by frfancha** [comment]
@m-amr As gkalpak says you need to understand javascript inheritance. My comment is just because I would like to say that it is absolutely not 'copied by value' or 'copied by reference' as you say. The best thing to do is to read the excellent book "Javascript the definitive guide", and what you need to specifically answer to this question is the part 6.2.2 Inheritance

**Comment by m-amr** [comment]
@frfancha  Thanks i will read i cam from c++ and java background so i thought it is copied by reference and value.
I will close the Issue since it it documented at the wiki
