### ISSUE TITLE
Validation with passed pattern from variable doesn't work with modifiers

### ISSUE THREAD

**Issue by vchampion** [angular/angular.js#12913]
When you want to pass regular expression as validation pattern for input from variable it works well if you don't use slashes (delimeters) and modifiers, but when you try pass regexp with modifiers (as i, g ..) validation is broken. 

See [example fiddle](http://jsfiddle.net/champion/wmnegLdz/)

**Comment by gkalpak** [comment]
As explained in the [docs][1]: 

> [ngPattern] sets pattern validation error key if the ngModel value does not match a RegExp found by evaluating the Angular expression given in the attribute value. **If the expression evaluates to a RegExp object, then this is used directly. If the expression evaluates to a string, then it will be converted to a RegExp after wrapping it in `^` and `$` characters**. [...]

<sub>(emphasis mine)</sub>

--
The wrapping in `^`/`$` is to match the behaviour of HTML5's `pattern` attribute, which should match the whole input. If you want to use a RegExp with flags, you have to reference a RegExp object directly:

```html
<input ... ng-pattern="myRegExp" />
```
```js
.controller('SomeCtrl', function SomeCtrl($scope) {
  ...
  $scope.myRegExp = /.../i;
})
```

[Demo][2]

---
BTW, since you mentioned the `g` flag, note that it is not a good idea to use it (as mentioned in the [docs][1] as well):

> [...]
**Note:** Avoid using the `g` flag on the RegExp, as it will cause each successive search to start at the index of the last search's match, thus not taking the whole input value into account.

---
Closing as it works as expected.

[1]: https://docs.angularjs.org/api/ng/directive/input#usage
[2]: http://codepen.io/ExpertSystem/pen/YyWJVq?editors=101

**Comment by vchampion** [comment]
Yes, you are right, if regular expression is set as  
```
$scope.myRegExp = /.../i;
```
it works as expected, but if you store it as string it doesn't work. 
I updated my [fiddle](http://jsfiddle.net/champion/wmnegLdz/) with usage of 
```
<input ... ng-pattern="myRegExp" />
```
and it doesn't work.

I need to use regexp as string because it fetched from database

**Comment by vchampion** [comment]
My example should work because in angular.js you can find that lines
```
forEach(ALIASED_ATTR, function(htmlAttr, ngAttr) {
  ngAttributeAliasDirectives[ngAttr] = function() {
    return {
      priority: 100,
      link: function(scope, element, attr) {
        //special case ngPattern when a literal regular expression value
        //is used as the expression (this way we don't have to watch anything).
        if (ngAttr === "ngPattern" && attr.ngPattern.charAt(0) == "/") {
          var match = attr.ngPattern.match(REGEX_STRING_REGEXP);
          if (match) {
            attr.$set("ngPattern", new RegExp(match[1], match[2]));
            return;
          }
        }

        scope.$watch(attr[ngAttr], function ngAttrAliasWatchAction(value) {
          attr.$set(ngAttr, value);
        });
      }
    };
  };
});
```
So, string regexp should transformed to object and then used in the directive code
```
var patternDirective = function() {
  return {
    restrict: 'A',
    require: '?ngModel',
    link: function(scope, elm, attr, ctrl) {
      if (!ctrl) return;

      var regexp, patternExp = attr.ngPattern || attr.pattern;
      attr.$observe('pattern', function(regex) {
        if (isString(regex) && regex.length > 0) {
          regex = new RegExp('^' + regex + '$');
        }

        if (regex && !regex.test) {
          throw minErr('ngPattern')('noregexp',
            'Expected {0} to be a RegExp but was {1}. Element: {2}', patternExp,
            regex, startingTag(elm));
        }

        regexp = regex || undefined;
        ctrl.$validate();
      });

      ctrl.$validators.pattern = function(value) {
        return ctrl.$isEmpty(value) || isUndefined(regexp) || regexp.test(value);
      };
    }
  };
};
```
So, but what happens? In first step correct object of regexp is really created and passed to the directive, when it set as value to pattern attribute of element (observer called at this moment)  it casts to string and embraced with ^ and $ which is not correct.

**Comment by gkalpak** [comment]
It would work if you set it directly (e.g. `ng-pattern="/[a-z]+/i"`, but interpolation won't work as expected.
(It will come later and overwrite the `attr.ngPattern` with a string value.)

This should be fixable, but interpolation isn't supposed to be used on attributes that evaluate Angular expressions (it works sometimes, but it is mostly by chance and not future-proof).

I suggest you create a little utility function that converts the regular-expression string to a `RegExp` object.
([Another demo][1])

---
I am re-opening this, since we might want to fix it anyway.

[1]: http://codepen.io/ExpertSystem/pen/JYKwZe?editors=101

**Comment by Narretz** [comment]
@gkalpak Do you mean fixing interpolations inside evaluated expressions or is there a more specific problem with ngPattern?

**Comment by gkalpak** [comment]
No, I meant with `ngPattern`. It might be a good idea to move the logic that parses strings like `'/.../'` to `RegExp` Objects inside `patternDirective`.
(But I haven't thought this through yet.)

**Comment by gkalpak** [comment]
@Narretz, #12918 is what I had in mind. <sub>(It might be kind of a BC though.)</sub>

**Comment by gkalpak** [comment]
So, this didn't gain any traction - it seems like it is an uncommon usecase.
Based on that and the fact that fixing it would be a breaking change and it can be worked around anyway, I am going to close it as _won't fix_.
