### ISSUE TITLE
ng-if as base element of replaced directive destroys isolate scope.

### ISSUE THREAD

**Issue by nosideeffects** [angular/angular.js#12936]
Example: https://jsfiddle.net/01mfdjwm/1/

**Comment by mzdunek93** [comment]
You could use `{{$parent.dir.hello}}`, but this clearly seems to be a bug, since the same issue doesn't exist when using `templateUrl`. Turns out that the directives at the root of a replaced directive get moved "next to" the containing directive, so the scope for the transclusion is set to be outside the directive. I submitted a fix to change the scope's prototype in such case:  #12975

**Comment by nosideeffects** [comment]
Super strange that it works with `templateUrl`. Thanks for submitting a fix!

**Comment by mzdunek93** [comment]
My pleasure. Just to be clear, it's not in yet, we'll have to wait for somebody from the core team to approve it.

**Comment by petebacondarwin** [comment]
Duplicate of #9837 ?
