### ISSUE TITLE
Pre-select an option in ng-options optgroup (with "group by" property)

### ISSUE THREAD

**Issue by pribilinskiy** [angular/angular.js#12966]
I need to pre-select an `<option>` in a dropdown that has option groups.

Without `<optgroup>` the `ng-model` reads the value and selects the right option, somewhy that doesn't work with option groups.

Giving a simple example:

```html
      <select 
        ng-model="selected" 
        ng-options="option.value group by option.type for option in options"
      ></select>
```

```js
  $scope.options = [
      {type:'Mini', value:'Option 1'},
      {type:'Mini', value:'Option 2'},
      ];
      
  //$scope.selected = 'Option 2';
  $scope.selected = {type:'Mini', value:'Option 2'};
```

and a sandbox
http://plnkr.co/edit/1AZ3VosOhfYkj1fImbwv?p=preview

**Comment by Narretz** [comment]
You can make this work by either setting the model to the item in the options:
 `$scope.selected = $scope.options[1];`
or by using `track by`:
`ng-options="option.value group by option.type for option in options track by option.value"`

This is because ngOptions by default watches the model by identity, not by equality. That means if you assign a new object to the model, even if it has the same properties as the item in your collection, ngOptions will not see them as the same (because they are equal, but not identical). This is done mainly for performance reasons, but the docs don't do a very good way of explaining this.
