### ISSUE TITLE
1.4.5 $http transformResponse property isn't fired when status code is 204 (No Content)

### ISSUE THREAD

**Issue by kvernon** [angular/angular.js#12976]
I keep wanting to use the transform response property of the config object with an http service wrapper. The docs claim that the transformResponse is fired when there is a successful status message. Instead, I get no transformResponse firing. 

I have tests that show OK, 200, works, but 204 with null or undefined data does not.

The reason why is I'd like to set up default data, but I cannot with this current behavior (I took out a few things, but this should get the gist:

```js
describe("When using the SubNavServiceUri", function() {
    var serviceUri;
    var requestUri = "/api/aliens";
    var collection = null;
    var httpBackend;

    beforeEach(function () {
        module("superSiteApp");

        inject(function (_$httpBackend_, _SubNavServiceUri_) {
            httpBackend = _$httpBackend_;

            serviceUri = _SubNavServiceUri_;
        });
    });

    afterEach(function () {
        httpBackend.verifyNoOutstandingExpectation();
        httpBackend.verifyNoOutstandingRequest();
    });

it("and NoContent it should return empty collection", function () {
        // set up correct end point
        httpBackend
            .expectGET(requestUri)
            .respond(HttpStatusCode.NoContent);

        var actual;

        serviceUri.get(requestUri).then(function (result) {
            actual = result.data;
        });

        httpBackend.flush();

        expect([]).toEqual(actual);
        expect(0).toEqual(actual.length);
    });


...
service("SubNavServiceUri", ["$http", function ($http) {
        var isNullOrUndefined = function(item) {
            return item === null || item === undefined;
        };

        var transformData = function(data) {
            var result = [];
            return result;
        };

        var get = function(uri) {
            var object = {
                cache: false,
                transformResponse: function (data, headersGetter, status) {
                    console.log("howdy ");
                    console.log("headersGetter " + headersGetter);
                    console.log("status " + status);
                    if (isNullOrUndefined(data)) {
                        return [];
                    } else {
                        return transformData(data);
                    }
                }
            };

            return $http.get(uri, object);
        };

        return {
            "get": get
        };
...
```

**Comment by gkalpak** [comment]
This isn't (directly) related to the status code, but to the response `data`. Namely, `transformResponse` is skipped if `response.data` is falsy (see [http.js#L1002-L1006][1]).

--
**A little background**

This wasn't always the case. The distinction was first introduced in 6e4955a and only affected `HEAD` requests, which makes sense, since `HEAD` requests have no body.

Then, in 9ba24c5 it was changed to apply to all requests with an empty response body, in order to _"allow empty json response"_ (when the the content-type is `application/json`).

--
I believe this is a bug. Furthermore, with the changes introduced in 6f19a6f and b9bdbe6, `defaultHttpResponseTranform()` is now able to ignore empty JSON responses.
So, I believe that the changes in 9ba24c5 can (and should) be reverted.

[1]: https://github.com/angular/angular.js/blob/6b123a0419d6cd2009f148e2f1c6be3b5465373f/src/ng/http.js#L1002-L1006
