### ISSUE TITLE
Bug Dialog in AngularJS@1.4.4

### ISSUE THREAD

**Issue by moacir-selinger** [angular/angular.js#12990]
Built a module to manage the loading templates for Modal Bootstrap. After upgrading my version of *angularjs@1.4.4*, to close a Modal, I can not open it.

**Simulation**: (http://embed.plnkr.co/3fLH5OaVQrnzalj8831U/preview)
Open your console in the browser, click the "Open Modal" button, it opened perfectly and the island was writing an element I scored. After open, close the Modal and try to open it again, see that it was no longer displayed. Note that the console the writing element is different from the first time it was opened.

**Note**: Change the version of *angularjs@1.4.3* and see that the problem does not happen.

**Comment by gkalpak** [comment]
I think it, having a more concise reproduction would help.
<sub>(I.e. one with less moving parts/dependencies.)</sub>

**Comment by fernandomoraes** [comment]
bug in my app too

**Comment by Narretz** [comment]
It seems in the plnkr, a file called bootstrap-modal.js is missing.

**Comment by moacir-selinger** [comment]
Okay @Narretz , this bootstrap-modal.js import was a modified version of Bootstrap, but could simulate the problem using the original version of them just forgot to remove the import, I'm sorry.

Towards a more concise playing, I do not know how to do, I cleared my code as much as I could without compromising the flow of my scenario. Right now, I need your help with more skills on the subject.

**Simulation**: http://embed.plnkr.co/3fLH5OaVQrnzalj8831U/preview

Thank you!

**Comment by Narretz** [comment]
It's because of this commit: https://github.com/angular/angular.js/commit/6838c979451c109d959a15035177ccee715ccf19 It does seem to have side-effect after all, but we need to investigate more (you are welcome to look at it, too).

**Comment by Narretz** [comment]
@lgalfaso Do you think you could take a look at this? It seems to happen because of the $q performance improvement you committted.

**Comment by fernandomoraes** [comment]
removing the lines of commit, works fine!

**Comment by Narretz** [comment]
I've checked this again, and this is a bug in the dialog directive. This has only worked before by chance, because the directive is doing some really odd stuff.
First, the dialog directive is compiled. Then, after the content promise is resolved, it is compiled and appended to the dialog. But because the dialog is replaced and has a templateUrl, the content wasn't correctly appended to the dialog on the second try. What you should do is to append the content to the dialog, and then compile it. http://plnkr.co/edit/4OwrRINQplQ00zioSPOm?p=preview
The directive is also leaking dom nodes when the modal is closed, so you should investigate this.

**Comment by fernandomoraes** [comment]
@HenriqueLimas
