### ISSUE TITLE
Input ngModel of type Date is not updated when changed from custom directive

### ISSUE THREAD

**Issue by katemihalikova** [angular/angular.js#13001]
**Overview of the Issue**
When the model shared between custom directive and input is changed from the directive, it is not updated in the input. Binding in template updates correctly. Updating input works as exprected - updates both binding in template and directive value.
**Angular Version(s)**
1.3.0 and up
**Browsers and Operating System**
Tested on Chrome 45.
**Reproduce the Error**
http://jsfiddle.net/mr58yjvr/
`+` and `-` buttons update the model in the directive.

**Comment by mzdunek93** [comment]
Notice that when you put
```
$scope.shownDate = new Date();
```
It updates correctly. Maybe there's something wrong with the formatting?

**Comment by katemihalikova** [comment]
@mzdunek93 http://jsfiddle.net/mr58yjvr/1/ Still the same problem in my browser, inputs are not updated.

**Comment by frfancha** [comment]
You can see the same behavior directly in your ng-app without using the embedded directive, just put your minus button at the beginning of your html and change $root.model in the minus function and you will observe the same: bind is changed and input is not.
It is because the code doesn't change the date but the content of the date, therefore the input doesn't "see" that the object is changed.
You must assign a new date to the model when you change it from the code and everything will run fine.

**Comment by katemihalikova** [comment]
I see.. Good old reference problem :) Thanks for your explanation.
