### ISSUE TITLE
Pre and post link functions execute together

### ISSUE THREAD

**Issue by tsclaus** [angular/angular.js#13026]
In directive A that has directive B in its template (A is B's parent), the order of link function execution is: 
pre-A, post-A, pre-B, post-B
despite no asynchronicity. Version 1.4.7. Full code:

    angular.module('didyouknow').directive('slideshow', [

	'$rootScope', '$timeout', '$q', '$http', '$resource', 'Settings',
	function($rootScope, $timeout, $q, $http, $resource, Settings) {

		return {
			restrict: 'A',
			replace: false,
			transclude: false,
			scope: true,

			template: '<div class="slideshow-wrapper"><div slideshow-frame="frame" ng-repeat="frame in frames"></div>',

			link: {
				pre: function(scope, element, attrs) {
					/**
					 * content - inherited array of frame content URLs
					 * scope.frames - computed array of content to be used by angular template
					 */
					var content = scope[attrs.slideshow];

					if (!_.isArray(content)) return console.error('Directive content not an array');

					scope.frames = _.map(content, function(frameURL) {
						/**
						 * ext - file extension of the URL
						 * video - boolean for if the content is a video
						 */
						var ext = _.last(_.words(frameURL, /[^.]+/g)),
							video = ext === 'mp4';

						if (ext === frameURL || ext === '') return console.error('content URL ', frameURL, ' has no filetype');

						return {
							source: frameURL,
							ext: ext,
							video: video
						};
					})
				},
				post: function() {
					console.log('c');
				}
			}
		};
	}
    ]);

    angular.module('didyouknow').directive('slideshowFrame', [

	'$rootScope', '$timeout', '$q', '$http', '$resource', 'Settings',
	function($rootScope, $timeout, $q, $http, $resource, Settings) {

		return {
			restrict: 'A',
			replace: false,
			transclude: false,
			scope: true,

			template: '<video autoplay><source ng-src="{{frame.source}}" type="video/mp4"></video>',

			link: {
				pre: function() {
					console.log('a');
				},
				post: function(scope, element, attrs) {
					/**
					 * scope.frame - frame information
					 */
					scope.frame = scope[attrs.slideshowFrame];
				}
			}
		};
	}
    ]);

**Comment by gkalpak** [comment]
This happens because of `ngRepeat`. In a nutshell, since `ngRepeat` is a [_terminal_][1] directive, compilation stops with it (i.e. `slideshowFrame` is not compiled/linked at the time).

Later, when `ngRepeat` decides it needs to create an element from the template, it compiles and links a `slideshowFrame` element.
By this time, `slideshow`'s post-linking has already taken place.

See also:

* More info on [`ngRepeat`][2] and [how it works][3].
* [Live demo][4] of the difference between `ngRepeat` vs no `ngRepeat`.

--
Closing as everything works as expected.
<sub>
BTW, this is a general support question and, as such, it is better suited for one of the [appropriate support channels][5].
GitHub issues are reserved for bug reports and feature requests.
</sub>

[1]: https://docs.angularjs.org/api/ng/service/$compile#-terminal-
[2]: https://docs.angularjs.org/api/ng/directive/ngRepeat
[3]: https://docs.angularjs.org/guide/compiler#an-example-of-compile-versus-link-
[4]: http://codepen.io/ExpertSystem/pen/XmRqXL?editors=101
[5]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by tsclaus** [comment]
Does the same also apply to the {{}} directive? Both pre- and post-link
functions see the unmodified {{}} in child template.

**Comment by gkalpak** [comment]
@tsclaus, sorry, I don't quite get the question. Could you elaborate, please (preferrably providing a code example) ?
