### ISSUE TITLE
ng-value sets value to undefined with >= 1.4.4

### ISSUE THREAD

**Issue by tkrotoff** [angular/angular.js#13037]
Regression regarding ng-value: http://plnkr.co/edit/sYzHLS?p=preview (the directive is from a popular [StackOverflow question](http://stackoverflow.com/questions/14514461)).

With AngularJS <= 1.4.3, ng-value sets `value` properly (console.log output):
```
scope.value (from ng-value): Object {name: "Adam", $$hashKey: "object:3"}
```

The result with AngularJS >= 1.4.4:
```
scope.value (from ng-value): undefined
```

Edit:
Tested under Chrome and Firefox.
List of commits between 1.4.3 and 1.4.4: https://github.com/angular/angular.js/compare/v1.4.3...v1.4.4

**Comment by Narretz** [comment]
I think it's because of this commit: https://github.com/angular/angular.js/commit/533d9b76704368ba9700ab08589118abca9f598c

Tricky question if this should work, or if you should simply do: 
```
scope: {
  value: '=ngValue'
}
```
because `@` is only for interpolations (strings) and the scope bindings do not really consider ngValue et. al.

**Comment by tkrotoff** [comment]
@Narretz Thx, I confirm it works with `value: '=ngValue'`: http://plnkr.co/edit/WLqOYh?p=preview

**Comment by Narretz** [comment]
I think we can close this as wontfix, because relying the another directive to set the attributes for the bindings is obscure and not really documented.
