### ISSUE TITLE
event.targetScope not showing include's $scope variables with $includeContentLoaded

### ISSUE THREAD

**Issue by vovafeldman** [angular/angular.js#13043]
Hi Guys,

I'm not an angular expert, but couldn't find any documentation of that. I've setup a simple ng-include element:
```
<ng-include src="'templates/partials/my-template.tmpl.html'"></ng-include>
```

I would like to pass some data into the include's controller scope. I've read that the best way would be to listen to `$includeContentLoaded` on the parent controller, and use `event.targetScope` to access the child scope. Something like:

```
$scope.$on('$includeContentLoaded', function(event) {
    event.targetScope.x = 1;
    event.targetScope.y = 2;
    event.targetScope.executeFunction();
});
```

The modification of `x` and `y` works when I inspect thigns in the include's controller, but while inspecting `event.targetScope` from within the `$includeContentLoaded` handler, it doesn't show the $scope params that I initiated in the include's controller, therefore `event.targetScope.executeFunction()` fails (the method just does not exist). When I inspect `event.targetScope.$$childTail` I do see all the $scope variables.

Any ideas what's going on? Or what's the right way to do it?

**Comment by Narretz** [comment]
ng-include creates a new child scope and ng-controller also creates a new child scope, so if you're code looks like this: http://plnkr.co/edit/gUrtQnUPNDCEcfF3Spbs?p=preview you have a scope tree that looks like this:
(1) mainCtrl -> (2) ngInclude -> (3) templateCtrl

By way of prototypical inheritance, all properties and functions set on the parent scopes are available on the child scopes. But it doesn't work the other way round, so scope (1) has no idea what is on scope (2) or (3).
This is the way it works, so there's no way to access the fn on the child scope without reaching into the scope tree.

**Comment by vovafeldman** [comment]
Can I specify the controller of the ng-include without creating a new controller in the template?

**Comment by Narretz** [comment]
You should be able to put the ng-controller on the same element as the
ng-include
Am 15.10.2015 22:32 schrieb "Vova Feldman" <notifications@github.com>:

**Comment by vovafeldman** [comment]
Now `event.targetScope.executeFunction();` works, but in the target controller:

```javascript
$scope.executeFunction = function() {
     alert($scope.x);
};
```

The variable `x` which is set via `event.targetScope.x = 1;` is undefined. What am I missing?

**Comment by Narretz** [comment]
That's because we now changed the scope order. The compiler is pretty complex and prototypical inheritance does adds another layer, stuff like this can happen ... now it's main -> templateCtrl -> include. In prototypical inheritance, children look at the parent to read, but when they write, they write locally. x and y are strings, they are only set on the child scope, not on the parent scope. But if you define an object on the templateCtrl, and then set the values inside this object from viewContentLoaded, it will work. Basically, your data on the scope should always be inside objects, then you will not run into this problem: http://plnkr.co/edit/gUrtQnUPNDCEcfF3Spbs?p=preview

**Comment by vovafeldman** [comment]
Thanks for the workaround and the code example - it worked! It does sound pretty complex :)
