### ISSUE TITLE
animateCss shoul not alter the original options object

### ISSUE THREAD

**Issue by sevdog** [angular/angular.js#13040]
When using `$animateCss` if the options passed are stored in a variable after the animation the original options object is altered and using it in a new animation will fail (as you can see  on codepen http://codepen.io/anon/pen/avWgaX).

If a copy of the configuration object (made using `angular.copy`) is provided the configuration object is reusable.
But forcing the developer to copy the configuration object each time he wants to use it is quite annoying. And copying the whole object might be a performance bottleneck.

If altering some elements of the configuration object is needed, this should not affect the original provided object.

Tested on Angular 1.4.7

**Comment by Narretz** [comment]
Sounds reasonable. Would you care to open a PR that implements this change?

**Comment by matsko** [comment]
Yes this is very important indeed. It shouldn't be a tricky thing to put together besides that the fact that the other areas of ngAnimate do infact work with a mutable options object. Therefore you'll need to ensure that $animate creates a copy of the provided options object as well as $animateCss.

If this is something that you're interested in putting together then please create a PR, otherwise let me know and I'll craft up a fix. Thank you @sevdog.

**Comment by sevdog** [comment]
I'd like to make a PR and fix this personally, but at the moment I don't have much time.
So, this time, I leave the fix to you.

**Comment by matsko** [comment]
@sevdog here we are: https://github.com/angular/angular.js/pull/13175

**Comment by sevdog** [comment]
Very good, thanks @matsko

**Comment by gkalpak** [comment]
@Narretz, did you reopen this on purpose ?

**Comment by Narretz** [comment]
@gkalpak Yes, because I accidentially merged the PR, before it was ready (imo). I reverted the merge, and reopened the issue and the PR. :|

**Comment by gkalpak** [comment]
Yeah, I just noticed :)
