### ISSUE TITLE
angular 1.4.7 ngModel.NgModelController.$parsers not call third time registered function

### ISSUE THREAD

**Issue by uhlryk** [angular/angular.js#13068]
How to reproduct problem: 

Create directive and register function in ngModel.NgModelController.$parsers
This function should whenever called change $viewValue to some fixed value. e.g char 'a'. Add directive as atribute to input field with model. Then focus on input field, and press 3 times same button e.g. '1'. First time it show 'a' in input field. Second time also the same. But third time it show 'a'+pressed char (e.g. 'a1'). In browser console at third time also Im not get messages from console.log.

it work correctly angular 1.2.9, problem is in angular 1.4.7. I test it in latest chrome and safari in os x (10.10.5).

I created examples:

angular 1.2.9 : http://jsfiddle.net/hwzxfon3/1/

angular 1.4.7 : http://jsfiddle.net/372re41m/1/

**Comment by Narretz** [comment]
This must have changed somewhere in 1.3, I think. The parsers API isn't really equipped to to modify the viewValue inside a parser, that's why the results can be a bit unexpected. However, instead of assigning the viewValue directly, you can do `ngModelController.$setViewValue('A');` to make sure the viewValue is correctly updated.
