### ISSUE TITLE
Can't Access `this` in filterFilter predicate function (es6)

### ISSUE THREAD

**Issue by ozsay** [angular/angular.js#13079]
Hi,

I'm developing an app in es6 using angular and I have the following scenario.

My controller is a class which has a method that i try to run as a filterFilter predicate function.
In the method I need to access the `this` keyword but it's undefined.

Here is a codepen to demonstrate the issue:
http://codepen.io/anon/pen/BodGLX

I'm accessing `this` in filter2 (filter1 works fine).

I can somehow add the array to the scope, but i try to avoid using scopes.

Any suggestions?

Thanks,
Oz

**Comment by gkalpak** [comment]
This is not ES6-specific (obviously) nor is it `filterFilter`. The problem is that the context (`this`) is not retained, when passing a (normal) function around as an argument.

As a work-around, you could use a fat-arrow function (which retains the context):

```typescript
class TestCtrl {
  ...
  filter2 = (value) => {
    if (this.array2.indexOf(value) === -1)
      return true;
  }
  ...
}
```

Or explicitly bind the controller's instantce as context:

```typescript
class TestCtrl {
  ...
  filter2 = this._filter2.bind(this);
  ...
  _filter2(value) {
    ...
  }
  ...
}
```

---
I wonder if we could try to retain the context on the Angular side (when parsing the expression), but there was a similar discussion about retaining the context in an `ngModel` getterSetter function and I think we decided against it (although I don't remember why: complexity? perf-hit? something else?).

**Comment by ozsay** [comment]
I used the second way.

Thanks for the fast answer.

**Comment by Narretz** [comment]
Good to hear I could help!

**Comment by Narretz** [comment]
Oops; I though I answered this, but it was of course @gkalpak ! :D

**Comment by gkalpak** [comment]
I had it coming since I don't set a milestone on the issues I triage :stuck_out_tongue:
(I'm still clueless most of the time when it comes to milestones...)
