### ISSUE TITLE
transclude element is causing duplicated attributes

### ISSUE THREAD

**Issue by skidvd** [angular/angular.js#13075]
I apologize if this is a duplicate, but I'm not sure how to continue the discussion in 3505 which has bee closed for some time.

As described in https://github.com/angular/angular.js/issues/3505, I have removed the duplicated attributes.  However, it does not work in all cases. Wrapping an input that has ng-required and ng-model attributes, for example, will move the effective copy of those attributes to the wrapping ```<div>```'s copy. This makes the ones on the input element themselves non-functional (even if you remove the additional copies as described above.

I am attempting to use transclude: 'element' in order to 'wrap' input elements so that I can apply CSS pseudo classes to support visual emphasis in certain circumstances (e.g. required).  Duplciated attributes (even though removed as described in 3505) make ng-model on input itself no longer effective - rendering entire approach not workable.  In essence, I want to declare an 'A' directive that overloads ng-required attribute and then wraps as the input element itself does not support CSS pseudo classes.  All works find except for the duped attributes supersede and the ones on the input are no-ops after the wrapping.

I have a very ugly plunker http://plnkr.co/edit/UD26hYq42DykR5KWJR2i?p=preview showing 3 different approaches I have attempted to realize this.  I apologize in advance as the plunker is very ugly as I have been hacking at it for a bit.  You can switch between the 3 different attempts by changing the inlcude in index. html.

ngRequired3.js (default) is as described above.  The ng-model and other attributes do not appear to have any effect as the watch is no longer triggered
ngRequired.js is actually the closest to working.  Although it is much more complicated than a transclude: 'element' based approach would be.  The main remaining issue in this option is that those input controlled by ng-if can have visual issues as the directive is compiled even when ng-if is false.
ngRequired2.js this is a different attempt to manipulate the DOM in the link function.  This seems to produce correct DOM structure for all but ng-if controlled input - which appears to get dropped entirely with this version.

Lastly, I have also made many other attempts including wrapping and/or use of $compile have resulted in endless compile/digest loops.

I'd appreciate any thoughts or ideas (that support CSS pseudo element based approached) on how to best accomplish this seemingly simple task.

**Comment by Narretz** [comment]
The main duplication issues are probably caused by using `replace: true`, which is deprecated. `transclude: element` is making this worse, I guess. However, this is not really the place for discussing these kinds of questions. You are probably better off in one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question 

That said, I think you will get more people to look at your examples if you clean them up. There seems to be a lot of code in them that is actually not needed for the core of the problem. I would suggest you make it so that one can see all three different implementations at the same time (so not using ngRequired as the directive). You should also structure your HTML better so we can see which inputs etc. belong together
