### ISSUE TITLE
memory leak using $http.get() 

### ISSUE THREAD

**Issue by angufix** [angular/angular.js#13089]
after using $http.get() function heap and listeners grow. Heap may be collected a bit, but not completely, listeners are never collected.   http://plnkr.co/oDIvkY

![5 clicks](https://cloud.githubusercontent.com/assets/15122959/10488018/0819131c-7297-11e5-8e0f-33abf24c2684.jpg)

![some clicks - pause - some clicks](https://cloud.githubusercontent.com/assets/15122959/10488020/0af2763c-7297-11e5-9278-113bbdd107b1.jpg)

**Comment by frfancha** [comment]
I am very happy that you could write a reproduce scenario and I will be extra happy when a fix will be available ;-)

**Comment by frankweb** [comment]
@angufix do you have any idea about why that happens?

**Comment by angufix** [comment]
Now I'm a bit unsure whether it is a real memory leak, because if you take 2 snapshots and compare them there are only system things (surrounded with round brackets) left allocated. Timeline and Heaprecorder still show some leaks.

So the question is which tool should I trust?

I looked around in angular.js especially in createHttpBackend function. an xhr object is created first
```javascript
var xhr = createXhr();
```
then it is filled with extra stuff like  callbacks for onload, onerror methods. In the completeRequest function xhr was set to null, but those callbacks were still unset, so a possible solution could be : 
```javascript 
function completeRequest(callback, status, response, headersString, statusText) {
      // cancel timeout and subsequent timeout promise resolution
      if (timeoutId !== undefined) {
        $browserDefer.cancel(timeoutId);
      }
      xhr.onload = null;
      xhr.onerror = null;
      xhr.onabort = null;
      jsonpDone = xhr = null;

      callback(status, response, headersString, statusText);
      $browser.$$completeOutstandingRequest(noop);
    }
```
in the time line we have then only one listener pro http request. What do you think about it?

**Comment by Narretz** [comment]
@angufix Can you create a custom build of angular with that change and check if it improves the situation?

**Comment by angufix** [comment]
@Narretz  I'm not angular developer and currently I cann't spent much time on setupping angular build environment. What I've done is to hack the 1.4.7  version of angular.js. as I described, and that was the solution to me.

**Comment by frfancha** [comment]
@angufix @Narretz I will put the hack in our solution and test our memory problem and let you know the result.

**Comment by thorn0** [comment]
@angufix Just press the 'Collect garbage' button in the middle of profiling, and you'll see that all the listeners are GC'ed. There is no leak.
![image](https://cloud.githubusercontent.com/assets/94334/10605356/5483686a-7733-11e5-9582-a75846ede3c7.png)

**Comment by tchavanis** [comment]
I think there are still an issue.

![listenergrowup](https://cloud.githubusercontent.com/assets/16155135/11595048/bf88f894-9aad-11e5-805f-2b72421113aa.PNG)

To get this result, I click during 90 secondes on button "test mem leak" and I force GC at the 92th second.
I think there are two issues:
- The number of listeners grow up without any reason. It seems that the "automatic" GC and the "forced" GC work differently because when "automatic" GC is executed only JS Heap is reduce and not the number listeners. It is necessary to force GC to "reset" correctly the number of listener.
- When I "forced" GC the JS Heap do not retrieve the initial size (at startup JS Heap is equal to 9 300 000 and after "forced" GC JS Heap is equal to 9 560 000). So maybe there is a leak.

Maybe it is a normal behavior but I need to understand why.
Thank you for your help.

**Comment by lgalfaso** [comment]
@tchavanis I understand that you have a need to explain this, but at the end of the day, that discussion needs to happen within the Chrome project (or within the specific browser that you would like to explain this behavior at) and not in Angular.
