### ISSUE TITLE
Possibility to send form from ngFormCotrnoller

### ISSUE THREAD

**Issue by piernik** [angular/angular.js#13098]
I've made my own form directive 

	<if-form form="vm.form" submit="vm.sendForm()">
		<if-fields fields="vm.myFields"></if-fields>
	</if-form> 
	
In that directive I have regular form `<form name="vm.form" novalidate ng-submit="vm.form.$valid && vm.sendFormUsingFunc()">....</form>` so in `vm.form` I have `ngFormController` (with $invalid, $dirty, $error and so on).

I want to submit form from outside `<if-form>`.
I whish I could use `vm.form.$submit()` and it would trigger `ng-submit` and check whole validation and eventually send form. 

	<if-form form="vm.form" submit="vm.sendForm()">
		<if-fields fields="vm.myFields"></if-fields>
	</if-form> 
	<a ng-click="vm.form.$submit()">Check and submit form</a>

**Comment by Narretz** [comment]
This sounds more like a support question than a feature / bug report. Please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

That said, the form directive reacts to submit events caused by user interaction. If you want to force submit, you can trigger the event manually, or extract what angular does on submit and put it in your own function.
