### ISSUE TITLE
updateOnDefault leaks to a sibling models 

### ISSUE THREAD

**Issue by bopm** [angular/angular.js#13135]
When I try to set updateOnDefault in my directive it starts leaking to a sibling models controllers. 
Here is example: http://plnkr.co/edit/MQAA6mxfCV88QQPSUadU?p=preview

**Comment by gkalpak** [comment]
I don't get what the problem is. Could you clearly describe what is the expected vs actual behaviour ?

**Comment by bopm** [comment]
@gkalpak before you press on "Include second directive" checkbox, there is only debounce directive active and both inputs have updateOnDefault set to true. It's already a problem as if you see on top level only update on blur defined in ng-model-options. But when you click checkbox and activate second directive which sets updateOnDefault to false that setting leak to all models on a form. I guess that somehow connected to ngModelOptionsDirective being non-isolated by scope. But I am not sure.

**Comment by gkalpak** [comment]
@bopm, I see what you mean :)
This is basically because `ngModelOptions` are inherited from parent nodes. Since your inputs do not have an `ngModelOptions` directive, they inherit the `$options` object of the `ngModelOptions` instance on the form element. So, it is indeed the exact same object that you are modifying in each directive instance (thus the propagation of values to all inputs).

--
Basically, what you need is a programmatic way to set `ngModelOptions`, but unfortunately there isn't one right now (at least not without resorting to hacks or private/unstable APIs). This feature has been requested in #12884 (and I think there's a good chance of it getting implemented).

You can track the other issues for any progress on this feature.

**Comment by bopm** [comment]
I aware about #12884 and hope it'll be here for us soon. I created this issue for case it'll not be covered by that. But looking on new implementation with $ModelOptionsProvider I think all will be fine.
