### ISSUE TITLE
Manual bootstrapping and using factories to share data between modules

### ISSUE THREAD

**Issue by armanforghani** [angular/angular.js#13136]
I have two modules as the following code. I want to share some data between these modules. I can do that and get the same instance (Singleton) of the factory when i bootstrap nodes using single botstrap  command ```angular.bootstrap(".app1, .app2", ['myApp']);``` but i get two separated instances of the factory when i use two bootstrap commands for my nodes ```angular.bootstrap(".app1", ['myApp']);``` and ```angular.bootstrap(".app2", ['myApp']);```. In the latter case i cannot share data between modules.

[Please see demo](http://jsbin.com/yecozu/edit?html,js,output)

```
var otherApp = angular.module('otherApp', []);

otherApp.factory('myService', function() {
  var viewModel = { test: "" };
    var myService = {
        query: function () {
            viewModel.test = "Hello";
        },
        getViewModel: function () {
            return viewModel;
        }
    };
  return myService;
});
otherApp.controller('otherCtrl', function($scope, myService) {
  $scope.query = function() {myService.query();};
  $scope.shared = myService.getViewModel();
});

var app = angular.module('myApp', ['otherApp']);
app.controller('myCtrl', function($scope, myService) {
  $scope.shared = myService.getViewModel(); 
});
  
angular.element(document).ready(function() {
  angular.bootstrap(".app1, .app2", ['myApp']);
  
  //angular.bootstrap(".app1", ['myApp']);
  //angular.bootstrap(".app2", ['myApp']);
});
```

**Comment by gkalpak** [comment]
Angular services (such as those registered using `.service()`/`.factory()`/`.value()`/`.constant()`/`.provider()` are "per injector" singletons.
Since you are bootstraping 2 apps (each with its own injector), there will be 2 `myService` instances.

This can be easily solved by re-using the same object. E.g.:

```js
var myService = (function () {
  var viewModel = ...;
  var myService = ...;
  return myService;
}());
app.value('myService', myService);
otherApp.value('myService', myService);
```

--
Still, there is a more difficult problem to solve: Informing one app that a value has been changed from the other app (i.e. manually handling the `$digest` cycle, which is usually automatically handled by Angular).

There are several resources out there (on Google, StackOrerflow and GitHub) abut how you can tackle this (but it's not a trivial problem). Off the top of my head, [angular-widget][1] can take care of this I believe (but sure there are others as well).

---
Closing as this already works as expected.

[1]: https://github.com/wix/angular-widget
