### ISSUE TITLE
"nodeName" as input's name

### ISSUE THREAD

**Issue by khernik** [angular/angular.js#13143]
Creating new input with "nodeName" name gives me an error in angular.js:12416 (angular 1.4.5) where angular is calling jQuery toLowerCase on name attribute, resulting in e.nodeName.toLowerCase is not a function.

**Comment by gkalpak** [comment]
This hapens because `form` elements are made accessible as properties on their parent `form` element with their `name` attribute values as keys. I.e.:

```js
var input = document.createElement('input');
input.name = 'someInput';

var form = document.createElement('form')
form.appendChild(input);

console.log(form.someInput === input);   // true
```

This is not Angular-specific. Thus, specifying an `input` with a name that equals a property of the parent `form` element, it effectively shadows that property.
Needless to say, (Angular or not) it is not a good idea to have an `input` named "nodeName".

--
Closing as this is not Angular-specific and there doesn't seem to be anything to be done on the Angular side.
<sub>Feel free to re-open (providing the necessary info), if you think otherwise :smiley:</sub>
