### ISSUE TITLE
non english support only works on 1.2.1

### ISSUE THREAD

**Issue by donghwicha** [angular/angular.js#13142]
as you can see the link below, typehead works fine on 1.2.1 with korean (you can test whatever language you want)

http://jsfiddle.net/ffuw2shL/1/

but if you change angular version then it won't work, which means that every version of 1.2.x won't work at non english type event. 
I've tested with angular ui select ( https://github.com/angular-ui/ui-select ) but it also occurs as the same. this widget can be buggy with 1.2.1 but you can find out key typing event only. 

is there any plan to solve this? 

thank you.

**Comment by Narretz** [comment]
Sorry, 1.2.x does not receive bug fixes anymore. Can you test if the problem happens in Angular 1.4.7? If it does and we can fix it there, maybe someone can create a patch for 1.2.x that you can apply in your app.

**Comment by donghwicha** [comment]
I've captured video. 
testing with 1.2.1
-> https://youtu.be/no1L3vgBbcM
testing with 1.2.29
-> https://youtu.be/Ur5awg8KeoA

as you can see, type ahead isn't working with one syllable of Korean 
at angularjs 1.2.29

but this works with angularjs 1.2.1 

some how angularjs core has some problem with typeahead,
because what is changed is angularjs core not typeahead libraries on the test video.

any suggestion?

**Comment by Narretz** [comment]
Does it happen in all browsers? The problem sounds vaguely familiar. And does it happen in version beyond 1.2.29?

**Comment by wesleycho** [comment]
It should be noted that the version of UI Bootstrap in that fiddle is also quite old - there is a real possibility that there is a bug there that has been since fixed.

However, it should also be noted that UI Bootstrap currently only supports angular 1.3+, soon to be 1.4+ in the next release.

I would recommend tracing the source code to see what is happening in angular and UI Bootstrap, and come up with a workaround, assuming upgrading the libraries is out of the question (upgrading is preferable here). It would be difficult for others to help in this instance due to the age of libraries used here.

**Comment by Narretz** [comment]
I'm gonna close this issue as it hasn't been shown that this is an issue with angular core.
