### ISSUE TITLE
Customs events is fired before controllers are initiated

### ISSUE THREAD

**Issue by m-amr** [angular/angular.js#13181]
I am using $rootScope.$broadcast an event from ControllerA
and listen to it by $scope.on in ControllerB

in HTML

     <div ng-controller='ControllerA'></div> 
     <div ng-controller='ControllerB'></div> 

ControllerA is initiated before controllerB so 
 1- ControllerA $fired event
 2- but ControllerB isn't initiated to handle the the event

should $broadcasting event fire the events after the controllers are initiated ? or there is an event or a callback after all controller initiated

I used Marionette.js and Backbone.js before
in Marionette.js all the controller are initiated first then rendered so using event driven never cause this problem.

**Comment by Narretz** [comment]
In angular, the event system uses the scope hierachy to propagate the events. Since elements can be created / destroyed on the fly during application lifetime, the event cycle does not "wait" for elements to be created. That said, I think you should ask this question (with a minimal demo showing what you want to do) on one of the support channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
