### ISSUE TITLE
Over two “< input type=number min= >” element in ngRepeat, just one can  display the number.

### ISSUE THREAD

**Issue by harole** [angular/angular.js#13186]
### html:
![image](https://cloud.githubusercontent.com/assets/4095799/10751999/56978c52-7cc0-11e5-8778-7e436fe946fc.png)
### js:
![image](https://cloud.githubusercontent.com/assets/4095799/10752021/7d1d6004-7cc0-11e5-92d4-96db6c2ebf9a.png)
### description:
I have three input element with "min" type, and they have same values with the "$scope.data".
### problem:
Just the last one can display in input element. And I don't know why, anybody help me?Thank you!

### sound code:
http://jsbin.com/yewipawiqe/edit?html,js,output

**Comment by gkalpak** [comment]
TBH, I am not sure what you are trying to achieve. You are creating 3 `div`s each with 3 `input`s (so you basically end up with 9 `input`s). This is the resulting HTML:

```html
<!-- ngRepeat: data in datas -->

<div ng-repeat="data in datas" class="ng-scope">
  <input type="number" ng-model="data.num" ng-show="$index == 0" min="2" class="..." />
  <input type="number" ng-model="data.num" ng-show="$index == 1" min="1" class="... ng-hide" />
  <input type="number" ng-model="data.num" ng-show="$index == 2" min="3" class="... ng-hide" />
</div>
<!-- end ngRepeat: data in datas -->

<div ng-repeat="data in datas" class="ng-scope">
  <input type="number" ng-model="data.num" ng-show="$index == 0" min="2" class="... ng-hide" />
  <input type="number" ng-model="data.num" ng-show="$index == 1" min="1" class="..." />
  <input type="number" ng-model="data.num" ng-show="$index == 2" min="3" class="... ng-hide" />
</div>
<!-- end ngRepeat: data in datas -->

<div ng-repeat="data in datas" class="ng-scope">
  <input type="number" ng-model="data.num" ng-show="$index == 0" min="2" class="... ng-hide" />
  <input type="number" ng-model="data.num" ng-show="$index == 1" min="1" class="... ng-hide" />
  <input type="number" ng-model="data.num" ng-show="$index == 2" min="3" class="..." />
</div>
<!-- end ngRepeat: data in datas -->
```

A quick explanation of what is going on:
All `input`s in a group bind to the same model value (`data.num`), so the 3rd `input` of each group overwrites the value of all inputs in the group (since it appears last in the DOM).
In the first 2 groups, the `min` validation fails on the 3rd `input`, so the model value is set to `undefined` in all `input`s of the group.

---
That said, general support questions (such as this) should be directed to one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

---
Closing as this is working as epxected.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by SrimalPriyanga** [comment]
Hey,
Check this you can find what happen inside your code in here,
http://jsbin.com/seyoyuwapo/edit?html,js,output 

When execute **ng-repeat** it's generate 9 input elements within html, but it only shows 3 of them by matching **ng-show="$index == *"**

**First Round**
When execute for **$scope.datas[0]** (num:2) it assign value **2** to the **"data.num"** and it 
update 1st input element of this round with value 2 and bind this value to the ng-model(**"data.num"**) by taking as input (because value== min:2) ,
update 2nd input element same as above (because  value > min:1) ,
& also update 3rd input element of this round **But** it doesn't take value as input (because  value < min:3) so it make ng-model(**"data.num"**) empty in this case becouse of angular 2way data binding it update **$scope.datas[0]** (num:2) as empty, so above first two elements update with an empty value & last element only hold the **$scope.datas[0]** (num:2) value.

##This Scenario happen in other two round also. you can check this using above url.

**Comment by harole** [comment]
@SrimalPriyanga 

But why the last element hold the $scope.datas\[0\](num:2) ?  

The last element is binded to the $scope.datas[0] too, why it have the num:2 ?

**Comment by SrimalPriyanga** [comment]
Actually it's difficult to understand what really happening here, because same pattern doesn't apply to the all elements.
