### ISSUE TITLE
When $scope is injected in a controller it appears to create dependency issues with Angular.mock.inject

### ISSUE THREAD

**Issue by micahblu** [angular/angular.js#13196]
For example given a controller:
```js
.controller('View1Ctrl', ['$scope', function($scope) {
}]);
``` 

and a test:
```js
describe('myApp.view1 module', function() {

	beforeEach(module('myApp.view1'));

	describe('view1 controller', function() {
		it('should ....', inject(function($controller) {
			//spec body
			var view1Ctrl = $controller('View1Ctrl');
			expect(view1Ctrl).toBeDefined();
		}));
	});
});
```
An error is given:
`Error: [$injector:unpr] Unknown provider: $scopeProvider <- $scope <- View1Ctrl`

The error is no longer present once the `$scope` injection is removed. The issue appears to be specific to `$scope` as other dependencies appear to work.

This can be quickly tested by cloning: `https://github.com/tnajdek/angular-requirejs-seed.git`
then adding the $scope injection in `app/view/view1.js` to see the error.

**Comment by gkalpak** [comment]
This is because `$scope` is not some sigleton service that can be directly injected. It is a Scope object that needs to be created (usually specifically for that controller instance).

Normally, Angular takes care of creating `$scope` and passing it to the controller, but when using the `$controller` service, you have to create it manually and pass it via `locals`. E.g.:

```js
it('...', inject(function ($controller, $rootScope) {
  var scope = $rootScope.$new();
  var ctrl = $controller('...', {$scope: scope});
}));
```

--
Closing as it works as expected.

**Comment by micahblu** [comment]
@gkalpak Thanks for clearing that up for me. I've re-reviewed the docs and it does state the $scope needs to be provided when using the $controller service. I should read more carefully. Thanks again.
