### ISSUE TITLE
Datalist combined with fallback support doesn't show proper data

### ISSUE THREAD

**Issue by klikstermkd** [angular/angular.js#13192]
If you provide a fallback support for ```datalist``` using a basic ```select``` inside ```datalist```, if you provide ```ng-model``` for the ```select```, in the options shown in the ```datalist```, the value of the ```ng-model``` is included in the ```datalist```. 

Demo: http://plnkr.co/edit/QL7H6LLKOlY30tflho7d

Screenshot:
![issue](https://cloud.githubusercontent.com/assets/520213/10791527/14d1b1a2-7d89-11e5-8654-186be78a8379.png)

**Comment by frfancha** [comment]
If you put the ng-model on the input itself, then it works.
Putting it on the select of the datalist set nothing in selectedContact even when you properly select an exiting entry such as John, I wonder if using ng-model on the select of the datalist really makes sense?

**Comment by klikstermkd** [comment]
If you open this on Safari it will make more sense. So basically whenever the user selects an option I want to be bound to a model.

**Comment by Narretz** [comment]
This is an interesting problem, but I don't think it's an angular bug, because we don't claim to have any datalist support. I agree with @frfancha that having the ng-model on the input definitely makes more sense if you are using the input with the datalist. Otherwise the model wouldn't update if somebody typed in the input without selecting from the datalist. I see room for a custom directive here that handles this, but I don't think it should be in core.

**Comment by frfancha** [comment]
And, if I correctly remember, datalists can be shared between different inputs. If this is the case ng-model on the datalist itself really doesn't make sense.

**Comment by Narretz** [comment]
I played around with it a bit, and created a very crude directive that creates the select fallback only if the browser doesn't support datalist (detection taken from https://github.com/thgreasi/datalist-polyfill). See http://plnkr.co/edit/PR1KUAIeZC3HR6maXTbF?p=preview. A real directive would probably include transclude the input element, rather than reaching out to get its values (which forced me to do some ugly stuff).

Bottomline, I think this could be a nice third party module, but I don't think it has to be in core.
