### ISSUE TITLE
Angular ng-options setting pristine to false on load (post 1.4)

### ISSUE THREAD

**Issue by jb-int** [angular/angular.js#13211]
Something about the following combination of "multiple" and "as" in the options expression is making ng-options set pristine to false when the form first loads. Is this an angular bug? Does anyone know of a workaround?

http://plnkr.co/edit/c9ZIgiiisntkJJBeFFdy

**Comment by Narretz** [comment]
Yep, that looks like a bug. You don't need `select as`,  but you need `multiple`. It's got something to do with us checking if the view / model has changed after the options have changed. When that's the case, we call $setViewValue with the new selection, which triggers a call to $setDirty.
As a workaround you could add a directive that runs after ngOptions which forces $pristine = true and $dirty = false after the initial loading.

**Comment by jb-int** [comment]
Thanks for the quick response!

Can anyone tell me how to add a directive that runs after ngOptions?

**Comment by m-amr** [comment]
@Narretz  I think i found the problem
prevoiusValue and nextValue are array for example

    previousValue = [1,2]
    nextValue = [1,2]

The are the same value but the === operator will return false because they are array

    if (!ngModelCtrl.$isEmpty(previousValue)) {
          var nextValue = selectCtrl.readValue();
          if (ngOptions.trackBy ? !equals(previousValue, nextValue) : previousValue !== nextValue) {
            ngModelCtrl.$setViewValue(nextValue);
            ngModelCtrl.$render();
          }
        }

what cause the problem is ngOptions.trackBy is undefined and 
(previousValue !== nextValue) i will be true becuase [1,2] !== [1,2]

why angular are just not use equals() function ??
