### ISSUE TITLE
Div width watcher does not fire properly upon switching Bootstrap tabs

### ISSUE THREAD

**Issue by mtevrst** [angular/angular.js#13221]
I  wrote this AngularJS directive to set the height of each list item on a page to be equal to its Bootstrap controlled dynamic width:

```js
app.directive('squareDiv', function () {
    return {
        restrict: "A",
        link: function (scope, element,attr) {
            scope.getWidth = function () {
                return element.width();
            };
            scope.$watch(scope.getWidth, function (width) {
                element.css({ 
                    height: width + 'px'
                });
            }, true);
        }
    };
});
```

When I load this page, the first tab's list items show up as squares which means the directive worked correctly. But after switching to another Bootstrap tab, the items take their default height. Console logs show that the watch is running one tab click behind. This seems like a bug.

Here is the link to a plunker that illustrates this problem: http://plnkr.co/edit/Pc7keuRXR9R3U6AhZmFE?p=preview

Here is the discussion on StackOverflow on this same question: http://stackoverflow.com/questions/33414355/why-does-this-width-watching-angularjs-directive-not-work-upon-switching-bootstr

**Comment by gkalpak** [comment]
From a quick look, it seems like an issue with jQuery (bug ?). (/cc @mzgol)

Under certain circumstances (which I haven't investigated in depth), it seems that `.width()` misinterprets a style of `width: 100%;` as `width: 100px` (i.e. returns a value of `100`).
It ends up in [this block][1] with `val === '100%'`. As a result `num = parseFloat(val)` results in `100` (which should mean "100px") and that messes up with your divs's height.

You can verify this by entering the following in the console of your plnkr:

```js
// While Tab2 is hidden
var oneOfTheHiddenDivs = document.querySelector('#tab2 [square-div]');
console.log('Width:', $(oneOfTheHiddenDivs).width());   // Prints: 100
```

--
That said, it is not considered a good practice to access DOM properties (especially if that results in [layout thrashing][2]) **in a watch function**, because a watch function can be triggered multiple times during a digest (at least 2).
(Performance is not the only reason, but it's a major one).

In fact, using jQuery's `.width()`, which uses `getBoundingClientRect()` under the hood, will cause a _forced synchronous layout_ (aka _layout thrashing_) each time.

--
Closing as this is a general support quetion and as such ill-suited for GitHub).
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: https://github.com/jquery/jquery/blob/99e8ff1baa7ae341e94bb89c3e84570c7c3ad9ea/src/css.js#L309-L310
[2]: http://ricostacruz.com/cheatsheets/layout-thrashing.html
[3]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by mgol** [comment]
> From a quick look, it seems like an issue with jQuery (bug ?). (/cc @mzgol)

The jQuery docs for [`.width()`](https://api.jquery.com/width/) say:

> The value reported by `.width()` is not guaranteed to be accurate when the element or its parent is hidden. To get an accurate value, ensure the element is visible before using `.width()`. jQuery will attempt to temporarily show and then re-hide an element in order to measure its dimensions, but this is unreliable and (even when accurate) can significantly impact page performance. This show-and-rehide measurement feature may be removed in a future version of jQuery.

In the @mtevrst's plunkr the code is firing `.width()` on hidden elements so the output may be completely broken according to the docs. There is not jQuery bug here then, it's documented to work like that.
