### ISSUE TITLE
ng-model does not update input[type=date] field

### ISSUE THREAD

**Issue by cicuz** [angular/angular.js#13224]
Binding from the form to the model works as expected, but I wanted to add some weeks-incremental buttons and I noticed that changes applied directly to the model are not reflected on the actual field.

To reproduce, and making sure that it was not something caused by my specific setup, I went to [the API documentation page for `input`](https://docs.angularjs.org/api/ng/input/input%5Bdate%5D#example) and put some code in the browser's console (after inspecting a random element in the output box, and selecting the proper frame as the current context): `angular.element($0).scope().example.value.setDate(20); angular.element($0).scope().$apply()`.

The result I'm getting is an update on the text value only; am I wrong in assuming that this should result in an updated input field as well?

**Comment by gkalpak** [comment]
This happens because `ngModel` uses the bound value **by reference** (for performance reasons). So, when you change the date of the current Date object, `ngModel` still sees that it's the same object and it doesn't trigger an update (even if the object's properties have changed).

You can work-around this by replacing:

```js
$scope.dateObj.setDate(20);
```

...with:

```js
var newDateObj = new Date($scope.dateObj.getTime());
newDateObj.setDate(20);
$scope.dateObj = newDateObj;
```

--
On the Angular side, I don't know if we can do better wrt data-family inputs.

At the very least we should probably document this behaviour on the [`ngModel` API docs page][1].
Currently, it is only document (by chance) on [`ngOptions` API docs page][2].

[1]: https://docs.angularjs.org/api/ng/directive/ngModel
[2]: https://docs.angularjs.org/api/ng/directive/ngOptions#complex-models-objects-or-collections-

**Comment by cicuz** [comment]
Thank you, this works, and I probably would not have ever figured it out.
I agree that this should be more clear in the docs, especially in the sections touching objects with `set` methods.
