### ISSUE TITLE
ngTransclude breaks HTML content rendering in custom directives, even with $sce.trustAsHtml() filter

### ISSUE THREAD

**Issue by matthew-sycle** [angular/angular.js#13231]
I am having trouble getting transcluded content to render properly in my custom directives.

Here are examples:

http://plnkr.co/edit/mvx5GuMrPcUPJbrOCKbD

The content coming from the external source has newline (\n) characters, and I want to use a filter to replace the newlines with <br> HTML tags.

```
app.filter('newline2br_trust', ['$sce',
    function($sce) {
        return function(input) {
          return input ? $sce.trustAsHtml(input.replace(/\n/g, '\n<br/>')) : '';
        };
    }
]);
```

This seems to work correctly if I use ng-bind-html on a single element, but if I have a custom directive with transcluded contents, it seems to ignore the $sce.trustAsHtml(), and escapes the HTML content:

```
<multiline>{{ example.data1 | newline2br_trust }}</multiline>
```

How can I get my directive to properly transclude this HTML content?

NOTE: It seems to be something with the $sce functionality with AngularJS expressions + ngTransclude, as raw/static HTML content works properly with transclude:

```
<multiline>BrLine1<br/>BrLine2<br/>BrLine3</multiline>
```

**Comment by gkalpak** [comment]
Interpolation always escapes html (actually the browser does, because interpolation sets the elements `nodeValue`, not `innerHTML` or something).

You should either use `ng-bind-html` or manually (in your directive) set the content as an elements html. In the latter case, you need to sanitize it manually (using `$sanitize`), it's more error-prone, difficult to retain the conection to the parent scope and I wouldn't recommend it.

--
It's not clear what the usecase is, but are you sure you need transclusion ?
If not and if you can't use `ngBindHtml` maybe you could pass the text to the directive via an attribute and let it handle the rest. E.g. something [like this][1].
(Note, that if you expect the data to change dynamically, thne you need to take care of updating the view manually.)

[1]: http://codepen.io/ExpertSystem/pen/ojMybw?editors=101

**Comment by matthew-sycle** [comment]
I suppose the best solution then is to wrap the transcluded content in a `<div>` or `<span>` tag with ngBindHtml.  It would be nice to have an ngTranscludeHtml directive, for situations like this, where trusted HTML is coming from an external source, and wants to be transcluded via an Interpolation/expression.

Thanks!
