### ISSUE TITLE
ng-pattern removes ng-model variable

### ISSUE THREAD

**Issue by skuepper** [angular/angular.js#13248]
ng-pattern removes ng-model variable.
See example: http://jsfiddle.net/wkzab/4/ 
If you insert a value for "title" that does not match the pattern "Data: {"title" }" is removed.
I my application the user can add a prefix and than search for the values.
But angular removes the variable, so there is nothing that can be searched for.
I think there is no reason for removing the ng-data, so please do not change it!

**Comment by gkalpak** [comment]
This has been fixed on `v1.3.x`/`v1.4.x` (e.g. see [updated fiddle][1]).
Since `v1.2.x` is only receiving security fixes (afaik), I don't think it will be fixed there.

(Leaving this open for someone to confirm it's a "won't fix" on `v1.2.x`.)

[1]: http://jsfiddle.net/ExpertSystem/ogbe805z/

**Comment by skuepper** [comment]
Thank you for the quick information, but currently I've the problem with angular version 1.4.3

**Comment by gkalpak** [comment]
I was talking about the issue, there the input was not populated with the model value.
Setting the model value to undefined, when an invalid value is read from the view is by design (so everything works as expected in that respect).

If you want to still set the model to an invalid value, you can use [`ngModelOptions`][1]'s `allowInvalid` flag. E.g.: `<input ... ng-model-options="{allowInvalid: true}" />`

[1]: https://docs.angularjs.org/api/ng/directive/ngModelOptions

**Comment by skuepper** [comment]
Thank You! ng-model-options="{allowInvalid: true}" saves my day.
And update to the angular documentation
https://docs.angularjs.org/api/ng/directive/input
is desirable.

**Comment by Narretz** [comment]
Ok, so this seems to resolved now :)
