### ISSUE TITLE
angular-sanitize.js can't parse "<scriptsssaasdsddad"

### ISSUE THREAD

**Issue by kolesnik** [angular/angular.js#13254]
Uncaught Error: [$sanitize:badparse] http://errors.angularjs.org/1.4.7/$sanitize/badparse?p0=The%20sanitizer%20w…20of%20html%3A%20%7B0%7D&p1=%3Cscriptsssaasdsddad%20trade%20filter%20saved

**Comment by Narretz** [comment]
Looks like this error has been removed for 1.5.
Is `<scriptsssaasdsddad` the whole string you wanted to sanitize? And did you call it directly with $sanitize or under which circumstances did this happen? I think the $sanitize service expects correctly formed HTML, and that's why the error is expected here.

**Comment by lgalfaso** [comment]
There is a high chance that to fix this it would need a breaking change on `$sanitizer`, and at the end of the day it would not be any better than what will be present in 1.5. I would recommend you to use the latest `$sanitizer` from the latest 1.5 beta

**Comment by kolesnik** [comment]
It works fine in the $sanitizer from the latest 1.5 beta. Thanks.
