### ISSUE TITLE
$animateCss transitionStyle not performing transition

### ISSUE THREAD

**Issue by bmmpt** [angular/angular.js#13262]
In the plunker below I have the same color transition applied 2 different ways with $animateCss.
The first uses transitionStyle and is my preferred option because I can inject any value in JS when I want to trigger an animation. In this particular case I'm injecting a value of "background-color 3s ease-out". Unfortunately, it's not working.
The second uses addClass which injects a class instead. Not totally bad, but requires me to define a class for each possible transition variance I would want to use. In this particular case I'm injecting
.color-transition {
  transition: background-color 3s ease-out;
}
You can see that the actual transition is the same, but only addClass works. I'm wondering if I misunderstood the usage of transitionStyle.

http://plnkr.co/edit/nVYAm0r8YcSJLBMEbNJD?p=preview

I have only tested with Chrome.

With a few more tests I have had times were even the addClass didn't produce the transition...

Thanks in advance.

**Comment by gkalpak** [comment]
This happens because animations are disabled by default until _"all directive and route-related templates are downloaded and compiled"_. This ensures that _"the page is fully downloaded and compiled before any animations are triggered"_.

You can either defer your animations (e.g. wrapping them inside a `$timeout`) or enable the animations during the initialization phase:

```js
...
app.run(function enableAnimations($animate) {
  $animate.enabled(true);
}
```

[Updated plnkr][1]

--
BTW, the class-based animation works, because the class will be added regardless if animations are enabled or not, so the animation is performed anyway, because of the CSS style attached to the class.

--
Closing as this seems to work as expected.
Feel free to get back if anything isn't clear.

[1]: http://plnkr.co/edit/TOyWebrctHGhnKCpdLS2?p=preview

**Comment by bmmpt** [comment]
That makes perfect sense. And now that you pointed that out, I remember coming across $animate.enabled(true); in some blog I read over my 1 month angular experience, I just didn't relate it to my issue.

Thanks

**Comment by bmmpt** [comment]
I did some research and discovered you can enable animations just for a given element and that works perfectly too. 

Is there a way to check if animations are already enabled either globally of for a given element?

Thanks in advance.

**Comment by gkalpak** [comment]
@bmmpt, you can use [`$animate.enabled(...)`][1] as a getter/setter for either a specific element or globally. E.g.:

```js
$animate.enabled();                   // Global getter
$animate.enabled(enabled);            // Global setter
$animate.enabled(element);            // Getter for specific element
$animate.enabled(element, enabled);   // Setter for specific element
```
 
[1]: https://docs.angularjs.org/api/ng/service/$animate#enabled

**Comment by bmmpt** [comment]
Thanks gkalpak.

I'm having lots of fun creating Angular animations using a service and triggering the animations from controllers or other services, without having to add or remove css classes to elements. $animate.enabled(); was the missing piece, thanks a lot!

Bruno
