### ISSUE TITLE
ngPluralize is not working when you use HTML entities

### ISSUE THREAD

**Issue by olostan** [angular/angular.js#13270]
When I use `ngPluralize` for french text I getting parse error:
```
    <ng-pluralize count="personCount"
                 when="{'0': 'Sélectionnez des articles pour plus d&apos;options',
                          'one': '1 person is &apos;viewing.',
                        'other': '{} people are viewing.'}">
```

This bug is connected with #13269 however may be there could be more simpler fix?

Plunker to reproduce: http://plnkr.co/edit/WfubVRInfBqJiUX7u8zp?p=preview

**Comment by lgalfaso** [comment]
even when this is not idea, there is no way for Angular to know when the original text had a `'` or a `&apos;` as this transformation is done by the browser. There are two ways to solve this issue:

Use `\'` instead of `&apos;` as in
```html
<ng-pluralize count="personCount"
  when="{'0': 'Sélectionnez des articles pour plus d\'options',
    'one': '1 person is \'viewing.',
    'other': '{} people are viewing.'}"
>
```

Use the expanded version
```html
<ng-pluralize count="personCount"
  when-0="Sélectionnez des articles pour plus d'options"
  when-one="1 person is &apos;viewing."
  when-other="{} people are viewing."
>
```


Other than this and given that there is no way to actually do what it is requested, then this is not actionable and can be closed
