### ISSUE TITLE
$http.post <> $.post

### ISSUE THREAD

**Issue by mvpssii** [angular/angular.js#13277]
Hello,
on left is jquerry post  ($.post("http://localhost:65066/Store/Browse2?QualificatifsIDs=483", { responseType: "json" })
on right angular post ($http.post("http://localhost:65066/Store/Browse2?QualificatifsIDs=483", { responseType: "json" }))
jquery is the good data but angular not ! 
![angular](https://cloud.githubusercontent.com/assets/15704458/11015614/2b9f82c2-8565-11e5-95b3-276dbf67116e.jpg)

**Comment by gkalpak** [comment]
Although there are some well-known differencs between `$.post()` and `$http.post()`, I don't think this is a `$.post()` vs `$http.post()` issue.

It's not about serialization (which is their main difference), but about different object values. There seems to be some other error/bug in your Angular code that puts your data in an unexpected state at the time of sending.
It's impossible to tell what it might be, due to lack of necessary info.

--
That said, this sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
