### ISSUE TITLE
Safari autocomplete not updating model

### ISSUE THREAD

**Issue by segersb** [angular/angular.js#13291]
When selecting items from the autofill menu in safari on an input field, the ng-model does not seem to update. When looking at the shadow DOM the autofill value is present though.

To enable the autofill the input tag must have an ID.
Tested on OXS 10.11.1 (El Capitan) - Safari 9.0.1 - Angular 1.4.7
http://jsfiddle.net/ro2je6ej/

Note the spell checker does seem to work.

![bug](https://cloud.githubusercontent.com/assets/15749423/11078952/4a5ef08e-8809-11e5-9244-9d8e68871040.gif)

**Comment by Narretz** [comment]
Did this work in previous version of Safari? This is usually a sign of the browser not firing the change / input event in that specifc case. Can you test if a plain change / input listener is fired?

**Comment by segersb** [comment]
I'm not sure if it worked in previous versions of Safari.
The plain onChange / onInput events are NOT being fired when using the autocomplete. However the onKeyUp and onBlur are bering fired correctly.

I tried using ng-model-options="{ updateOn: 'blur' }" in my example above but it didn't work.

**Comment by Narretz** [comment]
Looks like a bug in Webkit to me. Can you open a bug report?

**Comment by bharatn** [comment]
See if this helps - https://github.com/tbosch/autofill-event

**Comment by liviubunda** [comment]
+1

**Comment by karptonite** [comment]
This appears to still be in an issue; it is tagged as needs more info--what additional info is needed?

**Comment by Narretz** [comment]
This is a known issue, and atm Safari refuses to fire an event on a normal autocomplete. This also affects other libraries: https://github.com/facebook/react/issues/1159
Previously we decided not to change core for this fix, because we hoped that browser vendors would fix this: https://github.com/angular/angular.js/issues/1460#issuecomment-33837127
There's also no need to have a specific angular solution, as this affects other libs too.
