### ISSUE TITLE
ng-repeat of object with numeric keys sorted in reverse order

### ISSUE THREAD

**Issue by ilyador** [angular/angular.js#13298]
I have this object: 
```
streamStructure: {
    "2300": {
      countingAgent: false,
      turns: 1,
      cards: 10,
      score: 1
    },
    "2200": {
      countingAgent: false,
      turns: 2,
      cards: 5,
      score: 2
    },
    "2100": {
      countingAgent: false,
      turns: 3,
      cards: 4,
      score: 3
    } ... 
```

And I want it to repeat with the highest key number at the top (as the object is sorted.) I do  `<li ng-repeat="(kay, value) in data.streamStructure">` and no matter what I do, I get the lowest on top.

Seems like `orderBy` doesn't work since it is not an array. Other solutions suggest using filter that will turn it into an array, I don't like it since I need the keys for many other things.

 How can I get it done?
(angular 1.4.7)

**Comment by poonwu** [comment]
I think you should go by the alternative solutions, since ordering behavior for Javascript object properties is not defined. Array can be arranged, but Object properties cannot.

http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

Your best bet would be create filter that reassign the whole Object's properties in the order you want it to be read. However, above article specifically points out that not all browsers read Object's properties in the same order.

I would go with alternative solution--- something like generate keys array then apply `orderBy` filter 
```
<div ng-repeat="key in keys | orderBy:[]:true>
  {{ object[key] }}
</div>
```

**Comment by Narretz** [comment]
There's an toArrayFilter http://ngmodules.org/modules/angular-toArrayFilter that handles this conversion for you. It even saves the original key as a $key property of each array's item.
I don't think there's anything we can do here in angular core - repeating object key will never be equivalent to repeating array items.

**Comment by ilyador** [comment]
I switched to array to simplify things. Thanx.
