### ISSUE TITLE
What id the public API alternative to `$browser.notifyWhenNoOutstandingRequests` ?

### ISSUE THREAD

**Issue by kburson** [angular/angular.js#13310]
I  have rooted around forums and seen a lot of talk about `$browser` and `notifyWhenNoOutstandingRequests` to satisfy a common need to know when angular has finished all compile and digest cycles.  The ruling is that `$browser` is not a public API and it's use is therefore not recommended.

My question is, what API  or workaround is available that satisfies this need ?

I currently am using the `notifyWhenNoOutstandingRequests` to notify me when my app is finished loading and ready for user interaction, and it works great, but if this is a private method and not meant for public use, then I would surely like an alternate to fill the void.

Can you please direct me to some doc or discussion that satisfies this common request ?

Thanks

**Comment by petebacondarwin** [comment]
Generally you should not be relying on such a callback. I would be interested in your use case for this handler.

It is still a "private" API but there is the `$$testability` interface, which can be accessed publicly by `angular.getTestability(rootElement);`. This interface defines the `$$testability.whenStable(callback)` method.  While it is still private, which means that we could break it within a non-major version change, it is pretty stable since it is relied upon by Protractor.

**Comment by Narretz** [comment]
Closing due to lack of feedback.

**Comment by abstiles** [comment]
@petebacondarwin @Narretz I am not the original person who filed this, but I am also interested in the question.

I have a need to manipulate an AngularJS web page in an automated fashion for testing purposes. I am currently relying on `$browser` and `notifyWhenNoOutstandingRequests` to determine when a navigation action has completed and all relevant data has been loaded so that I can manipulate the page.

It would be a Big Problem if this mechanism were to disappear or change on me, so I am very interested in getting a proper public API that can meet this need. I can provide more information about my use case if it would be helpful.

**Comment by gkalpak** [comment]
I guess the proper thing to do, would be to make `$$testability` public, so people can depend on it.
Originally, it was exposed for the needs of Protractor, but it could be used for other tools as well.

@abstiles, could you please open a new issue about that ?

**Comment by abstiles** [comment]
@gkalpak If it helps, I will do so, but I do not know what exactly `$$testability` provides, so I'm not 100% confident it will solve my problem. An attempt to find documentation about it did not yield much. Can you point me in the direction of some information about it? @petebacondarwin mentioned a function `$$testability.whenStable(callback)` which is implied to do something similar to `notifyWhenNoOutstandingRequests`, but could I get some clarification about what `whenStable` actually waits for?

**Comment by petebacondarwin** [comment]
There is a tiny bit of documentation here: https://github.com/angular/angular.js/blob/master/src/ng/testability.js#L103-L110
Plus there you can also see that this effectively calls notifyWhenNoOutstandingRequests
