### ISSUE TITLE
how to understand the prefix（$ and $$）in the sourcecode?

### ISSUE THREAD

**Issue by Kuroky360** [angular/angular.js#13328]
had some special definition?

**Comment by Narretz** [comment]
$ denote angular APIs, core services (e.g. $scope), and properties that are added by angular (for example $index in ngRepeat). $$ are private angular services and properties that developers should not use, because they may change in the future.
As a developer you should therefore not add own services and properties that start with $.

**Comment by Kuroky360** [comment]
Awesome, thanks for the quick feedback! :+1:  Thanks.
