### ISSUE TITLE
shouldn't <input ngBind type="number"> support plus (+) prefix (i.e. +1)

### ISSUE THREAD

**Issue by NoHuman** [angular/angular.js#13338]
http://plnkr.co/fnMCtVqSDQwA2rACZSMa?p=preview

I created a small plnkr to reproduce my issue. To reproduce, just type +1 in the input element.
<input type="number" data-ng-model="valueA" />

When using Chrome or Opera, the ngModel is undefined.
When using IE or Firefox, the ngModel is 1.

![image](https://cloud.githubusercontent.com/assets/426279/11244202/91168d80-8e0c-11e5-8167-59d6554735c7.png)

**Comment by Narretz** [comment]
Looks like Webkit does not support plus signs in number inputs. You can see this here: http://plnkr.co/edit/jKyCxpoKLtOK726ozPLW?p=preview
I removed all angular app code. In the console, you can see that when I type `+1` in the input, the value of the input is empty string. So angular can never access the value, because the browser doesn't set it correctly.
I think we should open a bug in Webkit for this - `-1` works.

**Comment by cztomsik** [comment]
with an exception of mathematicians, I can't think of anybody trying to type +1 instead of just 1

**Comment by Narretz** [comment]
I opened an issue for this. https://code.google.com/p/chromium/issues/detail?can=2&q=input%20number&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&id=574157&thanks=574157&ts=1451936273 

I doubt it'll get much attention, though.

**Comment by Narretz** [comment]
Chrome's behavior is correct for this: https://code.google.com/p/chromium/issues/detail?id=574157#c4
