### ISSUE TITLE
ngCloak causes flicker when evaluating expression using not operator

### ISSUE THREAD

**Issue by bahagiga** [angular/angular.js#13364]
Hi,
Like a few I have had issues with some flickering using ng-cloak and expecting it to not flicker etc. and even though I have fixed my issue something struck me a bit for my use case.

This causes a flicker due to the second part in the expression, namely `!cartCtrl.basket.totalPrice`.
```javascript
<div ng-cloak ng-show="cartCtrl.basket.isEmpty || !cartCtrl.basket.totalPrice">
    Whoops your basket is empty!
</div>
```
If I remove the second part of the expression or simply change it to not use the not (!) operator it works fine.
```javascript
<div ng-cloak ng-show="cartCtrl.basket.isEmpty || cartCtrl.basket.hasNoPrice">
    Whoops your basket is empty!
</div>
```
I can obviously see when printing the value of `{{!cartCtrl.basket.totalPrice}}` that if first evaluates to `true` then `false` which causes the flicker. 

This has however left me a bit confused and wondering if this is as it should be? I would have expected it to immediately evaluate to false or at least somehow not have caused a flicker. 

The application I am working on uses v1.3.15 and has a rather large HTML document at its initial load but I am unsure if this has an impact on the above.

**Comment by gkalpak** [comment]
This sounds like expected behaviour. As you said `!cartCtrl.basket.totalPrice` briefly evaluates to `true` (making the element appear) and then to `false`, causing the flicker.

The fact that a "positive" expression (i.e. `cartCtrl.basket.hasNoPrice`) does not cause a flicker, indicates that the observed behaviour is caused by a (slight) delay in making `basket` available on `cartCtrl`.

Yet, it is not possible to tell with certaintly without more info. If you could create a runnable demo (e.g. using CodePen, Plnkr etc), it would be possible to investigate whether or not this is indeed expected behaviour and (if it is) suggest a good way to achieve what you want.

**Comment by bahagiga** [comment]
Hi @gkalpak,
Thanks for the fast reply. 

I am not exactly sure what you mean by *delay in making the `basket` available on `cartCtrl`*. 

I tried creating a Plnkr but I cannot reproduce the same effect. I am not sure if I should attribute it to the maybe larger initial HTML document load.

**Comment by gkalpak** [comment]
Glad I could help :smile_cat:
