### ISSUE TITLE
Is routing declaration possible in directive in Angular?

### ISSUE THREAD

**Issue by romykundal** [angular/angular.js#13387]
I want to define all site routes in directive and whole site will execute from directives. Is it possible?

I am doing projects with angularJS for front end and back end. Need to use maximum directives for every modules. So I need help from you experts buddy.

If anybody it has been done please share that example here.

**Comment by Narretz** [comment]
In angular 1, the route definitions are created in the config block. You can create different routes in different module's config blocks. It's not possible to create directives that correspond to routes. In the new router, routes are more closely mapped to directives / components, so that might be interesting for you. I'll have to close this issue though, since this is more of a general support question.
