### ISSUE TITLE
html5 mode routing

### ISSUE THREAD

**Issue by kishanmundha** [angular/angular.js#13381]
I have a website, which was running on 2 different server. In 1st server we set html5 disabled and in 2nd server html5 enabled, but project was same.

In my website there is many location where I use `<a ng-href="/path">link</a>`, angular render as `<a href="/path">link</a>` in both server. but I want to render both as per html5 setting.

It should render as

In 1st server - `<a href="#!/path">link</a>`

In 2nd server - `<a href="/path">link</a>`

But angular not rendring as per my expetation. I need to change `ng-href` in both.

I also read documentation of `$locationProvider`, but no solution found on there.

Please guide me how can I solve my problem

**Comment by gkalpak** [comment]
I have hardly played with HTML5 mode (irc), but if I understand the [dev guide][1] correctly, URLs with `#/...` would be rewritten in HTML5. If that is true, you should be able to have hash-prefixed links everywhere and let HTML5 mode rewrite the URLs for you. (But, again, haven't tried that.)

IF that doesn't work, you could create and use a custom directive (instead of `ng-href`), that prepends `#!/` when necessary (i.e. depending on whether HTML5 mode is enabled or not).

[1]: https://docs.angularjs.org/guide/$location#hashbang-and-html5-modes

**Comment by gkalpak** [comment]
FWIW, I don't think `ngHref` could do this automatically (without breaking stuff), because (with `base` into play) it is difficult to decide whether an `href` points to some path or a different page altogether (aka a full reload will be made) etc.

**Comment by kishanmundha** [comment]
Actually I can't use any directive in this point. I read a markup file and convert to html and render in view. so I have `href` only in view and `ngHref` in parent. So I can't use separate markup files for both server.

**Comment by zwacky** [comment]
@kishanmundha use ui-router with `ui-sref`. it will put in the right urls according to your html5 mode.
ng-href shouldn't cover that use case at all.

**Comment by kishanmundha** [comment]
@zwacky I don't want to use third party tools when angularJS providing `ngRoute`. If this can't done by `ngRoute` so why we use `ngRoute`. Remove this from angularJS library.

And in ui-router using `ui-sref` is bed idea because we don't remember mapping name. we remember url only. And @zwacky I already told that I am using markdown to render page. I decode markdown and render on `ng-view`. and I'm sure I can't use `ui-sref` in markdown.

I need to use core library `ngRoute` and it shoud fix by this only.

**Comment by zwacky** [comment]
don't wanna get too much in discussion with you, but ng-drc shouldn't have this.

also having names instead of urls IS good practice. but i understand if you don't want to use 3rd party tools.

why dont you wrap your url in a function call like `ng-src="{{ transformUrl('/path') }}"` where where it changes it to #/path, if `$location.$$html5` is true.

**Comment by kishanmundha** [comment]
I can't use any other directive, functions because I'm using markdown document (`[link](/mylink)`) to convert to html and render on `ng-view`.

**Comment by petebacondarwin** [comment]
You cannot simply switch between HTML5 mode and hashbang mode. If you are running in HTML5 mode and Angular detects that the browser does not support this then it does use a form of hasbang mode fallback but this is not the same as explicitly setting the mode in your app.

**Comment by gkalpak** [comment]
FWIW, I still believe one could always use `#!/...` hrefs and Angular would take care of them in HTML5 mode.

> I have hardly played with HTML5 mode (irc), but if I understand the dev guide correctly, URLs with #/... would be rewritten in HTML5.

**Comment by kishanmundha** [comment]
@gkalpak I tried all these but my problem not fixed by this. So finally I moved my both server to node.js because angularJS can't solve my problem

**Comment by gkalpak** [comment]
Thinking about it again, it is not desirable for Angular to rewrite all links to hmtl5/hashbang mode, because there might be links that need to be in a specific format. I.e. it is perfectly valid to have `#/...` urls in HTML5 mode and it is perfectly valid to have `/...` URLs in hashbang mode.

This could only be done using a custom directive which can work for your specific usecase, but it is not something Angular should do by default.

Closing as _won't fix_.
