### ISSUE TITLE
try to use "uib-tooltip-html" with angularjs template

### ISSUE THREAD

**Issue by flamant** [angular/angular.js#13404]
Hi,

I try to implement a tooltip with angularjs template inside. For this, I use "uib-tooltip-html" and I add an attribute on the element to compile the template. But it doesn't work.

Here is the plunker
http://plnkr.co/edit/y1TvogsFFBoBVra3gO3F?p=preview

Thank you in advance for your answer

**Comment by pkozlowski-opensource** [comment]
@flamant there are multiple problems in plunker:
* you are mixing versions of AngularJS modules - you need to use the same version for angular and ngSantize
* try to upgarde to the latest version of Angular (1.4.8)

But more importantly, this is a general support question that should be asked using an appropriate support channel, see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

Closing, since we are not handling support questions here but rather reserve GitHub issues for bug reports and feature requests.
