### ISSUE TITLE
Date Filter: Safari throws error if the date is an Invalid Date.

### ISSUE THREAD

**Issue by QuentinFchx** [angular/angular.js#13415]
Safari's `JSON.stringify` doesn't handle invalid dates correctly. It throws a `RangeError: Invalid Date`.
Whenever you try to interpolate an `Invalid Date` with the date filter, it breaks.
`{{ 1/0 | date }}` http://plnkr.co/edit/z8xKljNoR1GdsMQypzlq?p=preview

In https://github.com/angular/angular.js/blob/master/src/ng/interpolate.js
`parseStringifyInterceptor` > `stringify` > `toJson` > `JSON.stringify`

This issue might be too specific for a fix to be included in Angular though. Thoughts ?
I'd be glad to provide a PR.
Something along :
```
if(isNaN(date.getTime())){
  return '';
}
```
here https://github.com/angular/angular.js/blob/master/src/ng/filter/filters.js#L489

**Comment by petebacondarwin** [comment]
In my tests the date filter, on Safari, is returning a Date object correctly. It is just that this object represents an 'invalid' date.
It would seem to me that the problem is in our `stringify` function, which should catch the error thrown by `JSON.stringify` for invalid Date objects.

**Comment by petebacondarwin** [comment]
See http://plnkr.co/edit/IKr0VPSzs2Mh9ORV7iH1?p=preview

**Comment by BobChao87** [comment]
I decided to try and take a stab at fixing this as it seemed like a pretty simple first problem for getting involved here.

I'm not certain what the expected behaviour should be though. As is, in all browsers but Safari, the return from `angular.toJson` for this test scenario is the string `"null"`. Is this the desired behaviour? It matches the expected return type of `{string|undefined}`.

Catching the `RangeError` does indeed allow Safari to continue as expected, just not sure what it should return instead.

**Comment by petebacondarwin** [comment]
@BobChao87 - thanks for offering to fix this. I think that `angular.toJson` should return `null` for an invalid date on Safari, just like it does for the other browsers. The test should be on `toJson`

**Comment by BobChao87** [comment]
I'm having some issues with the actual build.

Travis seems to have failed on `apt-get` in build [115755797](https://travis-ci.org/angular/angular.js/jobs/115755797) for every test. All tests currently pass on my local build and I suspect this to be an issue with the build environment at that time. How should I go about rectifying this since there doesn't seem to be retry option?

Furthermore, in PR #14221 , @googlebot apparently found my CLA for the pull request, but not for my commits, even though both were performed on the same account. Is there a recommended way to rectify this issue as well? It could possibly be related to the fact that my email is hidden in GitHub. I'd prefer not to change that, but would if it is required.

**Comment by plong0** [comment]
I just updated to 1.4.12 and I still receive the RangeError: Invalid Date in Safari.

In my case I have an expression like: `{{ mything.timestamp * 1000 | date:'medium' }}` and the error is happening when `mything.timestamp` is `undefined`, so date filter ends up getting a `NaN` value.

This solution worked for me:

filters.js::591

    if (isNumber(date)) {
        date = new Date(date);
    }

change to: 

    if (isNumber(date) && !isNaN(date)) {
        date = new Date(date);
    }


I was going to submit a PR for this, but then I found this issue was closed already so I just updated.

Should I go ahead with a PR to add the `!isNaN` check?

**Comment by BobChao87** [comment]
Hi, @plong0, that fix addresses only a subset of the problems with this issue, though still sounds like a useful feature to have. For more details on why it doesn't address everything, check out #14221. I'm not sure on what the exact procedure is on proceeding from here, I'll let the Angular team handle that. I suspect you'll want to open a new issue, but I cannot be certain.

**Comment by gkalpak** [comment]
I haven't made up my mind if this should be fixed or not. (It will be a breaking change and I am not sure the benefits are enough to justify it).
But you can sure go ahead a create a PR and kick off the discussion :smile:

**Comment by plong0** [comment]
Hm, I never thought that it could be a breaking change - but now that you mention it, I can imagine how it could be.

I have a very simple workaround where I pass my date values through a `timestamp` filter before passing them to `date` filter.  The timestamp filter is doing the simple check that date will either get a valid timestamp integer  (* 1000 if conversion is needed) or null if the input wouldn't convert to a valid date object.
