### ISSUE TITLE
Animated element does not hide

### ISSUE THREAD

**Issue by JosephDAM** [angular/angular.js#13436]
This is basically my problem:
http://jsfiddle.net/mhff6u7y/3/

I have and array of items repeated and filtered, sometimes I animate one of those items. Problem is when the filter changes, and the animated item should not show anymore, the item stays until it finishes the animation. So yeah, why does the animated element stay and not disappear when I change the filter?

Thanks in advance

**Comment by Narretz** [comment]
This is not a bug, it's the way ngAnimate works.
The animation on .animated is picked up by the ngRepeat, and interpreted as the leave animation, that's why the element stays until the animation has finished. This is because ngAnimate allows having multiple animations at the same time. So in order to not confuse the animation engine, you should exclude specific "structural" animations from your styles, see here: http://plnkr.co/edit/onBcM37KxV2X3S5SgtuX?p=preview

A few notes on your demo:
-  Please include instructions how to reproduce the problem. I didn't know I had to click the items ...
- You have used a very old version of angular, please test with the latest if possible

**Comment by JosephDAM** [comment]
Thank you very much!! Sorry for the lack of instructions, will keep it in mind for the next time.
