### ISSUE TITLE
change move buffer size in $swipe.bind  in angular-touch

### ISSUE THREAD

**Issue by Binvention** [angular/angular.js#13463]
currently in angular-touch.js the move buffer radius is set to 10 px (set on line 57 in version 1.4.8 and used on line which  173) is too small for some applications particularly ones that draw on a canvas can a third parameter to the bind function be added to increase the buffer size? from what i can tell the move buffer radius determines what is a swipe vs what is a scroll.

**Comment by gkalpak** [comment]
Sounds like a reasonable addition. PRs welcome :smiley:

**Comment by Binvention** [comment]
i haven't worked with github that much and i haven't contributed to angular before but i was able to create a personal branch of angular with the changes desired but i don't if or how i could submit those changes in a pull request.

**Comment by Binvention** [comment]
Edit i found out that the move buffer size is dealing with the sensitivity more then determining a swipe vs a scroll so to adjust accordingly i think a new variable should be created to deal with a vertical buffer that separates swipe from scroll

**Comment by Narretz** [comment]
I'm closing this issue since the ngTouch module will be deprecated in AngularJS 1.7.0, and we will not do any more work on it. This is because touch handling is a complex topic, and there are stand-alone libraries that are better equipped to handle all the nuances and edge cases. For example, https://hammerjs.github.io/, which is also used by Angular.
