### ISSUE TITLE
Add a filter of Captialize like Uppercase and Lowercase

### ISSUE THREAD

**Issue by Developermayank** [angular/angular.js#13512]
I want you to add a filter of 'capitalize' like 'uppercase' and 'lowercase'

**Comment by gkalpak** [comment]
@Developermayank, it's not clear what this issue is about.

- [ ] Are you proposing to add a new `capitalize` filter in core ? (Feature request)
- [ ] Same as above, plus volunteering to implement it and submit a PR ? (Feature request + Contribution)
- [ ] Are you asking for help on how to implement it in your own app ? (Support request)

--
If you are looking for support, you can take a look at the [Creating Custom Filters][1] section of the developer guide. If you still need help, you can ask on one of the [appropriate support channels][2].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: https://docs.angularjs.org/guide/filter#creating-custom-filters
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by Developermayank** [comment]
Yes..  I proposed  to add a new Capitalize filter in core.

**Comment by gkalpak** [comment]
@Developermayank, generally we are trying to keep the core small, by only adding features that are (a) too common (i.e. used by the majority of applications) and/or (b) impossible/very difficult to implement outside of the core (e.g. require access to private, internal stuff).

The `capitalize` filter is really trivial to implement outside of core (and I am not sure how commonly needed it is). I am also pretty sure (without actually looking though), that must be implementation already available (maybe as part of larger "utility" filter collections).

So, I don't see it very likely being added to core.
I'll leave this issue open for a while, to see what others think.

<sub>(That said, it might help to have a PR submitted for this, but it is not guarranteed to get merged.)</sub>

**Comment by lgalfaso** [comment]
I agree with @gkalpak and would like to keep the core minimal

**Comment by wesleycho** [comment]
It should be noted that the [Underscore.string](https://epeli.github.io/underscore.string/) library already has a `_.capitalize` method...and one can also just create one's own capitalize filter by
```js
module.filter('capitalize', function() {
  return function(input) {
    return input.charAt(0).toUpperCase() + input.slice(1);
  };
});
```
Which is sort of trivially easy to implement on the user's side, and not necessarily something useful for all apps.

**Comment by Delapouite** [comment]
It's also included by default in lodash : https://lodash.com/docs#capitalize

**Comment by gkalpak** [comment]
Closing as we don't feel this belongs in core and it's easy to add as a 3rd party module.
