### ISSUE TITLE
Form $submitted (ng-submitted) is incorrectly triggering when elements are dynamically added within the <form> tags

### ISSUE THREAD

**Issue by Quirksmode** [angular/angular.js#13549]
I have a form setup and inside it is a Content Block Editor which allows you to Dynamically add a set of blocks (e.g. Text, Video, Image). The bug occurs when I try to add a block, the $submitted triggers, even when there is not a submit button on the page. I have created a fiddle to show the problem. Click to add any block and you will see the issue:

http://plnkr.co/edit/6CsUgumyDNcWaNmsWJIC?p=preview

**Comment by gkalpak** [comment]
This has nothing to do with dynamically adding elements. It happens because, according to the HTML spec, the default `type` of `<button>` elements is "submit". That means, if you don't specify a `type` explicitly, `type="submit"` will be assumed. 
This has nothing to do with Angular (i.e. the browser does that - in accordance to the spec). You can read more about it in the docs of the [`form` directive][1].

[Updated plnkr][2] with explicit `type="button"`.

[1]: https://docs.angularjs.org/api/ng/directive/form#submitting-a-form-and-preventing-the-default-action
[2]: http://plnkr.co/edit/lnjtm5D7b8en3O26oehL?p=preview

**Comment by Quirksmode** [comment]
You're a legend, that had been driving me crazy, well spotted!!
