### ISSUE TITLE
Drop-down lists in modals and dropdowns don't work correctly on iPad if ngTouch is a dependency

### ISSUE THREAD

**Issue by bart1990** [angular/angular.js#13558]
If you use a native drop-down list (<select>) inside a dropdown or a modal from angular-bootstrap and if your application has a dependency on ngTouch (1.4.3), the drop-down lists don't work as expected. When you click a drop-down list, the list with options blinks most of the time, making it very hard to choose an option. If you remove the ngTouch dependency, the drop-down lists work fine.

I created a plunkr which demonstrates this issue: http://plnkr.co/edit/fsU1zKpwalrxEEelsBka.
I'm using safari on an iPad air 5 (iOS 9.2).

Could you please provide a solution for this issue?
Thank you!

**Comment by bart1990** [comment]
Thank you for looking into this. Will this fix be merged into the 1.4 branch of Angular or do we need to update to a more recent version (if so which)?

**Comment by gkalpak** [comment]
We have deprecated `ngTouch#ngClick` and have it disabled by default, which be itself should solve several problems. Since this is a breaking change, it will only be available on `1.5` version onwards (it can't be backported to `v1.4.x`). 

For more info on this particular change and on how to upgrade to `v1.5.x`, you can also take a look at the [Migration Guide][1].

[1]: https://docs.angularjs.org/guide/migration#migrating-from-1-4-to-1-5

**Comment by bart1990** [comment]
Thank you for the information, we will upgrade as soon as possible. :)
