### ISSUE TITLE
Using $sce in a function to generate ng-include location leads to infinite digest

### ISSUE THREAD

**Issue by KamBha** [angular/angular.js#13555]
Plunkr: http://plnkr.co/edit/A7jqE4pG8h9n5fPQXPl6?p=preview

Basically, if you have an ng-include which calls a function that generates an template URL which does something like this:-
```
    $scope.findTemplate = function(templateName) {
      return $sce.trustAsResourceUrl(templateName);
    };
```

Then you will get an infinite digest loop.  This worked fine in v1.4.1, but stopped working in 1.4.2 onwards.  I worked around this problem by caching the result from $sce.trustAsResourceUrl and ensuring I return the same object everytime. 

I did not read anything in the changelog about breaking changes, so I thought I would check if this is how we should use $sce..

**Comment by gkalpak** [comment]
This was introduced in #12240. Nees further investigation.

**Comment by Narretz** [comment]
@KamBha does the stack strace provide any usable information?

**Comment by Narretz** [comment]
So the watch on ngInclude previously wrapped src with parseAsResourceUrl which creates a function from an expression. parseAsResourceUrl checks internally if  the expression value is trusted in the context, and then returns the trusted value (string).
In #12240 the trusted check was moved into the templateRequest fn.
What that means now is that if you watch a fn that returns $sce.trustAsResourceUrl(templateName), it will return a new object on every digest, instead of a the src string, which causes infdig.

I think caching the result of the trustAsResourceUrl call is the recommended migration strategy. If you think about it, if you are trusting a specific url, you only need to do that once, not every time the url is requested.

I don't see an easy way to fix that otherwise.

**Comment by Narretz** [comment]
Actually, the easiest fix is to use equality watch on the include src. This might cause performance problems, though.

**Comment by gkalpak** [comment]
In this specific usecase, you could also rmove the `$sce.trustAsResourceUrl()` call and use [`$sceDelegateProvider.resourceUrlWhitelist`][1] to white-list specific URLs.

[1]: https://docs.angularjs.org/api/ng/provider/$sceDelegateProvider#resourceUrlWhitelist

**Comment by KamBha** [comment]
I am happy to continue to cache the result or use the delegate, but can you clarify if this applies to all methods on $sce. Also, is this breaking change going to be documented somewhere? Not sure what the policy is on retroactively modifying the changelog, but that sounds like the right place to do it.

**Comment by KamBha** [comment]
@gkalpak ,
Just want to confirm, if we do the white listing, we don't need to use $sce?

Thanks.

Kamal.

**Comment by gkalpak** [comment]
@KamBha, exactly (afaict).
