### ISSUE TITLE
ng-keypress not work in firefox

### ISSUE THREAD

**Issue by brunocascio** [angular/angular.js#13559]
Hi!

I'm trying to use `ng-keypress="function($event)"` but in firefox the `$event.keyCode()` always return `0` or `8`.

For now, i'm using `ng-keyup="function($event)"` and works fine.

Some code:

```
<input autofocus type="text" ng-model="userWrite" ng-keypress="controlWords($event)"  />		
```

```
$scope.controlWords = function(e){
   console.log(e.keyCode); // in firefox always return 0 or 8, in chrome works fine.
}
```

Note: I'm using AngularJS `v1.4.8`

**Comment by fa137** [comment]
Having the same issue: 

```
User Agent:
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
```

**Comment by fa137** [comment]
Ok, I found a solution.

Try `e.which` instead of `e.keyCode`.

**Comment by brunocascio** [comment]
@fa137 that patch also works in google chrome?

**Comment by frfancha** [comment]
.which is not a patch, it is just the official way to read code (keyCode is obsolete in W3C docs, even if in some browser this is still what to use).
Anyway all of this is basic inter-browser event information problem (read mdn keypress for more info) and has nothing to do as angular bug.

**Comment by brunocascio** [comment]
@frfancha I understand. But using ng-keyup works fine. I don't understand it.

**Comment by brunocascio** [comment]
Anyway, `.keyCode` is deprecated, i will use `.which` or the recommended by standards.

Thanks!

**Comment by brunocascio** [comment]
The function `ng-keypress="nameOfFn($event)"` with `e.which` doesn't work with accented chars like `á, é, í, ó, ú`

**Comment by frfancha** [comment]
@brunocascio ng-keypress, ng-keydown, ... are only convenient shortcuts in angular to listen to the basic browser event keypress, keydown, ... and call the function you give embedded in a $apply in order to let the digest cycle of angular running.
There is no interaction at all of angular with the $event data which is the gross information from the browser.
Therefore if you need to use keypress, keydown, ... you have to "debug" them by hand in the different browsers you want to support to really understand what works and what doesn't (reading mdn docs really helps).
You can make all your tests with basic listener functions without any angular at all, angular doesn't play a role in what you get or not in $event.

**Comment by Narretz** [comment]
@brunocascio I get exactly the same result for angular / native listeners: http://plnkr.co/edit/TRs7BiZINiYDRlUnninf?p=preview

I'm closing this, but feel free to reopen if you can show a demo with this problem happening. Thanks!

**Comment by samagit** [comment]
Hi,
Does anyone have a working example of ng-keypress directive within a angular 1.5 component template?

Thanks
