### ISSUE TITLE
ng1.5 component modelValue not rendered to view, if it was changed in async fct

### ISSUE THREAD

**Issue by martinoppitz** [angular/angular.js#13609]
Hello everybody.

If I change a scope value in a async function, it does not rendered in the view - on-the-fly.

```js
function LoginComponent(AccountAPI, Error) {

  var that = this;

  function submit() {
    AccountAPI
        .login(this.username, this.password)
        .then(function (response) {
          console.info(response);
        }).catch(function (response) {
          console.warn(error);
          that.errorMessage = Error.parse(response);
          // $scope.$apply();
        });
  }

  this.errorMessage = '';
  this.username = '';
  this.password = '';
  this.submit= submit;

}
```

If I use `$scope.$apply();` after ` that.errorMessage = Error.parse(response);` it works.

How does it works, without **$scope**?

Thx for help.

**Comment by gkalpak** [comment]
How is `AccountAPI` implemented ? If it doesn't rely on Angular services like (`$q`, `$http` etc) that directly integrate with the $digest cycle, then it is run outside of the Angular context. This means that Angular has no way of knowing that something might have changed in order to update the view, unless you manually initiate a $digest loop (e.g. by means of `$scope.$apply()`).

In any case, there is not enough info to determine exactly what is wrong. You might want to try your luck on one of the [appropriate support channels][1] (since this sounds more like a general support question than an issue with Angular itself).
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by martinoppitz** [comment]
The Account API service is not the problem. Because the catch function are executed successfully. But the changed modelValue `that.errorMessage` does not rendered in the view. If I repeat the submit, the message can be logged before I send the request. So the value is realy changed but the view only update sync. Not async. Thats my issue.

Thanks for help

**Comment by gkalpak** [comment]
I'm not saying the functions are not getting called, they obviously are. But they are probably called outside of the $digest cycle. The symptoms you describe are pretty characteristic: the model changes, but the new values are not propagated to the view, until the next $digest is triggered (e.g. by clicking on a button).

I'm pretty confident it's the `AccountAPI` (or some underlying, lower-level  service it relies upon), but again there's not much to say without seeing a reproduction.

**Comment by martinoppitz** [comment]
How can I propagate the changed value to the view, if the code runs outside the $digest cycle. In ng1.5 only with `$scope.$digest();`?

Behind the AccountAPI.login there are a simple http-promise.

**Comment by Narretz** [comment]
Still $scope.$apply(), nothing has changed there in 1.5

**Comment by martinoppitz** [comment]
Thx. But I thought I could do that without *$scope*. Because in ng2 there is no more *$scope*. **And what then?**

**Comment by gkalpak** [comment]
> Behind the AccountAPI.login there are a simple http-promise.

It doesn't seem to be Angular's `$http` or `$q`, which integrate with the $digest cycle.

--
The only way to propagate changes to the view is through a $digest (e.g. calling `$rootScope.$digest()` or `scope.$apply()` - note: `scope.$digest()` might or might not be sufficient; only use it if you know what you're doing).
This is not `v1.5.x`-specific; it's been like this for at least since `v1.2.x`.

If you have code that executes asynchronously (e.g. HTTP requests, DOM event handlers, timeouts etc) and you are not using Angular's services or directives (e.g. `$http`, `$timeout`, `ngClick` etc), then you need to manually trigger a $digest cycle yourself.

**Comment by martinoppitz** [comment]
Thank you very much,

now I understand you, that is a helpful answer. I use a ES6 promise implementation, not $q.

It is like it is. **No issue**.

**Comment by gkalpak** [comment]
@martinoppitz, btw ng2 (since you asked) relies on zone.js which sort of patches the native implementations and triggers the change detection mechanism (the equivalent of ng1's $digest) at appropriate times. So, you no more need to manually trigger a $digest/change detection cycle in ng2 (even if using native or non-Angular services/events etc).
