### ISSUE TITLE
Memory Leak on IE 11 

### ISSUE THREAD

**Issue by livesankp** [angular/angular.js#13639]
Hello,

I am supporting a large angular.js application on IE 11. I am facing a big problem of memory leaks.
The app starts consuming memory as I navigates through screens when it reaches over 1100 mb it starts becoming slow and crashes or freezes IE between 1200-1700 mb. I had try IE v11.0.23 and v11.0.26. I had try IE 11.0.24 as well which was spiking memory to 1000 mb in couple view navigation so we applied patch for v11.0.26

However i tried IE edge too on windows 10 and it works fine there. App becomes slow after sometime but it recovers itself with some seconds of delay. Our users are suffering a lot due to freezes. Application is very huge and complex developed by vendor initially. Is there any fix available from framework level as application is such huge it is very hard to find the problems. All modules have been developed by different team of developers so each were having different coding styles. when i got the memory snapshot in IE i saw detached nodes a lot which are showing memory leaks of documentFragement. Is there a way to clear all detached nodes which could help or any way to fix at one common place which helps in releasing memory which were consumed previously for IE 11

Please help.

**Comment by frfancha** [comment]
We used to recommend Firefox to our users. But our angular application, under "memory" test from selenium makes firefox going from 300MB initially up to more than 1 GB memory...
Running the same test on Chrome memory usage goes from 50MB to 150MB, not more...
Since this experince we recommend Chrome...

**Comment by livesankp** [comment]
Is there any way to fix this ?
![image](https://cloud.githubusercontent.com/assets/13769236/12053409/70c0c06c-aede-11e5-93fe-2ad93d86cb80.png)

**Comment by Narretz** [comment]
It's very difficult to say where the problem is. As you said yourself, the problems are difficult to find in big apps. It's possible that IE11 garbage collector isn't cleaning up as well as other browsers do. So at this point I cannot say where the problem is. If you can isolate the element that consumes the memory, we might be able to take a closer look.

**Comment by ftheomunhoz** [comment]
Before trying to go any deeper inside the framework, have you tried to find bad practices like DOM Manipulation or not properly cleaning up after the page is being destroyed?

These things are easy to find, since a file search inside the app might find a few and give you a hint whether to continue this way or going deeper? Also, how are you loading your files/dependencies? I've also found that lazy loading usually helps a lot in these situations.

**Comment by Narretz** [comment]
Closing due to lack of feedback.

**Comment by ma-zal** [comment]
**This memory leak is NOT caused by Angular.** It is IE memory leak issue.

### Issue replication

Issue occures if you are **fill any textarea** element inside complicated page (DOM with many elements) and next you start DOM manipulation (switch angular route for example). If you do not touch to textarea fiels, all works fine.

Sencha has same issue. See https://fiddle.sencha.com/#fiddle/11kc for example. Issue occurs if you fill textarea and next press *Add grid*.

### IE issue details
- Discussion about this issue on Microsoft Connect (see https://connect.microsoft.com/IE/Feedback/Details/1974240)
- Issue occurs after applying "MS15-106: Cumulative security update for Internet Explorer: October 13, 2015". Is is know issue in this security update. (see https://support.microsoft.com/en-us/kb/3093983) 
- Standalone IE HOTFIX KB3119070 is available (see https://support.microsoft.com/en-us/kb/3119070).
 - Hotfix is part of "MS15-124: Security update for Internet Explorer: December 8, 2015" (see https://support.microsoft.com/en-us/kb/3104002)

**Comment by Narretz** [comment]
@ma-zal Thanks for the update. Always good to get confirmation.

**Comment by vasekch** [comment]
@ma-zal +1

**Comment by livesankp** [comment]
What about detached dom ? I can see 1000s of detached DOM in chrome snapshot. I am using kendo angular. I tried replacuing kendo angular datagrids with regular kendo jquery grid. And destroyed it properly in angular destroy event. After doing this i am able to avoid detached dom for datagrid. But there are so many such things to consider in such a big application.

**Comment by jphelan42** [comment]
KB3160005 seems to have fixed the memory leak we started experiencing with KB3093983.

We do use iframes, so it may have been this part of the update that did the trick... 
3168674 Storage event isn't triggered for localStorage updates in an iFrame in Internet Explorer 11
