### ISSUE TITLE
Angularjs app slow in firefox.

### ISSUE THREAD

**Issue by billyaraujo** [angular/angular.js#13654]
![untitled2](https://cloud.githubusercontent.com/assets/5067963/12049558/6b447654-aee0-11e5-8425-c075f9def306.png)

![untitled](https://cloud.githubusercontent.com/assets/5067963/12049548/4a130aae-aee0-11e5-9f04-dde66a603524.png)

It works OK in other browsers can't figure out why it doesn't work in firefox.

**Comment by aciccarello** [comment]
@billyaraujo I think it will be hard for anyone to help you with just these screenshots. You'll need to isolate the issue. I'd also suggest opening a [StackOverflow](https://stackoverflow.com/questions/tagged/angularjs) issue if it is an issue with your individual application rather than with the framework.

**Comment by Narretz** [comment]
I agree with @aciccarello . Please provide a demo / minimal example of the problem, and then reopen this issue. Thanks!

**Comment by billyaraujo** [comment]
It seems to be related with firefox. Works fine in firefox nightly build with multiprocess.
