### ISSUE TITLE
Closed issues with bounty

### ISSUE THREAD

**Issue by davidbaumann** [angular/angular.js#13679]
Hello,

I was surfing bountysource.com and found those 2 bounties with closed Issues:

https://www.bountysource.com/issues/67567-form-model-doesn-t-update-on-autocomplete
https://www.bountysource.com/issues/669179-ng-animate-animations-are-not-triggered-atomically-between-enter-and-leave-on-ng-view

So actually I guess, the bounty will never be paid out. Maybe there is a way to assign the solution to somebody there, or assign it to a maintainer who can so something useful with it?

David

**Comment by Narretz** [comment]
Hm, what does "closed" mean on bountysource? That it can't be solved and the issue lies with the framework? Please elaborate.

**Comment by davidbaumann** [comment]
You can still claim the issue.
After somebody claims it, the issuers will be able to vote, with a timeout of a week, I think.

I just think, nobody will take care of them here on github as they are closed.

Btw, some project have a "bounty" tag.

**Comment by Narretz** [comment]
If these are bugs, then there should be issues here on Github. I think at least the autocomplete issue is known, and was either marked as unfixable or is rotting in some issue.
The animation issue is more complex. The animation code has changed 3 times since this issue was opened, maybe it has fixed itself.
In any case, I'm not really sure what we should be doing about this. We don't really have a relation with bountysource. Maybe I'm just too dense to get what you mean ;)

**Comment by Narretz** [comment]
Ok, so it looks like for issue
https://www.bountysource.com/issues/669179-ng-animate-animations-are-not-triggered-atomically-between-enter-and-leave-on-ng-view
@matsko can claim the bounty. See here: http://plnkr.co/edit/0GXxiLhftaQKTi8oRFz3?p=preview (also works with 1.2.28)

and for  https://www.bountysource.com/issues/67567-form-model-doesn-t-update-on-autocomplete there are number of people who have posted solutions, including @tbosch, but since none of them are part of angular core, I'm not sure if they would be accepted.

In any case, thanks for bringing this up, but I think we can close this.
