### ISSUE TITLE
reset input type='number' having a invalid number input 

### ISSUE THREAD

**Issue by pavax** [angular/angular.js#13754]
If you have a input type='number' field and you enter an invalid number, the field is not reset if you change the underlying model (such as in a reset)

Steps in order to reproduce:
1. Open http://plnkr.co/edit/6d8Lks5AD347KjiqKmXy?p=preview
2. Type in a invalid number such as '1.1....' or '-'
3. Click reset
    Result: The input field still has the old invalid input
    Expected: The input field should show nothing (since the model value is now null)

In my opinion this is a bug since if you were to reproduce this with a different validation (such as min) everything works.

1. Open http://plnkr.co/edit/6d8Lks5AD347KjiqKmXy?p=preview
2. Type in a negative number such as '-1'
3. Click reset
4. Result: The input field shows nothing (since the model value is now null)

Tested Angular Versions: 1.4.8 and 1.5.0-rc.0
Tested Browser: Chrome 47.0, Firefox 43

**Comment by Narretz** [comment]
This is an issue caused by how browsers handle invalid inputs. When you enter an invalid number into an input, such as `1.`, the browser does not set the `value` property of the input, and application code has no chance to get the raw display value. When we reset the model, we can only set the value to "", but if an invalid number has been entered, it is "", even though the display value is different. 
I don't like how this is done, but that's unfortunately the state of the art.
You can however give your reset button the type "reset" which will clear all the inputs.
