### ISSUE TITLE
input[checkbox] doesn't catch checked in scope directive

### ISSUE THREAD

**Issue by reivaxm** [angular/angular.js#13767]
The attribute "checked" is not recovered in the scope of a directive.
This seems broken since version 1.4.4
https://plnkr.co/edit/0j7Y9mkeP4m2waCLYLxU?p=preview
Working on 1.3.15
https://plnkr.co/edit/GN4K5EdtfHxPpe7x3OCc?p=preview

**Comment by Narretz** [comment]
Seems to have been caused by https://github.com/angular/angular.js/commit/6f3b8622adce2006df5cf7eed4bf9262539004bd in combination with replace: true (if you remove replace, it works). Since replace is deprecated, I wouldn't hold out for a fix. If you want to provide a PR that fixes it, I'll be happy to take a look.

**Comment by Narretz** [comment]
Oh, i also works if you use a different name for the checked attribute: https://plnkr.co/edit/yHiTck5stWNkhASsWA7t?p=preview
It's possible that checked is somehow special cased by the browser.

**Comment by petebacondarwin** [comment]
The problem is that `checked` is a BOOLEAN attribute and Angular is converting it to a boolean value rather than leaving it as a string...

**Comment by petebacondarwin** [comment]
This is the relevant commit: https://github.com/angular/angular.js/commit/8a1eb1625c080445ce1e519762e1f2d4fd842b72

**Comment by petebacondarwin** [comment]
So since we always convert boolean attributes to a boolean value, you cannot use interpolation inside them as this will always be converted to `true`.
A simple workaround for you @reivaxm is to use `$attr` in your link function and write out the scope property manually... https://plnkr.co/edit/F6s1b50tHxsl5DQkeNlw?p=preview
But I have a basic fix coming anyway...

**Comment by Narretz** [comment]
Ah, I was looking for this previous commit.  Note that the plnkr only fails once you go to 1.4.4, though.

**Comment by petebacondarwin** [comment]
Well this commit was part of a bit of reverting and unreverting work at the time so it is not exactly clear where it appears

**Comment by petebacondarwin** [comment]
Here is the fix https://github.com/angular/angular.js/pull/13769
Can you take a look @Narretz ?

**Comment by reivaxm** [comment]
Thanks a lot for your reactivity,  the fix and globally for your work. I'll try that tomorrow.
