### ISSUE TITLE
keep the form invalid while debounce is executed ng-model-options

### ISSUE THREAD

**Issue by danicomas** [angular/angular.js#13788]
Hi,

I have a little problem. I can not keep the form invalid while the debounce is executed. I want to prevent the form submit.

To have the button ng-disable="pending (only works after debounce is called / async validator is processed), invalid (the previous state is used when we are in debounce)" doesn't works because the user can press the button before the debounce is ended.

here my code:

```js
.directive('unique', function (audioguidesService, $q) {
    return {
        require: 'ngModel',
        link: function (scope, elm, attrs, ctrl) {
            ctrl.$asyncValidators.example1 = function (modelValue, viewValue) {
                var value = modelValue || viewValue;

                var filters = {
                    "groupOp": "AND",
                    "rules": [
                        { "field": "field1", "op": "eq", "data": value },
                    ]
                };             

                var defer = $q.defer();

                service.getData({ page: 1, rows: 100, filters: filters }).then(function (data) {
                    if (data.rows.length > 0) {
                        if (data.rows[0].id != scope.model.id) defer.reject();
                    }
                    defer.resolve();
                }, function () {
                    defer.resolve();
                });

                return defer.promise; //it works correctly after the async function ends
            };
        }
    };
});
```

```html
<input type="text" class="form-control" name="field1" ng-model="model.field1" required unique ng-model-options="{debounce: 600}">
```

Regards,

**Comment by gkalpak** [comment]
This is a general trade-off when using a debounce: the forms validity might not be accurate based on the latest values. This isn't specific to async validators. If you care about showing up-to-date validity info to your users, then you should probably not use `debounce`. 

BTW, if you are using `debounce` in order to debounce the async validator (e.g. minimize calls to the backend), you could incorporate debouncing in your async validation logiv instead.

---
Anyway, this sounds more like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Closing as this is not actionable as is. Feel free to reopen if you want to suggest a feature or found an actual bug. 

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
[2]: https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#$asyncValidators
[3]: https://codepen.io/ExpertSystem/pen/XXzdbK?editors=100

**Comment by danicomas** [comment]
Thanks @gkalpak I resolved using this http://stackoverflow.com/questions/33088856/debounce-on-only-one-validator#answer-33103155

**Comment by gkalpak** [comment]
@danicomas, yes, that's what I had in mind.
BTW, if you find yourself needing debouncing in several places, you can write a simple `debounce` factory (or use a library) and avoid the boilerplate every time.
