### ISSUE TITLE
Angular can send XSRF token different from cookie for multiple parallel requests

### ISSUE THREAD

**Issue by EntityB** [angular/angular.js#13823]
In our app (with Angular v1.2.29) **some** requests cleary sends different xsrf token that is in cookie. We exanimed request headers deeply from console. This results in xsrf attack detection in backend. 

[From doc about xsrf protection](https://docs.angularjs.org/api/ng/service/$http):
"When performing XHR requests, the $http service reads a token from a cookie (by default, XSRF-TOKEN) and sets it as an HTTP header (X-XSRF-TOKEN). "

If Angular allows to happen any asynchronous code between **header is set for the XHR request** and **sending the request**, cookie might changed in the meantime, which will result in behavior that we are observing in our application (values are different for cookie and header).

Correct implementation would be set the header just before the request is send.

**Comment by gkalpak** [comment]
This is strange because that is exactly what happens: The cookie is read after calling `$httpBackend()` and from that point onwards, all code is synchronous until the request is sent.

Are you sure the cookie is not updated right _after_ the request is being sent (e.g. by some other request's response) ?

**Comment by EntityB** [comment]
Thank you for fast response, I will do deeper investigation.

**Comment by hakanson** [comment]
@bennadel has a blog post with similar race condition evidence. 

http://www.bennadel.com/blog/2991-cross-site-request-forgery-csrf-xsrf-race-condition-in-angularjs.htm

**Comment by gkalpak** [comment]
Basically, that post doesn't demonstrate a race condition inside Angular (rather a race condition between server-browser). As @bennadel mentions in the comments (and as already mentioned above), the code between reading the cookie and sending the request is synchronous.

--
One can't really do anything for a request being sent before the response with the new cookie arrives.

The only thing that I can think of, is making the server accept both tokens (old and new) for a very short period of time, to account for requests that left the browser before the response with the new cookie arrived.
It wouldn't be too difficult to implement, but it's a quite rare race condition, so I don't know it's worth it.

It's an interesting experiment though to implement as a POC :smile:

--
Closing as this doesn't seem to be an issue in Angular. Will be happy to re-open, if there is info indicating otherwise.

**Comment by buseodaci** [comment]
> In our app (with Angular v1.2.29) **some** requests cleary sends different xsrf token that is in cookie. We exanimed request headers deeply from console. This results in xsrf attack detection in backend.
> 
> [From doc about xsrf protection](https://docs.angularjs.org/api/ng/service/$http):
> "When performing XHR requests, the $http service reads a token from a cookie (by default, XSRF-TOKEN) and sets it as an HTTP header (X-XSRF-TOKEN). "
> 
> If Angular allows to happen any asynchronous code between **header is set for the XHR request** and **sending the request**, cookie might changed in the meantime, which will result in behavior that we are observing in our application (values are different for cookie and header).
> 
> Correct implementation would be set the header just before the request is send.

Did u find any solution ?
