### ISSUE TITLE
AngularJS isolate scope ng-model validation

### ISSUE THREAD

**Issue by je3f0o** [angular/angular.js#13830]
I would like to use the built in form validation provided by AngularJS for custom component directive. However it doesn't work. When validation is failed modelValue and viewValue set to '' empty string. I lost all my typing...
```
angular.module("myModule", [])
     .directive("customIsolateDirective", function () {
        return {
            restrict : "A",
            scope : {
                ngModel : "="
            },
            // Replace original template
            template : '<div ng-form="form"><input ng-model="ngModel" ng-maxlength="10" ng-class="{ error : form.$invalid }"></div>',
            replace : true
        };
    });
};
```
In DOM HTML
```
<input type"text" ng-model="model" custom-isolate-directive>
```
Can I use ng-model in the DOM element? Because I want to use ng-model directive without custom isolate directive too.

The goal is I want to each form component directives has it's own isolated scope and validating it's own scope independent parent scope. If I change `<input ng-model="model">` element's ng-model directive to `<input model="model">` it works fine. My question is can I use **ng-model** attribute to two way bind child isolated scope's **ng-model** with same name?
Because maybe I want to change my component directives dynamically.

Here is the problem that I created in [Plunker](http://plnkr.co/edit/muaNnjrItAl2rzpXvkdx?p=preview)
By the way I'm using angular.js 1.4.7

**Comment by gkalpak** [comment]
This won't work as expected, because with `replace: true` the attributes of the original element (including `ngModel`) are copied over to the replacing element (e.g. `<form>`) and `ngModel` is not designed to work like that.

There is no need to use `ngModel` on an element that is going to be replaced (nor is there any benefit in having `<input>` if you are going to replace it anyway). You can do soething [like this][1].

Finally, note that `replace: true` has been deprecated and will be removed in the next major release (i.e. 2.0). Still some corner case might not work as expected when using `replace: true`. You should try to avoid it, if possible.

--
Closing as there is nothing actionable. If you still need help, consider using one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: http://plnkr.co/edit/JkkMSGTij27Bh1CskKyN?p=preview
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by je3f0o** [comment]
Hi and thank you. I fixed the problem using ng-model-options="{ allowInvalid : true }" directive and add validation directive in to inside input element.
