### ISSUE TITLE
disable / enable auto digest run

### ISSUE THREAD

**Issue by tuchk4** [angular/angular.js#13833]
Is it possible to add global configuration to disable/enable digest auto run?

For example I don't need digest's auto run after ngClick, ngMouseover, ngMosuemove, $http queries,etc. but I need to execute these functions. And when needed - I will run digest manually.

If needed I can provide detailed examples when I need this behavior.

**Comment by gkalpak** [comment]
This not supported atm.

If you want event directives (for `click`, `mouseover` etc) that do not invoke a $digest, you can create your own, they are fairly simple.

`$http` is more deeply integrated with the $digest cycle, you should use an alternative solution for that.
BTW, there is already a request to add support for skipping the $digest from `$http`. It is tracked in #2049.

Also, since all digest cycles come through `$rootScope.$digest()`, you might be able to patch it up for your own needs, but it's hardly recommended, since it's such a core part of the framework and it's easy to mess things up really well.

--
Closing as it's not actionable.
