### ISSUE TITLE
Form Controller instance maintains incorrect validity properties when its destroyed

### ISSUE THREAD

**Issue by nishantkmr** [angular/angular.js#13856]
Consider, there is a form which has some validation errors which makes $invalid= true and $errors={...}
Now when the form is destroyed(DOM elements related to form is removed) the watcher function on form will have newValue as undefined and **oldValue will contain formController object with $invalid=false and $errors={}(blank object)**.

**Comment by Narretz** [comment]
What do you mean by "watcher function on form". You mean if you watch the form yourself?

**Comment by nishantkmr** [comment]
Please check out the plukr
[https://plnkr.co/edit/56zMdMarA0HjK4HXkel9?p=preview](https://plnkr.co/edit/56zMdMarA0HjK4HXkel9?p=preview)

**Comment by gkalpak** [comment]
The properties are not incorrect if you take into account what really happens in the DOM.
Imagine the following structure:

```
form ($invalid)
  div[ng-form-1] ($invalid)
    input ($invalid)
```

We have an invalid `input`, which makes the parent `ng-form` invalid, which makes the parent `form` invalid (but that's irrelevant).

When you swap `div[ng-form-1]` for `div[ng-form-2]` (but keep the controller of `ng-form-1` around) here is what happens:

1. The `input` DOM element is removed/destroyed. Upon removal, it looks up to its parent `formController` (i.e. `ng-form-1`) and unregisters itself, because that is what should happen when controls are removed from a form.
2. Once `input` is unregistered from the `ng-form-1` controller, `ng-form-1` does not have any invalid controls (it has no controls at all), so it becomes valid.
3. Then `div[ng-form-1]` is removed from the DOM and unregisters itself from its parent `formController` on the `form` element (which also becomes valid).

So, the `ng-form-1` controller (which you keep around) is correctly considered valid, since it has no controls registered with it.

--
Closing as everything works as expected, but feel free to continue the discussion below.

**Comment by nishantkmr** [comment]
@gkalpak  Ok, I understand but still in the watcher function the second argument(old value) should have $invalid = true. The first argument(newValue) in watcher function will be as per the flow you mentioned but the oldValue should convey the invalid state. The $dirty property of form controller always maintain its value in spite of the form elements removed from DOM.

**Comment by gkalpak** [comment]
Since you are removing and re-adding `infoForm1` from/to the DOM, the watched value (`demoCtrl.infoForm1`) is alternating between `undefined` and the old (removed) `infoForm1` controller (which has `$invalid: true` as explained above).

Here is what happens:

```
// Let's say at some point the "Form 1" tab is selected and `demoCtrl.infoForm1` points to a `infoForm1` controller.

1. The user clicks on the "Form 2" tab.
2. `div[ng-form-1]`'s controls get unregistered, setting `demoCtrl.infoForm1.$invalid` to false.
3. `div[ng-form-1]` gets removed from the DOM, which sets `demoCtrl.infoForm1` to `undefined`.
4. The $watch listener is triggered with: `newValue: undefined`, `oldValue: /* the previous infoForm1 controller */`
5. The user clicks on the "Form 1" tab.
6. A new `div[ng-form-1]` is created and added to the DOM.
7. A new form controller is created (for the new `div[ng-form-1]` element) and registered as `demoCtrl.infoForm1`.
8. The $watch listener is triggered with: `newValue: /* the newly created infoForm1 controller */`, `oldValue: undefined`

--
If you want to keep track of the last actual `infoForm1` controller, then only update `demoCtrl.infoModel.oldForm` when `oldForm` is truthy (i.e. not `undefined`).
[Updated demo][1]
<sub>(But it will still be `$valid` for the reasons explained in my previous comment.)</sub>

[1]: https://plnkr.co/edit/BCkvb429M7UgkE5ZP3ZW?p=preview
