### ISSUE TITLE
Convert string to number using i18n

### ISSUE THREAD

**Issue by rdkleine** [angular/angular.js#13855]
Using the ng.IFilterService in AngularJs I can convert a number to a string. The numberFilter uses i18n to determine if it needs a period or a comma to format the number.

Like so:

var numberString = $filter('number')(1.1234, 2);
// numberString = 1,12 when using i18n for nl-nl (Netherlands)
What I am looking for, and so far haven't found, is how to do this in reverse.

When having a string value '1,12' and knowing the i18n setting for decimal separator (in this case a comma) one would know enough to convert it back. Although I can't find any method in AngularJS to do this.

**Comment by gkalpak** [comment]
Indeed something like that, is not implemented in Angular. It's either not needed (because you have access to the original, unconverted number), or it is dangerous (because you can't reliably determine the decimal and group separators used when converting the number to a string).

If you happen to know the separators used, you could easily creating your own filter:

```js
// WARNING: Untested code - might break on corner cases
function parseNumberStr(str, decimalSep, groupSep) {
  var decimalSepRe = new RegExp('\\' + decimalSep, 'g');
  var groupSepRe = new RegExp('\\' + groupSep, 'g');

  return parseFloat(str.replace(groupSepRe, '').replace(decimalSepRe, '.'));
}
```

Here is a [demo][1] that retrieves `DECIMAL_SEP` and `GROUP_SEP` from Angular's `$locale` service (which again might be pointless if you don't know how the number was converted).

Closing as there's nothing actionable.

[1]: https://codepen.io/ExpertSystem/pen/jWxNKe?editors=0011

**Comment by rdkleine** [comment]
Hi Georgios, thanks for your reply!

I haven't explained why my need for such a method. I'm building a form with input for a decimal value. 

When I know the input should contain a decimal value after the user posts the form, it should be possible to  convert the string using the $locale like you mentioned. Or give a validation error when the value doesn't conform with a decimal value.

I will write an implementation to convert the string to the decimal value.

Thanks
