### ISSUE TITLE
Angular date filter in IE

### ISSUE THREAD

**Issue by shavo007** [angular/angular.js#13880]
Hi,

I have an issue with date filter and timezone in IE 11.

I created a plunker. 
http://plnkr.co/FzVbYl

The filter is not formatting the date-time based on the timezone.

Example, if you change your system time and run the plunker, the time is the local time of browser. Which is incorrect.

This works btw in chrome, safari and firefox.

**Comment by gkalpak** [comment]
Basically, this is an IE/Edge bug: 

When `Date.parse`-ing a date string, they don't recognize the timezone in the format `+HH:mm` (but only without the `:`). According to [the spec][1], the timezone should contain `:`.
The [ISO 8601 Standard][2] allows both forms (with and without `:`). Although the `Date` implementation in JavaScript does not 100% follow the ISO 8601 Standard (it's just _based on it_), all other browsers seem to recognize both forms as well.

Typically this is a browser bug, but since it should be easy to work-around, I believe this is worth fixing in Angular itself.

--
@shavo007, in the meantime, you can remove the `:` from timezone offset (i.e. replace `+09:30` with `+0930`) to work make it work consistently across browsers.

[1]: http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15
[2]: https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC

**Comment by shavo007** [comment]
Fantastic. I appreciate the detailed response.

**Comment by shavo007** [comment]
@gkalpak  what release is this in?

**Comment by gkalpak** [comment]
@shavo007, this has been fixed in master. It will be in the upcoming 1.5.0 and 1.4.10 releases (although I'm not sure about the exact release dates).

**Comment by shavo007** [comment]
No probs.

**Comment by edupes** [comment]
MICROSOFT LOVES STANDARDS. AS LONG AS THE ARE MADE BY THEM
