### ISSUE TITLE
Mocks don't seem to support spies.

### ISSUE THREAD

**Issue by eshansingh** [angular/angular.js#13893]
I have some code in a controller called `MainController` that calls a method from a certain `$security` service:

```js
// something something module.controller something
var vm = this;
vm.user = $security.$user.getCurrentUser();
// more stuff
```

Everything works great in production. Now I want to test where or not the method is being called. I do this:

```js
describe("The main controller", function() {
  beforeEach(module('app'));

  var MainController, $security;
  beforeEach(function() {
    inject(function(_$controller_, _$log_, _$security_) {
      MainController = _$controller_('MainController', {
        $log: _$log_,
        $security: _$security_
      });
      $security = _$security_;
    });
    spyOn($security.$user, 'getCurrentUser').and.returnValue({
      username: 'Eshan Singh',
      email: 'eshansingh@gmail.com'
    });
  });

  it('gets the current user', function() {
    expect($security.$user.getCurrentUser).toHaveBeenCalled();
  });
});
```

However, the test fails, because Jasmine says the method isn't getting called. Have I done something wrong or is this an `angular-mocks` issue?

**Comment by gkalpak** [comment]
The issue is your test code:

The controller is synchronously created when you call `$controller(...)`.
Then (after the controller has been created), you set up the spy on `$security.user.getCurrentUser`, but the method has already been called, so the spy never gets notified.

You should set up the spy **before** calling `$controller(...)`. See this [demo][1].

<sub>
BTW, it is not a good practice to use `$` prefixed names for your services. The `$` prefix is reserved for Angular stuff :smiley:
</sub>

[1]: https://codepen.io/ExpertSystem/pen/LGrxQW?editors=0010

**Comment by eshansingh** [comment]
@gkalpak Thanks! Also thanks for best practice stuff. I thought that was the standard for all services. Will update!
