### ISSUE TITLE
Plunker examples in directive doc page are linked incorrectly

### ISSUE THREAD

**Issue by rohithegde** [angular/angular.js#13906]
The Plunker examples as well as the linked output present in the https://docs.angularjs.org/guide/directive document are incorrect.

The linked examples are wrong by 1 ie instead of example 10, example 11 was incorrectly linked & this continues in most (if not all) examples on that page.

**Comment by gkalpak** [comment]
I checked it and can't see any problem.

Besides, the described issue couldn't happen, because there is no link to existing Plunkers.
The output is created "locally" based on the content shown in the files above it and clicking on the "Edit in Plunker" button, creates a new Plunker on the fly, again based on the content of the files.

**Comment by rohithegde** [comment]
@gkalpak  
I couldn't find any direct link to the example too via the code file (though could see it in the html) but how do you explain the output shown here : http://oi64.tinypic.com/wl91td.jpg
The index.html has the word "Hello" which is given in example 10 but the output given below the code is for example 11 (It has "Naomi" which is the output for the next code).

**Comment by gkalpak** [comment]
A similar issue has been reported in #13917. Let's track the problem there.
