### ISSUE TITLE
Exception thrown from postLink function is not rethrown if templateUrl is specified

### ISSUE THREAD

**Issue by dalelotts** [angular/angular.js#13911]
An exception thrown from the postLink function is only logged (not rethrown) if there is a templateUrl specified. 

However, if the template is embedded, the exception is rethrown.

The behavior appears to be identical in the browser when looking at the console stack traces, but the difference becomes obvious when running tests.

See https://github.com/dalelotts/angular-confusion for a simple example

Am I doing something wrong, is this by design, or is it a actual defect?

**Comment by lgalfaso** [comment]
This is the expected behavior. Directives that use `template` are fully compiled at compile time. Directives that specify `templateUrl` are fully compiled when the template is present (this is asynchronously).

At link time, the all the directives are fully compiled, then linking is done synchronously. If not, then this is done asynchronously (there are some variations when there is a mix of both) as linking needs to happen after compile is done.

**Comment by dalelotts** [comment]
Okay, that sense given when linking happens.  Thanks.

That leads to my next question. Is there an example somewhere of how to test that an expected exception is thrown when linking happens asynchronously?  

On second thought, perhaps postLink is the wrong approach now that I am moving the template out of the directive. I'll try moving the validation into preLink (assuming this would immediately throw the exception) thus allowing me to test the validation functionality.

**Comment by lgalfaso** [comment]
The exception is triggered within the next `$digest`. If you build a plunker with everything, then it should be easier to explain

**Comment by dalelotts** [comment]
Thanks!

I figured that out eventually. =)
