### ISSUE TITLE
using Non-GET instance method for ngresource (mutilple resource in single factory) 

### ISSUE THREAD

**Issue by 1nfinite** [angular/angular.js#13910]
I am returning multiple resource in single factory using ngresource. Strangely, i can't seems to be able to access the non-GET instance method like $update, $remove, and $save. What is the correct way of $update, $remove, $save in this situation?

```
angular.module('myApp.services').factory('Entry', function($resource) {
  return {
      method1: $resource('/api/entries/:id', { id: '@_id' }, {
        update: {
          method: 'PUT' // this method issues a PUT request
        }
      }),
      method2: $resource('/api/entries2', {}, {

      })
});

// not working: Entries is not a function at Scope.$scope.save
var entry = new Entries({});
entry.method1.$update();
entry.method1.$save();
entry.method1.$delete();
```

**Comment by gkalpak** [comment]
You are using `$resource` incorrectly. `$resource` is a factory for creating resource _classes_; you can't use it to create _methods_.
Also, there seems to be some issues with your code: For example, you can't call `new Entry()`, because (afaict) `Entry` is an **object**, not a **constructor/class**.

That said, this sounds like a general support question, so should ask for help on one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

--
Closing as there is nothing actionable.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
