### ISSUE TITLE
stateless filter still triggering digest cycle

### ISSUE THREAD

**Issue by cburgdorf** [angular/angular.js#14014]
I was digging into some performance optimizations for an application and stumbled over something strange. As of Angular 1.3 filters are considered stateless unless they are explicitly marked as `$stateful`.

However, when I explored the performance implications of that change, I couldn't find a difference between Angular 1.2 and Angular 1.4.

Here's a plunkr to demonstrate the issue: https://plnkr.co/edit/Tzc5IssKNtKTpcWI4hLa

What we see here is a simple collection being repeated through and applying a custom filter to it.

```html
    <ul>
      <li ng-repeat="item in items | custom">{{item}}</li>
    </ul>
    <button ng-click="unrelated()">run unrelated digest</button>
    <button ng-click="changeCollection()">change collection</button>
```

I added two buttons. One does a `noop` so it just triggers a digest whereas the other one actually changes the collection.

```js
  var count = 1;

  $scope.items = ['Hello', 'World'];
  
  $scope.unrelated = function () {
    console.log('running unrelated digest');
  }
  
  $scope.changeCollection = function () {
    count++;
    $scope.items.push('foo' + count);
    console.log('changing collection');
  }
```

The custom filter is just appending a static string to each item of the collection.

```js
app.filter('custom', function() {
  return function(input) {
    console.log('running filter');
    return input.map(function (item) { return item + '_x' });
  };
});
```

When I observe the output in the console one can clearly see that the unrelated digest cycle still triggers one filter run and the action that actually changes the collection causes two filter runs. This is exactly the same behavior as in Angular 1.2.

What am I doing wrong here? Do I have false assumptions what this performance feature actually was about or am I seeing a bug here or something different?

//cc @PascalPrecht

**Comment by gkalpak** [comment]
It's not that a stateless filter will always provide some optimization over a stateful one; it depends on it's inputs (and possibly other circumstances). In your example, you are not seeing any benefit, because of two reasons:

1. Stateless filters can't be optimized unless their inputs are primitives (or can be converted to primitives using their `valueOf()` method). In your case, you are passing an array, which cannot be optimized (as it would be too expensive trying to detect if it really changed since last time, which would beat the purpose).

2. `ngRepeat` uses `$watchCollection`, which uses a `$stateful` delegate.

--
You can see an example of an optimization [here][1].
Also, the related commit (fca6be7) has some more info and a few tests which call help illustrate the benefits.

---
Closing as this isn't actionable, but feel free to continue the discussion below.

[1]: https://plnkr.co/edit/GKpoNBWtpbhKRaCdT5iJ?p=preview

**Comment by cburgdorf** [comment]
Ah, ok. I think that clears it up! So, basically it is safe to say that this optimization does not apply to filters used in a `ng-repeat`. In such scenarios, doing the filtering manually and reinvoking the filter logic with a manual `$watch` on a filter object is still your best bet as a performance optimization then right? (e.g. like this https://plnkr.co/edit/eZ051ZtAMcnKVRkueXdj?p=preview)

**Comment by gkalpak** [comment]
Pretty much :smiley:
