### ISSUE TITLE
angular.constant like an object take same ref

### ISSUE THREAD

**Issue by furyscript** [angular/angular.js#14110]
Why if I define a constant object like

`app.constant('TEST', { title: 'Hello' });`

and I make this in controller

```javascript
var x = TEST;
x.title = 'Hello World';
console.log(TEST);
```
The value of constant has been change?? I read angular's doc and it says that constant cannot change their value. I think it's a bug because as documentation says, constant cannot change value.

**Comment by lgalfaso** [comment]
What does not change is the instance associated with `TEST`. Angular does not control what is inside it.
This is working as expected and this issue is invalid.

**Comment by furyscript** [comment]
No it's not correct. If you says in documentation that the value cannot be change, by this trick you can change the value of constant (object)...

**Comment by lgalfaso** [comment]
@furyscript so if I do `app.constant('w', window);` then Angular should prevent any modification in all exposed objects, `location`, `document`, etc?

If you think the documentation needs to reflect this, then feel free to open a PR, but the current behavior is not changing.

**Comment by furyscript** [comment]
Uhm so when I work with constants, to prevent some error or variable modication I should make a copy (e.g. `angular.copy`) @lgalfaso ?

**Comment by lgalfaso** [comment]
@furyscript it depends on what you expect the behavior to be. If you want to modify the value is injected and that this change is not reflected, then yes, you should make a copy.

**Comment by gkalpak** [comment]
@furyscript, the meaning of `constant` is that whenever you inject `TEST` in your app's services/controller/directives/filters/etc, you will always get the same "value" (whatever you chose this "value" to be). That's the guarantee and as @lgalfaso mentioned, that is indeed what happens.

If you say that `TEST` is an object (e.g. `{title: '...'}`), then this same object will always be injected. But JS objects do have properties and object properties are writable by default, so you will be able to mutate the object internally.

If you want to prevent that, you could do one of the following:

1. Don't use an object as `constant`; use primitives instead.  
    E.g.: `.constant('TEST_TITLE', 'Hello')`
2. Use [`Object.freeze()`][1] (if it's supported by the browsers you target).  
    E.g.: `.constant('TEST', Object.freeze({title: 'Hello'}))`
3. Use [property descriptors][2] to make your object's properties read-only (again, if it's supported by the browsers you target).
4. Use some 3rd party library for immutable data structures.

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze
[2]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties

**Comment by furyscript** [comment]
Correct me if I'm wrong, I don't test.

If this happen (In one controller I change object properties), when I inject same constant to other controller, does it keep old value ??

Or it has been changed ?

**Comment by gkalpak** [comment]
@furyscript, if you inject a "normal" object with "normal" properties (i.e. non-frozen, non-immutable (aka mutable :smiley:), with writable properties etc), then both controller will get the same object. This means that whenever a property changes in one controller, the other controller "sees" the change, since they both have access to the same object (it's literally the same instance, not two identical objects).

**Comment by furyscript** [comment]
@gkalpak Ok but this for me is not the correct term "constant" for objects.

As I can see and you tell me, if I change the properties in one controller, other controller see the change and for me is not correct. If I need that I should have used the `.value` and not the `.constant`. For me a "constant" is something immutable. For avoid this "bug" I should copy everytime the contant...

**Comment by jongunter** [comment]
Why can't Angular internally freeze a declared constant object, or make it a getter that returns deep-copied object every time it's injected? Working on a large codebase with lots of (possible inexperienced) javascript developers, I could imagine this becoming a problem really easily.

**Comment by gkalpak** [comment]
Making it a getter is out of question as it would break the singleton promise.
Freezing might work for many usecases, but it will not work for others (not to mention it will be a breaking change at this point). Also note that `Object.freeze()` was not supported by all browsers when this feature was implemented :smiley:

The basic "quality" of an AngularJS `constant` is that it available both during config and at runtime. In that sense, it is constant throughout the lifetime of the app. Also, note that most of the time "constants" are primitive values (e.g. strings or numbers or booleans).

##
In any case, if it makes sense for your usecase, there is nothing stopping you from freezing the object yourself.

Or even create your own helper:

```js
function angularConstant(module, name, value) {
  return module.constant(name, Object.freeze(value));
}
```

I won't even go as far as suggesting crazy stuff like monkey-patching `angular.constant` for the sake of junior devs, because everyone knows it is a bad, bad idea 😛 :

```js
var originalNgModule = angular.module;
angular.module = function () {
  var module = originalNgModule.apply(angular, arguments);
  if (arguments.length > 1) {
    var originalConstant = module.constant;
    module.constant = function (name, value) {
      return originalConstant.call(module, name, Object.freeze(value));
    };
  }
  return module;
};
```
