### ISSUE TITLE
Interpolation still recognizes old symbols in directive templates

### ISSUE THREAD

**Issue by danielkeller** [angular/angular.js#14113]
There is a bug with `$interpolateProvider`. If I set `startSymbol` and `endSymbol`, the default `{{ }}` symbols are still recognized in directive templates. See [this plunk](http://plnkr.co/edit/J9mgrPPEM8v0GaHTaRLO?p=preview) for an example. The expected behavior is that only the new symbols are recognized.

The motivation for ignoring the default symbols is that using a symbol which is escaped by interpolation on the server (ie, `<`) can prevent xss from the injection of Angular expressions. I would argue that this is necessary, since it is often not possible to restrict `ng-app` to static html.

Versions 1.4.8 and 1.5.0 are affected.

**Comment by lgalfaso** [comment]
This is the expected behavior. `startSymbol` and `endSymbol` only apply to the initial code that is being compiled or to html that is manually compiled. The rational is that module authors need to know how they should write values interpolation regardless of the fact that their code can be used by multiple apps (and some of them change these values).
