### ISSUE TITLE
ngRepeat should warn if unsupported object is given

### ISSUE THREAD

**Issue by jrencz** [angular/angular.js#14123]
* **Do you want to request a *feature* or report a *bug*?**
*feature* (helps debugging)

* **What is the current behavior?**
When array is passed to ngRepeat it work as expected (e.g. [plunkr from ngRepeat docs](http://plnkr.co/edit/BL0dJdcWBuPkKuXjoDVI?p=preview))
When unsupported object is given and filter is used it triggers [notarray warning](https://docs.angularjs.org/error/filter/notarray). [Example: `Set` and filter](http://codepen.io/jrencz/pen/XXvGWP?editors=1011)
When unsupported object is given but filter is not used no error is triggered
([example: `Set` without filter](http://codepen.io/jrencz/pen/KVOJYv?editors=1011))

* **What is the expected behavior?**
Passing an object which ngRepeat cannot iterate in case filter is not used should trigger an error similar to the one triggered when filter is used in ngRepeat expression.

* **What is the motivation / use case for changing the behavior?**
No feedback is given when an object which cannot be iterated is passed to ngRepeat

* **Which version of Angular, and which browser and OS does this issue affect?** Did this work in previous
versions of Angular? Please also test with the latest stable and snapshot versions.
*1.5.0*, the only one I checked.

**Comment by gkalpak** [comment]
The "problem" is that `ngRepeat` supports arrays/array-like objects and a objects. For arrays/array-like obejcts, it iterates over their items; for other objects it iterates over their key-value pairs (own properties only).

`Set` is not considered an array or array-like object (as far as Angular is concerned) and is thus treated as a plain ol' object. Since a set doesn't have any enumerable properties, there is nothing to iterate over, so `ngRepeat` won't create any DOM elements, but it's not because `Set` is recognized as un unsupported type.

--
If we were to fix anything, it would be adding support for some of the newer ES2015 data-structures (e.g. `Set`, `Map` etc), but that would go deeper than `ngRepeat` (e.g. `$watchCollection()` which is used under the hood etc).

<sub>ATM, considering the complexity vs benefit, I don't think this is a priority...</sub>

**Comment by gkalpak** [comment]
I'll go ahead and close this, since this feature request (warning about unsupported type) is invalid. `Set` is an object and as such it's supported (althoug not in the expected way).

Feel free to submit a new Feature Request about supporting iterables in `ngRepeat` (or something in that direction). Although it might be better done via a filter anyway... (just thinking loud)

**Comment by jrencz** [comment]
> Although it might be better done via a filter anyway.

can you explain what you mean?

**Comment by gkalpak** [comment]
@jrencz, since `ngRepeat` (and `$watchCollection()`) undrstands `Array`s, you should convert your `Set` to an array, before iterating over it. You could either do it in the controller (e.g. using `Array.from(set)` - which is probably the best) or using a filter that takes an iterable and returns an array (e.g. [something like this][1]).

<sub>A filter is useful if you find yourself doing this in a lot of places, but you need to be careful because it returns a new array every time (e.g. using it to iterate over a `Map`'s entries, would probably throw an _infinite $digest error_).</sub>

[1]: https://codepen.io/ExpertSystem/pen/yOBbzV?editors=1010

**Comment by jrencz** [comment]
@gkalpak Thanks for the explanation.

In fact I created a demo that used `Array.from` but I found it wrong to manually "dump" a Set to array only to expose it to the scope after each modification. Using filter to convert may be the solution since everything is going to work out of the box but it obviously is not performant.

**Comment by mgol** [comment]
Related: #13027.
