### ISSUE TITLE
Uncaught Error: [$injector:modulerr] Failed to instantiate module smashrite due to: TypeError: Object function () {         $cordovaInAppBrowserProvider.setDefaultOptions(inAppBrowserOptions);     } has no method 'toLowerCase'     at HTMLDocument.document.addEventListener (file:///android_asset/www/cordova.js:129:17)

### ISSUE THREAD

**Issue by ekumachidi** [angular/angular.js#14130]
App works well in browser and ionic view, but displays a whitescreen on android phone.
Using chrome://inspect/#devices, I got this error from the console, I think I'm loading all dependencies and services properly. Any workarounds?

**Comment by gkalpak** [comment]
@ekumachidi, this doesn't sound like an issue with core Angular. The Angular module fails to get instantiated, because there is an Exception thrown, but it doesn't seem to be caused by Angular.

You should probably try asking over at Ionic (and provide more context (e.g. the relevant code snippets)).
