### ISSUE TITLE
Use ^?ngModel on input directive

### ISSUE THREAD

**Issue by robstove** [angular/angular.js#14137]
We are building components that wrap some of the basic html elements and therefore angular directives. One of these components is of the form:
```
<div>
    <label></label>
    <input />
    <span></span>
    ...
</div>
```

Our component accepts an ng-model as the input value however we have to pass the ngModel as `<input ng-model="myComp.ngModel" />` which creates a second ngModelController and causes the one that the consumer gave us to be out of sync with our internal one that is bound to the `<input>` element. I believe this can be solved by changing the require option on the input directive from '?ngModel' to '^?ngModel'. This would allow the input directive to use the one our consumer gave us. I'll submit a PR if this seems like a viable option.

Cheers!
-rob

**Comment by Narretz** [comment]
Interesting idea. I would like to see a more fleshed out example of this, though. This one doesn't really explain why you have to have two ngModels.

**Comment by robstove** [comment]
Sure...so take this directive structure:
```
<div>
    <label>{{::caption}}</label>
    <input ng-model="value" />
</div>
```

and the directive definition:
```
class Textbox implements ng.IDirective {
    public require = ["^?form", "ngModel"];
    public restrict = "E";
    public scope = {
        caption: "@?",
        value: "=ngModel"
    };
...
```

and the usage of this is:
`<xui-textbox ng-model="someController.someValue" caption="Some Caption"></xui-textbox>
`

There are two ngModelControllers created here. One that gets created directly on the directive's parent scope and one that gets created on the `<input>` element inside the directive. The issue is that these two controllers get out of sync. The internal ngModelController reacts to the `<input>` changes however this is not reflected to the parent's ngModelController. There is a way to work around to this detailed [here](http://stackoverflow.com/questions/29915223/angularjs-pass-ngmodel-from-wrapper-directive-to-wrapped-directive/29915980#29915980) however we think this small change would open this up for a more streamlined design.

**Comment by petebacondarwin** [comment]
A common way of dealing with this is to give your `xuiTextbox` a higher priority than `ngModel`, making your directive terminal and then passing the expression in the `ng-model` attribute down to the ng-model on the input in your template.

**Comment by robstove** [comment]
Thanks, we'll try that as well. It still seems  to be a work around to an issue that would be solved by changing the input to search for parent models. Although I understand that could cause a breaking change.

**Comment by gkalpak** [comment]
Supporting inputs with `ngModel` on a parent element, is much more involved than simply changing `?ngModel` to `^?ngModel`. The current implementations assume that the directives are defined on the elements themselves, so certain features won't work as expected without further modifications.
You can try that out, by decorating the `input` directive to change `?ngModel` to `^?ngModel` ([demo pen][1]). E.g. the `$touched`-related functionality (among other things I bet) stops working, because it binds the listeners on the `xui-textbox` instead of the `input`.

Why do you even need an `NgModelController` on `xuiTexbox` ? Why not let the user bind to some arbitrary attribute (e.g. `xuiModel`) ? Something like [this pen][2] ?

[1]: https://codepen.io/ExpertSystem/pen/dMPPPP?editors=0010
[2]: https://codepen.io/ExpertSystem/pen/wGBBzr?editors=0010

**Comment by robstove** [comment]
Understood. We thought about using something similar to the xuiModel option you mention however having direct support for ng-model on our element seemed more appropriate. We'll try the priority/terminal approach as that seems better than our original plan. Thanks guys! I'll close this out as the point about needing ng-modal in the input for events makes this a no-go.
