### ISSUE TITLE
$compile returns link function returns only comment when ngIf exists

### ISSUE THREAD

**Issue by L42y** [angular/angular.js#14155]
**Note: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a _feature_ or report a _bug_?**
report a bug

**What is the current behavior?**
`$compile('<a ng-if="true"></a>')($rootScope.$new())` returns only the comment element

**What is the expected behavior?**
Should returns the element

**Which version of Angular, and which browser and OS does this issue affect? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot versions.**
Angular 1.5.0, Chrome 51.0.2664.0 canary, Mac OS X 10.11.3

**Comment by Narretz** [comment]
Hmm, looks like a bug, but I do believe the return value of the link function is not very clearly defined. The docs have this to say:
> Calling the linking function returns the element of the template. It is either the original element passed in, or the clone of the element if the cloneAttachFn is provided.

So you would assume that the original element is returned. However, in the case of ngIf that doesn't always make sense, because when the ngIf expression is false, getting the comment would be the expected result (because the element has been transcluded and the transclusion fn hasn't been called yet). Only when the ngIf expression is true, you should get the original element (or the clone of the original element, respectively).

Why do you need the return value of the link function anyway?

**Comment by petebacondarwin** [comment]
This is expected behaviour.

The `ngIf` is initially replaced with a comment. Even though its expression evaluates to true, this does not happen until the next digest. Unfortunately by then we no longer have the context to capture the extra elements that are added as siblings of the ngIf comment.

The workaround is to add the element to be compiled to a parent element before running compile. This gives you a reference to access the newly appended elements.

See http://plnkr.co/edit/QjJ6jdhkKOyMHsNzsE5x?p=preview

**Comment by L42y** [comment]
> Why do you need the return value of the link function anyway?

calculate size of the element

> The ngIf is initially replaced with a comment. Even though its expression evaluates to true, this does not happen until the next digest. Unfortunately by then we no longer have the context to capture the extra elements that are added as siblings of the ngIf comment.

is it possible to return both the comment and the element in the array?

**Comment by petebacondarwin** [comment]
> is it possible to return both the comment and the element in the array?

There is no element at that point in time. The element will only be created after the next digest when the `ngIf` calls its transclude function to create a clone of the template that it received.
