### ISSUE TITLE
Add support for attribute lookup for multi slot transclusion

### ISSUE THREAD

**Issue by david2tm** [angular/angular.js#14169]
Currently ti use multi slot transfusion, we need to name our elements using not standard HTML elements. Like in a snippet below.

```
<!-- parent.html -->
<div data-my-directive>
  <my-slot>
    <span>Lorem Ipsum</span>
  </my-slot>
</div>
```

This is not HTML5 compliant.  
Enabling attribute lookup, may help this. Consider following syntax:

```
<!-- parent.html -->
<div data-my-directive>
  <div data-my-slot>
    <span>Lorem Ipsum</span>
  </div>
</div>
```

**Comment by Narretz** [comment]
> This is not HTML5 compliant.

I assume you are using a validator or such?
Because the w3c has a spec for custom elements, and while that may not be 100% HTML5 compliant, it's definitely here to stay: http://w3c.github.io/webcomponents/spec/custom/

**Comment by petebacondarwin** [comment]
I agree with @Narretz. See http://stackoverflow.com/a/9845124/287070
Is using custom-elements breaking your application in some way?

**Comment by david2tm** [comment]
It was a decision we made about two years ago, to be fully compliant, meaning the use of data-* prefix instead of element names, etc.  
I had a discussion with a team, and we decided to to allow not standard elements (custom), so as of now it is no longer an issue  for us.  

After saying that, since most directives (or should I say features) in Angular do provide an ability to be used as attributes instead of elements, it seems only logical to me, that slots will allow this too.

**Comment by petebacondarwin** [comment]
@david2tm thanks for following up on this. The main reasons for the decision was simplicity and performance.

* It is much faster only to check the names of the top level elements of the template for matching slots.
* The code is simpler to understand and maintain

That being said, we were also conscious that this decision did not preclude us from making the matching more sophisticated later (such as jquery style selectors), whereas backing down from an overly sophisticated public API design is much harder.

So far you are the only person to have requested the more sophisticated API. If there are other people out there who would like to see it, then please say so and we can reconsider.

Given that this is no longer a problem for you I am going to close this issue.

**Comment by johngull** [comment]
Hello,

I faced problem when attribute lookup will help much.
It appears that when you add in transclude slot <tr> and <td> tags browser remove it, because there is no table around.
So when you append it to the table inside template you got just a 'text1\ntext2' instead of <tr><td>text1</td><td>text2</td></tr>

I beleive that with the attribute lookup this can be fixed.

If you have another workaround please share it.

Thank you.

**Comment by cheapsteak** [comment]
This does not seem to work with tables

```js
component('myTable', {
    transclude: {
      row: 'row',
    },
    replace: true,
    template: `
      <table>
        <tr ng-repeat="row in vm.rows" ng-transclude="row">
        </tr>
      </table>
    `,
  })
```

```html
<my-table>
    <row>
        <td>this doesn't show up</td>
    </row>
</my-table>
```

The "<row>" tag ends up being rendered inside the tr

![image](https://cloud.githubusercontent.com/assets/743976/21821078/2882d76e-d740-11e6-82ab-e794d7a41cd6.png)

**Comment by petebacondarwin** [comment]
I wonder if this is because the ngRepeat is creating its own transclusions?
Could you create a new bug for this?

**Comment by morewry** [comment]
I don't know when you guys removed the ability to specify a selector, but I'm unhappy about it. I assure this issue was not filed by the only person to have requested it. Maybe in these words, but not limiting to elements was part of the design Kara and I did and in the original PR she created to add multi-transclusion (the one that was closed and later rewritten). It was emulating Shadow DOM v0 at the time. Being able to specify a selector / use an attribute would allow authors to support the same interface for a multi-transclude Angular directive as for a Custom Element with Shadow DOM.

I've just run into a use case that's caused me to dig into the version of this that got shipped in Angular and it's completely in my way.

**Comment by petebacondarwin** [comment]
Hi @morewry!

Great to hear from you after all this time. I remember watching your talk with @kara about this feature. It was a really great piece of coding and presentation.

When we came to implement this, we made had to make some trade offs for performance and complexity. You can see that we debated lots of this at the time:

* https://github.com/angular/angular.js/pull/11736#issuecomment-136511625
* https://github.com/angular/angular.js/pull/12742
* https://github.com/angular/angular.js/pull/12934

This debate also included @kara in the process. I am not sure why you were not involved? I guess you were not aware of the development, in which case I am sorry.

The aim of the final design was a subset of the kind of features that you are looking for here. This would allow us to put out a performant feature that dealt with the majority of the use cases, while giving us the option of adding more functionality if it was needed.

It might well be true that there are lots of developers out there who desired these extra features, but we can only go on the direct feedback we get via issues opened. The fact is that, in the 3 years since we merged the final implementation, we have had only 3 developers (not including you) who have asked about this: the first one specifically said that they worked around it and no longer needed it; the second never followed up on their comment; the third created a new issue but it was closed after a discussion as invalid.

We were always open to the idea of extending the functionality but I fear that you have been bitten by the problem too late. Unfortunately we are now some way in to the LTS period for the AngularJS project, which means that new features like this are very unlikely to be added.

It is possible you could workaround this problem by using an external approach, similar to what you developed originally or something like https://github.com/angular/angular.js/pull/12934#issuecomment-143256787 developed by @fenduru.
