### ISSUE TITLE
ngMock: wrong parsing of pathParams when there are queryParams

### ISSUE THREAD

**Issue by marcoancona** [angular/angular.js#14173]
- **Do you want to request a _feature_ or report a _bug_?**
  This is a bug.
- **What is the current behavior?**
  `httpBackend.whenRoute()` does not parse correctly the path-parameters when they are immediately followed by query-parameters.
  
  Consider the following example:
  `$httpBackend.whenRoute('DELETE', '/api/resource/:_id').respond((method, url, data, header, params) => {}`
  
  If `whenRoute` is triggered by `/api/resource/1?q=hello`, `params` will contain wrong parsing of the `id`:
  
  `params = {id: '1?q=hello', 'q': 'hello'}`
- **What is the expected behavior?**
  `params = {id: '1', q: 'hello'}`
- **What is the motivation / use case for changing the behavior?**
  This behaviour looks wrong and inconsistent. 
- **Which version of Angular, and which browser and OS does this issue affect?** Did this work in previous
  versions of Angular? Please also test with the latest stable and snapshot versions.
  Angular 1.5, in previous releases `params` was not generated
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by gkalpak** [comment]
A little background:

(Almost) the same logic is used in `ngMock`'s [parseRoute()][1] and `ngResource`'s [pathRegExp()][2].
(It should be the same logic, but theu seem to have gotten slightly out of sync.)

The one intentional difference is this:

In `ngResource` we match the RegExp against `$location.path()` (not the whole URL, containing the query). Thus we don't have to take special care to avoid matching the query.
In `ngMock`, we need to have a way to ignore the query/hash part for `whenRoute()`.

[1]: https://github.com/angular/angular.js/blob/6a336ba6a0db29da0bee0a2ecf44857780ec682b/src/ngMock/angular-mocks.js#L1559-L1587
[2]: https://github.com/angular/angular.js/blob/6a336ba6a0db29da0bee0a2ecf44857780ec682b/src/ngRoute/route.js#L210-L238

**Comment by ferrao** [comment]
👍
