### ISSUE TITLE
Expression in template don't work on iPhone / iPad

### ISSUE THREAD

**Issue by bytecounter** [angular/angular.js#14192]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
The following code do not work on iPhone and iPad **only**! 
Instead of the result the template is shown in the browser.
Testet with iPhone 5/6 and iPad 2 with safari browser. 
It works well on iPhone with other browsers (e. g. Chrome) and it works well on all other testes browsers (IE, FF, Chrome, Safari (Desktop Mac and Windows), Opera, Android), too. It seems that it is a problem with Apple mobile devices only.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:yBpEi4).
I have a plnkr: 
http://plnkr.co/edit/sgfj8ktv45M6eudiggRR?p=preview
But, remember, if you want to see the problem, you must test with iPad/iPhone. All others (also an iPad-Simulator) works well!

* **What is the expected behavior?**
Parsing the template as on all other browsers

* **What is the motivation / use case for changing the behavior?**
Using expressions in view templates

* **Which version of Angular, and which browser and OS does this issue affect?** Did this work in previous
versions of Angular? Please also test with the latest stable and snapshot versions.

Testet with AngularJS Versions: 

- 1.4.7
- 1.4.9
- 1.5.0 

all has same behavior. Works on all browser, but not on Apple mobile devices.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

In case of the problem occurs on Apple mobile devices only, it is not easy to debug.

**Comment by Narretz** [comment]
Have you tested this directly in the browser (Safari) or in one of the webviews? (UIWebView, WKWebView)

**Comment by bytecounter** [comment]
Directly in the browser.

**Comment by Narretz** [comment]
I could reproduce this with an iPad ios9.2 simulator. It looks like iOs modifies the content of the DOM node, because the expression looks like a telephone number. The end effect is that the browser inserts an `<a>` element around the `0000-00-00`, and that somehow breaks the interpolation. I actually had the exact DOM, but then the VM crashed ... Maybe the interpolation fails because the DOM node is replaced and the interpolation data is lost. I'm inclined to say this is a bug with iOS.
Side note: the debugging experience with an IOS simulator is a joke, at least if you do it via Saucelabs on a VM. 

As a workaround I would suggest you put the expression inside a scope fn.

**Comment by Narretz** [comment]
Seems like a known issue. Here's a SO with some other workarounds: http://stackoverflow.com/questions/226131/how-to-disable-phone-number-linking-in-mobile-safari

I don't think there's anything we can do on the Angular side.
