### ISSUE TITLE
ngTouch does not work in MS Edge

### ISSUE THREAD

**Issue by julmot** [angular/angular.js#14207]
I just opened the documentation example:
https://docs.angularjs.org/api/ngTouch/directive/ngSwipeRight
on a Android tablet running Chrome and on a Windows tablet running MS Edge.
The example does not work in MS Edge.
### Expected behavior

Swiping to the left should show the action buttons like on Android.
### Actual behavior

Nothing happens.
### Environment informations

Windows: 10
MS Edge: 20.10240.16384.0
AngularJS: 1.5.0

**Comment by abenchi** [comment]
First of all you should make sure that the `Enable touch events` flag is enabled  under `about:flags`.
If it is already the case you can try to redirect the touch event to the JS by adding `-ms-touch-action: none;` to your html element.
Keep me informed please

**Comment by julmot** [comment]
Sorry, but this is now 1/4 year ago since I had the issue. I no longer work on this application. Please reproduce it yourself. The flag was enabled!

**Comment by petebacondarwin** [comment]
Is this still an issue for you @julmot or @abenchi ?

**Comment by Narretz** [comment]
I'm closing this issue since the ngTouch module will be deprecated in AngularJS 1.7.0, and we will not do any more work on it. This is because touch handling is a complex topic, and there are stand-alone libraries that are better equipped to handle all the nuances and edge cases. For example, https://hammerjs.github.io/, which is also used by Angular.
