### ISSUE TITLE
infinite load functionality in angularjs 

### ISSUE THREAD

**Issue by dheerajkhokhar** [angular/angular.js#14217]
I want infinite scroll functionality and i am injecting ui.filter in it to show unique records in ng-repeat with limitTo filter. I am incresing the limit of limitTo variable each time on clicking load more button but it failed to show loader.

**Comment by gkalpak** [comment]
It is not clear what the problem is (or how it relates to Angular core).
Please, provide more context and preferrably a live demo of the issue (e.g. using CodePen, Plnkr etc).

BTW, this sounds like a general support question. If that is indeed the case, please, use one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by Narretz** [comment]
Closing due to lack of feedback and because it's probably a support question.
