### ISSUE TITLE
Angular 1.5 - ngModelController.$parsers not executing consistently in IE vs. Chrome/Firefox/Safari

### ISSUE THREAD

**Issue by Asvarduil** [angular/angular.js#14273]
**Do you want to request a *feature* or report a *bug*?**
This is a **bug** report.

**Current Behavior:**
When a directive has at least one ngModelControllers.$parsers function attached to it, the parser functions will not execute if you are running Chrome, Firefox, or iPad Safari.

**Steps To Reproduce:**
Required Plunker - https://plnkr.co/edit/X3NSQGUeGYhbNnvH22u5

1. Open the Reproduction Plunkr in Internet Explorer
2. Modify the contents of the text field.
3. Observe that in IE, the text beneath the field will be modified as you type different characters.
4. Open the Reproduction Plunkr in Chrome, Firefox, or iPad Safari
5. Modify the contents of the text field in the browser that you opened in Step 4.
6. Observe that, no matter what you enter, the text beneath the input field will not change.
7. Hit return.  Only now will the value update.

**What is the expected behavior?**
In any browser, a field that has a directive that has a $parser function should execute that function any time the view value changes.  The synchronization should *also* occur upon return being pressed.

**What is the motivation / use case for changing the behavior?**
As you can see, the demonstration directive is a simple 'masked input' directive.  There are numerous use cases for such a directive, as seen in many line-of-business applications.  The point of the $parsers functions is to decouple the field value as presented to the user from the model value stored in the controller, thus allowing the programmer to have a user-friendly presentation, and a more machine-friendly format for actual storage.  

Currently, in the noted browsers, this decoupling is broken, as only the view value is ever being modified, until return is pressed.  This is a problem, though, as return is often defaulted to buttons on forms or modals, in order to let the user do something else after having entered whatever information.  Additionally, pressing return isn't the only paradigm for storing information; in the current setup, if a user never pressed return, and instead manually clicks a button with the mouse or their finger on a touch-screen device, they are guaranteed to have information loss.

The user does not care which browser they "should" use to use our tools, they just want it to work.  This is a bug that needs to be fixed.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
**Observed** on Angular 1.5 and Chrome v.49.0.2623.87 m
**Observed** on Angular 1.5 and Firefox v.44.0
**Observed** on Angular 1.5 and iPad Safari (I'm not a proficient iOS user, so I don't know how to find out what version I'm running.  Apple should make it easier to find out what version an app is, for cases like this.)
*Works* on Angular 1.5 and Internet Explorer v.11.0.9600.18230CO/Update v.11.0.29 (KB3139929)

**Workaround:**
Pretty much you have to manually replicate what ngModelController.$parsers does behind the scenes, in your link function.  This requires using the $parse service in your directive.

    $(element).on('keyup', function() {
        ctrl.$setViewValue($(element).val());

        // Specific formattings go here...
        var nonDigitCharacters = /[^0-9]/g,
            digitsOnly = ctrl.$viewValue.replace(nonDigitCharacters, '');

        var model = $parse(attrs.ngModel),
            modelSetter = model.assign;

        scope.$apply(function () {
            modelSetter(scope, digitsOnly);
        });
    });

**Comment by Asvarduil** [comment]
Identified a **workaround**.  Noted in the body of the bug ticket.

**Comment by gkalpak** [comment]
This is an issue with how the [`masked-input` jQuery plugin][1] you are using handles events on the input.
Namely, it listens for and prevents the `keydown` event (among others), and as a result, the `input` and `change` events what would normally have been triggered, don't.

In order for Angular to know that the input's value might have changed and run it's parsers/validators pipeline, it registers listeners for the `change` and `input` events (on most browsers - see below). Since the plugin prevents these events from being fired until the input has been blurred, it effectively prevents Angular from "realizing" the value has changed.

The reason it works on IE is that because it's behavior wrt firing the `input` event is buggy or unexpected (depending on the version), Angular can't use it for its purposes, so falls back to listening for a `keydown` event (and doing some extra work).

--
So, this works as expected or rather there's nothing we could/should fix in Angular.
If a directive decides to prevent certain events, we shouldn't try to work around this.

As a work-arounnd, you can add a listener for the `keydown` event (which is the only one that `masked-input` allows), and manually trigger a `change` event, to let Angular know something happened. Note, that you need to trigger the `change` event asynchronously, because the input's value hasn't actually changed yet, when the `keydown` event is triggered.

[Updated plnkr][2]

--
Closing as everything works as expected (as far as Angular is concerned), but feel free to continue the discussion or ask for clarifications below.

[1]: http://digitalbush.com/projects/masked-input-plugin/
[2]: https://plnkr.co/edit/OfcdINULZ5jrHH50lwBk?p=preview

**Comment by Asvarduil** [comment]
@gkalpak - Good information; I hadn't considered that the Masked Input plugin might be interfering with Angular.  I'll use the technique shown in the updated plunker in my code, as it's shorter still than brute-forcing a duplicate of the parser pipeline, and allows benefit to be obtained from the parser pipeline.
