### ISSUE TITLE
suspected bug : 1.5 component and function defintions 

### ISSUE THREAD

**Issue by jmls** [angular/angular.js#14360]
angular 1.5.3

when defining a component, you can specify either
```javascript
controller: function() {
   this.$onInit = function() {
    console.log("typea");
   }
}
```
or 

```javascript
controller : someFunction
[snip]
var someFunction = function() {
   this.$onInit = function() {
    console.log("typeb");
   }

}
```
however, if you use the second case, then the $onInit does not get called

this plunk http://plnkr.co/edit/1P8rPStvIoR50QcZBCcB?p=preview only shows "bar" - which is the first method described above

**Comment by gkalpak** [comment]
This happens because you are initializing the `c1` variable **after** you are using it to set the controller.
So when executing `controller: c1`, `c1` is undefined and a dummy controller will be created for your component.

[Updated plnkr][1]

[1]: http://plnkr.co/edit/Zd17BaH66Xy6HiITvlUg?p=preview
