### ISSUE TITLE
Browser.prototype.url() used a wrong API

### ISSUE THREAD

**Issue by linus87** [angular/angular.js#14422]
I see Browser.prorotype.url() method used a wrong API. In fact, history.pushState() only supports the same original URL. Reference: https://www.w3.org/TR/html5/browsers.html#dom-history-pushstate
 However, you see the code, if they are not in the same origin, you use history.pushState().

Current Code:
```
if ($sniffer.history && (!sameBase || !sameState)) {
        history[replace ? 'replaceState' : 'pushState'](state, '', url);
        cacheState();
        // Do the assignment again so that those two variables are referentially identical.
        lastHistoryState = cachedState;
 }
```

**Comment by gkalpak** [comment]
@linus87, I don't think we make any assumptions or validation about the origin. The `$browser.url()` method seems to only be called with the current URL as read by `$location`, so Angular wouldn't pass a URL with different origin to `history.pushState()`.

Do you see something different ? Can you give an example ?

**Comment by linus87** [comment]
Yes, I understand your point. If $browser.url() is only called with current
URL, It is certainly fine. However, $browser.url(url, replace, state) as a
public service, and parameter url is custom specified. Don't you think it's
confused to developer?
Many big enterprises have different sub domain sites, their domain switch
is frequent. So, they may well use $browser.url() to change current url.
And in modern browsers which support history.pushSate(), it will fail.

On Wed, Apr 13, 2016 at 4:19 PM, Georgios Kalpakas <notifications@github.com

**Comment by gkalpak** [comment]
`$browser` is not a public service. (Now why it's not `$$browser` is good question.)
It is an (intentionally) undocumented service, that's only meant for internal use.

I know that some people are using it, but they should be doing so on their own risk.
Even in this case, it's their responsibility to call it with appropriate URLs - in the end, one could call the history API directly, so if people are making improper use of it, we can't really stop them.

I'm going to close this, as it seems to be working as expected.
(Feel free to continue the discussion below, if you feel otherwise :smiley:)
