### ISSUE TITLE
ca-fr i18n file uses the "Euro" symbol.  Should be '$' (French Canadian)

### ISSUE THREAD

**Issue by craigfarrell** [angular/angular.js#14435]
The Angular i18n file for the French Canadian Locale (ca-fr) is using the Euro symbol "\u20ac".  It's in Canada, it should use the "$" symbol.

**Comment by gkalpak** [comment]
Angular.js uses the [Google Closure I18N library][1], to generate its own I18N files. This means that any changes to these files would be lost the next time that we import the library. The recommended approach is to open an issue or submit a patch to the I18N project directly, instead of here.

Closing as this in not actionable as far as Angular is concerned.

[1]: https://github.com/google/closure-library/tree/master/closure/goog/i18n

**Comment by craigfarrell** [comment]
Thanks for the response!  Oddly enough, they are correct in the closure library.  (Aruba = AWG)  In the Angular set, Aruba = Afl, which is also wrong.Is there a missing link somewhere?

Date: Thu, 14 Apr 2016 12:41:53 -0700

**Comment by gkalpak** [comment]
Actually, the `ca` in `ca-fr` doesn't stant for "Canada", it's "Catalan" (the language).
You are looking for `fr-ca`, which has the expected curreny symbol (`$`).
