### ISSUE TITLE
ng-transclude does not work inside of an included template

### ISSUE THREAD

**Issue by Elijen** [angular/angular.js#14449]
We have a directive that uses `ng-transclude`, but it also needs to switch its template dynamically so we are using `ng-include` for that. The problem is that `ng-translude` block defined in the template is not expanded. Instead `Illegal use of ngTransclude directive in the template! No parent directive that requires a transclusion found` is thrown.

**Comment by Narretz** [comment]
This happens because the included template is compiled before it is appended to the DOM, which means ngTransclude cannot find the transclusion parent directive. At this point, this works as expected.

Can you explain / show why you need ngInclude in the directive template? Can't you use a dynamic templateUrl function and load the template directly?

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
