### ISSUE TITLE
bindToController does not transfer form and model controller objects from scope to controller

### ISSUE THREAD

**Issue by rufio620** [angular/angular.js#14441]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**
The bindToContoller option when using a directive does not bind any of the formControllers or modelControllers.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

http://plnkr.co/edit/uT8nbdMuUE8dpSjBytfj

**What is the expected behavior?**
When using bindToController the form and model controllers should be transferred to the controller just like the bound properties. See comments in the js code.

**What is the motivation / use case for changing the behavior?**
The whole point of bindToController is to remove the complexities of dealing with the scopes. By not transferring over the form and model controllers when using the bindToController the developer is forced to reintroduce the scope object in order to do any javascript form validation.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

This appears to affect all versions that have bindToController implemented.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
There is no reason to not bind your form to the controller. Doing `<form name="vm.testForm">` is perfectly valid.

The reason why `this.testForm` is undefined during the controller instantiation, is that the controller is instantiated before child directives (including `form`) have been linked. BTW, injecting `$scope` in your controller won't help you at all (it will run into the same problems).

--
If you want to access the form controller from within your controller, you need wo wait until the post-linking phase, when the form controller will have been bound to your controller. 

In previous versions, you would rely on hacks like `$timeout`, or being forced to have `link` function anyway, but since `v1.5.3` directive controllers have [lifecycle hooks][1], so you can use `$postLink`.

[Updated plnkr][2]

--
Closing since what you requested is already possible.

[1]: https://docs.angularjs.org/api/ng/service/$compile#-controller-
[2]: http://plnkr.co/edit/PihyMMZanVUoKWnyRvcu?p=preview
