### ISSUE TITLE
orderBy  not supported persian language

### ISSUE THREAD

**Issue by captainhamid** [angular/angular.js#14455]
filter orderBy not supported persian language, 
orderBy ignore  letters "گ چ پ ژ".

**Comment by gkalpak** [comment]
Could you please create a live demo (e.g. using CodePen, plnkr etc), so we can reproduce and investigate the problem ?

**Comment by captainhamid** [comment]
demo : `http://codepen.io/captianhamid/pen/grzZpM`
correct sort is: 
1. احمد
2.پروین
3.ترانه
4.حمید
5.ژاله
6.ساسان
7.گوهر
8.مهران
but angular ignore letters "گ چ پ ژ".

**Comment by mrak1001** [comment]
I have same problem.
angular ignore  letters "گ چ پ ژ".

**Comment by uxitten** [comment]
hi this problem for javascript. just solution overwrite sort and bind to ng-repeat

موفق باشید

![3](https://cloud.githubusercontent.com/assets/1549069/14640142/5ec03d2e-0655-11e6-9006-6d877c1841ea.PNG)

**Comment by gkalpak** [comment]
This is because of how JS orders the strings (in a locale-unaware way).
One could use `String.prototype.localeCompare`, but then you could get different results based on the user's locale.

Ideally, `orderBy` could accept a custom comparator function, so you could define your comparing logic there (and use `localeCompare` or whatever would produce correct results for your particular usecase).
Since this is not supported (yet :stuck_out_tongue:), you should create a custom filter.
