### ISSUE TITLE
Using scope inside of Service and Factory -- bad or normal practice?

### ISSUE THREAD

**Issue by Novitoll** [angular/angular.js#14473]
**Do you want to request a *feature* or report a *bug*?**
I want to clarify the best practice.
**Using scope inside of Service and Factory -- bad or normal practice?**

Here is the [stackoverflow question](http://stackoverflow.com/questions/36721153/angularjs-is-it-bad-to-fire-broadcast-emit-from-services#comment-61068251)

**What is the current behavior?**
It is working with scopes in Factories, but would like to understand the best practice

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Angular 1.4

**Comment by gkalpak** [comment]
This sounds like a general support question - not suitable for the repo.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

**Comment by Novitoll** [comment]
Ok, so it's a lil bit frustruating that you didn't help me, so I had to answer to myself based on my researchment. Anyone who was concerned of same issue, I left my answer in this [here](https://github.com/angular/angular.js/issues/14473), hope it will help.

**Comment by Narretz** [comment]
@Novitoll You are generally correct that you should keep the scope out of services / providers, because it makes it easier to understand the application. The scope is also less visible when you use `ctrl as` and the new component helper. We also don't encourage using the scope's event system heavily, which minimzes another use case.
The only exception is really the injection of the $rootScope into a service, because it's stable, and can be used for compilation and application wide events.
