### ISSUE TITLE
$onChanges does not fire after initial load

### ISSUE THREAD

**Issue by anuragsimgeker** [angular/angular.js#14490]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have two components, one parent and one child. The ```obj``` is passed to child via one-way binding. When the ```obj``` changes via an ```input[ng-model]```, the child's ```$onChanges``` does not fire. Although, the ```$watch``` fires.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

http://jsfiddle.net/asimgeker/rmhqt9v7/

**What is the expected behavior?**
Both ```$onChanges``` and ```$watch``` should fire.

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Angular Version 1.5.5, Mac 10.11.4, Google Chrome Version 49.0.2623.87 (64-bit)

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Afaik, $onChanges fires when the identity of the bound object changes, i.e. only when you replace the object, not when you change any of its properties.

**Comment by gkalpak** [comment]
@Narretz is right. One-way bindings are not deep-watched. Quoting the docs:

> One-way binding watches for changes to the **identity** of the parent value. That means the `$watch` on the parent value only fires if the reference to the value has changed.
[...]
If you now change a property of the object in your parent scope, the change will not be propagated to the isolated scope, because the identity of the object on the parent scope has not changed. Instead you must assign a new object.

Closing as it works as expected. (If you think there is a way to improve the docs - e.g. add a warning in `$onChanges()` section - PRs are welcome :smiley: )
