### ISSUE TITLE
$locationChangeStart if prevented with e.preventDefault doesn't emit any event to inform

### ISSUE THREAD

**Issue by codekraft-studio** [angular/angular.js#14498]
**Steps to reproduce the error**
1. Run a function on $routeChangeStart (example: show a page loader)
2. Ask for confirm before $locationChangeStart (example code below)
3. No other event get fired and the function started during $routeChangeStart that will be blocked on $routeChangeSuccess or $routeChangeError keeps running 
```javascript

before = angular.copy($rootScope.myData);

$scope.$on('$locationChangeStart', function(e){
    if( !$scope.myForm.$pristine && !$scope.myForm.$submitted ) {
      if (!confirm("You have unsend changes, exit will remove them!")) {
        e.preventDefault();
        return;
      }
      // restore previous data
      $rootScope.myData = before;
    }
})
```

**Expected/desired behavior**
Broadcast a $routeChangeError event or similar event like $routeChangePrevented.

**Other information**
I built a angular directive that shows a page loader when a route is changed and start it at $routeChangeStart and removes it on $routeChangeSuccess or $routeChangeError, but when a user implement a script like the one above, that prevent $locationChangeStart, the function called from $routeChangeStart keeps running over and over because there's no other event that inform the route/location change has been prevented/blocked.
The directive is [here](https://github.com/codekraft-studio/angular-page-loader/blob/master/dist/angular-page-loader.js)

**What is the motivation / use case for changing the behavior?**
If someone run a function on $routeChangeStart and expect to stop it on $routeChangeSuccess or $routeChangeError, get stucked if user prevent the $locationChangeStart event

Actually if I manually add $scope.$broadcast('$routeChangeError') after e.preventDefault(), I get the expected beheviour, my question is about make it part of the script so I can call $rootScope.$on('$routeChangePrevent') or something similar and stop (hide) the page loader started during $routeChangeStart event inside my directive instead to force the user to do it manually.

I hope this makes sense. Thanks in advance.

**Comment by Narretz** [comment]
Hmhmhm. I actually would expect that routeChangeStart isn't fired when loactionChangeStart has been prevented

**Comment by codekraft-studio** [comment]
@Narretz actually in the last release of angular (1.5.x) $routeChangeStart is fired before $locationChangeStart and after is prevented, nothing is fired to notify the prevention.

**Comment by Narretz** [comment]
Hm, I'm pretty sure that's not how it works. See
https://github.com/angular/angular.js/blob/8d1ee0c3b9026737910dcd9b8fb6c48fb7091aec/src/ngRoute/route.js#L522 and https://github.com/angular/angular.js/blob/8d1ee0c3b9026737910dcd9b8fb6c48fb7091aec/src/ngRoute/route.js#L561-L576

In your case, can't you just listen on $routeChangeStart?

I also see that we only emit $routeChangeError when one of the promises in the route resolve fails. So there may be potential for improvement, but since we are working on a new router and there are good alternatives such as ui-router, I think we are not gonna work much on this.

**Comment by codekraft-studio** [comment]
@Narretz actually the ngRoute code shows that $locationChangeStart is fired and through it $routeChangeStart is fired, but why in this simple [plunker](http://plnkr.co/edit/bVhzb3jC5aIu1O2OMKZa?p=preview) happen the opposite?

My issue is related to a function that I call on $routeChangeStart event and if the $locationChangeStart is prevented no events gets fired to notify the $routeChange process has been prevented or blocked and the `$timeout.cancel(promise)` in my code above that is runs from both $routeChangeStart and $routeChangeError to hide the loader never gets fired.

Am I doing something wrong or I'm using improperly ngRoute events?

**Comment by Narretz** [comment]
That's weird. If you listen to the events in the controller, the direction is inverted, but if it's in the run block it is correct: http://plnkr.co/edit/di5GUoFkU4JOSitKfu5a?p=preview

**Comment by Narretz** [comment]
Hm, that's kind of bad. 
So ngRoute has its own locationChangeStart listener, which then fires routeChangeStart. This means all locationChangeStart listeners that are registered after the ngRoute one will receive the routeChangeStart event first, because we are looping synchronously through the registered listeners. It works as expected for the run() block because that one actually is registered even before ngRoute.
So yeah this is pretty bad.

@gkalpak This looks like it might be related to the problems introduced by injecting $route into the run block. when you do that, any $locationChangeStart listeners will be called after any $routeChangeStart listeners.

**Comment by gkalpak** [comment]
> That's weird. If you listen to the events in the controller, the direction is inverted, but if it's in the run block it is correct

Basically, `controller` vs `run` isn't so important. What _is_ important is if your listener is registered before or after `$route`'s listener, which translates to: "whether your listener was registered before or after `$route` is instantiated".
So, if your code (e.g. your `run` block) has a dependency on `$route`, it is guaranteed that `$routeChangeStart` will be fired before `$locationChangeStart`.

--
> This looks like it might be related to the problems introduced by injecting $route into the run block.

Could be. It is indeed not ideal that the order of `$locationChangeStart` vs `$routeChangeStart` depends on one's code's "timing" vs `$route` instantiation. The `$routeChangeStart` event _must_ be broadcasted synchronously, because the user should be able to prevent the associated `$locationChangeStart` event, when preventing the `$routeChangeStart` event.

By injecting `$route` in a run block (as we are planning for 1.6.x), it will make the order consistent (as long as one includes their code after `angular-route.js`), but will be a breaking change (which is OK for 1.6.x though).

--
Now, the fact that there is no event fired when a `$locationChangeStart` or `$routeChangeStart` event is canceled (prevented), isn't ideal either. We could introduce one such event (e.g. `$locationChangeStartPrevented`, but then we should probably do the same for every event and that's not ideal either.

FWIW, there _is_ already a way to detect whether such an event has been prevented and I believe this is what people should use. Namely, one can check the event's `defaultPrevented` boolean property. There is a catch: Since you don't know if the prevention will happen in a subsequent handler, you should check inside an `$evalAsync` block, e.g.:

```js
.directive('myAwesomeLoaderDisplayer', function () {
  // DDO
  return {
    ...
    controller: function MyAwesomeLoaderDislayerCtrl($scope) {
      $scope.$on('$locationChangeSuccess', hideLoaderIfVisible);
      $scope.$on('$locationChangeError', hideLoaderIfVisible);

      $scope.$on('$locationChangeStart', showLoader);

      // Functions - Definitions
      function hideLoaderIfVisible() {
        // Hide the loader if visible
      }

      function showLoader(evt) {
        $scope.$evalAsync(function () {
          if (!evt.defaultPrevented) {
            // Show the loader
          }
        });
      }
    }
  };
})
```

**Comment by codekraft-studio** [comment]
@Narretz @gkalpak Thanks thanks for having clarified how it works, is much appreciated!

> Since you don't know if the prevention will happen in a subsequent handler, you should check inside an $evalAsync block

That is exactly what I was looking for!
I should have read the documentation thoroughly, in fact, I see now that the definition of `$evalAsync` tells exactly what you explained:

> $evalAsync([expression], [locals]);
   Executes the expression on the current scope at a later point in time.

Thanks again!
