### ISSUE TITLE
strange behaviour when removing item from array which has one-way data binding

### ISSUE THREAD

**Issue by httpete-ire** [angular/angular.js#14500]
**Do you want to request a *feature* or report a *bug*?**

Not sure if this is a __bug__ or I am missing something about one-way data binding

**What is the current behavior?**

Using one-way data binding (:: syntax) on a list item, when the item is removed using the _Array.splice_ method, Angular will remove the last item from the array in every case. The correct object is removed from the array as it is printed to the console. Removing the one-way data binding will fix the issue. Is this a bug or am I doing something wrong?

_template_

```javascript
<li ng-repeat="person in vm.people track by $index" ng-click="vm.removeItem(vm.people, $index)">
   {{::person.name}} - {{::person.age}}
</li>
```

_controller_
```
vm.people = [
  { name: 'Jon', age: 54},
  { name: 'Mary', age: 45 },
  { name: 'Sarah', age: 29 }
];

vm.removeItem = function(array, index) {
  var removedItem = array.splice(index, 1);
  console.log(removedItem);
}
```

[demo of the issue](http://codepen.io/peter1red/full/MyBBEy/)

**What is the expected behavior?**

Remove the item that was clicked from the array

**What is the motivation / use case for changing the behavior?**

Sometimes it is not required to watch every property of an object (especially objects with a large amount of properties) for changes.

Issue is present in Chrome, Firefox and Safari on a Mac.

Tested with Angular v.1.5.5 and snapshot version

**Comment by gkalpak** [comment]
It is working as expected. This is because of how `track by $index` and one-time binding works (btw, one-way binding is something totally different - you are using one-time binding here).

Basically, the correct object is removed (you can verify that by grabbing the element's scope in the console and checking the associated `person` property), but since you are (a) reusing the previous element (because of `track by $index`) **and** not re-evaluating the bindings (because of `one-time bindings`) you still see the data associated with the previous (now removed) `person`.

--
In this particular case, there doesn't seem to be a reason to track by `$index`. You should either track by another property or fall back to the default tracking behavior.

(Closing, but feel free to continue the discussion below.)

**Comment by httpete-ire** [comment]
@gkalpak thanks for clearing that up.
