### ISSUE TITLE
Leading/trailing whitespace in directive attributes with scope "&" is lost

### ISSUE THREAD

**Issue by ChristopherBrix** [angular/angular.js#14539]
When I create a directive with an attribute which scope is defined with `&`, leading and trailing whitespaces are lost ([fiddle](http://jsfiddle.net/ChristopherBrix/1js02n8w/4/)).

While it can be circumvented by creating a variable and passing the evaluated variable as the value (using `attribute={{variable}}`, see the fiddle), this looks like a bug to me.

The fiddle uses Angular 1.4.9, but it's still present in the current snapshot v1.5.6-build.4785+sha.707664a

**Comment by gkalpak** [comment]
So, this has been the case since v1.0.0-rc.2 (8af4fde). I labelled this as a bug, but it could be expected behavior as well.

This is been around for so long, that I am not sure it is worth changing now.
If anyone wants to submit a PR, the problem "starts" at [compile.js#L1887][1].

[1]: https://github.com/angular/angular.js/blob/707664a3c448732443bf54027dacda39babdd0c4/src/ng/compile.js#L1887

**Comment by Narretz** [comment]
I think this is similar to https://github.com/angular/angular.js/issues/11859
