### ISSUE TITLE
Problem extending $resource object before the response has arrived.

### ISSUE THREAD

**Issue by carpasse** [angular/angular.js#1453]
Hi guys I've found what I think is an unexpected behaviour on $resource.

if you create a $resource obj, call get and try to extended it before the $http response has arrived whatever you have added to the object gets removed.

Here you have an example the problem. http://jsfiddle.net/carpasse/rUXVY/9/

I think the problem is that you are using 'copy' instead of 'extend' to fill the future once you get the response but again I don't even know if you consider this a bug.

**Comment by kyleburt** [comment]
hey is it too late to grab this issue?

**Comment by gkalpak** [comment]
TBH, I don't think the current behavior should be changed. It is intentional that we delete other properties, because the object is supposed to reflect the data from the server. Having the local object contain extra properties would be quite confusing (e.g. one would not be able to tell if a specific property is "client-only" or is part of the actual saved object on the server.

If one absolutely needs to have such properties, I think they are better added in a response interceptor. or in some other way (e.g. extending the return resource object).

**Comment by kyleburt** [comment]
Sounds good, I'm just going through old PR Plz issues to see what needs to
be doing.
