### ISSUE TITLE
Observe the registered callbacks of an Promise

### ISSUE THREAD

**Issue by JPVenson** [angular/angular.js#14605]
Hey,

I Would like to request this feature.

As seen in the extend for the promise there is an private ($$) variable on each promise object that contains all listeners to an promise, called "$$state.pending" and of type Array [Function,Function,Function,Function]. 

This list used used to enumerate the listeners and then invoked when the certain event is triggered. just bevor this list is enumerated in "processQueue" it is set to an variable inside the function and then set to undefined.

I would like to request to not clear the field on the Promise and/or make it public available

I have a function that returns a promise. After the rejecting i would like to check by my own finally if any other callback was attached to this promise i returned. If not so i would like to handle the catch block by my own.

Please make ether the "$$state.pending" variable usable or implement an function in Promise that attaches default/fallback callbacks.

**Comment by gkalpak** [comment]
I don't think we can keep the callbacks there, since they would get called over and over.

That said, I am not sure what the exact usecase is and if/how it could be supported differently. Can you give a concrete example ?

**Comment by dcherman** [comment]
FWIW, it sounds like what you actually want is something like #11754 - the ability to hook into unhandled rejections.  In fact looking at the source code, it looks like some amount of support already exists to pipe unhandled rejections to `$exceptionHandler`, but I don't see any documentation about it.

This proposal wouldn't work though since consider this:

```js
  function yourFunction() {
    return $q.reject(new Error());
  }

  yourFunction()
     .then(function() {
        console.log(true);
      })
     .catch(function() {
        console.log(false);
      });
```

Per the spec, a new promise is returned from `.then`, and you can see that any errors would have been handled here, however you'd never be able to observe that a `catch` was added since it's not your promise where the handling was added.

**Comment by JPVenson** [comment]
Assume:

You register an Http Interceptor that will handle both "requestError" and "responseError" by returning an new Promise that is rejected.

In your code you call any method on the $http service (assume $http.post(...) ).

The server will return an BadRequest on that method.

What i want:

I want to observe in my interceptor if any method has registered an catch on the new Promise. If so i should do nothing as the Http error is resolved by any other code. If not i want to process the message an show it in an general way ( within an bootstrap alert on the upper side of the page ) to the user and also log it localy.

i want to build an general error handling that will handle all messages that are not contains the status 200

**Comment by JPVenson** [comment]
https://gist.github.com/JPVenson/bf0cde0000d3afc39566a2e6e358bf21

**Comment by gkalpak** [comment]
Is this possible with native Promises (not afaik) or other promise libraries ?
I don't think we should add support for "non-standard" features as it will just make it more difficult for users to migrate to non-`$q` implementations.

**Comment by JPVenson** [comment]
I'm sory i do not have knowledge of other big promise libs. Therefore my approatch is to not support this directly but to not clear the "pending" field bevor invoking the callbacks.

**Comment by gkalpak** [comment]
As @lgalfaso mentioned, `$$state` is a "private" property and an implementation detail. You should not rely on it for any functionality and we should not worry about changing any wrt `$$state` (including removing it altogether in the future).

Maybe we decide to replace `$q` with another lib or switch to native promises + Zones.js. Who knows ?
Even today, some people are replacing `$q` to use another implementation (e.g. Bluebird) - there is no guarantee that `$$state` will be there or behave in a specific way. 

Just pretend it's not there :stuck_out_tongue:

**Comment by dcherman** [comment]
FWIW, the correct thing to use to implement this is an unhandled rejection hook.  I believe one is landing in 1.6, the code is already in master

**Comment by gkalpak** [comment]
@dcherman, it's not exactly an hook. (Possibly) unhandled rejections are raising an error that is passed to the `$exceptionHandler`, but there is no way to associate it back to the originating promise and rejection.

**Comment by dcherman** [comment]
@gkalpak Yep, but for the use case presented here, it looks like that would be acceptable since it's just for logging and alerting purposes.

Since you can use duck typing to determine that the thing passed to `$exceptionHandler` was a failed HTTP request, you should be able to accomplish that.  Worst case is that you add an interceptor to add metadata to the object for future usage in the logger.

**Comment by gkalpak** [comment]
> Since you can use duck typing to determine that the thing passed to $exceptionHandler was a failed HTTP request

That's the problem, you can't. Because only an error is passed to the `$exceptionHandler` (actually it's just a string - the error message), so there is no way to know where it came from or what other data it might be related to (e.g. failed URL etc).

**Comment by dcherman** [comment]
@gkalpak So that's a good point, and I'd argue that's actually a bad implementation of unhandled rejections - I'll file a separate issue related to that.  An unhandled rejection should be treated no differently than an unhandled exception - if I throw an uncaught error, I expect to catch that in the global `$exceptionHandler`, not a string representing the error.

There are bugs in the implementation anyway - if you reject a promise with an Error (which isn't an uncommon thing), the output isn't useful.

http://jsfiddle.net/rogqp47y/27/

**Comment by gkalpak** [comment]
This is because it is not an unhandled rejection hook, but rather a warning that there is an unhandled rejection (which you should catch and handle if interested).
That said, it might be more useful to provide more context or another means to hook into unhandled rejections (similar to the `unhandledrejection` event for native Promises).

**Comment by gkalpak** [comment]
As mentioned earlier, adding non-standard features to `$q` will only encourage bad practices and meke it more difficult for developers to switch or use other standards-compliant imlementations.

A better "unhandled rejection hook" is being tracked at #14631.

Based on the above, I'm going to close this for now.

--
BTW, if you want some custom features, you can most of the time decorate a service and enhance it (or replace it altogether). E.g., keeping track of rejection handlers:

```js
.decorator('$q', function decorateQ($delegate) {
  var _then = $delegate.prototype.then;
  $delegate.prototype.then = function then(successCb, errorCb) {
    this.__caught = this.__caught || angular.isFunction(errorCb);
    return _then.apply(this, arguments);
  };

  return $delegate;
}

// Then use it like this:

function AppCtrl($q) {
  var deferred = $q.defer();
  var promise1 = deferred.promise;
  var promise2 = promise1.then(angular.identity).catch(angular.noop);
  
  console.log(promise1.__caught, promise2.__caught);   // false true
}
```

**Comment by JPVenson** [comment]
that last idea to overwrite the "then" function was exactly what i was looking for. Nice one! thanks.
