### ISSUE TITLE
ngEventDirs.js is missing the W3 convention Pointer events

### ISSUE THREAD

**Issue by Valchris** [angular/angular.js#14634]
The list of automatically bound events via ngEventDirs, ng-click, ng-mouseup, etc.. is missing the specification for Pointer events (https://www.w3.org/TR/pointerevents/). This specification integrates various inputs from mice, touchscreens, and pens, making separate implementations no longer necessary and authoring for cross-device pointers easier. 

**What is the current behavior?**
None of the pointer events, below have ng-{directiveName} equivalents

- pointerdown
- pointerup
- pointercancel
- pointermove
- pointerover
- pointerout
- gotpointercapture
- lostpointercapture

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
My suggested fix is to update ngEventDirs foreach loop to include the list provided above and amend the documentation. Note that browser adoption for Pointer events is still catching up so a Polyfill is still likely required by most users who wish to leverage the new unified Pointer events.

**Comment by Narretz** [comment]
Pointer events are a recommendation and so far only supported in IE and Firefox. I don't think it makes sense to support proposed apis.

**Comment by Valchris** [comment]
@Narretz chrome is actively working on implementing the proposal as well, it's the 6th most watched issue in the chromium repository. It's also easily polyfilled making it available today on any browser. I think that makes it worthwhile.

https://bugs.chromium.org/p/chromium/issues/detail?id=471824

**Comment by gkalpak** [comment]
I agree with @Narretz. It doesn't make sense to add something that doesn't work out-of-the-box in all supported browsers (we don't really do this in ng1).

Note that creating (even) more directives makes the compiler a tiny bit slower (considering that all attributes of all elements in the app need to be checked against the list of known directives).
Moreover, some of the events aren't really suitable to `ng-<event>` directives, since you don't want to run a `$digest` on every `pointermove` for example.

Taking into account how easy it is to create these directives as a 3rd-party module (and the limited adoption they have at the moment), I think we shouldn't add them to core.
(At least not until the adoption and browser support are much better.)

**Comment by Valchris** [comment]
Thanks @gkalpak, that makes sense.

**Comment by kfenner** [comment]
I think this should get some more attention, since dealing with user interaction is probably one of the most fundamental parts of any web application. And as of 2017 the Pointer Events API seems to be the right tool for this, especially since it is supported in Chrome 55+ (Safari still doesn't support it, I know).

@gkalpak If I understood correct, it is not the idea to implement polyfills in Angular 1. I can live with this, but I think more and more people will run into these issues when developing cross platform apps. I still think Angular as a framework should provide the developers with the right tools for such a fundamental problem.

I created a stackoverflow post to see if others feel the same, or even better, already have some solutions ready: http://stackoverflow.com/questions/41587135/how-to-handle-mouse-touch-and-pointer-events-in-angular

**Comment by gkalpak** [comment]
> Angular as a framework should provide the developers with the right tools for such a fundamental problem

The tools are there: directives 😛
It is very easy to create the directives you need. And even distribute them as a reusable module.

##
My main points are:

1. These events are still neither well supported, nor widely used.
2. Each new directive slows the whole `$compile` down (by a tiny bit each, but still).
3. Many of these directives are not good candidates for integration with the digest, but having `ng-event` directives that don't integrate with the digest will definitely throw some people off. Which means you can't implement them in a way that keeps everyone happy.

For the time being, I still believe it is better to keep them off the framework and let the community provide them as external modules (if necessary).

**Comment by kfenner** [comment]
@gkalpak Fair enough :smile: 

1. Correct, maybe it's too soon from this point of view, but it just means people need to search or develop alternatives (can be good or bad)
2. If performance is a concern, why not deprecating also the `ng-mouse*` along with other `ng-event` directives and provide an opt-in module which handles all these user interaction events in a proper way?
3. See 2. Maybe even providing some options to make most of them happy i.d.k.

Since the community efforts are not yet that great, it could well be that most devs think this is something they just need to handle on their own like they did before all the jqueries and angulars and are not feeling too bad about it :wink: 

Thanks a lot for sharing your thoughts :+1:

**Comment by gkalpak** [comment]
Maybe we could introduce an `ng-on-<event>` pseudo-directive (something similar to `ng-attr-`) and handle all events. But digest integration is still an issue (sometimes you need it, sometimes you don't).

BTW, I think Angular (2+) has a similar problem with Zones, for events that you don't want change detection to run on every event (e.g. while dragging something). Let's wait and see how Angular (2+) solves it and decide then :smiley:

**Comment by kfenner** [comment]
I like the idea, at least it would make it easier to bind to whatever event you need. Maybe the event could be prefixed, so when subscribing you could choose if it runs in the digest loop or not: `ng-on-native-mousedown`, `ng-on-raw-mousedown`, or something better.

Good point about Angular 2. Tells me I should take a look what's going on there and how to deal with these problems in Angular 2+.
