### ISSUE TITLE
ngAnimate anchoring does not work the first time templates are loaded and displayed

### ISSUE THREAD

**Issue by sebastiendan** [angular/angular.js#14649]
Hi,

_First issue ever for me so please tell me if I missed some guidelines here..._
I'm trying to make great use of anchoring animations and I managed to make it work with a transition between 2 states (I am using angular ui-router). 

However my anchoring animation only works after both states templates have been loaded and displayed at least once.

Flow:

Page A: header view + **content list view**
Page B: header view + **content details view**

First transition from page A to page B follows my default view transition animation (anchoring animation is not triggered). Then, either getting back to page A or going to another page and starting again the flow will make the anchoring animation work, in both ways.

I can write a test for you but I wanted first to know I'm missing something obvious here...
I don't think the problem is from my code since anchoring works well after the first time.

Thanks (awesome job)!

**Comment by Narretz** [comment]
In general, I would say this is expected behavior, as the templateUrl means the actual element isn't yet available when the animation runs (it basically runs on a dummy element). Most apps don't have this problem, as they use a build-step to put their templates into the templateCache so that they are immeditately available when the application runs.

**Comment by Narretz** [comment]
You can post a plnkr that shows the problem so I can confirm this is the case.

**Comment by sebastiendan** [comment]
Indeed I managed to concat all my templates and to load the result at once, anchoring works fine now!
Thanks!
