### ISSUE TITLE
How can I set default value for ng-options by using object (not array )? 

### ISSUE THREAD

**Issue by ppneo007** [angular/angular.js#14654]
## the html file like this
`<select ng-model="seleted" ng-options="a.name for a in animals"></select>`

## ths js file like this
`$scope.animals = [
          {
            id: '00001',
            name: 'cat',
          },
          {
            id: '00002',
            name: 'dog',
          }
 ];
  var a = $scope.animals[0];
  var b = {
        id: '00001',
        name: 'cat'
  };`
     If I do this:　 `$scope.seleted = a`   ------ the default value is ok,  it will appear on the page
 but if I do this:   ` $scope.seleted = b`   -------nothing will show for the select , Why??????????

because I load the init value(a object)  from server,  so I do not know the index of the object in the array,  I do not think it is a good idea to check the object index in the array.---but how should I do??

**Comment by Narretz** [comment]
That's because ngOptions matches the model and the matching option with object identity, i.e. the selected option and the model must be the same object. If you can't set the model to a reference to the options collection, you can use track by, e.g. `track by item.id`. You need a unique identifier for that, though.
