### ISSUE TITLE
ng-model gets updated before ng-click on input radio

### ISSUE THREAD

**Issue by victorherraiz** [angular/angular.js#14667]
**_Note_: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

ng-model gets updated before ng-click on input radio and there is no way to prevent the default action

**What is the expected behavior?**

It should be a simple way to prevent default action.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Browsers: Chrome, IE11
Angularjs: 1.5.0

**Comment by Narretz** [comment]
In general, we don't make guarantees about the order of events in connection with ngModel. ngclick cannot prevent the default in your case, because its click handler is added after the click handler that gets added by the radioInput. A few thoughts:

- we should probably listen to the change event in the radio directive. I assume it wasn't done because support for this is buggy in IE8.

- you can achieve what you want by creating a directive that adds a click handler before the radio input
- you'll also need to call e.stopImmediatePropagation, otherwise you only prevent the visual update

See http://plnkr.co/edit/yQ4qOlUczgimDPtMUmHa?p=preview

HOWEVER, I don't think it's good ui to stop such a basic function as selecting a radio, especially when it looks like the user can click the radio. Instead, you should use ngDisabled to disable the radio when you don't want anyone to select it.
