### ISSUE TITLE
Link to Workspace Reset Instructions dead in tutorial (all steps)

### ISSUE THREAD

**Issue by maacl** [angular/angular.js#1473]
Link should go to http://docs.angularjs.org/tutorial/step_00 instead of http://docs.angularjs.org.

**Comment by lukeblechl** [comment]
I'm still seeing this issue as well and feel it should be reopened. On the page https://docs.angularjs.org/tutorial/step_01 the "Workspace Reset Instructions" link still points to http://docs.angularjs.org instead of http://docs.angularjs.org/tutorial/step_00. Could this link please be updated?

Thanks much.
