### ISSUE TITLE
$provide.decorator to extend directive scope no longer works in > 1.5.1

### ISSUE THREAD

**Issue by sbessah** [angular/angular.js#14785]
Hi,
Presented solution in https://github.com/angular/angular.js/issues/10149 to extend directive scope is no longer work in >1.5.1
We can reproduce it in below plunker by changing angular version by 1.5.1
http://plnkr.co/edit/CRxhX6?p=preview

are there others alternatives to extend directive scope?

**Comment by Narretz** [comment]
Since 1.5.1, you can decorate the scope as usual again, so this regression was fixed. This should be obvious from the issue, the changelog, or the migration guide.
See http://plnkr.co/edit/LkxtF9?p=preview

**Comment by eolamisan** [comment]
The plnkr doesn't work anymore. :cry:

**Comment by gkalpak** [comment]
@eolamisan, it was probably some save error. Here is a [similar plnkr][1] that works and OP's [modified plnkr][2]. The concept shown in @Narretz's plnkr is the way to go in recent Angular versions.

<sub>Note that when using the `.component()` helper or setting `bindToController` to an object, you need to update `ddo.bindToController` instead of `ddo.scope`.<sub>

[1]: http://plnkr.co/edit/8fclacP7qMClbup9zouM?p=preview
[2]: http://plnkr.co/edit/uZ9biOrcAqzemtwfsCUa?p=preview
