### ISSUE TITLE
ngDocs: angular.mock.dump is not injected to window

### ISSUE THREAD

**Issue by e-cloud** [angular/angular.js#14790]
https://docs.angularjs.org/api/ngMock/function/angular.mock.dump

the docs now implys dump function is available on window. it's not true

**Comment by Narretz** [comment]
Hm, I'm using it pretty often. Are you sure you have the ngMock module included when you try to call it?

**Comment by gkalpak** [comment]
@Narretz, you probably mean that it is available as `window.angular.mock.dump`, but @e-cloud is right: it is not available on window (`window.dump`) as documented. 

Bug or docs issue ?
Since it isn't necessary on window, let's fix the docs to avoid breaking tests where `window.dump` is defined by the developer.

**Comment by wesleycho** [comment]
There are some situations I've found where not all ngMock globals are not truly published to window, mainly when transpilers like TypeScript or Babel are involved.

When using TypeScript, I've found that I've had to use `angular.mock.module`, but strangely `inject` worked fine.

**Comment by gkalpak** [comment]
This is different though. We are not publishing `angular.mock.dump` on `window`, so transpilers are hardly to blame :)

I can see why `module` would get overwritten with transpilers that try to support `CommonJS` and put things on `module.exports` :smiley:

**Comment by wesleycho** [comment]
Ah, I mistook the issue...and that makes sense, I think I knew that but forgot - sorry for the diversion!
