### ISSUE TITLE
Duplicate 'ng' and 'ngMock' modules pushed to  currentSpec.$modules caused by window.inject function in angular-mocks.js

### ISSUE THREAD

**Issue by chendachao** [angular/angular.js#14802]
It will unshift 'ng' and 'ngMock' to modules variable exposed on current spec, if we inject services with window.inject function

![baidushurufa_2016-6-20_17-19-58](https://cloud.githubusercontent.com/assets/18575321/16189163/90c72a76-370b-11e6-8f21-a1d68b8220ef.png)

Code like below

```js
beforeEach(inject(function($q){
	
}));

it('', function(){
	inject(function($httpBackend){
		
	});
});
```

After a research I found it's caused by window.inject function in angular-mocks.js.

Can anybody fix it or it's unnecessary?

**Comment by gkalpak** [comment]
This only happens in tests (i.e. when `angular-mocks` is included) and the overhead is minimal (i.e. Angular will check if a module is already loaded and not do anything), so it is actually working as intended.

**Comment by gkalpak** [comment]
To be a little more clear:
It is true that the `modulesToLoad` (the modules that Angular will load at the beginning of a test) may end up containing multiple instances of `ng` and `ngMock`. We could probably avoid this duplication, but it is not worth it, since (a) it doesn't affect the overall behavior, (b) it only happens in tests, not "real" apps, (c) the added overhead is minimal (even if we were concerned with performance in tests) and (d) avoiding it would be more complex (and introduce a different overhead anyway).

Thx for pointing out though. It's good to know people are paying attention :smiley:

**Comment by chendachao** [comment]
I see. Thanks for your quick support @gkalpak
