### ISSUE TITLE
Infinity $http GET/POST when call function directly

### ISSUE THREAD

**Issue by cybercoder** [angular/angular.js#14844]
When I use $http.get in a function like this:

$scope.myFunc()=function() {
  $http.get ....
}

in Html when a button with ng-click="myFunc()" it works well, but when use it directly like: {{myFunc()}}
the $http requesting infinity get!

Is this usual?

Regards

**Comment by Narretz** [comment]
This is expected. When you do {{myFunc}} for example in a text node, then Angular will evaluate (digest) the function until the result is stable, i.e. you get an identical result on two subsequent passes. Since you are doing http requests, it will never stabilize. You should instead call the $http in the controller and assign the result to variable that you will bind to.
BTW, `$scope.myFunc()=function() { ... ` this isn't correct Javascript, but this might just be a typo.

**Comment by cybercoder** [comment]
@Narretz Thanks for your light & useful explain.
