### ISSUE TITLE
I cannot parse the JSON containing 2D array in angular JS

### ISSUE THREAD

**Issue by manoj1991** [angular/angular.js#14861]
This is my code:
https://plnkr.co/edit/ZtqFdgCQEvfc7zJcnPnY?p=preview

**Comment by gkalpak** [comment]
I am not sure what the problem is (everything seems fine to me in the demo after a quick look).

In any case, this sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
