### ISSUE TITLE
using 'disabled' as a binding name in component causes problems in form in IE 11

### ISSUE THREAD

**Issue by rayzmundo** [angular/angular.js#14880]
A Bug in IE 11, apologies if this has been raised before

If  'disabled' is used as a binding name it causes issues in IE 11.Cant tab, placeholder does not work

The following example shows 3 input buttons, 2 of which are in the parent component form and 1 is in the child component. The first example shows with binding 'disabled'. tab on the input boxes does not work and place holder does not work correctly.
The second example is with binding called 'isdisabled'. Everything works correctly in IE 11
DEMO: 
with binding '**disabled**' = https://plnkr.co/edit/3KRHdmj7Y93L8qaD9Ziv?p=preview
with binding '**isdisabled**' = https://plnkr.co/edit/fQuxhW14TcrkfvqS9Umo?p=preview

**Comment by gkalpak** [comment]
This is a IE11 issue. It isn't related to Angular or directive bindings.
The funny behavior happens when using a `disabled` attribute on a container (regardless if it is related to a binding or not - in fact regardless of Angular). [This demo][1] shows the same bug without Angular at all.

While there is not anything we can do to fix this (IE should fix this), you can prefix your attributes with `data-` or `x-` to work arounf the issue. Angular denoralizes the attribute names, so it will interpret `data-disabled` or `x-disabled` the same as `disabled`, but IE11 won't act funny on `<prefix>-disabled` attributes.

[1]: https://plnkr.co/edit/RQrYhfgFX0O4gEa7IQdz?p=preview
