### ISSUE TITLE
Are there ng-animate directive?

### ISSUE THREAD

**Issue by Thaina** [angular/angular.js#14905]
To simplified update loop, such as clock and other animated values that changed over times. I would like to have ng-animate as directive able to put on any element

Suppose we want to make a clock

```html
$scope.UpdateClock = (){
    $scope.clock = new Date();
}

$scope.time = 0;
$scope.UpdateTime = ($event){
    // $event will contain $event.previousTime and $event.deltaTime for value of last update
    $scope.time += $event.deltaTime;
}

////

<span ng-animate="UpdateClock()">{{clock | date:"HH:mm:ss.sss"}}</span>
<br>
<span ng-animate="UpdateTime($event)">{{time | date:"HH:mm:ss.sss"}}</span>
```

UpdateClock and UpdateTime would pending in a list that will fired with `requestAnimationFrame` globally. Also it may be skip update if the element was disabled in hierarchy. Or removed from event list when element is removed or hidden with ng-if

**Comment by gkalpak** [comment]
I don't feel this is something commonly used in apps - although I understand it might come in handy is certain usecase. It is very easy to create it on your own (as custom directive), though, and even publish it as 3rd-party module for others to use.

Therefore, I don't think this belongs in core. We try to keep the core as small as possible and avoid adding extra weight that (a) everyone has to "carry" even if few people actually need it and (b) can be easily implemented outside of core.

**Comment by Thaina** [comment]
@gkalpak It seem easy but the hard part is to handle the state and lifecycle of element in angular. There are ng-if ng-repeat and so on that would be complicate for module

And I think timer and clock is not so specific. Angular even have $interval shortcut in angular. This is to simplify it and make angular centralize the update handle

I made this request after I read angular doc and see it was state that, we need to handle destruction of interval by ourselves. I think it not comfortable, most of the time interval will be used on some value so it need to handle the angular lifecycle

**Comment by gkalpak** [comment]
> It seem easy but the hard part is to handle the state and lifecycle of element in angular. There are ng-if ng-repeat and so on that would be complicate for module

These directives take case of themselves and the lifecycle and cleanup of elements under their control. You don't need to do anything special to handle them.

> Angular even have $interval shortcut in angular. This is to simplify it and make angular centralize the update handle

Not really :grin: This is so that Angular can run callbacks inside a `$digest`, so it can react to changes.
You can easily do the same thing yourself, be wrapping your callback body in `scope.$apply()` calls, but you don't always have to. In fact, it will probably affect your application performance negatively if you run a `$digest` on every animation frame. You might want to handle this differently (or outside Angular). But it's all very specific to your needs.

> I made this request after I read angular doc and see it was state that, we need to handle destruction of interval by ourselves.

It is true that if you have a directive that attaches "global" listeners/callbacks, you need to clean up when it is being destroyed. But it easy to handle the clean-up logic with `scope.$on('$destroy', ...)`.

**Comment by Thaina** [comment]
@gkalpak I mean handle the callback function we create for interval or timeout by ourself while angular has `ng-if` `ng-repeat` and also any other add/remove enable/disable

Think about it, normally we use $interval to create ticking clock in code

```html
$interval(() => $scope.clock.time = new Date(),1000);
////
<button ng-click="clock = null">RemoveClock</button>
<span ng-if="clock">{{clock.time}}</span>
```

Something like this would need to handle many cleanup. Like you have `scope.$on('$destroy', ...)` but it need to do on every element that we want to update on interval

Easy use case is to have world clock widget that user could add or remove clock on any timezone. We would like to attach/detach interval by each clock

And that's right. I would not like to call `scope.$apply()` on every animation frame that's why I would like to let angular watch over animation of values to see when it change inside animationframe

**Comment by gkalpak** [comment]
> Something like this would need to handle many cleanup.

There is not much clean-up. You just clear the timeout on `$destroy`.

> Like you have scope.$on('$destroy', ...) but it need to do on every element that we want to update on interval

That's why you will put the logic in a directive. You write it once and apply it to any element that needs this functionality.

> I would not like to call scope.$apply() on every animation frame that's why I would like to let angular watch over animation of values to see when it change inside animationframe.

Angular does the same thing under the hood. It just wraps things in an `$apply()` call (more or less). Angular doesn't know what you care about, so it has to run a "global" $digest (i.e. check all watchers throughout the app). You know what you need to check and you could run a "local" $digest (if you knwo your changes won't affect other parts fo your app) or manually update the element's content and avoid running any watchers (if you don't have to).

--
Trust me, anything that you need to implement this outside of core is already available to you :smile:

The fact that nobody has requested something similar until now (and I haven't ever seen it used or used it myself) means that this is an uncommon usecase, which few users would benefit from. So, not suitable for core.
