### ISSUE TITLE
angular is growing too much

### ISSUE THREAD

**Issue by wyrfel** [angular/angular.js#14978]
**_Note_: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a _feature_ or report a _bug_?**
a concern ;-)

**What is the current behavior?**
The angular source has been growing over the releases - i remember it being about 120kB minified at 1.2, at 1.4.9 we were able to minify it to about 150kB, we just updated to 1.5.8 and it now minifies to 160kB (those numbers are with a few of the optional core modules like cookies etc. and unzipped).

From a page load time performance point of view, a 100KB framework is already quite large. Angular just keeps getting larger with every release.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**
Please optimise for minified size when including new features and fixes.

**What is the motivation / use case for changing the behavior?**
Page load performance.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
That's a valid concern :wink: Ooc what other modules are you including in the bundle?

**Comment by mgol** [comment]
The most important size from the page load perf is the gzipped size, as that's what gets downloaded which is usually the slowest part. For various Angular versions these are gzipped sizes:

* 1.0.0: 32.6 KB
* 1.2.0: 40.9 KB
* 1.3.0: 50.9 KB
* 1.4.0: 58.0 KB
* 1.5.0: 61.6 KB
* 1.5.8: 63.7 KB

**Comment by Narretz** [comment]
The biggest jump in 1.5.x came from 1.5.3 to 1.5.5 (1.5.4 was borked, so let's not include it):

1.5.3: 61.99 KB
1.5.5: 62.62 KB

But I can't make out one change that could have caused this.

**Comment by wyrfel** [comment]
Sorry for responding late. Just checked and we are actually only including two extra packages
    'bower_components/angular/angular.js'
    'bower_components/angular-cookies/angular-cookies.js'
    'bower_components/angular-promise-tracker/promise-tracker.js'

**Comment by Narretz** [comment]
The promise-tracker is not a core module, so this should not factor in the equation. Like others have mentioned, the size that's important is the gzipped size, which is well under 100kb. You should also use the provided min.js angular core files, as they *should* be smaller (because they use the closure compiler).
We're also removing some parts of core in 1.6, which should help keep the size stable. Overall, more features mean more bytes. We could theoretically move some parts of core into their own modules, but it's a difficult decision, because it's always a BC (and might not save many bytes in the end, if many people are using the feature anyway). If someone has any suggestions which part we could move, then please go ahead.

**Comment by Narretz** [comment]
We are still again under 60kb gzipped, so the growth actually has stopped. Since we're moving to LTS in July, there will be no more efforts to decrease the size even more.
