### ISSUE TITLE
IE fires parsers on blur event

### ISSUE THREAD

**Issue by capesean** [angular/angular.js#14987]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Using the tab key to trigger a blur event (without modifying the model) causes the parsers to fire in IE.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
Here is a demo: https://jsfiddle.net/capesean/htorwgs5/3/
Using IE you can check the events being logged to the console. If you focus on the textbox and then Tab out, the parsers fire. 

Here is a demo of the same code, with an older version (1.3) of Angular, where this isn't an issue:
https://jsfiddle.net/capesean/htorwgs5/

**What is the expected behavior?**
The parser shouldn't fire, so that the blur event can update the model correctly.

**What is the motivation / use case for changing the behavior?**
The parser gets fired so it updates the model incorrectly.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Doesn't work (incorrect behaviour) with Angular 1.5.3 or 1.5.8. Works with 1.2.0 and 1.3.0.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Which versions of IE are affected? (9,10,11?)

**Comment by gkalpak** [comment]
This is expected bahavior (I'm afraid) and I can reproduce as back as 1.3.20 (I didn't try older versions).
(Btw, your 2nd plnkr is the same as the first - it uses 1.5.3.)

This happens because the `input` event (which we rely upon in other browsers) is too messed up in IEs to be useful, so we rely on keyevents and checking the input's value for changes. I.e. whenever a key is pressed on IE, Angular schedules to check the input's value in the "next tick" and run the parsers/validators if it has changed (that is an iversimplified explanation of what is happening under the hood).

I don't think there is much we can do and it should usually not be a problem, except for uncommon usecases (like yours), where people programmatically change the input's value in the `blur` handler.
An easy workaround is to update the value asynchronously ([updated plnkr][1]):

```js
elem.on('blur', function onBlur() {
  $timeout(function () {
    elem.val(...);
  });   // Possibly prevent the extra digest from running if you don't need it
})
```

[1]: https://jsfiddle.net/htorwgs5/5/

**Comment by gkalpak** [comment]
I would be fine closing this as a _won't fix_, but leaving it up to @Narretz :stuck_out_tongue:

**Comment by capesean** [comment]
Thank you @gkalpak that workaround works perfectly.
