### ISSUE TITLE
Trailing space issue in Angular Locale

### ISSUE THREAD

**Issue by TudorSfatosu** [angular/angular.js#15018]
**_Note_: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a _feature_ or report a _bug_?**
Reporting a bug

**What is the current behavior?**
A trailing space is added to RO and IT angular locale, maybe in similar locales as well.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
DEMO: http://jsfiddle.net/4gyjtu8g/245/
![one](https://cloud.githubusercontent.com/assets/6681480/17619465/785a5a26-607d-11e6-958d-eebd4540df75.png)

**What is the expected behavior?**
There should be no trailing space, like the EN angular locale

**What is the motivation / use case for changing the behavior?**
To fix a general bug

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js
https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.5.8/angular-locale_ro.js

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
![two](https://cloud.githubusercontent.com/assets/6681480/17619560/f16ddfb4-607d-11e6-91ac-77afce803daf.png)

**Comment by gkalpak** [comment]
This is kind of expected and is not specific to the `ro` locale. All locales that included a space before or after the currency symbol are affected in the same way.

According to the `ro` locale file, the currency-formatted number should be suffix with ` <CURRENCY_SYMBOL>` (a space, followed by the currency symbol).
By default, the currency symbol is `RON`: `currencyFilter(10)  -->  '10.00 RON'`
When you are replace the default currency symbol with the empty string, the result will still contain the space: `currencyFilter(10, '')  -->  '10.00 '`

You won't see the same problem with the default `en` locale, because in that locale there is no space between the number and the currency symbol:
`currencyFilter(10)  -->  '$10'` (no space before `10`)
`currencyFilter(10, '')  -->  '10'` (no space before `10`)

--
The easy way out is to trim the output before returning it to the user, but I am not sure if there are valid usecases for having leading/trailing whitespace characters.

Does anyone happen to have any insights on that?

--
Obviously, it is very easy to work-around it yourself - if you are sure you don't need the extra space - by:

1. Trimming the output:

    ```html
    {{ (10 | currency:'').trim() }}
    ```
    (Bonus points for creating a `trim` filter :stuck_out_tongue:)

2. Create your custom filter that wraps `currency` and automatically trims the output:

    ```js
    .filter('currencyNoSymbol', function currencyNoSymbolFactory(currencyFilter) {
      return function currencyNoSymbol(input, fracSize) {
        var output = currencyFilter(input, '', fracSize);
        return output && output.trim();
      };
    })
    ```
    Then use it like this: 

    ```html
    {{ 10 | currencyNoSymbol }}
    ```

3. Overwrite/Decorate the built-in `currency` filter to always trim the output (then use it normally).

**Comment by wesleycho** [comment]
I think it make sense to have the currency filter do the trimming in core itself, as it sounds like it is unintended behavior in this case. The overhead added should be minimal, and it would be easy to address without impacting anyone.

**Comment by gkalpak** [comment]
The only thing I m concerned/unsure about, is whether there is some locale that requires a space before/after its values. (I doubt it, but I am not sure either.)

**Comment by gkalpak** [comment]
From a quick search through the i18n files I didn't find any locale for which the trimming would be problematic.

This is more involved though, because there is another usecase that suffers from the same issue, but won't be solved by trimming: negative values for locales that have the currency symbol before the number. E.g.:

```js
// Assuming a locale the format `10` as `X 10.00` and `-10` as `-X 10` (where `X` is the currency symbol)

// Desired
currencyFilter(-10, '')   // --> '-10'

// Actual
currencyFilter(-10, '')   // --> '- 10' (space between `-` and `10`)
```

**Comment by TudorSfatosu** [comment]
I want to thank you guys for the involvement on this matter. 
I don't feel like adding more for the moment.
If you feel you have more questions for me, just let me know!
