### ISSUE TITLE
Dynamic input type change

### ISSUE THREAD

**Issue by madmages** [angular/angular.js#15034]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when input type changes dynamically, value does not change if its type became checkbox.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
http://plnkr.co/edit/sxYWF9eR7XArJhFucrUr?p=preview

**What is the expected behavior?**
im expecting that ngmodel variable should change on check\uncheck.

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
chrome 52.0.2743.116 m 
windows 7
angular 1.5.8

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
Dynamically changing the input's type is currently not supported. The reason is that the built-in `input` directive sets up specific behavior and configures the `NgModelController` differently based on the type of the input. Not that it is not possible to fix this, but it would introduce unnecessary overhead for one of the most commonly used directives in almost every app (i.e. `input`), only to support a raarely used feature.

It seems more appropriate to handle this on a higher level, e.g. use `ng-switch` or implement a higher-level component that compiles a new input when the `type` changes.

<sub>If you feel strongly about it, feel free to open a feature request for tracking the input type to see what others think.</sub>
