### ISSUE TITLE
Feature Request: Specify in Component "bindings" whether one-time binding is required or disallowed

### ISSUE THREAD

**Issue by azaslavsky** [angular/angular.js#15070]
**Do you want to request a *feature* or report a *bug*?**
feature for v1.5.z

**What is the current behavior?**
There is no way to specify whether a particular component binding can, must, or cannot be one-time bound

**What is the motivation / use case for changing the behavior?**
Generally speaking, a component should be able to handle two cases: it having some value set on instantiation, and that value being changed during the life of a component.  These require two different types of logic, and often times it's unnecessary to write both of these when the binding will only be one-time bound (or never will be).  It would be great to be able to explicitly specify whether or not one-time binding is required/banned for a given component, and to have an error thrown when those rules are violated.  For example, this could mean that a one-time binding is always required:

```javascript
{
  bindings: {
    sampleBinding: '::<?'
  },
  controller: function() {
    //Some code
  }
```

If the above component was instantiated as `<my-component sampleBinding="someScopeVal"></my-component>`, it would throw an error.  Similarly, one-time binding could also be explicitly banned:

```javascript
{
  bindings: {
    sampleBinding: '!:<?'
  },
  controller: function() {
    //Some code
  }
```

Now `<my-component sampleBinding="::someScopeVal"></my-component>`, would throw an error.

**Comment by gkalpak** [comment]
I can't of a good reason to either ban or require one-time bindings. The ony thing that is useful is for the consumer of a directive to know whether it will respond to changes in a binding's value, so they can decide whether the can use a one-time binding.

But this info can only be conveyed through docs. Maybe it is a good subject for community discussion (and a potential guideline for a styleguide?).

I will close this, but feel free to continue the discussion below.
<sub>(I will be happy to reopen if you can provide a usecase where it makes sense to ban/require one-time bindings.)</sub>

**Comment by azaslavsky** [comment]
Banning may be difficult to justify, but non-one time (multi-time?
regular?) bindings require added logic in the component.  If I don't want
to write that logic, it would be nice to have a way to inform the
component's consumer that they are doing an unsupported action (namely,
updating data that is expected to be immutable).

I also feel like thrown errors are preferable to docs, since they
immediately tell the implementer what they have done wrong.  On the other
hand, when their updated value silently fails to update in the component,
they could become very upset.

Example: say I am making a "custom" video player component, with its own
set of controls.  I've decided to require 1 video source per component
(let's say my custom video player has expensive setup logic) - if the
implementer wants to change the video source, they should create a new
instance of the component, rather than update the "my-componet-src" prop.
Making a required one-time binding would prevent the implementer from
trying to code in a use case (changed video source) for which the component
has no logic.

On Tue, Sep 6, 2016 at 10:41 AM, Georgios Kalpakas <notifications@github.com

**Comment by gkalpak** [comment]
I think we agree that the only reasonable usecase is to inform a user (directive consumer) whether a specific binding reacts to value changes or not. Still, there is no good reason to "force" the consumer to either use or not use a specific type of binding.

For example, if your directive does not react to value changes, it might be a good idea for the consumer to use one-time bindings. But it is also perfectly valid to use regular bindings, e.g because they are using it with a version that does not support one-time bindings, or because their team has decided to avoid one-time bindings altogether, or because it that specific context initial rendering is more  important (and one-time bindngs - for all their performance boost - come at a small initial-setup cost).

Another example would be a directive that does react to value changes. In that case too, it doesn not make sense to "force" the use of regular bindings. It is again perfectly valid to use one-time bindings, e.g. because you know that your bindings won't change, or because you don't want the directive to react to chenges to the value (even if the value changes).

So, all in all, other than docs I still don't see any way to assist developers/consumers in making the best decision when supplying bindings to a directive, while still supporting all common usecases.
Did I miss something?
