### ISSUE TITLE
Incorrect Currency Format for DKK

### ISSUE THREAD

**Issue by harisshahid** [angular/angular.js#15096]
DKK currency format is not displaying correct formatting for the Krone. Correct format is kr40.000,00 but it displays kr40,000.00 as we've for US.
This is the js fiddle link. [http://jsfiddle.net/nqf0ye00/102/](url). I've edited an example. Which is showing DKK in wrong format.
Please confirm that is it a bug or I'm doing something wrong.

**Comment by jesperronn** [comment]
Your link is not working for me. (404 not found) for https://github.com/angular/angular.js/issues/url

**Comment by harisshahid** [comment]
Copy the link and open in the new tab.

**Comment by Narretz** [comment]
Hi, Angular.js uses the Google Closure I18N library to generate its own I18N files (the ngLocale module). This means that any changes to these files would be lost the next time that we import the library. Since the Closure library i18n data is itself auto-generated from the data of the Common Locale Data Repository (CLDR) project, errors in the data should be reported there. See also the Closure guide to i18n changes.
