### ISSUE TITLE
Memory leaks in directives with transclusiion

### ISSUE THREAD

**Issue by djfd** [angular/angular.js#15115]
Hi,

This affects a scopeless directives with transclusion mode set to 'element', via bindings watchers. (maybe other kinds are affected too, not tested)

There is a sample [codepen](http://codepen.io/djFD/pen/KgdPoR)

What is coming there. Every time as you press the button, the directive is removed from DOM, then recreated in the same point. A counter below shows a number of watchers in the scope. So every press gives us a few extra watchers.

By the steps.
A.directive 'template' looks like this:
```xml
<container sid="{{'container-'+$id}}">
    container contents
</container>
```
that is has the only binding at the directive node itself.
B.Directive is scopeless, transclusion mode 'element'

At the directive compile time all is going fine, no extra watchers.
Then miracles begins.

At entering to pre-link routine we can notice that a watcher for a binding was created. It is good only for a directives with boolean transclusion mode, as nobody can be sure that 'element'-transcluded node will be ever attached to DOM (I mean requested through $tfn) - so why to have a binding activated for it in this point? (please note, there is the only binding, at the topmost directive element only)

Next, at the post-link, transclusion function is called, and after that we get one more the same binding watcher. This seems to be ok, we need to get it created at this point.

At directive removal both cloned node and node placeholder elements are deleted, which does not cause the watchers removal, they are still there. So we got two lost watchers for a single binding.

Well, it is rather rare to use scopeless transclusion, so in scopeful environment we just cannot notice that because watchers are simply removed together with a scope.

That is it. Or am I wrong and just doing something in wrong way?

**Comment by djfd** [comment]
@gkalpak , could you please explain a few?

**Comment by gkalpak** [comment]
This is all expected behavior (one way or another) :smiley:

There are actually 3 watchers created when "creating" a new instance and only one of them is removed when "dropping" , so we get 2 extra watchers per "recreation". So, what are those watchers, why do some of them stick around and how to get rid of them?

## What are those watchers?

### Interpolation in the compiled template

The template that you manually compile includes: `<container sid="{{...}}">...`.
When the compiler sees that template it doesn't (yet) know anything about the `transclude: 'element'` of `container`. It just starts to parse the template and collect directives.

> **Under the hood**
Any attribute value interpolation creates an implicit directive on-the-fly. That implicit directive executes at priority 100 and adds a watcher in its pre-link phase (that watches the interpolated expression and updates the attribute value as necessary).

The interpolation directive - having a higher priority than the `container`'s default 0 - will be have it's pre-linking function executed before the transclusion takes place and add a watcher (on the outer scope since no directive on the template requested a new scope).

### Interpolation on each clone

Once transclusion takes place - and since you request a new clone to be passed - the original template is cloned, so another attribute interpolation is present on the cloned elements. This adds another watcher on the outer scope.

### Explicit watcher added in post-linking function

Finally there is the watcher that you add manually in the post-linking function of `container`.

## Why do they stick around?

Now, when the element is removed, you are explicitly unregistering the 3rd watcher (see above). The other two (implicitly added) watchers stay behind though. They are bound to the outer scope, which is never destroyed, thus the watchers stay around forever.

> This is exactly why structural directives (i.e. `transclude: 'element' directives that are responsible for inserting/removing DOM fragments) always have high priorities and create child scopes.
The high priority ensures that no other directive executes first (including interpolation directives).
The child scope, which is destroyed every time they need to remove a fragment from the DOM, ensures that no watchers/listeners/etc will be left behind.

Also, as noted in the docs:

> **Best Practice:** if you intend to add and remove transcluded content manually in your directive [...], then you are also responsible for calling `$destroy` on the transclusion scope.

Of course, here you can't really destroy the scope, because you are passing the outer scope (which other component live in).

## How to get rid of the extra watchers?

It is hopefully clear by now how to get rid of the 2 "zombie" watchers.

1. Give your directive a priority higher than 100, to avoid the interpolation watcher.
2. Allow Angular to create a new scope for each of your transcluded clones, keep a reference to it and destroy it when "dropping" the element:

    ```js
    var  ..., my_scope;
    
    function drop() {
      ...
      my_scope && my_scope.$destroy();
      ...
    }

    ...

    $tfn(function(cloned, scope) {
      my_scope = scope;
      ...
    });

    ...
    ```

--
Here is a [demo][1] of the "fixed" version.

[1]: http://codepen.io/ExpertSystem/pen/kkrgrm

**Comment by djfd** [comment]
wow! amazing! Thank you very much for this great 'how-to'!

Yeah, I did read all that, except the 'under hood' part, missed it somehow. Now I know how to avoid a watcher in pre-link function, thanks! ))

But all that, imho, contra-intuitive. When I create my stuff I am solely responsible for a proper cleanup, thus I am expecting the same from the framework. And there is a lot of cases when directive not need to have a dedicated scope [which is costly enough, both in memory and cpu load terms, as I suppose], and I am trying to make it as lightweight as possible.

So the only question remains here: need angular be responsible for the destroying of second watcher (coming from $tfn) or not. I think there are two ways: right and easy ones. Right [and hard] way is you remove such watchers on element removal (remove, not detach), easy way is to provide customer with some cleanup callback so I can flush the stuff properly ))

Thanks

**Comment by djfd** [comment]
back to the documentation )) such things need to be described, and need to be in bold. I mean that currently we have to supply a scope otherwise there will be zombie watchers after directive element removal, that inherit parent scope, instead of using fresh dedicated one.

**Comment by djfd** [comment]
Well, after a few thinking.

Compiler itself does not know nothing about directives, it just compiles. It is all  right.

But linking process does know about transclusion mode. So, IMHO, the binding process need to be as lazy as possible, and make all these bindings only upon actual call of transclusion function (for 'element' and 'true' mode), and for contents-only transclusion that part binded directly to a top level need to be done by priority (current behaviuor). That seems for me most right way.

**Comment by gkalpak** [comment]
> Need angular be responsible for the destroying of second watcher (coming from `$tfn`) or not? I think there are two ways: right and easy ones. Right [and hard] way is you remove such watchers on element removal (remove, not detach), easy way is to provide customer with some cleanup callback so I can flush the stuff properly ))

Providing a clean-up callback is an interesting idea, but I am afraid not possible with the current implementation. Linking is a sort of "distributed" operation: Each directive is passed the scope and it does its work, so it is not possible for the framework to know what is going on in a linking function that might need to be clean up when the element is removed.
The only thing that is possible is for the directive creator to hook into the appropriate event (e.g. `$scope.$on('$destroy')` or `$element.on('$destroy')` etc) and do the necessry clean-up. This mechanism is already available and this is exactly what Angular is doing with the built-in directives.

It is also not possible for the frame work to know _when_ is an appropriate time to do any clean-up (assuming it could automatically infer the necessary operations). 

> Such things need to be described, and need to be in bold.

Like I have said before, these are very advanced Angular concepts and I will be the first one to admit that the documentation does not cover everything. On the other hand, going into all the details would be too overwhelming for beginners/intermediate users (which I suppose is the majority of the docs users).
Maybe it is a good idea to have a dedicated "Advanced Concepts" section in the Developer Guide or even an "Advanced Transclusion Concepts" section specifically.

PRs are welcome :smile: 

> I mean that currently we have to supply a scope otherwise there will be zombie watchers after directive element removal, that inherit parent scope, instead of using fresh dedicated one.

The only reason there are zombie watchers is because you are setting them up on the outer/parent scope (which outlives the linked template). Again, that is why built-in structural directives always supply a new scope that lives and dies with the linked template and why your should do too.

> Compiler itself does not know nothing about directives, it just compiles. It is all right.
But linking process does know about transclusion mode. So, IMHO, the binding process need to be as lazy as possible, and make all these bindings only upon actual call of transclusion function (for 'element' and 'true' mode), and for contents-only transclusion that part binded directly to a top level need to be done by priority (current behaviuor). That seems for me most right way.

I don't agree. If I understand correctly, you are suggesting that `transclusion`should somehow assume a priority role and suppress other directives from executing (and possibly resulting in bindings). That is not correct. `transclusion` is just a feature of a directive and as every other feature it needs to obey to the same rules (including priority).
The side effect (i.e. the extra binding) of a directive running before your transclusion directive by virtue of priority is undesirable for you in this case, but can be a perfectly legitimate usecase under other circumstances.

**Comment by djfd** [comment]
well, all that said makes sense, but...

e.g.
> so it is not possible for the framework to know what is going on in a linking function that might need to be clean up when the element is removed.

> It is also not possible for the frame work to know when is an appropriate time to do any clean-up (assuming it could automatically infer the necessary operations). 

As ic, the key is DOM node, it is very primary thing, primordial one. Scopes, bindings etc are secondary. So right time it is node removal, and right things to do is just undo that framework did upon node creation. If you created a scope, then drop it, if you add a bindings then unbind them. Exactly this is happening now for a directives where scope is provided by angular, it is destroyed by angular. so why situation is different for a bindings?

The rest is up to directive creator. just place that node into undo queue (to let a few time for a directive to complete properly), then clean up. Directives nodes creation can be easily tracked in transclude function. So nothing prevents to add on-destroy for it. [memory impact ? I do not know] 

That I disagreed with some things does not mean that I dislike your great framework, rather the situation is opposite, I do like it so much that take my weak efforts to make it better )) Good job, guys ))

**Comment by ThomasBurleson** [comment]
Please post further conversations in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)
