### ISSUE TITLE
Not able to test error handling (only errors thrown not rejected) while using $q service

### ISSUE THREAD

**Issue by sultanahamer** [angular/angular.js#15183]
**What is the current behavior?**
Throwing an error from a then block is being caught in catch block but we are not able to unit test the same. trying to run scope.$apply from a window.setTimeout is also saying that its running in a digest cycle.

Here is a plunker of the same:
https://plnkr.co/edit/hY15QxVNHOp1Fa602nPY?p=preview

**What is the expected behavior?**
we should be able to test catch block

**What is the motivation / use case for changing the behavior?**
we should be able to test catch block

Tested with angular version 1.5.8 and also the latest snapshot. Did not try with previous versions.

**Comment by gkalpak** [comment]
There are several different parts in play, so here is a break-down:

1. When an error is thrown inside a `.then()` callback, it is coverted to a rejection (as per the Promises A+ spec).
2. In addition to the above, the error is passed to the `$exceptionHandler` service (because it could be a programming error).
3. By default, the `$exceptionHandler` will log a warning to the console, but the flow of the program will continue normally.
4. `ngMocks` overwrites the default behavior of `$exceptionHandler` and makes it re-throw the error, because this usually indicates an unexpected situation or error that should be handled in the code (so we want the test to fail).

There are several ways to test this. Here is one:

1. Since promises are asynchronous by definition, you need to write an asynchronous Jasmine test (i.e. use the `done` callback passed to your spec to notify Jasmine that your test has been completed - see demo below).
2. Since you are deliberately throwing the error (i.e. it is not an accidental behavior or programming error), configure the mock `$exceptionHandler` to just log errors, not re-throw them (see [the docs][1] for more info).
3. Assert your expectations asynchronously (e.g. in the `.catch()` or a subsequent `.then()` callback) - see demo below.

[Demo below][2] :smiley:

--
While passing the thrown error to the `$exceptionHandler` (in addition to rejecting the promise) is not against the Promises A+ spec, it has turned out to be confusing in many cases, especially since no other promise library does it. Thus it will likely to be removed in 1.6.x.
(What this means is that in 1.6.x onwards, you will be able to test errors thrown inside promises the same way as you would test "plain old" rejections.)

[1]: https://docs.angularjs.org/api/ngMock/provider/$exceptionHandlerProvider
[2]: https://plnkr.co/edit/80MverEcOKLUN6qlTIgW?p=preview
