### ISSUE TITLE
ng-if breaks attributes sharing among a directives

### ISSUE THREAD

**Issue by djfd** [angular/angular.js#15204]
**Actual Behavior**:
 -  `What is the issue? *` ```ng-if``` directive somehow breaks attributes sharing chain
 -  `What is the expected behavior?` as per [$compile manual](https://docs.angularjs.org/api/ng/service/$compile#attributes) it is expected that there will be attributes sharing among all a directives tied to the same node

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` [here](http://codepen.io/djFD/pen/PGJoaO)
 -  `Details:` There are 2 directives, first one is to inject attribute, it works with a priority of 601 (just above ng-if), and second directive is to accept that injected attribute (at regular priority). Without ng-if all works as expected, but with ng-if added to a directive sharing chain gets broken and second directive could not get injected attribute anymore

**Angular Versions**: *
 -  `Angular Version:` 1.5.7

**Additional Information**:
 -  `Browser Type: *` Firefox, Chromium
 -  `Browser Version: *` 49.0, 52.0.2743.116
 -  `OS: *` Ubuntu 16.04 (64-bit)
 -  `Stack Traces:` --

**Comment by gkalpak** [comment]
This happens exactly because your directive is running with a priority higher than `ngIf`. `ngIf` is a "structural directive"&trade;; here is an (oversimplified) description of what is going on under the hood:

1. Directives with a priority higher than `ngIf` get compiled as usual (sharing the same Attributes object as usual too).
2. When `ngIf`'s turn comes, it considers the element (in its current form) as a template, which will be cloned, compiled (only for directives with a priority lower that `ngIf`) and inserted into the DOM when needed.

So, directives with a priority higher than `ngIf` are useful for affecting/modifying the original element, _before_ `ngIf` gets to work - they are essentially non-existent for the cloned elements inserted into the DOM by `ngIf`). The directives with a priority lower than `ngIf` will be present on the clones inserted into the DOM by `ngIf` and are suitable for interacting with other directives (e.g. by a shared Attributes object).

--
In your case, it seems you need a directive with a priority lower than 600. Note that if you need to interact with both the original element _and_ the clones, you can specify two directives with the same name, but different priorities - one higher than 600 and one lower than 600 - and they will be applied at appropriate times.

Closing, since everything is working as expected.
