### ISSUE TITLE
Make urlResolve function public

### ISSUE THREAD

**Issue by clemgrim** [angular/angular.js#15200]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
`urlResolve` function is not in the angular public API, and we need to create our own

**What is the expected behavior?**
expose `urlResolve` function via a service or factory, or just add it to angular public API (in `publishExternalAPI` function)

**What is the motivation / use case for changing the behavior?**
We don't have to rewrite this useful function, it's a lightweight change

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
1.5.8

**Comment by gkalpak** [comment]
`urlResolve` is used in several places and is involved in critical tasks, so making it an overwritable service isn't a good idea imo (unless we can find a strong usecase for it).

And as discussed several times, exposing internal utilities as public isn't a good option either. Having a private utility means that:

1. We can only support (or optimise for) the usecases that are necessary, which in turn leads to more lightweight and maintainable implementations.
2. We are able to break the API without affecting the end users, which gives us the flexibility to fix bugs and add features more easily and without breaking backwards compatibility.

Especially (1) is something people tend to ignore, until they run into a corner case that is not supported and consider it a bug in our implementation (while we never intended to support that usecase).

--
So, while I understand it would be useful for some people, making it public would impose an unnecessary maintainance cost for minimal benefit (since most people would either not need it or need a more powerful/complete implementation).

Using a specialized, 3rd-party utility library (or rolling your own helper) is the recommended way forward.

<sub>We could revisit this if a complelling usecase comes up, of course.</sub>
