### ISSUE TITLE
orderBy is not locale sensitive

### ISSUE THREAD

**Issue by rlintern** [angular/angular.js#15210]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
both

**What is the current behavior?**
The default comparator of the orderBy filter is not locale sensitive.  We would argue that in this global age it should be locale-sensitive by default and have the option to make it not locale sensitive if that is a requirement.  As an example, the current sorting when our app is running in Japanese is (incorrectly):
1) 基本
2) 文章
3) 標識

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**
As an example, the current sorting when our app is running in Japanese should be:
1) 基本
2) 標識
3) 文章

**What is the motivation / use case for changing the behavior?**
We would either like to see a change in the default comparator or have a documented mechanism to override it, so that all components in our complex web app (**some 3rd-party**) use the same locale-aware sorting algorithm when using the "orderBy" filter.  This is a must for our fully globalized enterprise software.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
1.5.x

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
How about sorting strings as follows, by default:
try {
 return s1.toLocaleLowerCase().localeCompare(s2.toLocaleLowerCase(), $local.id);
} catch (err) {
 return s1.toLocaleLowerCase().localeCompare(s2.toLocaleLowerCase());
}
This would utilize the newer browsers'  ECMAScript Internationalization API to sort in a locale sensitive way.   See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#See_also .   This new standard is supported in all the latest browsers. See http://caniuse.com/#feat=internationalization

**Comment by gkalpak** [comment]
The problem with using locale-sensitive comparison by default is that (a) it is not available in all supported browsers (e.g. Safari 9) and (b) it is more expensive (we don't want everyone to pay the extra cost if only few people will benefit).

In order to support this usecase, we have recently-ish added the ability to use a custom comparator function, so people can define their own locale-sensitive or whatever comparators. This is documented in detail in the [orderBy API docs][1] and there is also a simple example using locale-sensitive comparison for strings [there][2].

Since you obviously don't want to have to specify the custom comparator every time, you can either create a wrapper filter (e.g. `lsOrderBy` - as in "locale-sensitive order by") or even overwrite the built-in `orderBy` filter to do locale-sensitive comparisons by default:

```js
// Create your own, locale-sensitive wrapper filter
.filter('lsOrderBy', function lsOrderByFactory(orderByFilter) {
  return lsOrderByFilter;

  // Helpers
  function lsComparator(v1, v2) {
    // Compare in a locale-sensistive way
    // ...
  }

  function lsOrderByFilter(input, expression, reverse) {
    return orderByFilter(input, expression, reverse, lsComparator);
  }
})

// OR

// Overwrite `orderBy` itself
.decorator('orderByFilter', function decorateOrderByFilter($delegate) {
  return decoratedOrderByFilter;

  // Helpers
  function lsComparator(v1, v2) {
    // Compare in a locale-sensitive way
    // ...
  }

  function decoratedOrderByFilter(input, expression, reverse, comparator) {
    return $delegate(input, expression, reverse, comparator || lsComparator);
  }
})

[1]: https://docs.angularjs.org/api/ng/filter/orderBy
[2]: https://docs.angularjs.org/api/ng/filter/orderBy#using-a-custom-comparator
