### ISSUE TITLE
$controller called in finally statement doesn't log errors

### ISSUE THREAD

**Issue by aartek** [angular/angular.js#15241]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
errors comes from controller created with `$controller` are not logged into console when `$controller` is called in promise's `finally` statement.

**Steps to reproduce**
Call `$controller` with not existing dependency, or something wrong in code (i.e null pointer), in promise's `finally` statement. Errors will not be logged in console.

Example (open developer console):
http://plnkr.co/edit/ud0yCCC8IRM3heW7a2Ln?p=preview
In this example two errors should be logged, but there is only one, which comes from the first promise with `then` statement. `$controller` called in `finally` does not show any errors.

**What is the expected behavior?**
`$controller` called in `finally` should log errors.

**Motivation**
I use `$controller` to create controllers dynamically, with given name, and I inject there some dependencies (by `locals` argument). It's really hard to debug these controllers, when errors are not visible in console. 

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
I think it's long a time issue but for sure it doesn't work on 1.5.x in Chrome.

**Comment by gkalpak** [comment]
So, here is what happens:

When  an error is thrown inside of a promise's handler, then it is converted to a rejection (according to the Promises/A+ spec, which `$q` is compliant with). Since you don't have any rejection handlers on your promises, nothing should happen...
...Except that up until 1.5.x, when an error is thrown inside a promise - in addition to converting it to a rejection - we also pass it to the `$exceptionHandler` (which by defaults logs it to the console)...
...Except that we seem to break that "convention" for `finally` blocks (possibly just an omission).

Not that from 1.6.x onwards, thrown errors will not be passed to the `$exceptionHandler` (as it has turned out to be confusing/undesirable), but unhandled rejections will be reported as errors.

--
@lgalfaso, do you happen to know if not calling `$exceptionHandler` in `finally` was intentional or just an oversight?

**Comment by Narretz** [comment]
Unless I'm missing something, this works as expected in 1.6.1
