### ISSUE TITLE
$postLink looks has a weird linking order on its children

### ISSUE THREAD

**Issue by abruzzihraig** [angular/angular.js#15240]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
I suppose it is a bug.

**What is the current behavior?**
If any child element has a directive such as 'ng-if', it won't be linked to DOM when executing the lifecycle method '$postLink'. If I want to get the child node, I have to get it on next tick.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
Pls look at the demo with console: http://jsbin.com/milapaqove/edit?html,js,output

**What is the expected behavior?**
I'm not sure if it is actually a bug. But I met a similar problem and I think there should be a way to get child nodes even if they have any other directives on themselves.

**What is the motivation / use case for changing the behavior?**
It seems there are many use cases for the behavior. 
For example, If I want to control whether a child node is visible by a binding property, and I also want to get its DOM properties(width, height, etc) at the mean time. There is no hook method for me to handle the situation. I think it should be $postLink, but we cannot get such child node within $postLink.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Angular: v1.5.8
OS: MacOS
Browser: Chrome 53
Not sure if it worked in previous versions.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
If it is an expected behavior, pls tell me how should I do in those situations I mentioned above.
Thanks!

**Comment by gkalpak** [comment]
I am afraid this expected behavior/known issue. The post digest phase is guaranteed to run after the child-directives' post-digest for _synchronous_ child-directives only. E.g. even directives with a `templateUrl` are considered asynchronous and a parent directive will not wait for them to compile/link before entering its post-link phase.

Similarly, since `ngIf` will evaluate its expression (and possibly load its children) asynchronously, you can't access the `ngIf` content synchronously from a parent directive.

--
It is a known limitation of Angular 1.x that there is not lifecycle hook/phase related to compiling/linking asynchronous children or generally updating the contents of a DOM subtree. If your directive relies on the presense/absence of child directives, you currently have to manually wire that up.

From your description it sounds like checking for the elements on the next tick might be enough. For more complicated cases, or when you want to notify a parent whenever adding/removing a child element, you can either use scope events or let the child directives `require` a parent and register/unregister themselves.

**Comment by abruzzihraig** [comment]
@gkalpak Thanks so much for your detailed explanation! It really helps me out.
