### ISSUE TITLE
Angular ng repeat with filter issue.

### ISSUE THREAD

**Issue by gaojianzhuang** [angular/angular.js#15254]
This is the jsfiddle demo:
https://jsfiddle.net/gaojianzhuang/grr2rL8L/ 

When the page first loaded, the directive trigger is ok. But when we input a filter query just like "1", the directive not trigger, then we remove the query filter, the directive trigger again.

How to make the directive trigger every time when the filter result change ?
Thx.

**Comment by jbedard** [comment]
You're only outputting the trigger when `$scope.$last`. It seems to be working under that condition just fine.

If you want to detect when the filter changes use `ng-change` on the filter input.

**Comment by gkalpak** [comment]
@jbedard is right. Closing since there is nothing actionable here.

BTW, for general support question such as this, it is better to use one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by gaojianzhuang** [comment]
@jbedard Actually, I will use a jquery plugin after the ng repeat dom rendered. Because of the angular js does not have the event for listening the dom render. And now the directive not be detected when do the filter.
And the element dom updated, but the directive not execute by my expected, this will cause the jquery plugin error. If we detect the filter change, the jquery plugin still will not expected.
Thx.
This is the updated jsfiddle demo: https://jsfiddle.net/gaojianzhuang/grr2rL8L/
