### ISSUE TITLE
#! Hashbang is being added in the 1.5.9 version.

### ISSUE THREAD

**Issue by Mmatiasn** [angular/angular.js#15255]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Angular 1.5.9 is adding #! to my url
http://localhost/Trips/All**#!**/#mycorrecthash/

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
You have to create an ng-route to replicate this behavior.

**What is the expected behavior?**
Angular should not add hashbang to a controller url
expected
http://localhost/Trips/All/
when using ng-route 
http://localhost:40150/Trips/All/**#**mycorrecthash

**What is the motivation / use case for changing the behavior?**
My application I'm working on broke and bower is not letting me get version 1.5.8

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
1.5.9 angular
used with 1.5.8 ngroute

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I'm a student and might be posting in the wrong section. If so please don't hesitate to delete this.

**Comment by gkalpak** [comment]
1.5.9 has not been released yet. You are probably using the "nightly" builds tagged as `v1.5.9-build.XYZ`, which will eventually become 1.6.0 (despite what the current tags imply).

Indeed in 1.6.0 the default hashbang prefix will be `'!'`. On the 1.5.x there will be no breaking change; the hashbang prefix will remain the empty string. (The latest 1.5.x version is 1.5.8, so you this is what you should be using.)

Closing since everything works as expected.
