### ISSUE TITLE
multi slot transcluded elements are disconnected from parent scope

### ISSUE THREAD

**Issue by arkarkark** [angular/angular.js#15258]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If you have a directive that uses multi slot transclusion. the contents of each slot can see all the variables in the scope containing the multi-transcluding directive, but modifying values on the scope inside a transcluded slot is not reflected outside of the slot.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

* go here https://jsfiddle.net/arky/tqxyfncr/
* click the first button (everything changes!)
* click the second button (only that slot's value changes

here it is working as expected with a single transcluded element
https://jsfiddle.net/arky/7uLxjt3w/

**What is the expected behavior?**

modifying the variable inside the slot should update it everywhere.

**What is the motivation / use case for changing the behavior?**

each transcluded section is supposed to exectute in the context it was originally in, this seems to break that.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

I tried all angular 1.5.x up to 1.5.8

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
This works as expected and is related to how prototypal inheritance works in JS (since Angular scopes rely on it). It is explained in more details [here][1].

--
Keeping in mind that transcluded content gets a new scope that prototypally inherits from the parent scope, the scope hierarchy tree in your exampe looks like this:

```
scope1 (<container>)
|___ scope2 (<one>)
|___ scope3 (<two>)
```

When there is no value set for `scope2.var`/`scope3.var`, then they prototypally inherit `scope1.var` from the container. Once you set values for `scope2.var`/`scope3.var`, they shadow the value from container in their contexts.

As explained in the wiki article mentioned above, this is not Angular-related; it is how JavaScript works.
You can overcome this issue, by referencing an object (e.g. `var.value` instead of `var`).

<sub>The exact same happens in the `transclude: true` case (i.e. single transcluded element). Your second plnkr is incorrect, because you forgot to use the `<multi>` element; thus there is no transclusion taking place. Fixing that will restore the expected behavior.</sub>

[1]: https://github.com/angular/angular.js/wiki/Understanding-Scopes

**Comment by arkarkark** [comment]
Apologies, thanks for the explanation. I'm embarrassed my second example not working!
fixed it in https://jsfiddle.net/arky/7uLxjt3w/2/ for completeness.

Looks like I'll be binding things to the controller to avoid this (the controller will be my object in your example).
