### ISSUE TITLE
Ng-Disabled wont prevent Ng-click if it's not a button

### ISSUE THREAD

**Issue by camjocotem** [angular/angular.js#15260]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently ng-disabled only affects ng-clicks on inputs and buttons

**Expected behavior**

It would be nice if this could apply to other elements regardless of if it's a button or not

**Minimal reproduction of the problem with instructions**

I have personally used ng-click on an 'a' tag while also including ng-disabled,
an example of this is [here](http://plnkr.co/edit/BMbj71giAoUKQ6CHePRl?p=preview)

**What is the motivation / use case for changing the behavior?**

Received custom designed buttons using 'a' tags in the design.

**Please tell us about your environment:**

OS: Windows 7,
IDE: Brackets,

* **Angular version:** Angular 1.5.5

* **Browser:** All

* **Language:** All

**Comment by gkalpak** [comment]
As mentioned in the docs:

> This directive sets the disabled attribute on the element if the expression inside `ngDisabled` evaluates to truthy. [...] A special directive is necessary because we cannot use interpolation inside the disabled attribute."

This is exactly what `ngDisabled` (and similar directives) are designed to do. Setting the `disabled` attribute. The semantics of having the `disabled` attribute set are handled by the browser (e.g. not alloing clicks on disabled buttons). Angular shouldn't interfer with that.

This is also one of the reasons why you should strive to use native elements whenever possible.

--
BTW, if you really want to, you could write your own directive that catches `click` events and stops their propagation if the expression is falsy. 

Closing since this is not something that Angular should do.

**Comment by camjocotem** [comment]
Fair point, thanks for your time :)
