### ISSUE TITLE
null vs undefined in validation breaks some APIs

### ISSUE THREAD

**Issue by mprobst** [angular/angular.js#15390]
I have an API (a JavaScript side representation of protocol buffers), that I'd like to data-bind into a form value:

```html
<input ng-model="proto.property" required>
```

`proto.property` enforces that it can only ever be `null` - it converts any `undefined` values into `null` under the hood. When validation fails on the `ngModel`, Angular sets `proto.property` to `undefined`, which gets converted to `null`. So far so good. However because the value changes `null !== undefined`, Angular then perceives this as a model change and updates the `<input>` field again to an empty value.

The effect is that it's effectively impossible to bind a value that cannot be `undefined` (but just `null`) using Angular.

I wonder if this is something we could change, e.g. by having `ngModel` treat `null` as the same as `undefined` when updating the UI/formatting a value? I'm not sure if this would be breaking backwards compatibility, it seems rather unlikely that somebody would need to differentiate between `null` and `undefined` in this way?

I cannot easily change the underlying API, and having each use site introduce an indirection seems rather tedious.

**Comment by gkalpak** [comment]
> I wonder if this is something we could change, e.g. by having `ngModel` treat `null` as the same as `undefined` when updating the UI/formatting a value? I'm not sure if this would be breaking backwards compatibility

I am afraid it _will_ break backwards compatibility, because `null` is a valid value for indicating "emptiness". 😞
For example, imagine the following scenario:

1. User enter some invalid value(`view: 'some invalid value', model: undefined`).
2. User decides they want to start over and click the "Clear form" button, which the developer has implemented to set all model values to `null`.
3. Expected result: `view: '', model: null`

If we were to treat `undefined` the same as `null`, we wouldn't have detected the change and the form fields would not have been cleared (even if the model values would have changed to `null`).

**Comment by petebacondarwin** [comment]
@mprobst - Could you work around this using a bit of `ng-model-options="{ allowInvalid: true }"`?
This would mean that even if the `required` validator fails then the `ngModel` would not change the value of the model.

**Comment by mprobst** [comment]
@gkalpak @petebacondarwin thanks for the feedback.

I think I have a workaround that essentially stores a `nullMeansUndefined` bit in another place, so that Angular sees `undefined` coming out of the accessor on the property. It has some issues (e.g. cannot reset values by setting them to `null` because there is no more value transition from `undefined` to `null`), but I think it'll do.
