### ISSUE TITLE
Angular 1.5.8 component works different with typescript (ecma6) and (ecma5) configs

### ISSUE THREAD

**Issue by Alikhll** [angular/angular.js#15398]
I'm using angularjs 1.5.8 with TypeScript 2.0.6. Consider following tsconfig.json and angular component:
```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5"
  }
}
```
and component:
```
var app = angular.module('App', []);
class testComponent {
    public message: string = "worked!";
}
app.component('ctrl', {
    bindings: {
        message: '<'
    },
    template: '<div>Hello {{vm.message}}</div>',
    controller: testComponent,
    controllerAs: "vm"
});
```
It's working fine, until I change target to "es6", and it doesn't work as expected and I achieve two different results without changing my codes. Within es6 the "message" property will be null.

The following code works with both configs:
```
app.component('ctrl', {
    bindings: {
        message: '<'
    },
    template: '<div>Hello {{vm.message}}</div>',
    controller: function () {
        this.message = 'test';
    },
    controllerAs: "vm"
});
```
What's going wrong when I use es6 and class component?

**Comment by gkalpak** [comment]
This happens due to how pre-assigning bindings works with classes vs constructor functions.

In a nutshell, when instantiating the directive controller using a constructor function, Angular used to pre-assign the directive bindings on the controller instance, before calling the constructor (magic!). The trick that Angular uses to achieve that does not work with classes, so the bindings are applied after invoking the class constructor.

So, with `target: 'es5'` (i.e. constructor function):

1. Create controller instance.
2. Assign bindings on the instance (`ctrl.message = null`).
3. Invoke the constructor, which overwrites the property, setting `this.message = 'test'`.

With `target: 'es6'` (i.e. class):

1. Invoke the constructor, which sets `this.message = 'test'`.
2. Assign bindings on the instance, which overwrites the current value of the `message` property.

--
Essentially, your code is broken (and it just happens to work under certain circumstances). Then again, pre-assigning bindings is not great either. Luckily, since 1.5.9 (yet to be released) and 1.6.0-rc.0 you will be able to disabled this "feature" via [`$compileProvider#preAssignBindingsEnabled`][1] and it will be disabled by default in 1.6.0.

The proper way of dealing with this is to not touch bindings inside the controller constructor (regardless whether it is a class or a function), but inside the `$onInit()` lifecycle hook instead (when bindings are guarranteed to have been bound on the controller).

[1]: https://docs.angularjs.org/api/ng/provider/$compileProvider#preAssignBindingsEnabled
