### ISSUE TITLE
Changing `ng-required` calls `ng-change`

### ISSUE THREAD

**Issue by matiishyn** [angular/angular.js#15425]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
> plunker (https://plnkr.co/edit/zaHVJeK8hdxk2gaOL9Pf?p=preview) and video(http://recordit.co/eszvfdfC9S)

**step 1.** At the beginning changing `ng-required` doesn't call `ng-change` function
**step 2.** After making changes in `input` AND removing them (`input` is empty) `ng-required` DOES call `ng-change` function

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
plunker (https://plnkr.co/edit/zaHVJeK8hdxk2gaOL9Pf?p=preview) and video(http://recordit.co/eszvfdfC9S)

**What is the expected behavior?**
**step 2.** After making changes in `input` AND removing them (`input` is empty) `ng-required` SHOULD NOT call `ng-change` function. As it was at the beginning, and as it is when input has some value

**What is the motivation / use case for changing the behavior?**
Looks like unexpected behavior and it causes some serious problems on my project

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Angilar 1.5.8 / Windows 10

Please let me know if it's a bug or not. If not then why changing `ng-required` calls `ng-change` NOT always or even at all?

**Comment by Narretz** [comment]
This is expected behavior. This boils down to the fact that Angular sets the model on the scope to `undefined` when it is invalid. When you change ngRequired, the input is validated, and if found invalid, set to `undefined`.
In your example:
1) When input is empty at start, changing required from no to true doesn't call ngChange, because the model is already undefined
2) After sending and removing input, the input is invalid again, and the model is undefined, but the input value is actually empty string. When you change required to no, the actual input value is set to the model.

Does that make sense?

You can choose to always have the input value set to the model with `ng-model-options={allowInvalid: true}`.

Otherwise, it would be good to know how exactly this behavior interferes with your application logic.

**Comment by matiishyn** [comment]
thank you @Narretz for a great explanation.
I also got the same answer here: http://stackoverflow.com/questions/40781705/changing-ng-required-calls-ng-change

**Comment by gkalpak** [comment]
This is expected I'm afraid based on how validators work.

Initially (before interacting with the input), the model value is undefined. Also, when a validator fails (due to invalid input), it sets the model value to undefined. So, by switching between "required" and "not required" at that point, will not change the model value (it stays `undefined` either way).

Once you set some value and then deleted, the model value is set to an empty string. At this point, switching between undefined ("required") and the empty stirng ("not required"), does indeed constitute a change and the `ngChange` callback is called.

If you want the behavior to be consistent, you could initialize the model value to an empty string (or whatever makes sense per input type).

--
Closing, since this works as expected.

**Comment by matiishyn** [comment]
`ng-model-options={allowInvalid: true}` helped in my case
