### ISSUE TITLE
Form Validation Utilizing $touched Does Not Trigger All Validations or ng-click on Submit

### ISSUE THREAD

**Issue by nwenner** [angular/angular.js#15469]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When using the $touched/$untouched form properties, setting focus on an input field, and immediately clicking submit will only run the validation on the field that had focus, and the ng-click will not trigger for the submission.

This behavior can be seen on the Angular Form Validation page as well: https://docs.angularjs.org/guide/forms

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

https://plnkr.co/edit/QrSzsSztyrO1t4J0gMn1?p=preview

1) Load Plunker
2) Set focus to E-mail field
3) click Save
4) Note the validation will not show for Name, only E-mail validation will be shown
5) Note the ng-click will not have triggered (I added a console.log in the ng-click to demonstrate this)

**What is the expected behavior?**

When Save is clicked, ng-click is triggered, and both validations should be applied.

**What is the motivation / use case for changing the behavior?**

Our clients requested we do field level validations as focus changes on the input fields, as well as apply all validations when submit is clicked.  This bug prevents us from doing field level validations in the instance the user performs the above steps, it appears that they have to click the submit button twice.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

This behavior seems to exist in all recent versions of Angular (verified it exists from 1.3.20 up through 1.6.0-rc.1)

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
This is what actually happens:

1. As soon as the user presses down the mouse button on "Save", the email field loses focus and becomes `$touched`.
2. As it becomes `$touched`, the validation error is made visible (via `ngShow`).
3. Showing the message, pushes the rest of the form further down the page, so that the cursor is no longer over "Save" when the mouse button is released.
4. Since the mouse button was pressed but not released on "Save", the browser does not dispatch a `click` event (so naturally `ngClick` is not triggered either).

This is a common pitfall (and is actually not specific to Angular). You should make sure that any validation or other dynamic messages do not change the layout of your form in a way that moves buttons around. Typically, you would either change the messages' visibility via `visibility` or `opacity` (which retains their "physical" dimension) or position them absolutely inside a fixed height container.
