### ISSUE TITLE
Add support for new auxclick event (Chrome 55 onwards)

### ISSUE THREAD

**Issue by papadopa** [angular/angular.js#15476]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
ng-click doesn't handle non-left-click on Chrome 55 anymore (see https://www.chromestatus.com/feature/5663174342737920 and https://bugs.chromium.org/p/chromium/issues/detail?id=625847). We are now unable to handle middle-button click events for Chrome (never seemed to be possible on FF fwiw).

**What is the expected behavior?**
Add support for new auxclick event type (ngAuxClick?).

**What is the motivation / use case for changing the behavior?**
It will allow developers to support middle and/or right click events.

**Comment by Narretz** [comment]
First time I hear of this behavior. Is that non-standard?

**Comment by papadopa** [comment]
If you refer to ng-click working for middle-click, it seems this shouldn't be the case (it did work though in Chrome until 55):
https://www.w3.org/TR/uievents/#click
"The click event should only be fired for the primary pointer	button (i.e., when button value is 0, buttons value is 1). Secondary buttons (like the middle or right button on a standard mouse) MUST NOT fire click events."

**Comment by mgol** [comment]
We shouldn't support non-standard events as they may always change if only one browser implements it (just look at changes to Shadown DOM CSS selectors). On the other hand, it's quite easy to write an `ngAuxClick` directive if you need it, something like https://github.com/angular/angular.js/blob/13b7bf0/src/ng/directive/ngEventDirs.js#L48-L77 should work.

Since Firefox has never dispatched middle-clicks here, no Web-facing app should be affected by this change (this was most likely the Chrome team reasoning as well). Therefore, I don't think there's anything actionable for us to do wrt this issue.

**Comment by papadopa** [comment]
Yes, that makes total sense. I assumed middle-click fired on other browsers too and only tested it while I was reporting this.

I'll go ahead and close this then and address this on our end. Thanks!
