### ISSUE TITLE
Expose angular-mocks createControllerDecorator helper

### ISSUE THREAD

**Issue by tuhoojabotti** [angular/angular.js#15482]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
The function createControllerDecorator is private and inaccessible.

**What is the motivation / use case for changing the behavior?**
We rely heavily on promises and async code, angular-mocks tries to make testing async code easier by making it appear sync. However this leads to many difficulties when you have multiple chained promises, because you have to call flush between all of them.

For us the async code is not a problem because we use async/await with Babel so writing async tests is a breeze.

Our solution was to dump ngMock and use our own ['ng', 'ngMockE2E', 'customMock'] stack, where customMock module provides ngMock-providers, but excluding $httpBackend and others that mess with async code.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
This worked in at least 1.5.8
It broke in 1.6.0 due to changes to $compileProvider that required changes to the $ControllerDecorator

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Expose, for example, angular.mocks.$ControllerDecoratorFactory so I can call it myself.
Currently I have copied the function from angular-mocks.js to my test helper, but it would be nice to be able to reference it.

**Comment by gkalpak** [comment]
I am not very keen on exposing new APIs without a solid usecase. I am afraid I don't understand why you need something like this. Why do you need to replicate `$ControllerDecorator` yourself? Can you give an example of how you would use it and why it is necessary?

In addition, I have a few more questions (:innocent:):

> However this leads to many difficulties when you have multiple chained promises, because you have to call flush between all of them.

Can you elaborate on this?

> For us the async code is not a problem because we use async/await with Babel so writing async tests is a breeze.

OOC, does this allows you control the flow?

> This worked in at least 1.5.8
> It broke in 1.6.0 due to changes to $compileProvider that required changes to the $ControllerDecorator

What worked? How is it broken now?

**Comment by tuhoojabotti** [comment]
Sorry for not being clear. Maybe I'm using the library wrong.
**The problem (pre 1.6.0):**

If I have this kind of service method:

```javascript
async doStuff() {
  const result1 = await thirdPartyRestService1();
  const result2 = await thirdPartyRestService2(result1);
  return result2;
}
```

ngMock expects me to flush $httpBackend between the http calls:

```javascript
  it('should fetch stuff', async () => {
     $httpBackend.expectGET('http://third-party1.com/service');
     $httpBackend.expectGET('http://third-party2.com/service');
     const response = await myService.doStuff();
     $httpBackend.flush(); // Flush first request.
    expect(response).to.be.whatever();
   });
```

The problem is the second (or third, etc.) http call. I cannot call flush before the request has been made and if I try to call if after the code ever executes because it is waiting for me to call flush because of the await.

**My workaround:**

In my test helper I have:

```javascript
angular.module('myMock', [])
	.provider({
		$rootElement: angular.mock.$RootElementProvider,
		$componentController: angular.mock.$ComponentControllerProvider,
		// etc...
	})
	.config(['$provide', '$compileProvider', ($provide, $compileProvider) => {
		// $provide.decorator('$controller', createControllerDecorator($compileProvider));
	}]);
const MODULES = ['ng', 'ngMockE2E', 'myMock'];

export default testModule => {
	const injector = angular.injector([...MODULES, testModule]);
	return injector.get.bind(injector);
};
```

And I can use it to make tests simple:

```javascript
inject = testModule(APPLICATION_MODULE);
myService = inject('myService');
```

**The problem with 1.6.0:**

angular.mock.$ControllerDecorator used to be available directly, so I could just call: `.decorator('$controller', angular.mock.$ControllerDecorator)` on the myMock module. However with 1.6.0 angular-mocks uses an internal function called createControllerDecorator which configures the $ControllerDecorator.

I want to be able to use it without copy pasting angular code into my test helper.

**Better idea:**

Make the async flush behavior optional and allow me to write async tests with angular-mocks. I do not want to write all the mocks myself since angular-mocks work fine for the most part.

@gkalpak Now you see what I mean? If you have an idea how to write async tests with the angular-mocks as-is that would be fantastic, too. But I just couldn't get the flush model to work without huge amount of spaghetti code in my tests.

**Comment by petebacondarwin** [comment]
Isn't the problem here that `async` is not using the angular `$q` promise mechanism and so it is not hooking into the digest/flush lifecycle properly?

**Comment by gkalpak** [comment]
I think that's exactly the issue here. Which is a little unfortunate as more and more people start using async/await :(

<sub>We need Zones :grin:</sub>

---
Regarding the controllerDecorator issue, why don't you make `ngMock` a dependency of your `myMock` module and just overwrite the things you need to, instead of creating a totally independent module and then reuse several `ngMock` stuff?

**Comment by tuhoojabotti** [comment]
@gkalpak Hopefully we can hop to Angular 2 soon, so we don't have to deal with this long. I think the idea of using ngMock and overriding $httpBackend and $browser, which seem to be the things messing with timers and ajax, seems like a good workaround for now. The original solution was just the result of: "Gotta get this working after 2 days of banging my head to my keyboard."

Or have that configuration option for ngMock to disable the flush api and let stuff be async. Indeed it is a bit unfortunate that async/await does not work out of the box. We have to add some triggers to make digest work in some cases, but overall the code ends up much cleaner.

**Comment by gkalpak** [comment]
> I think the idea of using `ngMock` and overriding `$httpBackend` and `$browser` [...] seems like a good workaround for now.

👍 
Considering that this should work for your usecase, I'd say we should avoid exposing a new public API (such as `createControllerDecorator()`), because that makes it more difficult to change things in the future.

##

> Or have that configuration option for ngMock to disable the flush api and let stuff be async.

That would require a big change in some of ngMock's internals and frankly making things asynchronous seems outside of the scope of ngMock atm.

In the future we would like to offer better support for `async/await` out-of-the-box, both during testing and in application code (e.g. better integration with the digest cycle). So this is on our radar.

Unfortunately we are not there yet. Native implementations are still in flux (and likely to be affected by other proposals such as [zones][1]) and implementation relying on transpiling (or even polyfilling) may work completely differently. So, we decided it is best to wait for these to stabilize a bit more.

But of course, this is a different issue altogether :smiley:

---
In any case, thx for bring this up. Since there is a way to work around your original issue, I am going to close this. We can further discuss `async`/`await` support on a different issue (when the time comes).

[1]: https://domenic.github.io/zones/
