### ISSUE TITLE
Angular 1.6.0 incorrectly redirects to hashbang

### ISSUE THREAD

**Issue by TitanNano** [angular/angular.js#15496]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Our App is not in HTML5 mode and after updating from 1.5.9 to 1.6.0 urls like `example.org/#/start` get redirected to `example.org/#!#%2Farticles`.

run.plnkr.co/DYwKq82dRIUcFzhZ/#/start

**What is the expected behavior?**
it should redirect from `example.org/#/start` to `example.org/#!/start`

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular?**
Affected: 1.6.0 +
Works with: 1.5.9 and earlier

**Comment by gkalpak** [comment]
This works as expected (and is due to a [documented breaking change][1]). Not sure why you think this should redirect. It didn't redirect before in similar situations.

Since `!` is now the default hashbang prefix, URLs that do not contain a `!` after the `#` are not recognized as "Angular URLs". As a result, the path is considered empty and the part after the `#` is considered the hash.

As mentioned in the migration guide. You should either change your URLs to contain the correct hashprefix (`!` by default) or (maybe temporarily) switch the hashprefix back to the empty string using `$locationProvider.hashPrefix('')`.

[1]: https://docs.angularjs.org/guide/migration#commit-aa077e8

**Comment by mistic100** [comment]
If, like me, you have applications opening other applications and everything cannot be migrated in one sprint, but you still wish do use the new standard, you can rewrite the hash at the very startup of the page (before loading AngularJS).

```js
        if (window.location.hash.indexOf('#/') === 0) {
            window.location.hash = '#!/' + window.location.hash.substr(2);
        }
```

This way, old links to a migrated application will still work.
