### ISSUE TITLE
ngLocale with wrong FIRSTDAYOFWEEK in arabic (AR)

### ISSUE THREAD

**Issue by evilaliv3** [angular/angular.js#15508]
FIRSTDAYOFWEEK of the week for arabic is Sunday (6) (that in arabic means literally first day of the week)

Currently the angular codebase declares it as Saturday (5)
https://github.com/angular/angular.js/blob/master/src/ngLocale/angular-locale_ar.js#L27

**Comment by gkalpak** [comment]
Angular.js uses the [Google Closure I18N library][1], to generate its own I18N files. If there is something wrong you should report it (or submit a patch) to the I18N project directly, instead of here.

Once it is fixed there, we can import the library to get the latest changes into Angular's i18n files.

[1]: https://github.com/google/closure-library/tree/master/closure/goog/i18n

[1]: https://github.com/google/closure-library/tree/master/closure/goog/i18n

**Comment by evilaliv3** [comment]
I see, thank you @gkalpak

**Comment by evilaliv3** [comment]
The upstream fix is now tracked by https://github.com/google/closure-library/issues/780 and https://github.com/google/closure-library/pull/781
