### ISSUE TITLE
$httpBackend.flush() - each 20th of equal tests fails

### ISSUE THREAD

**Issue by dkrupenya** [angular/angular.js#15564]
I have found a strange behavior while testing an application.
Working example you can find here: https://plnkr.co/edit/NqOS8YyKrmOuJFFQUyFs?p=preview
This is a simple test of $http.get(), see code below
```
 angular.module('myApp', []);
 describe('Lets repeat one test many times', function () {
    var $httpBackend, $http, result;

    beforeEach(module('myApp'));
    beforeEach(inject(function (_$http_, _$httpBackend_) {
        $http = _$http_;
        $httpBackend = _$httpBackend_;

        $httpBackend.expectGET('/api/a').respond('a');

        result = $http.get('/api/a').then(function (res) {
            return res.data;
        });

        $httpBackend.flush();
    }));

    afterEach(function () {
        /* $httpBackend.verifyNoOutstandingExpectation();
           $httpBackend.verifyNoOutstandingRequest(); */
    });
    /**** Repeat this test 100 times *****/
    it('All work and no play makes Jack a dull boy', function (done) {
        result.then(function (res) {
            expect(res).toEqual('a');
            done();
        });
        $httpBackend.flush();
    });
    /**********************************/
 });
```
One test pass, two tests pass, but if you repeat this test many times each 20th test will fail!
How is it possible?
I know how to fix this test to work well, but I considered that it is in principle impossibe situation when one test influence to another, so probably it is some kind of a bug.

**Comment by gkalpak** [comment]
The tests are actually broken, because you are calling `$httpBackend.flush()` twice per test (once in the `beforeEach()` block and once inside the `it()` block). Normally, every test would fail.

The reason they don't fail, is in some (unclear to me) way related to how Jasmine's `QueueRunner` [queues asynchronous tests][1] (i.e. when using `done`) and the number 20 comes from Jasmine's [`maximumSpecCallbackDepth`][2]. There is some relevant discussions [here][3] and [there][4].

##
**UPDATE:**
This was indeed a bug in Jasmine and has been fixed in jasmine/jasmine@17c89c6. Here is the [updated plnkr][5] that shows all tests failing with the latest Jasmine version (the fix will probably be included in Jasmine 2.5.3).

##
In order to fix the tests, you should remove one of the `$httpBackend.flush()` calls ([demo][6]).

Of cource, Angular's mocked `$httpBackend` service, means that you don't need to have asynchronous tests, so you don't need `done` at all ([another demo][7]).

##
Closing, since everything works as expected on the Angular side.

[1]: https://github.com/jasmine/jasmine/blob/141fd910f27eeecd27f66646efe00f7512649bd2/lib/jasmine-core/jasmine.js#L1887-L1916
[2]: https://github.com/jasmine/jasmine/blob/141fd910f27eeecd27f66646efe00f7512649bd2/lib/jasmine-core/jasmine.js#L651
[3]: https://github.com/jasmine/jasmine/issues/945
[4]: https://github.com/jasmine/jasmine/issues/366#issuecomment-27530150
[5]: https://plnkr.co/edit/d7oyZtFRuwQS9Q3vnLvz?p=preview
[6]: https://codepen.io/ExpertSystem/pen/MJgeZj?editors=0010
[7]: https://codepen.io/ExpertSystem/pen/vgBKvQ?editors=0010
