### ISSUE TITLE
Add Factory / Dependency Injection to `angular.Module.prototype.component`

### ISSUE THREAD

**Issue by daprahamian** [angular/angular.js#15583]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Currently, `angular.Module.prototype.component` takes two arguments:
1. Name of the component
2. A [Directive Definition Object](https://docs.angularjs.org/api/ng/service/$compile#directive-definition-object)

This limits dependency injection to within the `controller` attribute. For regular components, this is fine. However, it makes it very roundabout to implement class inheritance using ES6 classes,

If we could pass a factory function instead of a DDO (like with a non-component directive), this would be a lot easier:

```js
angular.module('myModule').factory('myBaseClassFactory', function() {
  return class MyBaseClass {
    ...
  };
}).component('myComponent', ['myBaseClassFactory', function(MyBaseClass) {
  return {
    ...
    controller: class MySubClass extends MyBaseClass {
    },
    ...
  };
}]);
```

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
>= 1.5.0

**Comment by gkalpak** [comment]
Usually, such type of inheritance doesn't have to go through Angular's DI (what would be the benefit?). So, you can directly extend the base class. If you need to have it DI'ed (for whatever reason), you can always use the goog ol' `.directive()` method. Since `.component()` is just a wrapper around `.directive()` I don't think overloading it with a function version makes much sense (especially since all usecases are already possible via other means).

Considering all that (plus the fact that Angular 2+ works the same way), I am going to close this as  _won't fix_.
