### ISSUE TITLE
Self-closing ng-view tag is no longer parsed correctly

### ISSUE THREAD

**Issue by kveretennicov** [angular/angular.js#15642]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Document with `<ng-view />` followed by `<script type="text/ng-template" id="...">...</script>` is broken: the template is not registered in $templateCache, the app doesn't work. Note that this is a 1.5.x+ regression compared to 1.4.x.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
See https://plnkr.co/edit/2KgDRZ3dVvwLAHyK0scF?p=preview
Red text "Spam!" is not rendered unless `<ng-view />` is modified or an older version of angular is used.

**What is the expected behavior?**
`<ng-view />` to be equivalent to `<ng-view></ng-view>`, `<div ng-view></div>`, etc.
At the very least, a better diagnostics should be in place. The current error in the console is not exactly pointing to the root cause:
> Error: [$compile:tpload] Failed to load template (HTTP status: 404 Not Found)

**What is the motivation / use case for changing the behavior?**
Compatibility with existing 1.4.x applications. One example is [TodoMVC AngularJS Example](https://github.com/tastejs/todomvc/blob/3d3b8c3/examples/angularjs/index.html#L11).

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Browsers:
- Firefox: 50.1.0
- Chromium: Version 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit).

It works in 1.4.x and in 1.5.0-beta.0. It stops working in 1.5.0-beta.1 and up, including latest snapshot.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I didn't track down the exact commit that introduced this, but I suspect #12524.

Thank you.

**Comment by gkalpak** [comment]
The commit causing this must be 652b83e. The thing is that browsers do not treat "self-closing" custom tags the way you think they would. In their attempt to fix broken syntax, they treat...

```html
<ng-view />
<foo></foo>
<bar></bar>
```

...as...

```html
<ng-view>
  <foo></foo>
  <bar></bar>
</ng-view>
```

(Note that this is something that happens in the browser, before Angular gets access to the HTML.)

##
So, in your example, the HTML becomes:

```html
<ng-view>
  <script type="text/ng-template" id="...">...</script>
  <script src=".../angular.js"></script>
  <script src=".../angular-route.js"></script>
  <script src="script.js"></script>
</ng-view>
```

Before 652b83e, `ngView` would be compiled eagerly (which would result into compiling the `script[type="text/ng-template"]` element (thus adding the template to the `$templateCache`).
After 652b83e, `ngView` won't be compiled until after the template has been fetched. But because it is not compiled, there is no template in the `$templateCache` (remember that the browser has placed the `script` tag inside `ngView` itself).

As you can see, using `<ng-view />` will cause you much bigger problems that missing a template (i.e. all elements after `<ng-view />` (e.g. a static footer) will be "swallowed".

##
In any case, this is not something that Angular should try to fix (in fact it only worked with eager compilation by accident). Nor can it give a more descriptive error message, because it only sees what the browser wants it to see (it doesn't know what was there before).

Closing, since everything works as expected (afaict).

**Comment by kveretennicov** [comment]
Makes sense. Thank you for the detailed explanation.
