### ISSUE TITLE
any plans to run digest cycle in a web worker?

### ISSUE THREAD

**Issue by cynx** [angular/angular.js#15640]
*Feature Request / Road Map*

Any plans to include ability to run digest cycle in a web worker (in 1.x)? something like http://slides.com/bahmutov/run-digest-cycle-in-web-worker#/

**Comment by Narretz** [comment]
There are no plans, and such wide-ranging architecture changes are out of scope for AngularJS.

**Comment by gkalpak** [comment]
I agree with @Narretz.

Besides, just having the Scope `$digest` run in a web worker won't work, if your app doesn't run in the web worker too, because the type of data you can send over is limited. So, in order to get proper web worker support, we need to run the whole app on the web worker and just have the DOM-related parts of the framework live in a separate script that runs on the page (not the web worker) and is able to communicate with the web-worker bit. Considering how tightly AngularJS's `$compile` is coupled to the DOM, this would require a heavy refactoring of the internal logic. (Actually, this is already done. It's called Angular (2+) 😛)

That said, for AngularJS, it makes more sense to run specific, computationally heavy tasks on a web worker imo. AngularJS doesn't have to know anything about this - you can implement it independently.
