### ISSUE TITLE
not able to select multiple options on IE with ng-model

### ISSUE THREAD

**Issue by ak6777** [angular/angular.js#15675]
Reporting Bug: Not able select multiple options sequentially (shift+down/up arrow alone) when binded with ng-model on IE alone (tested versions IE edge, 10, 9)

Current behavior: Not allowing more than two options to be selected

JSFiddle sample code: http://jsfiddle.net/JB3Un/597/
https://plnkr.co/edit/?p=preview
This issue can be reproduced with the angular documentation sample as well for multi select.

Expected behavior: Should be able to select more than two options sequentially and should hold all the sequence for both shift+ up/down arrow

OS: windows 10
Browser: IE edge, 10, 9
AngularJS: 1.6.2

**Comment by Narretz** [comment]
hi, there are a few issues with your repro:
- The plnkr doesn't work 
- The fiddle is using Angular 1.1.1
- AngularJS 1.6.2 has not been released, current is 1.6.1

However, I see a problem in this plnkr: https://plnkr.co/edit/aDaSpU8axanaFszLNjpU?p=preview

When you make a selection with shift+click, AngularJS does not keep the first selected option if more than 2 options are selected. In a vanilla select, all options stay selected. Is this the bug you see?

This only happens in the snapshot, 1.6.1 is good. So it looks like it is caused by https://github.com/angular/angular.js/commit/89f3e3b0af74d6ea2f2741b4d6eced184e1a2b1a

**Comment by gkalpak** [comment]
I can reproduce OP's problem in 1.6.1 and even 1.5.x. Example steps:

1. Select an element by clicking.
2. Use Shift-DOWN/UP multiple times to select more elements.

**Comment by Narretz** [comment]
Right. IE seems incapable of maintaining all but the last currently selected option when selecting more with shift+key or shift+click
E.g. if you have three selected then select one more, only the last of the previously selected will be kept
