### ISSUE TITLE
https://docs.angularjs.org/guide/directive https, copyright 2017, hr

### ISSUE THREAD

**Issue by NilsHolger** [angular/angular.js#15702]
please update plunker copyright http://angular.io/license to https for secure
please update https://angular.io/license Copyright (c) 2014-2016 Google, Inc. to 2017

i have observed these anomalies in angular 2 documentation also a couple of weeks ago.

also please ensure consistency, either < hr > or < hr / >, select one or the other and then stick to it. it confuses the readers.

apart from these minor details the documentation is a dream. :1st_place_medal: to all angular contributors.

**Comment by frederikprijck** [comment]
Actually, http://angular.io/license does get redirected to `https`, so I don't think it's a matter of insecurity. 
Updating the plunkr to explictly use `https` over `http` wouldn't hurt, I guess.

I do agree in consistently using the `hr` element, if feel free to create a PR. If you have no interest, I'm happy to work on the PR for you. (if @gkalpak / @Narretz / ... agree on resolving this that is)

Btw, #itsjustangular
> i have observed these anomalies in angular ~~2~~ documentation also a couple of weeks ago.

**Comment by Narretz** [comment]
Hi,
the actual license as found on angular.io/license must be changed in the  https://github.com/angular/angular repository. Please open an issue there.
The link to the license file can be changed here if someone wants to make the change: /docs/app/src/examples.js, but since it redirects to https, this is ok to me atm.
I see that @frederikprijck has already started to change  `<hr>`, so a PR isn't far away probably.

**Comment by frederikprijck** [comment]
@Narretz I can throw it in if you want. It only adresses the `hr` inconsistency tho.

**Comment by Narretz** [comment]
@frederikprijck Sure, go ahead!
