### ISSUE TITLE
$animate areAnimationsAllowed returns false negative if `$rootElement` is `html` tag

### ISSUE THREAD

**Issue by ilovett** [angular/angular.js#15738]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

queuing `$animate.leave` doesn't seem to wait for animations defined

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

define `ng-app` on your `html` tag or bootstrap on the document

**What is the expected behavior?**

animations are allow if inside the body

**What is the motivation / use case for changing the behavior?**

angular-material used in conjunction with an application which is bootstrapped on `html` tag or manually on the `document` object.  backdrop animations in particular do not work properly due to `$animate.leave` incorrectly thinking that animations are not allowed.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

1.5.11, 1.6.1 -- have not tried others

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

at this line: `      return allowAnimation && rootElementDetected && bodyElementDetected;`

```
allowAnimation === true
rootElementDetected === true
bodyElementDetected === false
```

`bodyElementDetected` should be `true`, even if the `$rootElement` is `html`

stack trace

```
areAnimationsAllowed (angular-animate.js:2840)
queueAnimation (angular-animate.js:2518)
push (angular-animate.js:2403)
leave (angular.js:5653)
options.hideBackdrop (angular-material.js:10324)
onRemove (angular-material.js:10075)
(anonymous) (angular-material.js:3904)
$Q (angular.js:16945)
hideElement (angular-material.js:3901)
(anonymous) (angular-material.js:3720)
handleCallback (angular.js:16815)
(anonymous) (angular.js:16628)
processQueue (angular.js:16648)
(anonymous) (angular.js:16692)
$eval (angular.js:17972)
$digest (angular.js:17786)
processQueue (angular-material.js:1724)
(anonymous) (angular.js:19916)
completeOutstandingRequest (angular.js:6111)
(anonymous) (angular.js:6390)
```

**Comment by gkalpak** [comment]
Not sure how this can be. If we have detected the root element and since the root element is the `<html>` (which is a parent of `<body>`), then the only case where `bodyElementDetected` can be false, is if you are trying to animate things outside `<body>` (which is not supported indeed).

Can you provide a demo of the problem (e.g. using CodePen, Plnkr etc).

**Comment by ilovett** [comment]
`ng-app` is defined on the `body`, backdrop animation is working
https://embed.plnkr.co/AsA8ydhifyVl9kfGZceo/

`ng-app` is deifned on `html`, backdrop animation NOT working
https://embed.plnkr.co/PLhfbWJUyvVpijfx5rlp/

**Comment by gkalpak** [comment]
This happens because `mdBackdrop` [pins itself][1] to the `$rootElement`, not taking into account that the `$rootElement` might be outside `<body>`. Pinning an element to a parent, is like saying to `$animate` that this is the element's parent, so it essentially sees `<md-backdrop>` as a direct child of `<html>` (i.e. a sibling to `<body>`) and does not run an animation, as expcted.

This is a bug in ngMaterial. Please, report it [over there][2].

[1]: https://github.com/angular/material/blob/25aeb0d5cf498e47fb01fcf2e6b562b2d77eb1cf/src/components/backdrop/backdrop.js#L32
[2]: https://github.com/angular/material

**Comment by gkalpak** [comment]
BTW, you can see a dirty POC [here][1]: Disabling `$animate.pin` brings back the animation.

[1]: https://plnkr.co/edit/k98cvN4Ww00jNANzX8Xe?p=preview

**Comment by ilovett** [comment]
Thank you very much for the explanation!
