### ISSUE TITLE
Wrong translation for month shortcut RO

### ISSUE THREAD

**Issue by kplogo** [angular/angular.js#15748]
In file 
angular-locale_ro-ro.js and 
angular-locale_ro-md.js

short version of November is "nov.", but Romanian name for November is "noiembrie", so a shortcut for this month should be rather "noi." than "nov." 

Regards 
kplogo

**Comment by Narretz** [comment]
Hi, AngularJS uses the Google Closure I18N library to generate its own I18N files (the ngLocale module). This means that any changes to these files would be lost the next time that we import the library. Since the Closure library i18n data is itself auto-generated from the data of the Common Locale Data Repository (CLDR) project, errors in the data should be reported there. See also the Closure guide to i18n changes.
