### ISSUE TITLE
Component height

### ISSUE THREAD

**Issue by Moataz-Hammous** [angular/angular.js#15760]
Component height is always zero even it contains children element

**Comment by Moataz-Hammous** [comment]
why closed ?

**Comment by Moataz-Hammous** [comment]
i see that there is issue in component as its restricted at element level only no attribute which cause the component element height equal zero. like the following:
`<my-component>
<div> any content </div>
</my-component>
`

**Comment by frederikprijck** [comment]
Did you try `display: block` on the element ?

**Comment by Moataz-Hammous** [comment]
yes

**Comment by Narretz** [comment]
Sorry, I wanted to close this with a message.
Basically, your issue description is so basic that it's impossible to say
what your issue actually is. Please don't ignore the issue template, but
try to fill it out completely. A demo of the problem is especially
important. That said, AngularJS is not a CSS framework so any CSS problems
are probably not AngularJS related.

2017-02-28 15:41 GMT+01:00 Moataz Hammous <notifications@github.com>:

**Comment by frederikprijck** [comment]
@Moataz-Hammous  Anyway, it's solved in the plunkr I added. It's a CSS issue, it doesn't have anything to do with AngularJS.

**Comment by Moataz-Hammous** [comment]
please view issue produced here
https://plnkr.co/edit/uPIp2NMnzx683J1vDs0g?p=preview

**Comment by frederikprijck** [comment]
@Moataz-Hammous The problem is due to the content of the component, not the component itself.

This works: https://plnkr.co/edit/hHGJw6rYvZBwZ0dxE0l5?p=preview
