### ISSUE TITLE
Angular.module support for functions as dependencies

### ISSUE THREAD

**Issue by augustobmoura** [angular/angular.js#15808]
It's a bad ideia to support functions as requires? Using functions instead of "string named components" we can move foward on using es2015 modules. With this we can just import a "angular module" factory as a dependency, and add it to the requirements array for a new module. For example:
``` .js
// Current form of module dependencies
angular.module('CoolComponents', []);
angular.module('app', [
  // You can't have static code analysis here, any typo needs to be catched at runtime
  'CoolComponents',
]);
const module = angular.module('app', []);
// Old issue, the app module is cleared here instead of being saved on the var



// Using factories references instead of strings we can manage all the
// dependencies with es2015 modules

/* cool-components.module.js */
export default angular.module('CoolComponents', []);

/* app.module.js */
import CoolComponents from './cool-components.module.js';

angular.module('CoolComponents', []);
// Even overriding the angular module `CoolComponents`, we still have a reference to
// the correct module

export default angular.module('app', [
  CoolComponents,
]);
```
We have plans for supporting es6 modules? It's difficult to implement this feature?

**Comment by gkalpak** [comment]
There have been some discussions, but nothing concrete yet.
In the mean time, most of what you want seems to be already possible and you can get better static code analysis by using the `name` property of modules:

```js
/* cool-components.module.js */
export default angular.module('CoolComponents', []);

/* app.module.js */
import CoolComponents from './cool-components.module.js';

angular.module('CoolComponents', []);
// Even overriding the angular module `CoolComponents`, we still have a reference to
// the correct module

export default angular.module('app', [
  CoolComponents.name,
]);
```

**Comment by mgol** [comment]
I was thinking of allowing something other than strings as module names to avoid collisions, e.g. symbols; see how this would work with a patched version of AngularJS: http://plnkr.co/edit/yfTTgO8BidbvpMdiSzsB?p=preview

However, I like your proposal even more as it seems more natural and in line with other tools to just import a module. This proposal would require a little more changes than the symbol one.

I wonder what to do with module names if this proposal was accepted, though. They seem kind of redundant and as long as we keep them there's always a question of what happens if someone imports a module in one place via its name, in another via the full module instance...

**Comment by mgol** [comment]
I guess we could still keep the `module names -> modules` map and in that case registering two modules with the same name would mean adding the module name to dependencies would always choose only one of them but you would still be able to depend on both if you used full module instances.

I'd be interested in prototyping that (unless you'd like to try, @augusto-moura).

**Comment by augusto-moura** [comment]
@gkalpak yeah, my suggestion would be just temporary (maybe not so temporary, dependending on the discussion about the appropriate solution). The definitive approach might be extinguishing the angular modules in favor of es modules. -some day-.

@mgol I didn't clearly understand your ideia. You are saying to change the behaviour of `angular.module('foo', [...deps])` with a already defined module, to not reset the module but instead just adding `deps` as dependencies to it?

**Comment by mgol** [comment]
@augusto-moura 

> You are saying to change the behaviour of angular.module('foo', [...deps]) with a already defined module, to not reset the module but instead just adding deps as dependencies to it?

No, nothing like that. I'm proposing that we should be able to put modules in the dependencies array instead of their names, i.e.:

```js
var module1 = angular.module('mod1', []);
var module2 = angular.module('mod2', []);
angular.module('app', [
    module1,
    module2,
]);
```
insead of the current:
```js
angular.module('mod1', []);
angular.module('mod2', []);
angular.module('app', [
    'mod1,
    'mod2,
]);
```
Doing it wisely would mean modules with the same name work correctly:
```js
var common1 = angular.module('common', []);
var common2 = angular.module('common', []);
angular.module('app1', [
    common1,
]);
angular.module('app2', [
    common2,
]);
```
This code should make the `app1` & `app2` modules depend on different `common` modules even though they share their names.
