### ISSUE TITLE
Compile out CSP eval code with define plugins

### ISSUE THREAD

**Issue by graingert** [angular/angular.js#15823]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
You have to use ngCsp, and the bundle is bigger than it needs to be.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**
use webpack define plugin (or UglifyJS or closure) to define a variable ANGULAR_CSP that enables or disables code paths that rely on an insecure or missing CSP.

**What is the motivation / use case for changing the behavior?**
I don't want to change all my templates, when I could configure it in one place in my build config.
I also want to strip out any code that even tries to use eval, because I won't need it.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
any code that uses CSP should do:
```
if (typeof ANGULAR_CSP !== 'undefined') {
    ...
}
```
so that optimizing compilers can wipe it out.

**Comment by graingert** [comment]
Another option is to provide an angular-csp.js CJS module.

**Comment by petebacondarwin** [comment]
I would like to see the actual difference in size from doing this before making a decision.
Moreover there are other switches that could trigger different modules to be generated.
So it could cause an explosion of complexity in our builds.

**Comment by graingert** [comment]
Probably avoid the angular-csp.js CJS module then. That way the builds flags would only be selected by module bundling angularjs users

**Comment by graingert** [comment]
Also I'm not super worried about the size of the bundle. It just makes it easier to review when `eval(.*)` doesn't appear in my final build

**Comment by gkalpak** [comment]
<sub>(FWIW, AngularJS does not use `eval()` anywhere :smiley:)</sub>

**Comment by graingert** [comment]
or new Function

**Comment by Narretz** [comment]
Can't you use an AST transformation (via babel plugin) that removes the csp condition, which would then allow to drop the dead code?

**Comment by graingert** [comment]
@Narretz that would break if someone renamed the csp function in a context sensitive way

**Comment by Narretz** [comment]
Not sure what you mean by "context sensitive way", but yes, any transformation is dependent on the correct naming. But you'd have to test the resulting code anyway.

**Comment by graingert** [comment]
@Narretz so something like `var someCsp = csp; someCsp();`

**Comment by Narretz** [comment]
Afaics there is only one condition in the parse.js file that handles the use of CSP. And like I said even if we provide a variable someone would have to test of the resulting code has csp compiled out and works otherwise as expected.

**Comment by graingert** [comment]
I don't think angular team should compile it out. Let users of the library
do it in their own bundles

**Comment by mgol** [comment]
While wrapping the CSP-related code in a condition strippable by UglifyJS wouldn't require us to generate two files it doesn't really make it any easier for us. If we officially support strippable CSP code, we'd have to ensure such a build works correctly - that would, in turn, require us to generate such a file during build process and run most of unit tests on it (while changing the CSP-related ones to be skipped during such a build).

That is a pretty significant overhead for us to handle and if we started doing that, there would be many more builds to support that have valid use cases - for example a build that doesn't support `ng-app` as it's a security nightmare. The number of configurations to test would skyrocket and excluding this code wouldn't really make the final file size much smaller while it would make our tests take longer to finish.

There are other techniques you can employ to make sure the CSP mode is used - you can ban using the `ng-app` attribute and add a linter rule that requires proper parameters to be passed to `angular.bootstrap`, for example.

Due to the required complexity in maintaining such custom build support and limited gains, we decided to not do it.

Thanks for your input, though!
