### ISSUE TITLE
removing jQuery causes app to hang and crash browser

### ISSUE THREAD

**Issue by r3wt** [angular/angular.js#15889]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (see above))

**Current behavior:**

With jQuery, all is fine. But when jQuery is removed and the page is loaded, it hangs forever in the parent state resolve (angular-ui-router) here:

```js
code removed
```

**Expected / new behavior:**

Everything works as expected

**Minimal reproduction of the problem with instructions:**

I cannot provide a minimal repro. but, i can give email a copy of my codebase for someone to run, if you even want to seriously investigate it. Regardless, as long as i include jquery in the page, it works perfectly fine.

**Angular version:** 1.6.2 - 1.6.4

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Windows - Firefox, Chrome, Edge, Brave

**Anything else:**

Here's the stack trace:

> Error: Script terminated by timeout at:
> extend@http://localhost:3000/dist/angular/angular.js:530:1
> q/this.study/<@http://localhost:3000/dist/angular-ui-router/angular-ui-router.min.js:7:2961
> q/this.resolve@http://localhost:3000/dist/angular-ui-router/angular-ui-router.min.js:7:3393
> v@http://localhost:3000/dist/angular-ui-router/angular-ui-router.min.js:7:16353
> w/z.transitionTo@http://localhost:3000/dist/angular-ui-router/angular-ui-router.min.js:7:18615
> w/z.go@http://localhost:3000/dist/angular-ui-router/angular-ui-router.min.js:7:16936
> @http://localhost:3000/app.js:400:10
> $RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://localhost:3000/dist/angular/angular.js:18498:15
> w/z.transitionTo/z.transition<@http://localhost:3000/dist/angular-ui-router/angular-ui-router.min.js:7:19498
> processQueue@http://localhost:3000/dist/angular/angular.js:16843:37
> scheduleProcessQueue/<@http://localhost:3000/dist/angular/angular.js:16887:27
> $RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:3000/dist/angular/angular.js:17982:15
> $RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:3000/dist/angular/angular.js:18280:13
> bootstrapApply@http://localhost:3000/dist/angular/angular.js:1912:9
> invoke@http://localhost:3000/dist/angular/angular.js:5003:16
> bootstrap/doBootstrap@http://localhost:3000/dist/angular/angular.js:1910:5
> bootstrap@http://localhost:3000/dist/angular/angular.js:1930:12
> angularInit@http://localhost:3000/dist/angular/angular.js:1815:5
> @http://localhost:3000/dist/angular/angular.js:33340:5
> trigger@http://localhost:3000/dist/angular/angular.js:3435:5

**Comment by Narretz** [comment]
This could be anything. Maybe you have something in your app that depends on jquery? Own code or 3rd party? Only the core angularJS modules work with jqlite or jquery, everything else has their own assumptions. Since you are using at least ui-router, you should debug this by removing code / 3rd party modules until the error is gone.

**Comment by r3wt** [comment]
@Narretz None of the modules i am using use jQuery to my knowledge. I do use `$q` alot, it seems to be promise related. Anyway, I'm out. This doesn't seem like it will be productive.

**Comment by Narretz** [comment]
Sorry, without an accessible repro it's very difficult to investiagte this. I think it shouldn't be too difficult to find the origin as it happens when the page starts up. I assume there's something in your route logic that interacts with dom / jquery wrapped elements where a difference between jqlite and jquery manifests this error.
UI-router uses extend when it creates various state/resolve-related things and maybe you have something in there that somehow references a DOM element.
Like I said, hard to say

**Comment by Narretz** [comment]
You can reopen this issue once you have more information.

**Comment by r3wt** [comment]
@Narretz i found it. It's in my own module code :-/

jqLite:nosel angular was swallowing the error.
