### ISSUE TITLE
"Edit in Plunkr" should be able to open in a new tab/window

### ISSUE THREAD

**Issue by lacivert** [angular/angular.js#15888]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [x] other (Please do not submit support requests here (see above))

**Current behavior:**

On the documentation pages, there are plunkr editing links which are very important to check the working examples. But when I want to see the example in plunkr, I have to click the link and the link makes the browser page change to the plunkr page. Then I have to go back in a new window or tab to check both plunkr and documentation.

**Expected / new behavior:**

I expect to have a link to plunkr via **open in a new tab or new window option**

**Minimal reproduction of the problem with instructions:**

Just go to the docs in any page and click to the "edit in plunkr" button which you cannot make it open in a new window or tab.

**Angular version:** 1.x.y

Just the docs, example: https://docs.angularjs.org/guide/forms

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Anything else:**

**Comment by frederikprijck** [comment]
Have you tried using `ctrl/cmd + click` ?

**Comment by lacivert** [comment]
Thanks, I had not tried via Ctrl+click until your comment. I tried via scroll click which always makes the links open in a new window without having the second hand push (sroll click is only mouse click but ctrl + click is mouse click and keyboard together)

**Comment by frederikprijck** [comment]
This is the check used to decide whether or not the plunkr should be opened in a new tab:
https://github.com/angular/angular.js/blob/5b477614ff92dcdf5eff62e2143b7fb43aab5653/docs/app/src/examples.js#L138

Replacing the button with an `a` tag wouldn't really help I guess as click event requires to execute some javascript instead of navigating to a certain URL.

**Comment by lacivert** [comment]
Thank you for the code analyzing, I think this is a big lack but if there is no luck, I have nothing to say then :)

**Comment by frederikprijck** [comment]
Let's say we'd replace the button with an `a` element without a `href` attribute but instead executing javascript code to open the plunkr.

How would you ensure the context menu to open (it's not opening, it's executing javascript) works? Afaik, this is not possible. If you think otherwise, please feel free to provide a PR!

**Comment by Narretz** [comment]
Afaik it's not possible to overwrite the context menu action. It's only possible to overwrite the click ... 
Since the plnkr is generated on the fly with a form submit, I don't think there's currently a better way to do it. PR obviously welcome if there's a better solution.
