### ISSUE TITLE
$http is parsing a request to JSON ignoring the content-type

### ISSUE THREAD

**Issue by jrivera294** [angular/angular.js#15897]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
The transformResponse is being executed based on a text/plain content, instead of the content-type headers, causing errors sometimes.

**Expected / new behavior:**
The transformResponse has to be called based on the content-type headers.

**Minimal reproduction of the problem with instructions:**
$http.get is trying parse to json a text/plain response (the content-type header from the server is "text/plain") when the text starts with "[" and ends with "]" characters.

Looking the documentation for [baddata](https://docs.angularjs.org/error/$http/baddata) it says that it parses the body when the content-type header is application/json, and "the response looks like a valid JSON-stringified object or array".

And when I change the default transformResponse function to:
`
$http.get('/', {
      transformResponse: [function (data) {
          return data;
      }]
    })
`
To do nothing when it's called, the request works.

The $http request ignores the content-type response header and try to parse my response based in the body of the response?

**Angular version:** 1.6.2

**Browser:** all

**Anything else:**
I'm not sure how it detects that the body "looks like" a json to parse it automatically. But if the content-type of the response is "text/plain" it doesn't have to parse it, even if the body is a json object (not my case).

**Comment by Narretz** [comment]
Originally, AngularJS ignored the content type header completely and always tried to parse JSON: https://github.com/angular/angular.js/commit/7b6c1d08aceba6704a40302f373400aed9ed0e0b This was changed, and after that, only the json-likeness detection was updated.

Changing this would possibly break a lot of apps that simply don't set their content-type headers on the server correctly.

If you know that your response will always return text, you can detect this and skip the default transform, e.g. like this http://plnkr.co/edit/DgNEA1s62brfhVgsv6OL

Note that the error you linked to is valid only from 1.6.4 onwards - before that you get a generic JSOn parse error.

But you are right that the error description is not correct about the workaround, because setting the header doesn't fix it.

**Comment by Narretz** [comment]
We could also employ some advanced heuristics to detect that this is not json, but this basically means we would have to parse the JSON. Pinging @gkalpak since he last worked on this code.

**Comment by jrivera294** [comment]
Question: 

The responseType option shouldn't define the expected content-type? 

And if that option doesn't do it, we can't add an option to set the expected content-type and don't try to parse to json?

Because even if we improve it with advanced heuristics, if we send a json object as text, or something that still appears to be a json we will have the same problem.

**Comment by Narretz** [comment]
Yes, this is the current status quo. Text that looks like json according to our detection will be parsed as such. We could add an option, but I don't know many devs would benefit from this, especially since there are workarounds.

**Comment by gkalpak** [comment]
At this point, I agree it is probably not worth addressing other than documenting the current behavior and work-around (as it could be a significant breaking change) 👍

**Comment by alexellis** [comment]
Hi folks,

I found this thread through Google and was not expecting the conclusion:

> I agree it is probably not worth addressing

I think I'm seeing the same issue as described above but don't know how to get `$http` to stop parsing as JSON.

The HTTP call returns `text/plain` but the value looks similar to JSON (it is not JSON) and this breaks the page. I'm setting the request/response types to `text` but the `success` part of the promise never executes.. just the `error` part with a parsing error.

Please could you point me at the docs or workaround that I can use to prevent angular / `$http` from force-parsing text as if it were JSON? Related https://github.com/openfaas/faas/issues/528

**Comment by petebacondarwin** [comment]
@alexellis - The workaround depends upon your situation. See https://github.com/angular/angular.js/issues/15897#issuecomment-292515629

The heavy-handed approach (which especially works if you never get JSON from $http requests) is to remove the default transform from the `$http` service.

Otherwise you could remove the default transform on a request by request basis.

Or finally you could replace the default transform with a more complex one that is able to work out whether your request expected JSON or not.

**Comment by alexellis** [comment]
Thanks for a quick response @petebacondarwin. The UI for [OpenFaaS](https://www.openfaas.com/) can invoke functions via a web form - it looks similar to Postman. So you will see a request body entered and can indicate its format and after invoking will see the response in the bottom part of the screen. I believe we should largely be able to detect the content through the Content-Type sent back from the server.

I looked at the plunker example but I don't see how the function `transformData` relates to the `$http` module in that example or how it is specifically preventing the parsing as JSON? Can you talk me through it?

Example:

<img width="1261" alt="screen shot 2018-02-22 at 9 41 10 am" src="https://user-images.githubusercontent.com/6358735/36531030-8ab8f50c-17b4-11e8-848b-19e376fac77c.png">

**Comment by petebacondarwin** [comment]
Yes, that Plunker is not very helpful :-/

Here is the relevant section in the docs: https://docs.angularjs.org/api/ng/service/$http#transforming-requests-and-responses

**Comment by Narretz** [comment]
I believe we changed this behavior here: https://github.com/angular/angular.js/commit/7f2accaa3aed18e811338c9593fb363808c2b40d#diff-748e0a1e1a7db3458d5f95d59d7e16c9 so that http will only throw if the content type is set to json, but can't be parsed. This is available in 1.6.6. Open Faas uses AngularJS 1.5.5. So this could be fixed by updating AngularJS
