### ISSUE TITLE
ng-pattern allows literal RegExp syntax; expression documentation says this is disallowed

### ISSUE THREAD

**Issue by nmschulte** [angular/angular.js#15929]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
The `ng-pattern` directive works when supplying a literal RegExp:
`<input ... ng-pattern="/^\d+$/" ... />`

[The Angular expression documentation](https://docs.angularjs.org/guide/expression) notes this is not allowed.

**Expected / new behavior:**
Some sort of consistency; preferably the ability to create RegExps from Angular expressions.

**Comment by gkalpak** [comment]
The docs are correct, `ng-pattern="/^\d+$/"` does not work. Please provide a reproduction if you think this is not the case :smiley:

**Comment by nmschulte** [comment]
@gkalpak https://plnkr.co/edit/udsNM6KX690nQYVwnoXK?p=preview

**Comment by gkalpak** [comment]
Wow, it seems that `ngPattern` is a special case (as seen [here][1]) and it has been [since forever][2]. I wonder how I missed that.

So, the general rule that AngularJS expressions do not support RegExps is true, but it would be nice to have a special mention in the `ngPattern` docs. @nmschulte would you like to submit a PR?

[1]: https://github.com/angular/angular.js/blob/3c259ce624a9bf8a7baa0168b2635fbdfb516dae/src/ng/directive/attrs.js#L387-L390
[2]: https://github.com/angular/angular.js/commit/d9b90d7c10a8e1bacbee0aeb7e86093cca9e8ed2

**Comment by thamaranth** [comment]
I can submit the PR for the docs if it's still open

**Comment by gkalpak** [comment]
@thamaranth, that great! Nobody is working on it afaik, so it's yours :smiley:
