### ISSUE TITLE
listeners registered using attrs.$observe are not removed when the element is removed

### ISSUE THREAD

**Issue by vinayk406** [angular/angular.js#15944]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

listeners registered using attrs.$observe are not removed when the element is removed

**Expected / new behavior:**

listeners registered using attrs.$observe should be removed when the element is removed/destroyed

**Minimal reproduction of the problem with instructions:**

Here is plnkr to illustrate the problem:
https://plnkr.co/edit/DXzdS8mtt8dQYbg3we3l?p=preview

**Angular version:** 1.6.2

**Browser:** [all]

**Anything else:**

**Comment by gkalpak** [comment]
What you see in the plnkr is expected behavior. Removing elements like this is not guaranteed to clean up properly, because the actual scope the contains the directive is not destroyed/cleaned up. The isolate scope passed to the linking functions is the scope that owns **the template** of the directive (if any), not the directive/element itself.

For such cases, where you want to be able to add/remove elements form the DOM and be sure that everything is cleaned up correctly, you need to have a wrapper scope and destroy it at appropriate times. This is what the built-in, structural directives (e.g. `ngIf`, `ngSwitch`, `ngRepeat` etc) are really good at. 

Direct DOM manipulation is not "the AngularJS way". You should either create your own custom directive or ue a built-in one ([demo][1]).

[1]: https://plnkr.co/edit/TFYuKamg4jQhixYItO1O?p=preview
