### ISSUE TITLE
Why assigned function to ng-checked is called more than once?

### ISSUE THREAD

**Issue by saeidalidadi** [angular/angular.js#15951]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

Function is called more than once when using `ng-checked` directive. 

**Expected / new behavior:**

It should called once.

**Minimal reproduction of the problem with instructions:**

`userSearch.component`

```javascript
class SearchController {
  /*@ngInject*/
  constructor() {
   // assign injected values
  }
  $onInit() {
    this.columns = {
      firstname: true,
      lastname: true,
      mobilePhone: true,
      registered: false
    }
  }
  hasColumn(name) {
    console.log(name);
    return indexOf(this.columns, name) ? true : false;
  }
}

export default angular.module('searchuser', [])
  .component('searchuser', {
    template: require('./searchuser.jade'),
    controller: SearchController
  }).name;
```
`searchUser.jade`:

```jade
    .col-md-6.form-group
      label.col-md-3.pull-right Last Name
      .input-group.col-md-8
        span.input-group-addon
          input(type="checkbox", ng-checked="$ctrl.hasColumn('lastname')")
        input.form-control(type="text", name="lastname")

```

`console log`:

![angularjs-bug-checkbox](https://cloud.githubusercontent.com/assets/2406828/25578103/babff318-2e80-11e7-879f-b1619fc1924f.png)

**Angular version:** 1.x.4

**Browser:** Chrome Version 54.0.2840.100 (64-bit)

**Anything else:**

**Comment by gkalpak** [comment]
The `ng-checked` expression needs to be evaluated on every `$digest`. Depending on what else is going on in your app (which we can't infer from the code you shared above), there can be several digests until your expressions settle down. You can read more about this on the [Developer Guide][1].

As you can see [here][2], when no other expressions have changed, the `$digest` is run twice (the first time picking up the new value, and a second time to verify it hasn't changed as a result f other expressions being evaluated).

Closing, since everything works as expected.

##
BTW, this is a general support question. In the future, you can use one of the [appropriate support channels][3] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://docs.angularjs.org/guide/scope#integration-with-the-browser-event-loop
[2]: https://codepen.io/ExpertSystem/pen/rmwmyx?editors=0011
[3]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
