### ISSUE TITLE
Counterintuitive output with ngIfEnd and ngIfStart on same element

### ISSUE THREAD

**Issue by gabrielmaldi** [angular/angular.js#15962]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**

Case 1:
```html
<ul>
    <li ng-if-start="true">A</li>

    <li ng-if-end
        ng-if-start="false">B</li>

    <li ng-if-end>C</li>
</ul>
```
Output: `AC`

---

Case 2:
```html
<ul>
    <li ng-if-start="false">A</li>

    <li ng-if-end
        ng-if-start="true">B</li>

    <li ng-if-end>C</li>
</ul>
```
Output: ` ` (empty)

**Expected / new behavior:**

Case 1: `A` (`C` shouldn't be rendered because its `ngIfEnd` matches `ngIfStart=false` on `B`)

Case 2: `C` (`C` should be rendered because its `ngIfEnd` matches `ngIfStart=true` on `B`)

**Angular version:** 1.6.4

**Browser:** all

**Comment by gkalpak** [comment]
Putting the `ngIfStart/End` attributes on an element, is the same as putting `ngIf` on it. By having both `ngIfStart` and `ngIfEnd` on the same element, is like using two `ngIf`s on it. This is not a supported usecase imo.

**Comment by gabrielmaldi** [comment]
Then I suppose that my current workaround isn't supported either:

```html
<ul>
    <li ng-if-start="condition1 && condition2"></li>
    <li></li>
    <li></li>
    <li ng-if="condition3 && condition4"></li>
    <li ng-if-end
        ng-if="condition3 && condition4"></li>
</ul>
```

I want all `<li>`s to be governed by `condition1 && condition2`; and the last two `<li>`s to also depend on `condition3 && condition4`. But I understand that the above is currently working by chance and may break in the future.

The only currently supported alternative I can think of is:

```html
<ul>
    <li ng-if-start="condition1 && condition2"></li>
    <li></li>
    <li ng-if-end></li>
    <li ng-if-start="condition1 && condition2 && condition3 && condition4"></li>
    <li ng-if-end></li>
</ul>
```

Which forces me to repeat `condition1 && condition2` on the last two `<li>`s; if another condition that should apply to all `<li>`s were to be added, I would need to remember to add it to both `ng-if-start`s.

I guess that what I really want is a way to add more conditions to some of the elements in a `ng-if-start`/`ng-if-end` group.

One more thing, do elements between `ng-if-start` and `ng-if-end` also get their own `ng-if`? If that is the case, I suppose this isn't supported either:

```html
<ul>
    <li ng-if-start="condition1"></li>
    <li></li>
    <li ng-if="condition2"></li>
    <li></li>
    <li ng-if-end></li>
</ul>
```

Thanks

**Comment by gkalpak** [comment]
I see what you are after. In your initial example, it seemed like you where trying to have two interleaved `ngIf`'d collections (e.g. [item1, item2] and [item2, item3]), which is definitely not supported.

The way this works now, it is possible to have nested multi-element directives, but you can't have the start or end attributes for more than one directive on the same element (because of how we scan for these `-end` directives).

So, what you want is this (which is currently not supported):

```html
<div ng-if-start="cond1">Item 1</div>
<div>Item 2</div>
<div ng-if-start="cond2">Item 3</div>
<div ng-if-end ng-if-end>Item 4</div>
```

What does work, is having one extra element at the end to enclose the whole group. E.g. something like:

```html
<div ng-if-start="cond1">Item 1</div>   <!-- group-1: start -->
<div>                    Item 2</div>
<div ng-if-start="cond2">Item 3</div>   <!-- group-2: start -->
<div ng-if-end>          Item 4</div>   <!-- group-2: end -->
<div ng-if-end class="ng-hide"></div>   <!-- group-1: end -->
```

[Demo][1]

##
This is obviously not ideal, but should be fine for most usecase. Considering that there are also other (less dry but more flexible) solutions, I don't think it is worth trying to somehow support multiplt `-end` attributes on the same element.

<sub>(Closing, but feel free to continue the discussion below.)</sub>

[1]: https://codepen.io/ExpertSystem/pen/dWzaBJ?editors=1000

**Comment by gabrielmaldi** [comment]
I solved my use case following your nested multi-element directives example. I agree that supporting the same attribute twice on the same element isn't worth it. Thanks for your help!
