### ISSUE TITLE
href and stopPropagation in ngClick adds 2 states to the history and blocks the browser's back button

### ISSUE THREAD

**Issue by SuperCorks** [angular/angular.js#15981]
**I'm submitting a ...**

- [ x ] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

Browser's back button doesn't go back. You always stay on the same page as if you were in an
infinite loop of the same history state. It looks like the same state is pushed twice to the history's stack.

**Expected / new behavior:**

Back button works as expected, shift's between the states as intended.

**Minimal reproduction of the problem with instructions:**

Using angular-route, add an ng-click="$event.stopPropagation()" to an anchor tag (<a>) with an href="#someView".

Here's a plunker : http://plnkr.co/edit/hcpFONnYkFgUYfMlntkr

**Angular version:** 1.5.11 (but in the plunker it's 1.6.x)

**Browser:** [all | Chrome 58 | Firefox XX ] (didn't try the other ones)

**Anything else:**

**Comment by gkalpak** [comment]
AngularJS adds a click handler on `$rootElement` and handles the internal URLs (to views) specially. It prevents the default browser event, normalizes the URLs (e.g. `#!view2` is changed to `#!/view2`) and does other book-keeping stuff.

By stop the propagation of the event, the browser does performs the default action (in this case adding a new history state for `#!view1`). AngularJS will then pick this change up, normalize the URL to `#!/view2` and update the `location`.

Now going back, will get you to `#!view`, which will then be picked up by AngularJS and normalized to `#!/view2`. So you are essentially stuck there.

##
In order to avoid this, you need to do one of the following:

- Not stop the propagation of the event.
- Use the correct path (e.g. `#!/view2` instead of `#!view2`). 
- Navigate programatically (preferrably using a `<button>` element.

##
Closing, since this (kind of) works as expected and although we might be able to detect such cases and work-around them in `$location`, I don't feel it is worth the extra complexity. It also is outside of scope of AngularJS trying to work-around the user's stopping the propagation of the event.
