### ISSUE TITLE
$cancelRequest() on completed resource request throws error

### ISSUE THREAD

**Issue by jazdw** [angular/angular.js#16016]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

Canceling a completed Angular Resource request using .$cancelRequest() results in
```
angular.js:123 TypeError: Cannot read property 'resolve' of null
    at Array.cancelRequest (https://localhost:8443/modules/mangoUI/web/vendor/angular-resource/angular-resource.js:831:30)
```

**Expected / new behavior:**

The function call should do nothing, as per docs
```
Calling $cancelRequest() for a non-cancellable or an already completed/cancelled request will have no effect.
```

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.6.4

**Browser:** [all]

**Anything else:**

Looks like this bug was introduced in 71cf28cf06295e0936f706c048bc07e6c963acc4

**Comment by gkalpak** [comment]
I could reproduce it. Can you post a reproduction (preferrably a live demo using CodePen, Plnkr etc)?

**Comment by gkalpak** [comment]
I could not reproduce it. Can you post a reproduction (preferrably a live demo using CodePen, Plnkr etc)?

**Comment by jazdw** [comment]
OK, so the issue only occurs if you store a reference to the cancel function. It seems the behaviour has been changed so that the cancel function is replaced by angular.noop

https://codepen.io/jazdw/pen/eWwNdJ

**Comment by gkalpak** [comment]
Yeah, you should not store a reference. You should use it from the resource instance, because we update the `$cancelRequest` property on/after every request.

That said, feel free to submit a PR that adds a check inside `$cancelRequest` to account for properties being null (which means the request has been completed/aborted already).

**Comment by jazdw** [comment]
IMO the current behavior is pretty strange and I'd consider it a regression, however its not worth my time submitting a PR. Anyway the issue if here if anyone else encounters it.

**Comment by chirag64** [comment]
Hi @gkalpak, I'd like to attempt a PR for this.

My guess is we need to check if the Object `timeoutDeferred` is not null before this line https://github.com/angular/angular.js/blob/3bce707421464c320e38fe758a6143003ce87522/src/ngResource/resource.js#L825. 

If that is correct, what should we do when it is null (throw an error saying request has been completed / aborted already?). Would appreciate your help on this one.

**Comment by gkalpak** [comment]
Thx for taking it up @chirag64. Checking that it is not null sounds good to me. We should do nothing if it is (throwing an error would beat the purpose of fixing this to not throw an error :smiley: Since the request is not cancellable any more we don't need to do anything (unless I'm missing something).

**Comment by 4O4** [comment]
Done in https://github.com/angular/angular.js/pull/16037, this issue can be closed.
