### ISSUE TITLE
High security issue in angular-js

### ISSUE THREAD

**Issue by SudheendraModa** [angular/angular.js#16066]
**I'm submitting a ...**
bug report

**Current behavior:**
High security issue(s) found in angularjs sources used, reported by HP-Fortify scan tool.

**Expected / new behavior:**
No Critical/Blocker/High security issues to be reported when sources scanned for security review.

**Minimal reproduction of the problem with instructions:**
Scan the sources of angularjs using HP-Fortify or any other static code review tools for security issues. angular-scenario.js is reported to have insecure random issues and hard coded password issues. 

**Angular version:** 
1.6.2

**Browser:** 
all

**Anything else:**
![security-issue-in-angularjs162](https://user-images.githubusercontent.com/29593413/27372750-472136d0-5683-11e7-8ab8-acd077dabf77.png)

**Comment by frederikprijck** [comment]
I'd say the error linked to 2107 is a false positive as HPE Fortify will look for anything that looks like `password: **`, but this is not storing a password (`password: true`) hence not a security risk.

Looking at the source code, the other two don't look "high security" issues either. But maybe @gkalpak has a better idea about the impact/risk of that code.

**Comment by Narretz** [comment]
angular-scenario is an e2e test library. It's also deprecated (in favor of protractor). I don't think these are security issues.

**Comment by gkalpak** [comment]
In addition to what @Narretz said these warnings are coming from jQuery's code (which `angular-scenario.js` contains - from [here][1], [here][2] and [here][3]) and are not actual vulnerabilities.

You can find several relevant discussions online, e.g. [here][4] and [here][5]. Quoting from the last one:

> It is important to audit all findings identified by Fortify to determine if they pose a risk to the application, including those in third party libraries like jQuery. [...]

##
Closing since this is not actonable.

[1]: https://github.com/jquery/jquery/blob/731c501155ef139f53029c0e58409b80f0af3a0c/src/core.js#L203
[2]: https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/external/sizzle/dist/sizzle.js#L1981
[3]: https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/external/sizzle/dist/sizzle.js#L1620
[4]: https://forum.jquery.com/topic/security-issue-about-jquery
[5]: https://wiki.mobilehealth.va.gov/display/OISSWA/Common+Fortify+findings+in+jQuery
