### ISSUE TITLE
ng-trim should not trim the view value

### ISSUE THREAD

**Issue by cleavera** [angular/angular.js#16087]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
When applying ng-trim to an input it affects the view value

**Expected / new behavior:**
I would expect the view value to remain unaffected as this is meant to reflect the value as it appears in the input. 

**Minimal reproduction of the problem with instructions:**
https://codepen.io/antisback/pen/QgBQpG?editors=1010

**Angular version:** 1.6.1

**Browser:** all

**Anything else:**
The use case we have is we have some functionality that makes a text area grow as you type in characters. To do this we bind the view value to a pre block with the same width as the textarea and then update the height of the text area to match the pre block. As ng-trim is removing all the whitespace off the front of the view value it means the textarea's height doesn't update properly. We can't set ng-trim to false as we need it to make ng-required work properly.

**Comment by gkalpak** [comment]
This is a feature, not a bug. Initially, AngularJS would trim whitespace off the viewValue. Then [`ngTrim` was introduced][1] to allow turning that off.

Changing that default behavior now would be a significant breaking change for little benefit (this has obviously been working well for people for years now :grin:). It is useful in most cases.

##
> We can't set ng-trim to false as we need it to make ng-required work properly.

You would have the exact same problem if we changed the default trimming behavior (since `ngRequired` operates on the `$viewValue` :grin:)

##
Possible solutions:

1. Set `ngTrim` to false and use a custom `required` validator that ignores whitespace.
2. Set `ngTrim` to false and overwrite the `$isEmpty()` method of `NgModelController` (either globally or for your specific textarea), so that it ignores whitespace. (Note: `ngRequired` uses `$isEmpty()` under the hood to determine the empty-ness of an input field.)

(In both cases, you might need a custom parser to remove the whitesace if you don't want your model value to contain extra whitespace.

[1]: https://github.com/angular/angular.js/commit/d519953a4b219035587e3fcb2e9cc52e02b408ca

**Comment by cleavera** [comment]
Fair enough, I figured it may have been as designed but its still strange behavior. Thanks for the answer anyway.
