### ISSUE TITLE
ng-show/ng-hide does not work  in a select option in IE11 

### ISSUE THREAD

**Issue by eassa** [angular/angular.js#16082]
**I'm submitting a ...**

- [ x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

i have put ng-show in the <select> <option ng-show"expression"></option </select>
in chrome or edge it is working but in IE11 , it show it anyway
i had to use ng-if to overcome this problem  

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.6.4

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

IE11

**Anything else:**

**Comment by Narretz** [comment]
Hi, thanks for the report. Can you please put a demo of the problem in a [Plunker](https://plnkr.co) or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)? That makes it much easier to assess the problem and create a fix, if possible.

**Comment by gkalpak** [comment]
Actually, this is not an AngularJS issue (see [here][1], [here][2] and [here][3]).

This happens because IE does not respect the `display: none` style on `option` elements (you can try that without AngularJS). Remember, that all `ngShow`/`ngHide` do is add/remove the `.ng-hide` CSS class. The `.ng-hide` CSS class is associated with a `display: none` style rule.

So, this works as expected as far as AngularJS is concerned. You could use your own rule for `.ng-hide` (or possibly `.ng-hide` on `<option>` elements), but using `ngIf` (which adds/removes the DOM node) sounds like a better alternative.

[1]: https://stackoverflow.com/questions/9234830/how-to-hide-a-option-in-a-select-menu-with-css
[2]: https://stackoverflow.com/questions/19565864/option-with-displaynone-does-not-work-on-ie
[3]: https://stackoverflow.com/questions/20373558/options-with-displaynone-not-hidden-in-ie

**Comment by eassa** [comment]
thx for the info , 
but i still think a framework such as angular should do something about this , 
i saw that ng-show was working perfectly with all browsers , but in this case specifically it is not working with IE only . 
if i have not found out this issue, i would have a lot of trouble in the permissions and license of my software validation later on.
in my opinion , ng-show and ng-hide are directives not a css classes , such an issue should not be happening .

**Comment by gkalpak** [comment]
@eassa, what do you suggest? How should `ngShow`/`ngHide` deal with IE not respecting `display: none` on `<option>` elements?

**Comment by eassa** [comment]
@gkalpak  my experience with building directives is a bit limited , but i know in jquery you can use .hide() and .show() on a selected attribute something like this : 
`$('select.some-list option[id=someId]').attr('disabled', 'disabled').hide();
$('select.some-list option[id=someId]').removeAttr('disabled').show();`
can't something simeler be done in the directive  ?

**Comment by gkalpak** [comment]
@eassa, jQuey's `hide()`/`show()` do the same thing here: They apply/remove the `display: none` style.
So, jQuery doesn't work for hiding `option` elements on IE either.

Again, if the browser does not respect a CSS rule, there is little AngularJS can do. And for your usecase there is a perfectly viable solution, which is using `ngIf`.
