### ISSUE TITLE
Cannot pass a function to directive if the function is not defined on the scope

### ISSUE THREAD

**Issue by mhdSid** [angular/angular.js#16094]
## I'm submitting a ...
[ x ] Bug report 

## Current behavior
We have a TypeScript class used as a component controller that has private and public members.
The component template is populated using $ctrl.controllerMemberName (where controllerMemberName belongs to the controller prototype). 

Within this component template we are passing a function, that is not defined on the scope, to another directive, and once that function is called from the directive, AngularJS throws an error "TypeError: Cannot use 'in' operator to search for '$ctrl'".

`<any data-function-to-be-called='$ctrl.fn()'></any>`   
Doesn't Work (fn belongs to component controller prototype)

`<any data-function-to-be-called='fn()'></any>`  
Works (fn is defined on the scope)

If we do scope.functionName = this.functionName in the component controller, then, it will be called normally without an error.

## Expected behavior
The function should be called properly same as defining it on the scope

## Please tell us about your environment

<pre><code>
Angular version: 1.6.3

Browser:
- [ X ] Chrome (desktop) version  59.0.3071.115
 
For Tooling issues:
- Node version: 7.5.0
- Platform: Mac

**Comment by gkalpak** [comment]
It is impossible to know what the problem is without a reproduction (or at least some code to look at).

By default, directive bindings are bound to the scope. You need to specify `bindToController: true` on the directive definition object to bind bindings to the controller instance. (If you use the `.component()` helper, it defaults to `bindToController: true`, so you don't need to explicitly specify it.)

##
That aid, this is a general support question, so you are better of using one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by mhdSid** [comment]
I guess what I said is simple and straight forward. I will try to use bindToController: true to check if it works.
