### ISSUE TITLE
compile template + data without scope and controller

### ISSUE THREAD

**Issue by prashant-saxena** [angular/angular.js#16121]
**I'm submitting a ...**

- [ ] bug report
- [* ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
When you are loading both template and data from server, remove the need of scope and controller

**Expected / new behavior:**
A new way either in terms of a directive or something else that helps to compile a template and data
without scope and controller

**Minimal reproduction of the problem with instructions:**
[https://plnkr.co/edit/bxStqRcGzJzH4kWROxED?p=catalogue](url)

I have written a service to get the data from server and a directive to get the data and compile it.
The server is sending two types of data:
1. A template and data to compile against with. Here I don't see fit the requirement of a scope and controller, although service and directive are working fine. A better approach to introduce a new
functionality where such case can be handled much easily. Instead of SPA if you are using Angular
for website it would really helpful.

2. In second case I am getting a form and data. I'm new to angular and I might have done something
wrong in my directive. When I'm using this directive in my HTML only once, form is rendered properly
and i can see data in input fields, problem arises when I am using this directive twice. First form is rendered and immediately after that second form is rendered and data from first from vanishes. Some
time data stays at first form and vanishes from second form. Further more the first printing command
in directive to print the random name is printing only once even when I'm using directive twice
in HTML.

Under the hood either this is caused by get service or may be I'm overwriting controller, I'm not sure.
As you can see in the code I'm using **controllerAs** which as far as my understanding goes will creating
an instance of myPluginCtrl controller's instance with a random name. I could be completely wrong here.

The idea is to decide the controller once data is received. If it's a simple template and data then at run time you bind the scope to a controller that's just a controller and has nothing inside or if it's a form
then bind to a baseFormController's instance where you have some generic code to handle your form's
requirements.

Third is that if a particular form is having some extra requirements as in terms of couple of extra functions
written in a java script file, bind it with formBaseController at run time. I think this would solve this:
[https://oclazyload.readme.io/](url)
Although I haven't tested it.
All said and done, I'm sorry to post here if this is not the place for what I have mentioned but I'm hoping
I have something which either I'm missing it or it can be implemented.

Cheers
Prashant 

**Angular version:** 1.6.4

**Browser:** [al]

**Anything else:**

**Comment by gkalpak** [comment]
It is not exaclty clear what you are asking, but it sounds like a general support question (plus some misconception of the directive API).

1. You don't need a controller on every directive. 
2. You don't need a directive to compile a template (you just need the `$compile` service and a scope).
3. Compiling a template and linking it to a scope creates a "live" view of your model. Thus changing the properties of the scope (as you seem to be doing in your two-form example) will update your view with the new data.
4. A scope is necessary for linking the model (data) to a compiled template (view), because it has certain methods that are necessary for evaluating expressions, updating values, cleaning up etc (e.g. `$eval`, `$watch`, `$destroy`). But the overhead of using a scope instead of "raw data" is minimal:

```js
// Instead of:
$compile(myTemplate)(myData);   // <----- WRONG

// Do:
$compile(myTemplate)(angular.extend(myScope, myData);   // <----- OK
```

##
I am going to close this, but feel free to continue the discussion below in case I missed your point. For general support questions, please, use one of the [appropriate channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
