### ISSUE TITLE
Change detection fails when multiple instances of a component are present

### ISSUE THREAD

**Issue by levilindsey** [angular/angular.js#16122]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
AngularJS fails to detect changes to an individual component when a second instance of the component is present.

**Minimal reproduction of the problem with instructions:**
https://plnkr.co/edit/1uHMSpsMGqGt0hOGy2Rr?p=preview

**Angular version:** 1.6.4

**Browser:** all

**Anything else:**
Note that when the same state-change is applied to both component instances, then AngularJS does correctly update the DOM for both.

**Comment by gkalpak** [comment]
AngularJS works as expected. The (un)expected behavior stems from the fact that you are using directives that don't create their own scope and thus re-use the parent scope. In doing so, both try to set `parentScope.ctrl.isFooShown` to their controller instance, so effectively the second instance overwrites the first one. What you end up with is two directive instances which both rely on the second controller's `isFooShown` property (because that is what `parentScope.ctrl.isFooShown` refers to).

I can't be sure, but it seems that you want isolated components, in which case you should use `scope: {}` in your Directive Definition Object to request an isolate scope. (If you are using a recent AngularJS version, you can use the `.component()` helper, which uses isolate scopes by default.)

[Updated plnkr][1]:

```diff
 function fooPanelDirective() {
   return {
     template: '<div class="foo" ng-if="ctrl.isFooShown"></div>',
+    scope: {}
     controller: FooPanelController,
     controllerAs: 'ctrl'
   };
 }
```

[1]: https://plnkr.co/edit/oD9VYteRfCY0x6DIx8N0?p=preview

**Comment by levilindsey** [comment]
@gkalpak, If the problem is that both instances of the component are sharing the same scope, then shouldn't both instances be hidden when I change the state of the first one?

Interestingly, I found that if I use an ng-repeat to generate the two instances (instead of individually defining each one), then the DOM is correctly updated with the state of an individual instance.

https://plnkr.co/edit/4YGZYUXxB5ZOmQzEMncU?p=preview

**Comment by gkalpak** [comment]
As explained in my previosu comment, both instances refer to the second instance's controller in their template. So, when you change `firstControllerInstance.isFooShown` (as you do in your tests), nothing happens. If you changed `secodnControllerInstance.isFooShown` then both directive instances would be affected.

Using `ngRepeat` is expected to solve this, because with `ngRepeat` _"each template instance gets its own scope"_ ([docs][1]).

[1]: https://docs.angularjs.org/api/ng/directive/ngRepeat

**Comment by levilindsey** [comment]
That makes sense. Thanks for the explanation!
