### ISSUE TITLE
Step validation for numbers ignores the $parsers pipeline

### ISSUE THREAD

**Issue by alexis-y** [angular/angular.js#16142]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
Add custom $parsers and $formatters to an input[type=number]'s ngModelController (ie.: thru a directive). Add a step or ngStep attribute to it. If the value in the input is not a number, but the $parser turns it into one, then the step validator is always invalid regardless.

**Expected / new behavior:**
The step validator correctly uses the result of the custom $parser.

**Minimal reproduction of the problem with instructions:**
Parse roman numerals thru a directive: http://plnkr.co/edit/knSGYGz7213ZGRkahqWV
Notice that the min validator works as expected (It only let's values greater or equal to 10 or 'X'), but the step doesn't (It should let even numbers like 'X' or 'XVI').

**Angular version:** 1.6.5

**Browser:** all

**Anything else:**
The [step validator function](https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L1632) uses the viewValue instead of the modelValue. The min and max validators, declared lines above, use the modelValue instead.

**Comment by gkalpak** [comment]
Unfortunately, different validator operate on different values (`modelValue` vs `viewValue`). This is necessary, because some validators make more sense on one or the other, but it also makes validators less predictable, which is not nice 😟

(I think @Narretz would move all validators to use the `viewValue` if he could 😛)

##
Not sure why we chose `step` to operate on the `viewValue` (there might be legit reasons I don't recall), but it does indeed look reasonable to follow what `min`/`max` are doing (operate on the `modelValue`). Especially since we are converting `viewValue` to a number anyway.

@Narretz, WDYT? Any idea why we use `viewValue`?

##
In the meantime, it is very easy to overwrite the built-in `step` validator with your own (which uses the `modelValue`). You can even leverage the built-in validator (with its non-trivial logic) and just swap the arguments to that it operates on the `modelValue` instead ([updated plnkr][1]):

```js
var originalStepValidator = ngModelCtrl.$validators.step;
if (originalStepValidator) {
  ngModelCtrl.$validators.step = function(modelValue) {
    // Validate the `modelValue`, instead of the `viewValue`.
    return originalStepValidator(null, modelValue);
  };
}
```

[1]: http://plnkr.co/edit/6mbTty4MP0n4iC6r4C3F?p=preview

**Comment by Narretz** [comment]
It's true, I think all validators should operat by default on the viewValue, because that's what covers most use cases. In general, the validators follow HTML5 validators which validate *exactly* what the user sees in the input, and not some transformed representation. In your example it would definitely make sense to validate the transformed value, however you are also changing the type of the input, and assume that the number validator still works ... I don't think we guarantee anything like this.

What we could do:
- make min / max validate viewValue
- document what is validated
- allow a switch (via ngModelOptions) for each validator to switch to modelValue

**Comment by alexis-y** [comment]
Hmmm, researching this I quickly fell down an i18n rabbit-hole :(
The browser always _reports_ the value of the input as a string in an invariant format ("1234.5" for numbers, "2017-08-03" for dates, etc). There's a fundamental disconnect with the underlying JS types like Date and Number, and I'm guessing it's because of the separation of concerns between JS and HTML, and also because there are several input types with no corresponding JS type, like week or time. HTML just wants to make sure the data is POSTed correcly so the server can read it, no matter what. And that's great.

However, for inputs of types with localizable formatting (ie.: number, date, datetime-local, etc) the browser will render the value in the browser's UI locale format (or, Firefox only, according to the _lang_ attribute of the <input> or the <html>, bless them). So me, using chrome in es-ES, will always have numbers displayed in the input as "1.234,56", datetimes as "03/08/2017 17:00" and so on, while you in en-US get '1,234.56' and '8/3/2017 5:00 PM', and a guy in middle east gets arab digits (I'm guessing, judging by Firefox's behavior with html[lang=ar].
[Exploratory plunker](http://plnkr.co/edit/8r2uJz97KfOnWIy52mCQ?p=preview), check it in various browser to see the disarray of input methods.

Where does this leave me? I'm not sure, but I came to appreciate @Narretz argument, that validating on viewValue is more useful, since the text format is stable in those inputs. Also, it's clearer to me that the purpose of the $parser/$formatter pipeline, at the moment, is to allow different types implementations (ie.: [type=date] into momentjs instead of a vanilla Date), and not necessarily different textual representations (ie.: roman numerals, hex). To do that (reliably, predictably), a switch in ngModelOptions or in ngModelController would be needed.

**Comment by petebacondarwin** [comment]
Sorry. We are not going to change this. Instead you can use @gkalpak's workaround here as suggested here: https://github.com/angular/angular.js/issues/16142#issuecomment-319705825
