### ISSUE TITLE
if <video> attribute volume Initialization failure ,it will prevent ngAfterViewInit circle Life 

### ISSUE THREAD

**Issue by lxcyha** [angular/angular.js#16157]
like this <video [volume]="null"

**Comment by frederikprijck** [comment]
Despite the fact that this issue is somewhat cryptic, you might want to move this over to https://github.com/angular/angular as that's where issues with Angular should go. This repository is for AngularJS only. 

But ensure to provide some more information, a reproduction of the issue is a good idea aswell.

**Comment by Narretz** [comment]
Hi, your issue sounds like an issue for Angular 2. Please open in the Angular 2 [repository](https://github.com/angular/angular/issues). This repo is only for AngularJS.

**Comment by lxcyha** [comment]
thx
