### ISSUE TITLE
orderByFilter not functioning correctly with zone.js

### ISSUE THREAD

**Issue by dblVs** [angular/angular.js#16160]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
If you are using @angular/upgrade module with angular and you want to order objects in an array without predicate you can't reverse the order of the objects unless you use the 2nd parameter. OrderBy gets confused by the `.toString()` thats polyfilled by zone.js and tries to compare them by string value which makes them all equal (as `'[object Object]' === '[object Object]'`) 

**Expected / new behavior:**
OrderBy ignoring the polyfilled toString or not comparing them based on toString value at all or ignoring the toString if it returns [object Object].

**Minimal reproduction of the problem with instructions:**
1. Load zone.js
2. Load angular.js
3. Use this and see that the generated paragraphs are always 1,2,3 unless you provide 2nd param
```<p ng-repeat="obj in [{a: 1}, {a: 2}, {a: 3}] | orderBy: '-'">{{obj.a}}</p>```
**Angular version:** 1.5.8 (still relevant in most recent version)

**Browser:** [all]

**Comment by gkalpak** [comment]
I checked with both v1.6.5 and v1.5.8 and it [works correctly][1]. It shouldn't matter if `Object.prototype.toString` is patched, because AngularJS will compare against the patched method.

Due to its nature, in order for Zone.js to work correctly, it should be loaded before everything else on the page. What sounds like you are loading angular.js before zone.js, so AngularJS will store the unpatched `toString()` method and later compare it with the patched one.

Closing, since it works as expected.

[1]: https://codepen.io/ExpertSystem/pen/ayWLeJ?editors=0010

**Comment by dblVs** [comment]
@gkalpak yes you are right. I was cofused by other project where i was loading Zone before angular and just realised that in the project which i was doing the orderBy was loading zone js after angular js. Sorry for the mistake.

**Comment by arashkbanan** [comment]
On 9 Aug 2017 19:12, "Veli Veli" <notifications@github.com> wrote:

@a2ashk <https://github.com/gkalpak> yes you are right. I was cofused by
other project where i was loading Zone before angular and just realised
that in the project which i was doing the orderBy was loading zone js after
angular js. Sorry for the mistake.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/angular/angular.js/issues/16160#issuecomment-321276070>,
or mute the thread

**Comment by arashkbanan** [comment]
من یک مورد را با شما به اشتراک گذاشته‌ام:

https://plus.go.txt
http://drive.google.com/file/d/1IujtzDVlHYdekN8IEC8e6lCAVskVAogr/view?usp=sharing&invite=CMWD8_cN&ts=5a2c98bf

این یک پیوست نیست -- به صورت آنلاین نگهداری می‌شود. برای باز کردن این مورد،  
فقط کافی است روی پیوند بالا کلیک کنید.

#A2ASHKE

**Comment by arashkbanan** [comment]
من یک مورد را با شما به اشتراک گذاشته‌ام:

https://plus.go.txt
http://drive.google.com/file/d/1IujtzDVlHYdekN8IEC8e6lCAVskVAogr/view?usp=sharing&invite=CMWD8_cN&ts=5a2c9b18

این یک پیوست نیست -- به صورت آنلاین نگهداری می‌شود. برای باز کردن این مورد،  
فقط کافی است روی پیوند بالا کلیک کنید.

#A2ASHKE
