### ISSUE TITLE
ngOptions when disable expression changes.

### ISSUE THREAD

**Issue by fishgills** [angular/angular.js#16174]
**I'm submitting a ...**

- [X] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
When using ngOptions with the `disable` feature, if the disable evaluation changes, the model/options loses its value.

If ngOptions is initially loaded with a disable option selected, it's selected correctly.

The documentation states 

> disable: The result of this expression will be used to disable the rendered <option> element. Return true to disable.

I believe this implies that the *rendering* should impacted, but not the model.

**Expected / new behavior:**
When the evaluation changes, I wouldn't expect the model value to change.

**Minimal reproduction of the problem with instructions:**
Here's a working example:

https://embed.plnkr.co/5MSJB9E7AMNDF5oZQJRR/

Select a new selectable value and then click the button. The model loses its value. But on page load, the model has its value.

**AngularJS version:** 1.6.2

**Browser:** [all]

**Anything else:**

**Comment by Narretz** [comment]
I intentionally added this, I think to create consistency with how the regular select works. It's debatable if the model should be reset, and I guess the reasoning was that since a disabled option is not available , it gets removed from the model.
When the model is initalized, we ignore all "invalid" states because on init the disable state usually is set without user interaction. The usual example is that a user has selected a value previously that is now disabled, and can't be re-selected, but is still valid as long as the user doesn't change it.
I'm not sure if it's worth it to change this now. Did you find a workaround for this issue?

**Comment by fishgills** [comment]
Nah, that explanation works for me. I'll take it back to my bosses. 👍

**Comment by Narretz** [comment]
Ok, I'll close this issue then :)
