### ISSUE TITLE
Polyfilled library code run after angular dependency VS native toString

### ISSUE THREAD

**Issue by cary-smith** [angular/angular.js#16207]
**I'm submitting a ...**
- [ x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
Angular is loaded as an external dependency before our babel-compiled library allowing developers to choose the angular version they wish to use. In IE11 (failboat that it is), angular's [hasCustomToString](https://github.com/angular/angular.js/blob/3651e42e49ded7d410fd1cbd46f717056000afd4/src/Angular.js#L516) method _always_ returns true making object comparison impossible.

**Expected / new behavior:**
The hasCustomToString function should compare against the Object.prototype.toString to use whatever is currently in play...polyfilled or otherwise. This would allow library code to run as expected without having to require developers to add the polyfill before angular.

**Minimal reproduction of the problem with instructions:**
http://plnkr.co/edit/xo7KIdrekPbHcXOOVS7W?p=preview
1. Open in IE (needs the polyfill)
2. Notice the lack of sorting
3. Open in Chrome (which does not need the polyfill)
4. Notice all is good.

**AngularJS version:** 
^1.5.x (roughly)

**Browser:** 
IE11 (_please die soon_)

**Anything else:**
Changing hasCustomToString to 
```JavaScript
function hasCustomToString(obj) {
  return isFunction(obj.toString) && obj.toString !== Object.prototype.toString;
}
```
...and everything works great!

Hello angular team and thanks for all the hard work!

We have run into an edge case that is a bit odd but is affecting multiple developers in our organization. I really do not want to make patch requests for IE11's "rough" implementations, but I do not believe there will be additional overhead for the change although you would be the better judge. 

Thanks ahead of time!

**Comment by Narretz** [comment]
Your proposed solution was actually in place before commit 2c8d87e064, so it's probably non-trivial to change this.
If you can provide a PR with a test that passes all existing tests, we are happy to take a look at this.

**Comment by cary-smith** [comment]
I will take a look and submit one. Thanks for the fast feedback!

**Comment by gkalpak** [comment]
The real issue, of course, is that polyfills (or any code that affects built-ins in general) should always be loaded before anything else. Even if this workaround works in your case, it might break in others (because Angular still uses the original (unpolyfilled) `toString = Object.prototype.toString` (even if the polyfilled `Object.prototype.toString` is used for the `hasCustomToString()` check).

I am not too keen on "fixing" this in the proposed way, because the fix is not 100% correct.

**Comment by cary-smith** [comment]
I am going to close this until I can actually address it. I do appreciate the responses.

**Comment by epimeth** [comment]
Ok guys, dead thread I kind of need to revive.  Of course, by the time anything is done about this I will have put into place a workaround for my immediate problem, but honestly this is a little more than "inconvenient" because this functionality is absolutely broken in IE.  We can go on and on about my immediate issue but honestly, I think we're all aware of the reasons and implications of what is happening here.

Bottom line for me is that @gkalpak 's concerns about the fix being "not 100% correct" is a silly concern because *the current implementation is most certainly not 100% correct*.  In my opinion, the proposed solution is actually more correct than the current implementation as any potential argument being sent to `hasCustomToString` that does *not* ultimately inherit from `Object` would most certainly also not use the global `toString` as well.

If not for me then for the next guy!  But really, for me :-)

**Comment by Narretz** [comment]
Hi @epimeth , AngularJS is in Long Term Support mode, so this issue will not get addressed in the future.

**Comment by epimeth** [comment]
OK so I couldn't actually replicate this.  Weirdest thing ever...

So the angular source has `var ...... toString = Object.prototype.toString ....` right near the top.  In the angular-seed project this results in `hasCustomToString` later being correct.  It also has the side effect of running `toString === Object.prototype.toString` in the IE console after the page has run resulting in `true`... not so for my project.  No idea why not.  A grep for `toString\s* =` across my project yields nothing of value.

If, like me, you are experiencing a problem with `<my-directive my-prop={{some.property}}>` and getting a runtime error of `unexpected token` when you `attrs.$observe('myProp', function(myProp) { ... })` in your link function, know that I fixed this by changing the html to `<my-directive my-prop={{some.property | json}}>`.  Assuming you `scope$eval(myProp)` in the observe function you'll get exactly the same result as you should have to begin with... After all, the `stringify` function that is called on the interpolated property resulting in trying to parse `[object Object]` (incorrect result due to hasCustomToString` returning `true` simply does a `toJson` when `hasCustomToString` is false, anyway! :-D
