### ISSUE TITLE
Step validation?!

### ISSUE THREAD

**Issue by thany** [angular/angular.js#16218]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

Add any form with a number input like this:
```
<input type=number min=0 max=100 step=10>
```
And make sure it's hooked up to a controller and yadayada, nothing special. Then, enter a value of 5 and look at how it validates.

**Expected / new behavior:**

A value of 20 in the input above works fine. A value of 5 doesn't. A validator `step` kicks in.

Wat.

The value is between 0 and 100, that's all that counts. The `step` attribute is not a thing to be validated. It's *only* a hint to the browser to tell it how the spinner buttons should work, if any. Nothing. More.

**Minimal reproduction of the problem with instructions:**

Here it is: http://embed.plnkr.co/eOc58EjK3CuwmA8cqed8/

**AngularJS version:** 1.6.6

**Browser:** Firefox, Edge, Chrome (on desktop). Haven't tried on mobile.

**Anything else:**

Just add `ng-step=1` To work around this issue.

I suppose the main problem is that this behaviour was added somewhere between Angular 1.4 and 1.6. Even if the spec says the step specifies a "required" granularity for the value ([tucked away in brackets](https://www.w3.org/TR/html5/forms.html#the-step-attribute)), I imagine loads of people expect it to be solely a hint to control the spinner buttons and not trigger any validation errors. Ergo, this change, whenever it was, will break certain pages, and must therefor be optional. But I don't see it being an option in, say, ngModelOptions.

**Comment by gkalpak** [comment]
The step is actually very clear about that:

> **Constraint validation**: When the element has an allowed value step, and the result of applying the algorithm to convert a string to a number to the string given by the element's value is a number, and that number subtracted from the step base is not an integral multiple of the allowed value step, the element is suffering from a step mismatch.

AngularJS implements the spec and our behavior is also consistent with how browsers' native validation works. 

##
You can always overwrite the built-in `step` validator (e.g. with a custom `step` directive to apply it on every instance through-out the app), but the current behavior is by design.
(Note that older versions did not support `step` at all and thus you wouldn't get such errors.)

**Comment by thany** [comment]
Does NOT "work as expected", if you're upgrading from an older version of Angular! My app worked as expected, but not after the update.

What you may think is correct and by design and all that, others may not.

Anyway, none of this takes away the requirement for an option of what exactly to check. Creating a whole new directive to *remove* unwanted functionality seems reversed to me.

**Comment by gkalpak** [comment]
> Does NOT "work as expected", if you're upgrading from an older version of Angular! My app worked as expected, but not after the update.

According to our version policy, breaking changes are allowed between minor AngularJS versions. All breaking changes are documented in the [changelog][1], as well as the [migration guide][2] (when possible with instructons of how to migrate your apps or revert to the old behavior).

You should always refer to the chngelog and/or migration guide upgrading from an earlier minor version.

You can find the `step`-related breaking change in the "Breaking Changes" section of the [1.6.0-rc.0][3] and the [1.6.0][4] releases (you have to scroll to down to the end of the breaking changes list) and also in the [1.5-to-1.6 section] of the migration guide.
Both places make it clear that the new `step` validator follows the spec and give instructions on how to revert to the old behavior if desired.

##
> What you may think is correct and by design and all that, others may not.

When I say it is "by design", I mean it behaves the way we designed and implemented it. So, the behavior is intentional (for better or worse). I didn't use the word "correct". I said it follows the spec (which is objectively true - I am not judging whether the spec is "correct" or "good") and that iconsequently it is consistent with the browsers native validators (since they also follow the spec), which we strive for with all AngularJS validators that have native counterparts. 

##
> Anyway, none of this takes away the requirement for an option of what exactly to check. Creating a whole new directive to remove unwanted functionality seems reversed to me.

Let's agree we disagree on that. What if someone decides they don't want the `min` or `required` validators to work the way they do? Having configuration options for every validator is unnecessary overkill imo. [As documented][6], it is already possible to overwrite or remove any of the built-in validators (in the edgecase where you don't want your validators to work according to the spec 😛) and adding a tiny directive seems fine to me.
<sub>(Again we don't have to agree on that :grin:)</sub>

##
I understand that upgrading from 1.5.x to 1.6.x involves a lot of breaking changes and can seem like a big undertaking. However, the great majority of breaking changes are either not affecting most apps or really trivial to adapt to, so hopefully the process ends up being much easier than anticipated. But there are still some subtle ones that could bite you. 

We are always happy to discuss any ideas on how to improve the migration guide (or the upgrade process in general).

[1]: https://github.com/angular/angular.js/blob/master/CHANGELOG.md
[2]: https://docs.angularjs.org/guide/migration#migrating-from-1-5-to-1-6
[3]: https://github.com/angular/angular.js/blob/master/CHANGELOG.md#160-rc0-bracing-vortex-2016-10-26
[4]: https://github.com/angular/angular.js/blob/master/CHANGELOG.md#160-rainbow-tsunami-2016-12-08
[5]: https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-directives-input%5Bnumber%5D
[6]: https://docs.angularjs.org/guide/forms#modifying-built-in-validators
