### ISSUE TITLE
Bug report with expression close to 0 (zero)

### ISSUE THREAD

**Issue by enrybisco** [angular/angular.js#16223]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by enrybisco** [comment]
Angular 1.6 doesn't work with the below and 0 input is consider as 0.000000001 (Ang .1.2 + Chrome)

Hello I am trying to Extract VAT(or iva in Italian) but after changing one row with the vat the amount below is wrong:

totImp += (item.qty * (item.price -(item.price * item.percent/100))) / ((100 + item.iva)/100);

**Comment by gkalpak** [comment]
It isn't exactly clear what the issue is (or what version this happens on), but it sounds like have fallen victim of [Floating Point Arithmetic][1] precision issues, which are not Angular-specific.

There are several resources on how to deal with it, depending on the usecase and requirements (e.g. precision, number ranges, etc). For example, see [this question][2] for some explanations and pointers to resources.

[1]: https://en.wikipedia.org/wiki/Floating-point_arithmetic
[2]: https://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript
