### ISSUE TITLE
Nested form validation v1.6.4

### ISSUE THREAD

**Issue by yoki91** [angular/angular.js#16249]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x ] other (Please do not submit support requests here (see above))

**Current behavior:**
the isolate form validate doesn't perform correctly. It throws ctrlCopy.$setValidity is not a function error. I following the issue #5858 but the solution provided is no longer supporting the new version of angularjs. 

**Expected / new behavior:**
I want the isolate form do its own validation without propagates any changes to the parent form and vice versa

**Minimal reproduction of the problem with instructions:**
http://jsfiddle.net/j3u1xed2/
Open developer tool on Chrome, you will see the error message in console.
**AngularJS version:** 1.6.4

**Browser:** [Chrome Version 61.0.3163.100]

**Anything else:**

**Comment by gkalpak** [comment]
The example/workaround stopped working, because some of the methods it relied on were moved to the prototype of the NgModuleController, instead of the NgModelController instance itself. This is a documented breaking change.

Here is a [modified version][1] that accounts for that.

##
Please note that we cannot guarantee that community-provided workarounds and custom solutions will continue to work (especially between breaking releases), so use them at your own risk and always try to understand how/why they work.

[1]: http://jsfiddle.net/u6k8cdca/

**Comment by yoki91** [comment]
Thanks for the answer. Could you provide the document which has registered breaking change? 

Best regards

**Comment by gkalpak** [comment]
You can read about all breaking changes in the [changelog][1].
Also, the [migration guide][2] has useful info on upgrading between minor (breaking) versions.

[1]: https://github.com/angular/angular.js/blob/master/CHANGELOG.md
[2]: https://docs.angularjs.org/guide/migration
