### ISSUE TITLE
ngAnimate keeping element visible if it has any CSS animation despite ng-if condition being false

### ISSUE THREAD

**Issue by adamreisnz** [angular/angular.js#16289]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
The "checked" and "spinning" icons co-exists for some time, because ngAnimate causes the element not to be removed via `ng-if` while the CSS animation is running.

**Expected / new behavior:**
If there are no classes like `ng-enter` etc. added to an element, I don't expect `ngAnimate` to interact with the element at all through `ng-if`.

**Minimal reproduction of the problem with instructions:**
http://jsfiddle.net/hqstmc8e/1/

1) Observe incorrect behaviour when status switches from busy to ok.
2) Remove the dependency on `ngAnimate`
3) Run again and observe it working as expected

**AngularJS version:** 1.6.6

**Browser:** Chrome, probably all

**Anything else:**
I thought `ngAnimate` only binds itself to elements that have classes like `.ng-enter` etc. But in this fiddle it is demonstrated that `ngAminate` is not hiding the spinning element until the css animation is finished, causing the success and spinning icons to co-exists for a while.

I don't think this is the intended behaviour, as there are no ngAnimage trigger classes defined in the CSS for the elements.

Any thoughts on how to fix this without removing the dependency on `ngAnimate`?

**Comment by adamreisnz** [comment]
I managed to "fix" it using `$animateProvider.classNameFilter(/angular-animate/);`, but I was under the impression that ngAnimate would *not* apply itself to any and all elements with an animation/transition, only ones where you specify `ng-enter` `ng-leave` classes etc.

**Comment by adamreisnz** [comment]
Reading the guide again, I found:

> For CSS transitions, the transition code **must** be defined within the starting CSS class (in this case .ng-enter). The destination class is what the transition will animate towards.

So it definitely looks like a bug. I don't have the starting CSS class defined, so I don't know why ngAnimate is picking up on the animation.

**Comment by gkalpak** [comment]
I think you are reading this incorrectly. What the docs are saying is that you should not put the transition into the destination class (e.g. `.ng-enter-active`), because that will be applid too late. You need to apply the transition in a class that will be available at the beginning of the animation (such as the starting class - e.g. `.ng-enter`).

`ngAnimate` does not really know what styles are defined in your app (and whether you have an `.ng-enter` style that would apply to your element (and not be overwritten by another style and what not). This is CSS's and browers responsibility. `ngAnimate` picks the applied styles (e.g. `transition`) and uses them to animate the element.

It also adds some classes that help you apply these styles in appropriate moments for the animation to work (e.g. `.ng-enter`/`.ng-enter-active`/`.ng-leave`/etc). It is your responsibility to specify CSS styles that will result in the desired animation behavior.

##
In your case, you are specifying a transition on a class that is always present on the element. You are essentially saying that at any point in time (including when `ngAnimate` is trying to animate the element into or out of the view) this element should have a transition.

If you oly want to have a transition for the entering element, you should add the `.ng-enter` class on the CSS selector of the rule:

```css
.u-Spinning--reverse.ng-enter {
  animation: spin-reverse 1s linear infinite;
}
```

[Updated demo 1][1]

##
Or, as in your case, when you want an animation/transition style to be always on, but not affect animations, you can use the `.ng-animate` class (which is only aplied during animations) in your selector:

```css
.u-Spinning--reverse:not(.ng-animate) {
  animation: spin-reverse 1s linear infinite;
}
```

[Updated demo 2][2]

##
Closing since it works as expected.

[1]: http://jsfiddle.net/hqstmc8e/2/
[2]: http://jsfiddle.net/hqstmc8e/4/

**Comment by adamreisnz** [comment]
> In your case, you are specifying a transition on a class that is always present on the element. You are essentially saying that at any point in time (including when ngAnimate is trying to animate the element into or out of the view) this element should have a transition.

Yes that is correct, the element needs to be spinning, whenever that spinning class is applied to it.

Thanks for the updated demo 2, that does the job, I'll use the `:not(.ng-animate)` directive!
