### ISSUE TITLE
Angularjs undocumented redirectTo behavior change between 1.4 and 1.6

### ISSUE THREAD

**Issue by simonrenoult** [angular/angular.js#16291]
**I'm submitting a ...**
- [x] bug report (might be a bug or a missing documentation)
- [x] other 

**Current behavior:**
Using the `redirectTo` instruction with AngularJS@1.6 redirects the browser from `/#/reset/test@example.com/foobar1234` to `/#!/home#%2Freset%2Ftest@example.com%2Ffoobar1234`

**Expected / new behavior:**
Using this instruction with AngularJS@1.4 redirects the browser from `/#/reset/test@example.com/foobar1234` to `/#/home?email=test@example.com&token=foobar1234`.

This might be an expected behavior, however I can't find any mention if it in the migration guides (https://docs.angularjs.org/guide/migration). Is this supposed to happen? Should I change my code base?

**Minimal reproduction of the problem with instructions:**
```js
angular
  .module("app.test", ["ngRoute"])
  .config($routeProvider =>
    $routeProvider.when("/reset/:email/:token", { redirectTo: "/home" })
  )
```

The result differ depending on your AngularJS version, difference not mentioned in the documentation.

**AngularJS version:** 1.6.6

**Browser:** [Firefox 57 | Firefox 45]

Is there a way to preserve the `AngularJS@1.4` behavior?

**Comment by gkalpak** [comment]
There was no change specific to `redirectTo`. It is the result of changing the default hash-prefix for `$location`'s hashbang mode (as documented [here][1] and in the changelog). This was a breaking change in 1.6.

So, previously, `/#/reset/...` would be interpreted as having `/reset/...` as the path (and redirect according to your config). In 1.6 - by default - `/#/reset/...` is interpreted as having an empty path and having `/reset/...` as the hash. In your case, I assume you have a catch-all or empty route that also redirects to `/home` and that is why you end up with `/#!/home#%2Freset%2Ftest@example.com%2Ffoobar1234`.

##
So, to solve this you need to either set the hash-prefix back to `#` (via `$locationProvider.hashPrefix('#')` or change the URL to `/#!/reset/...`.

<sub>Closing, since everything works as expected and is documented.</sub>

[1]: https://docs.angularjs.org/guide/migration#commit-aa077e8

**Comment by simonrenoult** [comment]
It's obvious now you say it. We changed all our urls when migrating to 1.6.6 excepted the ones generated by our backend. Thanks!
