### ISSUE TITLE
nRepeat with dynamic textbox addition and value multiply

### ISSUE THREAD

**Issue by M1991** [angular/angular.js#16341]
# ngRepeat with dynamic addition and deletion

I am trying to add multiple text boxes with ng-repeat, that dynamically adds 3 text boxes and upon entering value to 1st and 2nd text box shows the result in 3rd text box.

The problem is data is not passed to controller and again not returning the product of two numbers back to view for each number pair. Below provided are the Image and fiddle for reference.

[Fiddle Link](https://jsfiddle.net/Manoj_89/158dz3nz/)

![ng-repeat_multiple](https://user-images.githubusercontent.com/22197822/33171145-277d91da-d071-11e7-813b-9fdba783878e.jpg)

![ng-repeat_multiple2](https://user-images.githubusercontent.com/22197822/33171325-a5c4accc-d071-11e7-82a0-fbde22b3934e.jpg)

Logic: Get the values of 1st and 2nd text Box by ng-change. Each change will pass data to controller. The controller will return the product. The total product array will be added and saved in DB getting the values from model as IEnumerable list(using C# in backend).

Could you help me with this please?
Thanks

**Comment by petebacondarwin** [comment]
@M1991 - this is a support question and not a bug with AngularJS. Please use one of our [support channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question) for this kind of request.

But as I am here, I notice that you are assigning the email property on the array rather than the item that changed: 

```
$scope.personalDetails.email = total;
```

and there are various other problems with that compute function.
