### ISSUE TITLE
ngMin/ngMax validators don't work with input[type=range] 

### ISSUE THREAD

**Issue by splatonov92** [angular/angular.js#16415]
I'm submitting a bug report
Current behavior: ngMin/ngMax validators don't work with input[type=range]
Expected behavior: this should work

**Comment by Narretz** [comment]
So, I personally removed the ngMin / ngMax support here: https://github.com/angular/angular.js/commit/a272a3c0bd88b6df354102dc059a0d14b5b22675#diff-c244afd8def7f268b16ee91a0341c4b2 because it doesn't really work with browsers that support range inputs.
This is in the docs: https://code.angularjs.org/1.6.8/docs/api/ng/input/input[range]

However, I forgot to remove the example from the page.

You should use normal "min" and "max" instead.

**Comment by Narretz** [comment]
Actually, input range wasn't supported before 1.6.0, and all the changes to it were made before 1.6.0 wa released, so no Breaking Change notice is needed.
