### ISSUE TITLE
ng-model value bug with "month" input type

### ISSUE THREAD

**Issue by jdussouillez** [angular/angular.js#16430]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
The ng-model value is wrong when changing a input of type "month" (type only implemented in Chrome and Edge). The bug happens with some dates, but not all.

On the angularjs docs website, you have [this example](https://docs.angularjs.org/api/ng/input/input%5Bmonth%5D#examples) which works. But if you change the date to `new Date(2018, 0, 31)` and then you choose February (using the popup or using the up arrow) the ng-model value is not 2018-02(...) as expected but 2018-**03**(...).
But it works as expected if the date is `new Date(2018, 0, 1)`.

Demo : 

![image](https://user-images.githubusercontent.com/5428355/35618163-6b551ccc-067a-11e8-8d18-08bbfa599909.png)
Then: change month to february by clicking on the up arrow. Results :

![image](https://user-images.githubusercontent.com/5428355/35618198-85ed9ffa-067a-11e8-949a-482644b5b0a9.png)

_"janvier" is french for "january" and "février" for "february"_

**Expected / new behavior:**
When incrementing the month of the date 2018-01-31, the date variable in the ng-model should be 2018-02.

**Minimal reproduction of the problem with instructions:**
[JSFiddle with the bug](https://plnkr.co/edit/5TXVE0eqV8dNDoTRmy3B?p=preview)

**AngularJS version:** 1.6.6 / 1.6.7 / 1.6.8 / snapshot

**Browser:**
Chrome 64.0.3282.119 (64bit)
Edge 41.16299.150

**Anything else:**
I tried with UTC dates but it didn't fix the issue (I'm in UTC+1).

**Comment by gkalpak** [comment]
This is expected behavior imo. Since February does not have 31 days, it is typical JavaScript behavior to "overflow" the extra days and end up in the next month. E.g. `new Date(2018, 1, 31)` ends up as March 3rd.
I don't think any other behavior would be "more correct". It is your responsibility to use a date and timezone that will not cause "overflows". Typically using `1` is safe (and is the default when omitting the `date` part: `new Date(2018, 1) --> February 1, 2018`). If you are also switching timezones, you might want to choose something like 15 (`new Date(2018, 1, 15)`), which is safer :)

**Comment by jdussouillez** [comment]
I know the standard behavior is to overflow when using dates. But since the type is explicitely "month" I thought the calculation would be different and stop to the last day of the month instead of overflowing. My bad !
Thanks anyway !
