### ISSUE TITLE
Images not loading in docs

### ISSUE THREAD

**Issue by Kapeli** [angular/angular.js#16438]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

Images at https://code.angularjs.org/1.6.9/docs/guide/databinding aren't displayed

**Expected / new behavior:**

Images should be displayed

**Minimal reproduction of the problem with instructions:**

Open https://code.angularjs.org/1.6.9/docs/guide/databinding in browser

**AngularJS version:** 1.6.7+

Docs for 1.6.7 through 1.6.9 seem to be affected

**Browser:** [all]

**Comment by Narretz** [comment]
Looks like they are gone for basically every version. Either a problem with the firebase function or with the firebase cdn. The files exist in storage.

**Comment by Narretz** [comment]
So:

- this actually affects all image files in the docs, with the exception of the svg (?) (header file is svg)
- the files is correctly displayed when opened directly with the gcs download url - so it's not corrupted by the upload
- I can also download it when running the firebase functions locally (on Windows)
- This seems to be because We gzip all docs files before upload. GCS can transcode these, but with images it does something special (because you really shouldnt gzip them ...): https://cloud.google.com/storage/docs/transcoding
- however, that doesn't really explain why it works when I serve the function locally

**Comment by Narretz** [comment]
I've replaced the non-loading image files in 1.6.7 - 1.6.9, and removed the compression during deployment. I suspect that the Travis plugin for deploying to gcs uses and older version that cannot handle the compression correctly, because the older versions were uploaded with a local script, and these image files can be loaded.
