### ISSUE TITLE
ng-attr- used for custom directive. If expression is undefined, still fires directive link function, even though the directive is not added in the DOM.

### ISSUE THREAD

**Issue by piyushsh** [angular/angular.js#16441]
I'm submitting a bug, regarding `ng-attr-` directive, used to conditionally add directive (as an attribute), if expression is undefined, still fires `link` function of the directive, even though directive is not added in the DOM.

**Current behavior:**
Refer [plunker](https://plnkr.co/edit/rTUfUnlT6CGB8pbYcw0c?p=preview)
- Added conditional directive (as an attribute), using `ng-attr-test-directive` (as mentioned in plunker).
- Even though `ng-attr-` expression is `undefined` and directive is not added in the DOM, the `link` function of the directive is fired (check console while executing plunker)
![image](https://user-images.githubusercontent.com/10875373/35929519-95a0a0f2-0c27-11e8-94d3-4e782ca76bb9.png)

**Expected / new behavior:**
When `ng-attr-` expression is undefined, 
- It shouldn't add directive to the DOM.
- It should not call link function of the directive as well.

**Minimal reproduction of the problem with instructions:**
Please refer [plunker](https://plnkr.co/edit/rTUfUnlT6CGB8pbYcw0c?p=preview)
Same repo steps as mentioned in Current behavior.

**AngularJS version:** 1.6.4
Yes it is an issue.

**Browser:** [all | Chrome 63.0.3239.132 | Firefox |
OS: Windows 10

**Comment by gkalpak** [comment]
This is expected behavior I'm afraid. `ng-attr-` is not a way to conditionally apply directives. Even if it allows conditionally adding/removing an attribute, this behavior depends on evaluating an expression in the context of the current scope, which cannot happen during the compilation phase (when the directives on an element are collected and processed).

You need to devise a different way (depending on your usecase) to conditionally apply directives (e.g. use `ng-switch` and have two versions of the HTML; one with the directive and one without, or have terminal directive with high priority that evaluates the expression during the linking phase, applies the necessary directive(s) and compiles the element).

**Comment by piyushsh** [comment]
@gkalpak Thanks for your reply, makes sense.
