### ISSUE TITLE
Android webview can not open angular5  url， blank view 

### ISSUE THREAD

**Issue by pipagg** [angular/angular.js#16529]
we use angular5 to make html5 view in android and ios native app. so the Hybrid App。but 
Android use the  webview can not open angular5  url , can only see blank view.
the android console can see is the bundle js error . 
the angular code is simple . only a button in the view . when click it , can go back.
the goback() I write in the index.html

**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by gkalpak** [comment]
This repo is for AngularJS (a.k.a 1.x). Since you re using Angular v5 (a.k.a. Angular), use https://github.com/angular/angular instead.

That said, this sounds like a support request (i.e. it doesn't fall into the bug report or feature request category). The Angular issue tracker is not suitable for support requests, consider reposting your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

<sub>If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).</sub>

**Comment by pipagg** [comment]
thank you for your replay
