### ISSUE TITLE
angular.lowercase is undefined

### ISSUE THREAD

**Issue by ITGuy9401** [angular/angular.js#16563]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
Using a library that uses the angular.lowercase function (in my case, textAngular, a WYSIWYG html editor) it breaks down because angular.lowercase was undefined

**Expected / new behavior:**

angular.lowercase should be a function that returns the lowercase of the given input

**Minimal reproduction of the problem with instructions:**

install angular >= 1.7.0
install textAngular latest version

**AngularJS version:** 1.7.0

**Browser:** [all]

**Anything else:**

**Comment by frekele** [comment]
Hi @ITGuy9401 ,

of according to the migration guide: https://code.angularjs.org/1.7.0-rc.0/docs/guide/migration#migrating-from-1-6-to-1-7 this is not an AngularJS bug but a textAngular support update for AngularJS 1.7.x;

The bug should be opened here, https://github.com/textAngular/textAngular .

Hope this helps.

**Comment by jbedard** [comment]
The `lowercase` and `uppercase` methods have been deprecated since 1.5 were removed from the public API in 1.7 (1daa4f2231a89ee88345689f001805ffffa9e7de).

Ideally the textAngular library would not be using these methods and I'd recommend filing a bug there.

For now you could add the methods back yourself if you want...
