### ISSUE TITLE
async/await in agnularjs

### ISSUE THREAD

**Issue by yongqingxie** [angular/angular.js#16578]
i use async/await in agnularjs ,when i remove some data from angular's list ,the html page can't update  ,only when $scope.$apply() . for example:
`const remove=async ()=>{
const obj=await ajaxrequest();
if(obj.data.success){
$scope.row.splice(data, 1);//html page can't update
$scope.$apply();// if i add this code,html page can update
}
};
`
angularjs version:v1.6.6
browser:google chrome 66.0.3359.181

**Comment by gkalpak** [comment]
This is expected. Only the built-in `$q` promise library is integrated with the `$digest` cycle (i.e. runs a `$digest` when promises are resolved). If you use another promise library or native promises (including `async/await`, then you have to manually trigger the `$digest`.

**Comment by jamie-pate** [comment]
I was hoping someone would have bright ideas for a zone.js style intervention to allow this feature `automagically` in angularjs.  Now that all the evergreen browsers support native async/await it's kind of painful to use angularjs.

Extensions like https://github.com/ben-hunter-hansen/angular-async-await technically work but are very cumbersome to use.

**Comment by jamie-pate** [comment]
One idea might be to modify class instances during injection (with an opt-in?) wrapping all members which are `instanceof AsyncFunction` (`Object.getPrototypeOf(async function() {}).constructor`  => `AsyncFunction`)

**Comment by langdonx** [comment]
> I was hoping someone would have bright ideas

Same... this is the only new language feature I'm unable to use at the moment. I've tried a bunch of different things so far...

- http://jsfiddle.net/langdonx/n4qysvrz/1/ Baseline implementation...
- http://jsfiddle.net/langdonx/n4qysvrz/2/ My first discovery was that I couldn't even mark a controller as async.  It just doesn't do anything.  Not sure why exactly...
- http://jsfiddle.net/langdonx/n4qysvrz/3/ It doesn't really matter though, because you can wrap the code in an IIFE, but really, everything you'd be writing would exist inside a method ($onInit or otherwise) which is just fine being marked as async.
- http://jsfiddle.net/langdonx/n4qysvrz/7/ And then the moment of truth, but as you know, it doesn't digest.
- http://jsfiddle.net/langdonx/n4qysvrz/8/ I was hoping it would magically work with `window.Promise = $q`, but it didn't.
- http://jsfiddle.net/langdonx/n4qysvrz/9/ Of course using `new Promise` in lieu of `$q` in `TestService` and calling it without await still works fine.

At this point, I thinking maybe I can do something with Babel, which I'm already using but currently fails to even compile async/await.

**Comment by jamie-pate** [comment]
For our team I've implemented a base class you can inherit from which wraps all asynchronous functions so that they actually return a $q instead of a Promise.

I used the mixing pattern to allow inheriting from another base class as well. 
http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/

**Comment by miluoshi** [comment]
I just needed to await ui-router transitions in my tests and as ui-router uses $q promises I was looking for a workaround. In case anyone is looking for the solution, this worked for me:

```typescript
function goToState(...params: Parameters<ng.ui.StateService['go']>) {
  // `inject` is my helper function to inject services anywhere in the code. 
  // You can use something like `angular.element(document.body).injector().get('ServiceName')`
  const $state = inject('$state')
  const $rootScope = inject('$rootScope') as ng.IRootScopeService

  // ui-router uses $q promises which depend on digest cycle to be resolved.
  // We need to run digest cycle first to resolve $q promise (and call it's .then callback)
  // and return native Promise so it can be await-ed.
  const transitionQPromise = $state.go.apply(null, params)
  const transitionPromise = new Promise((resolve, reject) => {
    transitionQPromise.then(resolve).catch(reject)
  })
  $rootScope.$digest()

  return transitionPromise
}

// then in test file:
test('makes transition', async () => {
  await goToState('existingState')

  expect($state.$current.name).toBe('existingState')
})
```

**Comment by swar30** [comment]
In my case, when compilation target is ES5, this does the job most of the time `window['Promise'] = $q;` (inside a `run` block).

When compiling to ES6 / ESNext and using native async / await, above will not do the trick and need to add (again inside `run` block)

```typescript
	function patchNativePromiseWithInterceptor() {
		const originalThen = Promise.prototype.then;

		Promise.prototype.then = function promiseThenInterceptor() {
			const promise = originalThen.apply(this, arguments);

			originalThen.call(promise, triggerDigestIfNeeded, triggerDigestIfNeeded);

			function triggerDigestIfNeeded() {
				const phase = $rootScope.$$phase;
				const insideDigest = phase === '$apply' || phase === '$digest';
				const alreadyHasScheduledWork = $rootScope['$$applyAsyncQueue'].length > 0;

				if (insideDigest || alreadyHasScheduledWork) {
					return;
				}

				$rootScope.$applyAsync();
			}

			return promise;
		} as any;
	}
```

This will do the trick for many flows, in which using some kind of mix of async / await and `Promise`.
If whole flow is written using async / await, it might not trigger digest

**Comment by swar30** [comment]
@langdonx just found https://github.com/noppa/babel-plugin-angularjs-digest-await and it seems to do the trick

**Comment by Fundebug** [comment]
@swar30 I tried [babel-plugin-angularjs-digest-await](https://github.com/noppa/babel-plugin-angularjs-digest-await), but it is not working.

Here is my babel setting:

```javascript
{
    "sourceMap": true,
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "chrome": 56,
                    "ie": "11"
                }
            }
        ]
    ],
    "plugins": ["angularjs-digest-await"]
}
```

Here is some component version of my project:

```
"angular": "~1.5.8",
"@babel/core": "^7.1.2",
"@babel/preset-env": "^7.1.0",
"babel-plugin-angularjs-digest-await": "^2.0.0",
```

**Comment by swar30** [comment]
@Fundebug try dropping `IE 11` from targets, and change chrome to `last 1 chrome version`, like so:

```js
		presets: [
			[
				'@babel/env',
				{
					targets: {
						browsers: ['last 1 chrome version', 'last 1 firefox version'],
					},
				},
			],
		],

```

May be it would be better to move discussion regarding `babel-plugin-angularjs-digest-await` to https://github.com/noppa/babel-plugin-angularjs-digest-await

**Comment by Fundebug** [comment]
@swar30 Thanks for your reply. I have to stick to IE 11, otherwise my "grunt build" pipeline will fail,  it's another problem...

**Comment by swar30** [comment]
@Fundebug I meant just as a way to verify that it's not working because of configuration.

Have you tried my initial proposed solution, of overriding `then` in native promise?

That should work by itself if you are building for IE11, in my case I used Babel plugin because that solution but itself does not work if target is latest chrome
