### ISSUE TITLE
The ngBlur repeatly fired when lose focus by click somewhere out off the web(like the windows os task bar)

### ISSUE THREAD

**Issue by Tommy-White** [angular/angular.js#16576]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

The ngBlur repeatly fired when lose focus by click somewhere out off the web(like the windows os task bar).

**Expected / new behavior:**

No matter how it will lose focus, the ngBlur should be fired only once.

**Minimal reproduction of the problem with instructions:**

Demo like this: https://jsfiddle.net/TommyLee/qp0hfxay/1/

**AngularJS version:** 1.x.y

AngularJS version: 1.4.8

**Browser:** [Chrome XX | Edge XX | IE XX ] has under the test, showed same problem.

**Anything else:**

**Comment by frederikprijck** [comment]
Hey @Tommy-White ,

When I look at that jsfiddle, the ng-blur callback is executed once when clicking outside of the textbox.
![image](https://user-images.githubusercontent.com/2146903/40467948-0f675bea-5f2c-11e8-964b-7b20a74cc70b.png)

I tried clicking both inside the web page and outside the browser to lose focus, both result in a single ngBlur callback execution.

**Comment by gkalpak** [comment]
I can reproduce the issue on Chrome/Windows 10, when clicking on Windows' taskbar.
@Tommy-White, the observed behavior is a result of how the browser/Windows handles focus when showing an `alert()`. It seems that showing the alert focuses the browser, then clicking the OK button closes the alert and briefly focuses the page (i.e. the text field) before blurring it again (creating another alert).

If you change your `alert()` to `console.log()` for example, you will see that `ngBlur` fires only once.
In any case, `ngBlur` just hooks into the `blur` event, so whanever that is fired `ngBlur` is fired as well. Anything you do with `ngBlur` you could have done with `.addEventListener('blur', ...)`, so any unexpected behavior is caused by the browser/OS.
