### ISSUE TITLE
ng-max allows inputs to exceed max value with up arrow

### ISSUE THREAD

**Issue by georgeawg** [angular/angular.js#16628]
**I'm submitting a ...**

- [ x] bug report
- [ ] feature request
- [ ] other 

**Expected / new behavior:**

The number should stop increasing when 100 is reached with both `ng-max` and `max`.

**Minimal reproduction of the problem with instructions:**

See Stackoverflow: [AngularJS ng-max with expression (with DEMO of bug)](https://stackoverflow.com/questions/51311106/angularjs-ng-max-with-expression-with-demo-of-bug/51311384#51311384)

**AngularJS version:** 1.7.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Verified on Chrome

**Anything else:**

**Comment by gkalpak** [comment]
The purpose of `ngMax` (and other similar `ng`-prefixed validation directives) is to not affect browser behavior but only AngularJS validation state. If you want to also affect browser behavior, either use their non-`ng`-prefixed counterparts (to apply default browser behavior, in addition to AngularJS validation) or create your own directives (to apply custom behavior).

Closing, since it works as expected.
