### ISSUE TITLE
Checkbox model not updated before onClick is fired

### ISSUE THREAD

**Issue by farlock85** [angular/angular.js#16631]
**I'm submitting a ...**

- [X] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
The model attached to a checkbox isn't updated before the onClick is called.

**Expected / new behavior:**
Before 1.7 the model would have assumed the new value from the clicked checkbox before going in the click handler, now you need a 1 tick delay before the model is set.

**Minimal reproduction of the problem with instructions:**
https://codepen.io/anon/pen/pZyrZE
See the console output

**AngularJS version:** 1.7.3

**Browser:** All

**Comment by gkalpak** [comment]
This is due to a [documented][1] breaking change in 1.7.x. The fix depends on your usecase, but you might just need to change `ng-click` to `ng-change` (which btw is a special `ngModel`-specific directive and does bind to the native `change` event, but works similarly).

[1]: https://docs.angularjs.org/guide/migration#-input-radio-and-input-checkbox-
