### ISSUE TITLE
ng-model-option for the keydown event is not working for the first key down 

### ISSUE THREAD

**Issue by thirukumarangceb** [angular/angular.js#16687]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

First key down value is not updated. but the second value is working properly 
https://docs.angularjs.org/guide/forms#custom-model-update-triggers 

**Expected / new behavior:**

Entered value should updated immediately after the key down event. 

**Minimal reproduction of the problem with instructions:**

https://plnkr.co/edit/WCxpmXpDpUuV4Z396Pnp?p=preview

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Anything else:**

**Comment by gkalpak** [comment]
You my have noticed that essentially the `ngModel` value is always on character behind. This happens because on `keydown` the value of the input is not updated yet. Thus `ngModel` is updated with the value that is assigned to the input before the current key was pressed.

I am going to close this issue, since `ngModel`/`ngModelOptions` work as expected here, but feel free to continue the discussion below.

##
OOC, why do you want to use `keydown` instead of the default behavior?

**Comment by thirukumarangceb** [comment]
@gkalpak  Thanks for the clarification. the keydown events fires before the ngModel value is updated.
