### ISSUE TITLE
Wrong behaviour of radio input inside ng-repeat with double values

### ISSUE THREAD

**Issue by emaborsa** [angular/angular.js#16690]
**I'm submitting a ...**
- [ x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
I created a ng-repeat with a radio input inside. It bevavies strange when the ng-model of the radio is a nested object (ie. ng-model="data.fieldName"). Otherwise (ng-model="fieldName") it works fine.

**Expected / new behavior:**
As a radio usually behavies

**Minimal reproduction of the problem with instructions:**
Here the [plunker](https://next.plnkr.co/edit/ytKRYvbEDaZShRC9?open=lib%2Fscript.js&deferRun=1&preview).
The third radio works fine since it has no dupes. The first one has dupes but the ng-model is local and also works fine. The second one has dupes, is global and does not really works fine: Try to select _'Tetst2'_ and then select one of the _'Test'_ .

**AngularJS version:** 
1.2.9 and 1.7.2

**Browser:** 
Tested on Chrome, IE11, Edge. Same problem on all browsers

**Anything else:**
Here again the code:

&lt;table ng-app="myApp" ng-controller="myCtrl"&gt;
&nbsp;&nbsp;&lt;tr&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;td class="ms-cellstyle ms-vb2 hgv_data" ng-repeat="i in data"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;input type="radio" ng-model="thisWorks" name="Title" ng-value="i.Title"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;span&gt;{{i.Title}}&lt;/span&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/td&gt;
&nbsp;&nbsp;&lt;/tr&gt;
&nbsp;&nbsp;&lt;tr&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;td class="ms-cellstyle ms-vb2 hgv_data" ng-repeat="i in data"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;input type="radio" ng-model="data.thisDoesNotWork" name="Title" ng-value="i.Title"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;span&gt;{{i.Title}}&lt;/span&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/td&gt;
&nbsp;&nbsp;&lt;/tr&gt;
&nbsp;&nbsp;&lt;tr&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;td class="ms-cellstyle ms-vb2 hgv_data" ng-repeat="i in data"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;input type="radio" ng-model="data.selectedAnotherValue" name="AnotherValue" ng-value="i.AnotherValue"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;span&gt;{{i.AnotherValue}}&lt;/span&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/td&gt;
&nbsp;&nbsp;&lt;/tr&gt;
&lt;/table&gt;

`var myApp = angular.module('myApp', []);

myApp.controller('myCtrl', ['$scope', function ($scope) {
&nbsp;&nbsp;$scope.data = [{
&nbsp;&nbsp;&nbsp;&nbsp;ID: 1,
&nbsp;&nbsp;&nbsp;&nbsp;Title: 'Test',
&nbsp;&nbsp;&nbsp;&nbsp;AnotherValue: 'hello'
&nbsp;&nbsp;}, {
&nbsp;&nbsp;&nbsp;&nbsp;ID: 2,
&nbsp;&nbsp;&nbsp;&nbsp;Title: 'Test2',
&nbsp;&nbsp;&nbsp;&nbsp;AnotherValue: 'its'
&nbsp;&nbsp;}, {
&nbsp;&nbsp;&nbsp;&nbsp;ID: 3,
&nbsp;&nbsp;&nbsp;&nbsp;Title: 'Test',
&nbsp;&nbsp;&nbsp;&nbsp;AnotherValue: 'me'
&nbsp;&nbsp;}];
}])`

**Comment by gkalpak** [comment]
This happens because you use the same name for all radio buttons in a group. This is what you need to do in traditional (non-AngularJS) apps, but AngularJS needs each radio to have a different name (they are grouped by their `ngModel` value instead).

See #15009 for more info.

**Comment by emaborsa** [comment]
Thx for your answer, I read the other issue.
I updated the plunker added the ng-name instead the name attribute.
Could you tell me if the fourth example has the right behaviour? IMHO don't think so, but don't know how to fix it.

**Comment by gkalpak** [comment]
The behavior is expected. Whether the radios are checked or not (in an AngularJS form) depends on the current value (determined by `ngModel`) and the radio's associated value (determinved by `ngValue` in your example). Since the 1st and 3rd radios have the same value (because `data[0].Title === data[2].Title === 'Test'`), whenever the model is set to `Test`, both radios will be selected (since the model value matches with their associated value).

**Comment by emaborsa** [comment]
I get the point. 
But why does the first example work?

**Comment by gkalpak** [comment]
The reason it works (which may not be obvious at first - especially if you are not familiar with scope hierarchies and [how prototypal inheritance comes into play][1]), is that `ngRepeat` creates a new (non-isolate) scope for each clone it stamps out.

So, each `td` gets its own scope, and thus each `ngModel` refers to a different `thisWorks` property (the one on its own scope). So, despite all radios seemingly binding to the same `thisWorks` property, each one will be bound on a different object (scope) and as such be different than the other ones.

What this actually means, is that they are independent as far as AngularJS is concerned (i.e. all of them could be selected at the same time and clicking the one does not affect the others through `ngModel`). But because they have the same `name` attribute, the native browser behavior kicks in and makes them a radio-group (alowing only one to be selected).

However, notice they don't actually work as expected (although they visually seem they do), since `thisWorks` will still be undefined outside of their own scopes (i.e. in the rest of the template and in your controller).

[1]: https://github.com/angular/angular.js/wiki/Dev-Guide%3A-Understanding-Scopes

**Comment by emaborsa** [comment]
I knew that ng-repeat creates a new scope. I tought a scope for the iteration itself (1 for each ng-repeat declaration) would be created, not for the single iterated item.
Thanks for the explanation.
