### ISSUE TITLE
PROPOSAL: ngMock toBeRejectedTo / toBeResolvedTo $rootScope.apply decoration

### ISSUE THREAD

**Issue by codymikol** [angular/angular.js#16744]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other 

**Current behavior:**

Currently in the jasmine framework the methods toBeRejectedTo and toBeResolvedTo can be used to test async functionality. 

You would expect the following spec to pass:

```javascript
it('should resolve the given promise', function(){
  return expect($q.resolve('AngularJS')).toBeResolvedTo('AngularJS');
}); 
```

Because no $rootScope.digest(); is made this spec will just hang until you reach the timeout limit for jasmine. 

Currently you can make this work by wrapping your expectation inside of a $rootScope.$apply:

```javascript
it('should resolve the given promise', function(){
  return $rootScope.$apply(expect($q.resolve('AngularJS')).toBeResolvedTo('AngularJS'));
}); 
```

But this isn't really obvious and it's pretty verbose.

**Expected / new behavior:**

I am proposing that if the toBeResolvedTo / toBeRejected to functionalities are present on the testing framework, we decorate them so they trigger either a digest or apply. I think this would make async specs function in a more obvious way that is easier to write.

**Minimal reproduction of the problem with instructions:**

I think with the above information this should be fairly easy to reproduce with the above snippet. It would be difficult to make a codepen for this, but if you'd really like an example, I can make a repo that demonstrates this.

**AngularJS version:** 1.x.y

N/A

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

N/A

**Anything else:**

The toBeRejectedTo functionality is not yet in a versioned release of jasmine, but my MR for this has been approved [here](https://github.com/jasmine/jasmine/pull/1615) and my MR to make jasmine support async testing in angularJS has been approved [here](https://github.com/jasmine/jasmine/pull/1613).

So if you'd like to test this out with angularJS you'll need to work off of the master branch in the jasmine project. 

I am willing to work on a MR to get this working myself, I just wanted to get some feedback that this is something the angular team would consider merging before I get started.

**Comment by gkalpak** [comment]
TBH, I think it will be more confusing than helpful to have "built-in" support for `toBeResolved/RejectedTo()`, mainly for the following reasons:

1. These matchers are meant to deal with asynchronous code. During tests, AngularJS promises are essentially synchronous (which is so exactly to make testing them much easier). So, you don't need `toBeResolved/RejectedTo()` with AngularJS promises in the first place.

2. `$digest()` has other side effects, so monkey-patching some matchers to run it, will have unexpected and hard-to-track down results for some users.

3. If someone wants to, it is quite easy to either monkey patch these matchers themselves or create their own matchers that run `$digest()` or whatever. It is also very easy to publish this as a 3rd-party lib for others to use.

##
BTW, `return $rootScope.$apply(expect($q.resolve('AngularJS')).toBeResolvedTo('AngularJS'))` is NOT correct. It works in most cases (by accident), but it can break in certain scenarios.

Basically, you are passing a promise to `$apply()` and returning the result. `$apply()` expects either a function or a string expression. Being passed a different object (a promise in this case), it will just return `undefined`. Of course, it will also call `$digest()`, which will resolve the pending AngularJS promises synchronously and let `toBeResolved/RejectedTo()` do their assertions (again synchronously). Finally, you will return `undefined` (and not a promise as you would expect) from your spec function.

This is fine in most cases, where a single `$digest` is enough to resolve the AngularJS promise. But it is also possible that the `$digest()` is not enough (e.g. having a timeout-based promise), in which case your promise will not be resolved (thus `toBeResolved/Rejectedto()` will not run their logic) and your spec function will complete synchronously, because you returned `undefined`, and not wait for the promise to be resolved.

##
Bottom line: New, shiny toys are cool, but not necessarily useful for the task at hand 😛

I am going to close this as _won't fix_, since I don't think it is a good to add it in AngularJS (especially now that we are in [LTS mode][1]), but feel free to continue the discussion below.

[1]: https://docs.angularjs.org/misc/version-support-status
