### ISSUE TITLE
ng-disabled doesn't remove "disabled" attribute when jquery is loaded

### ISSUE THREAD

**Issue by charlemagnelasse** [angular/angular.js#16778]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
ng-disable creates disabled="false"/ng-disabled="true" attributes for elements when jquery was loaded before angularjs.

**Expected / new behavior:**
disabled attribute is removed when ng-disabled evaluates to false

**Minimal reproduction of the problem with instructions:**
http://next.plnkr.co/edit/1GxYGSKho4H0nDAD
(tested in chromium)

**AngularJS version:** 1.7.5 (or whatever your server currently ships)

**Browser:** all? (tested in chrome 70.0.3538.110 | Firefox 60.3.0esr)

**Comment by gkalpak** [comment]
This is a jQuery issues. You should use jQuery 3.x with AngularJS 1.7.x anyway, and this is fixed with the latest jQuery.
Closing since this is not an AngularJS issue.

**Comment by charlemagnelasse** [comment]
Bullshit. It is not fixed with the latest jquery. Please check what is included in my example - the latest version of both:

                        <script type="text/javascript" src="https://code.jquery.com/jquery.min.js"></script>
                        <script type="text/javascript" src="https://docs.angularjs.org/angular.min.js"></script>

**Comment by charlemagnelasse** [comment]
Also tried with jqueries latest git version and it is the exact same problem

**Comment by charlemagnelasse** [comment]
And it only seems to be a problem for XHTML and not HTML

**Comment by gkalpak** [comment]
Oh interesting. The demo (which was using 2.x when I checked) didn't work for me, so I created my own demo to check and I missed the XHTML requirement. Indeed, it doesn't work as expected on XHTML. This is because jQuery detects it as an XML document and handles it differently (i.e. just sets the attribute value to true/false, even for boolean attributes).

@mgol or @jbedard might know more about this jQuery behavior.

In any case, I'm afraid there is not much we can do. It either looks like a jQuery issues/limitiation or (if it boils down to AngularJS incorrectly using the jQuery APIs on XHTML documents) it is a limitation in AngularJS we will not be addressed at this point, as we are already months deep into [LTS mode][1].

[1]: https://docs.angularjs.org/misc/version-support-status

**Comment by jbedard** [comment]
I was probably debugging this the same time as you :p

I came to the same conclusion. I don't know the history behind this though. I *thought* the XHTML vs html(5 only?) difference was `disabled="disabled"` (XHTML) vs just `disabled` with no value (html5), but the XHTML one would also work in html5 so may as well always use it. But maybe that's wrong? I think that's what jqLite does, but jQuery seems to do something different...

**Comment by mgol** [comment]
See my analysis at https://github.com/jquery/jquery/issues/4249#issuecomment-443422815. tl;dr is jQuery skips special boolean attrs treatment in XML nodes for historical reasons. I think AngularJS could call `removeAttr(attrName)` instead of `.attr(attrName, false)` for boolean attrs to avoid the issue.

**Comment by mgol** [comment]
Since we're planning a release soon this may make it as well, let's reopen.

**Comment by mgol** [comment]
PR: https://github.com/angular/angular.js/pull/16779
