### ISSUE TITLE
errorOnUnhandledRejections does not work as advertised

### ISSUE THREAD

**Issue by ashconnell** [angular/angular.js#16828]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
`$qProvider.errorOnUnhandledRejections(false)` suppresses all errors not just unhandled rejections.

**Expected / new behavior:**
`$qProvider.errorOnUnhandledRejections(false)` should only suppress unhandled rejection errors.

**Minimal reproduction of the problem with instructions:**
http://plnkr.co/edit/9lpc6KBgtSqOmxzn8ej4?p=preview

**AngularJS version:** 1.7.5

**Browser:** all

**Anything else:**
The issue in it's current form makes it extremely hard to catch REAL errors and send them to our error logging platform (Sentry)

- `errorOnUnhandledRejections(false)` results in no real errors at all being observed in console or  $exceptionHandler
- `errorOnUnhandledRejections(true)` results in tens of thousands of "Possibly unhandled rejection" errors being sent to Sentry, even though there are no real issues.

It's worth adding that we intentionally do not catch quite a lot of our promises as we expect them to result in no more actions.

**Comment by mgol** [comment]
Thanks for the report.

To be precise, `errorOnUnhandledRejections(false)` doesn't silence all errors but Promise rejections. I added a synchronous error to your Plunker and it shows up:
http://plnkr.co/edit/JErDPnK7w7d9WO9mmYRz?p=preview

AngularJS Promises are compatible with the [Promises/A+](https://promisesaplus.com/) standard that many other promise library implements. Standard ES6 promises also adhere to those rules. And that standard states errors thrown in promise handlers should be treated in the same way as returning a rejected promise.

See the motivations explained at https://blog.domenic.me/youre-missing-the-point-of-promises/ (note that the header is not up to date as promises in jQuery 3.0+ are Promises/A+-compatible). Now, to be clear, I don't want to restart the discussion about the merits of this approach here. Those discussions have happened in the past, some people supported that, some opposed but the decision was taken and the whole ecosystem settled on implementing the Promises/A+ standard. And as long as AngularJS implements it as well - and since it's now in [LTS mode](https://docs.angularjs.org/misc/version-support-status) no major changes are planned - the current behavior is required and we cannot change it.

In light of the above, I'm closing the issue. Feel free to post additional comments here if something needs further clarification.
