### ISSUE TITLE
$injector.loadNewModules() does not update providers/values that are already defined.

### ISSUE THREAD

**Issue by richieforeman** [angular/angular.js#16834]
**I'm submitting a ...**

- [X] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
`$injector.loadNewModules()` does not apply any new `angular.module.value` or `$provide.decorator`  calls when loaded.  What this means is that it is not possible for a lazyload-ed module to update an injector value or decorate something that has already been provided in the upstream module.

If a value/service is exclusively defined in the "child lazy loaded module", then it can be over-ridden via `angular.module.value` and `$provide.decorator` -- so the behavior seems to be consistent with values/things already provided.

**Expected / new behavior:**
I would have expected lazy-loaded modules via `$injector.loadNewModules()` to run any appropriate `$provide.decorator` and `angular.module.value` blocks and update the injector values globally as needed for all future invocations.

I'm trying to lazy load AngularJS Material into my system, and it makes use of [several $provide.decorator statements](https://github.com/angular/material/blob/master/src/core/core.js#L38) here to hack things onto $q and $$RAF.  

AngularJs Material also uses several `$provide.decorator` [statements](https://github.com/angular/material/search?q=%24provide.decorator&unscoped_q=%24provide.decorator) in really interesting/scary ways (where it doesn't necessarily need to do so...).

**Minimal reproduction of the problem with instructions:**
I put together a stackblitz here that attempts to illustrate this problem with a simple service function call:
https://stackblitz.com/edit/angularjs-loadnewmodules-decorator-bug?file=home/index.js

- "MyService" is an eagerly loaded service in the "root" module
- "LateService" is a late loaded service in the "late" module
- I would expect after an initial "lazyload()" and then "click()", that the three values in my blitz would all be "789"

**AngularJS version:** 1.7.7

**Browser:** ALL

**Anything else:**

**Comment by kotl** [comment]
This is a real blocker to migrate to Angular and avoid huge initial payload. +1 to fix.

**Comment by gkalpak** [comment]
This actually works as expected.

##
It is not about decorating or overwriting something in the parent module. Unlike Angular (2+), AngularJS (1.x) only has a single injector, so not parent/child hierarchy in modules/injectors. All modules can contribute injectables to the (one and only) app injector.

What is probably confusing you, is the fact that AngularJS injectors only instantiate injectables once (when someone requests them). From that point onwards, they will return the same (cached) instance of the injectable. Additionally, decorators are run when something is instantiated.

As a result, if an injectable has already been instantiated by the time that the lazy module is loaded, overwriting or decorating it will not work, because it will never be instantiated again; the injector will serve the cached instance to new requests. If, one the other hand, an injectable is not instantiated yet, then overwriting or decorating in the lazy module will work as expected.

(And, of course, it woudn't be wise to overwrite an existing injectable instance, since that would violate the "services are singletons" contract and we would end up with different parts of the app having instances of an injectable that behave differently.)

##
That said, if you really want to work around that, you could monkey-patch the existing instances (for injectables that are objects). Not that I recommend that 😛

```js
angular.
  module('eager', []).
  factory('Foo', () => ({getValue: () => 1}));

angular.
  module('lazy', []).
  run(['Foo', Foo => Foo.getValue = () => 2); 
```

##
Closing, since the way this currently works (or rather does not work :grin:) is intended.

**Comment by richieforeman** [comment]
That doesn't seem to be consistently true.

`angular.module.provider` instances seem to actually be updated when a module is late loaded via `$injector.loadNewModules()`

Here's a stackblitz that demonstrates that:
https://stackblitz.com/edit/angularjs-loadnewmodules-decorator-bug-wp7tyv?file=home%2Findex.js

**Comment by gkalpak** [comment]
It is not that something cannot be updated; it is just that no new instances are created. As I showed in https://github.com/angular/angular.js/issues/16834#issuecomment-465338327, it is possible to update an existing instance (but no new instance will be created for the same injectable).

It just so happens that your implementation of `FavoriteThingsProvider` works when someone calls `.add()` at runtime (i.e. after the service instance has been created). Keep in mind that this is not true for all providers (but if you implement your's like this, then this is a fine way to augment their behavior at runtime (e.g. when lazy-loading a module)).

##
Just to be clear:
The `.config()` blocks (similar to the `.run()`) blocks _will_ run normally. The difference is that no new instances of services (or providers) will be created, if such instances already exist. For example, the `config()` call in your eager module will cause the injector to create an instance of the `FavoriteThingsProvider` provider (and then pass it to the callback to be configured). In contrast, the `.config()` call your lazy module, will not create a new instance, because it already has one. That is why you get both the values (`kittens` from the eager module _and_ `puppies` from the lazy module).
