### ISSUE TITLE
Un expected behavior  of ng-submit , getting triggred on hitting enter in input field

### ISSUE THREAD

**Issue by rajathms** [angular/angular.js#16841]
**I'm submitting a ...**

- [x ] Bug report from 1.7.6 
- [ ] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [ ] other 

**Current behavior:**
On clicking enter in the input field even when type="text"  **ng-submit** is getting triggred. It is not even the case of button tag without mentioning of type="button"

**Expected / new behavior:**
It should not submit form on clicking enter when enter is hit in input field.

**Minimal reproduction of the problem with instructions:**
code pen : https://codepen.io/rajathms/pen/zbqNXd

Step to reproduce the bug:  click enter in any of the input field you will get alert saying "ng-submit triggered"

**AngularJS version:**  1.7.6 
**Angular Material version:**  1.1.13

**Browser:** all

**Anything else:**

Behavior is same with my app, which I use older version Angularjs - 1..5.8 , Angular Material - 1.1.5,
I Don't want migrate my app from 1.5.8 to 1.7.x , so if possible suggest a fix for 1.5.8 also.

**Comment by gkalpak** [comment]
This is not Angular's doing. It is how HTML forms work. More specifically, it is called [implicit form submission][1]:

> A form element’s default button is the first Submit Button in tree order whose form owner is that form element.
>
> If the user agent supports letting the user submit a form implicitly (for example, on some platforms hitting the "enter" key while a text field is focused implicitly submits the form) [...]
> [...]
> There are pages on the Web that are only usable if there is a way to implicitly submit forms, so user agents are strongly encouraged to support this.

There are ways you can work-around that, though. For example, you can remove `ngSubmit` from the form and change the `type="submit"` button to `type="button" ng-click="save()"`.

##
Closing, since the behavior you are seeing is not caused by Angular.

[1]: https://www.w3.org/TR/html52/sec-forms.html#implicit-submission
