### ISSUE TITLE
angular-animate can't handle localization bug in chrome

### ISSUE THREAD

**Issue by sod** [angular/angular.js#16858]
* issue caused by an old browser version (chromium 59, used by cypress e2e testing tool, thats how I hit it)
* angular.js 1.7.8

Issue: angular-animate + this chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=720222

This is the problem:
![image](https://user-images.githubusercontent.com/905328/55157762-82d02c00-515d-11e9-8117-8c57079f8b1e.png)

What you see in the image: I'm in locale de_DE, and this chromium version 59 formats the computed style localized. So the fraction seperator is a `,` instead of a `.`.

How it manifests in angular-animate (see [parseMaxTime](https://github.com/angular/angular.js/blob/9ae51d751b3803d610652687b6a63f98f825a592/src/ngAnimate/animateCss.js#L277-L290) method):
* `parseMaxTime('0.35s')` returns durationTime: `0.35` <- normal behavior
* `parseMaxTime('0,35s')` returns durationTime: `35` <- this browser

So you expect an animation to last 0.35s, but instead it animates for 35s

**Comment by gkalpak** [comment]
Ouch! I guess this is because Cypress is using an older version of Electron. You can specify another browser for Cypress to use, though, so you can avoid the issue.

Given that (a) this is a browser bug (with a quite old version), (b) AngularJS only [supports][1] latest versions of evergreen browsers and (c) AngularJS is currently in [LTS mode][2], we are not going to add a work around for that.

##
Thx for reporting it anyway. Hopefully, it might help other people bitten by the same bug.

[1]: https://docs.angularjs.org/misc/faq#what-browsers-does-angularjs-work-with-
[2]: https://docs.angularjs.org/misc/version-support-status#long-term-support
