### ISSUE TITLE
Memory keeps on increasing while we click or move from one page to another page (any other event)  on Chrome,  ie 11 and edge

### ISSUE THREAD

**Issue by ghanavel** [angular/angular.js#16853]
When we work longer time on same browser (Angularjs SPA app) the memory allocation keeps on increasing while we click or move from one page to another page (any other event). Eventually after certain time browser get crashed (Chrome latest version, ie 11 and edge) . We already destroying $watchers , events at the end of $scope life cycle hook.Technology used : Angularjs 1.7 , angular-bootstrap, ui-grid.

![capture](https://user-images.githubusercontent.com/4058024/54018593-19d54400-41af-11e9-972e-f8da68eed12b.PNG)
![capture2](https://user-images.githubusercontent.com/4058024/54018594-1a6dda80-41af-11e9-9619-de243dd85af1.PNG)
![domnode1](https://user-images.githubusercontent.com/4058024/54018596-1a6dda80-41af-11e9-90c3-7f0418c97164.PNG)
![domnode2](https://user-images.githubusercontent.com/4058024/54018597-1a6dda80-41af-11e9-99ab-5cf702805cbe.PNG)

**Comment by gkalpak** [comment]
Unfortunetaly, there is nothing we can do without a minimal reproduction of the problem (without 3rd-party dependencies). It is not unlikely that the problem lies with one of the dependencies (which are not maintained by the AngularJS team).

Furthermore, AngularJS has entered Long Term Support mode some time ago and we are mainly only fixing security issues.

[1]: https://docs.angularjs.org/misc/version-support-status#long-term-support
