### ISSUE TITLE
angularjs version of 1.7.9 is not available in Maven

### ISSUE THREAD

**Issue by Shalini1703** [angular/angular.js#16921]
The angularjs version of 1.7.9 is not available in Maven.May i know, when it will be available because we faced one vulnerability in 1.7.0 which expects 1.7.9 to resolve this vulnerability.
and i couldn't see 1.7.9 version in the angularjs page also https://code.angularjs.org/.

**Comment by gkalpak** [comment]
I don't know who updates maven repositories, but it is not us. You should contact whoever is responsible for updating them.

I ensured the release is on https://code.angularjs.org/1.7.9/ (thx for pointing out it was missing).
You can also get the 1.7.9 release from CDNs (see https://github.com/angular/angular.js/issues/16919#issuecomment-557800575).
In a few days, it should be on the Google CDN too.

Closing this issue, since I don't think there is anything else for us to do (that is not already tracked in #16919).
