### ISSUE TITLE
ng-if condition that evaluates to TRUE can prevent GUI updates

### ISSUE THREAD

**Issue by KnutRyagerInmeta** [angular/angular.js#16984]
I'm submitting a bug report regarding the ng-if statement

**Current behavior:**
Adding the condition ng-if="true" to a HTML may cause GUI updates to stop functioning when triggered from inside the ng-if statement.

**Expected / new behavior:**
I have a button inside a span that toggles a boolean value, used by another ng-if to conditionally display some text.

Pressing the button should toggle the visibility of the text. Instead, pressing the button has no effect.

**Minimal reproduction of the problem with instructions:**
See this jsFiddle:
https://jsfiddle.net/0nr63zyp/

Remove ng-if="true" to see the correct functioning of the code.

**AngularJS version:** 1.7.9

**Browser:**
The bug occurs in Chrome, Edge and Firefox.

**Comment by gkalpak** [comment]
This is a combination of the fact that `ngIf` creates a new scope for its containing elements and how prototypal inheritance works in JavaScript (since Angular scopes prototypally inherit for their parent scope).

You can read more about that [here][1] and see a fixed version of your demo [there][2].

[1]: https://github.com/angular/angular.js/wiki/Dev-Guide%3A-Understanding-Scopes
[2]: https://jsfiddle.net/p1tnkmgw
