### ISSUE TITLE
Single NPM package (or tagged git repo) with all modules

### ISSUE THREAD

**Issue by MattIPv4** [angular/angular.js#17007]
**I'm submitting a ...**

- [ ] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [x] other 

**Current behavior:**

Currently, the Angular NPM package only contains the core files and not all the additional modules available in https://code.angularjs.org/1.7.9 -- these are only available by installing extra packages.

**Expected / new behavior:**

We're wanting to add an auto-update config for this library on cdnjs and have either the option of using a tagged git repo or a single NPM package as the source.

However, it seems this repo (though tagged) doesn't include the bundled files and I can't find an NPM package that contains all the modules at once.

It'd be great if there was a single NPM package available that contains all the Angular modules so that we can enable auto-updating on cdnjs for this library.

**Minimal reproduction of the problem with instructions:**

N/A

**AngularJS version:** 1.7.9

**Browser:** N/A

**Anything else:**

cc https://github.com/cdnjs/cdnjs/pull/13724

**Comment by gkalpak** [comment]
Thx for reaching out! AngularJS is currently in [Long-Term Support mode][1], which means two things (among others):

1. There is no point in considering to change our infrastructure/publishing at this point.
2. There will be very few new releases (if any) going forward.

##
That being said, I looked around at the cdnjs repo and here are a few things I noticed (related to AngularJS):

- While all core AngularJS packages are in [ajax/libs/angular.js/<version>/](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/angular.js), `angular-mocks` is also hosted as a separate package (at [ajax/libs/angular-mocks/](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/angular-mocks).
- That should probably be done for all AngularJS packages, since they are published to npm as separate packages.
- The independent `angular-mocks` package _has_ already been [updated to 1.7.9](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/angular-mocks/1.7.9) :grin:
- The independent `angular-mocks` package includes a [minified version](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/angular-mocks/1.7.9/angular-mocks.min.js), which we do not publish at [https://code.angularjs.org/1.7.9/](https://code.angularjs.org/1.7.9) (or [on npm](https://unpkg.com/browse/angular-mocks@1.7.9/)) 🤷‍♂

##
@MattIPv4, wdyt about hosting<sup>*</sup> each AngularJS package separately?

<sub>*: I know "hosting" is not the right term, but not sure what is 😇</sub>

[1]: https://docs.angularjs.org/misc/version-support-status#long-term-support

**Comment by MattIPv4** [comment]
Yeah, that does make sense, no point making such changes on your end now.

I honestly hadn't even realised we had mocks as its own lib. No idea when/how that happened and why not all of them.

I have suggested in the auto-update PR on our end that we create new cdnjs libraries for each of the modules and use npm auto-update for all of those, including the core library.

**Comment by MattIPv4** [comment]
Side notes:

No idea why we have a minified version for mocks that isn't on NPM, might be that our auto-updating bot automatically generates one if one isn't provided. I sadly don't know the internals well enough 😂 

And hosted is the right word! We are cloning them into the repo and then hosting them directly on the global Cloudflare network for CDN access.

**Comment by gkalpak** [comment]
Closing this issue, since I don't think there is any action to be taken on our side.
(Feel free to correct me below in case I missed something.)

Thx, @MattIPv4!
