### ISSUE TITLE
Upgraded Angular 1.5 to 1.6 and facing UI issues

### ISSUE THREAD

**Issue by Zain-Bin-Arshad** [angular/angular.js#17112]
# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**I'm submitting a bug**

- [ ] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [x] other 

**Current behavior:**
I have upgraded from angular 1.5 to 1.6, I am in the process of fixing all the breaking changes like `$onInit` etc. I noticed that all of my `md-tab-items` are not showing correct formatting. Upon investigating I found that in angular 1.5 `md-tab-item` was rendered like this:

```
<md-tab-item ...>
    <span ...>Heading</span>
<md-tab-item/>
```
I have all my CSS written to according to this rendering. But in angular 1.6 md-tab-item is being rendered like this:

```
<md-tab-item ...>
Heading
<md-tab-item/>
```
You can see there is no more any span tag in the html, this causes CSS to break as all my CSS looks for a span inside md-tab-item to apply formatting. I have a lot of CSS formatting and tabs inside my application and its not possible for me to change each CSS.

**Expected / new behavior:**
HTML rendering should be same so that all CSS works just fine with angular 1.6 also.

**AngularJS version:** 1.6

**Browser:** [all]

**Anything else:**
- I have upgraded jquery from 3.4.1 to 3.5.1
- Using angular-material 1.1.5
- Similar issue was caused to dropify default message. Instead of showing p tag outside a file-icon class it was being rendered inside that element, well I changes the CSS and it is working. I don't know how many such issues are still there to be found.

**Comment by gkalpak** [comment]
Without a reproduction, it is hard to tell where the issue lies and how to address.

That said, the latest version of AngularJS (and the only supported one - apart from 1.2.x) is 1.8.x. See [here][1] for more details.
Furthermore, AngularJS is in Long-Term Support mode and we focus exclusively on providing fixes to bugs that satisfy at least one of the following criteria mentioned [here][2].

[1]: https://docs.angularjs.org/misc/version-support-status
[2]: https://docs.angularjs.org/misc/version-support-status#long-term-support

**Comment by petebacondarwin** [comment]
Also it might be worth looking at the Material Design for AngularJS project, since this is probably what is generating (or not generating) those spans. See https://github.com/angular/material (cc @Splaktar)
