### ISSUE TITLE
Transclution behaves incorrectly with table elements

### ISSUE THREAD

**Issue by pdeva** [angular/angular.js#3542]
Full detailed explanation on this StackOverflow thread:
http://stackoverflow.com/questions/18156930/transclude-in-angular-directive-putting-elements-inside-a-single-span/18157128?noredirect=1#comment26611579_18157128

I am using angular 1.0.7 and bootstrap 2.3.2 for in that example

**Comment by Narretz** [comment]
Old issue, but yeah. This is a won't fix. The browser will discard the ´<tr>` etc. elements, because they don't have a `<table>` parent. This is unfortunately how HTML works, see https://github.com/angular/angular.js/issues/1459#issuecomment-67235182. As a workaround, use the directive like this: `<table envtable> ...`
