### ISSUE TITLE
$swipe does not handle a mechanism for properly unbinding callbacks bound via service

### ISSUE THREAD

**Issue by wesleycho** [angular/angular.js#3939]
I noticed that while $swipe will bind touch events properly, it will not remove them properly when an element with touch events bound to it via the service is removed from the DOM.  It should add a listener for the `remove` event and deregister the listener.

**Comment by standup75** [comment]
+1

**Comment by Narretz** [comment]
I'm closing this issue since the ngTouch module will be deprecated in AngularJS 1.7.0, and we will not do any more work on it. This is because touch handling is a complex topic, and there are stand-alone libraries that are better equipped to handle all the nuances and edge cases. For example, https://hammerjs.github.io/, which is also used by Angular.
