### ISSUE TITLE
ngTouch: Swipe easily activates accidentally while selecting text

### ISSUE THREAD

**Issue by cleercode** [angular/angular.js#4090]
I'd like to at least be able to disable the behavior for mouse events and only use it for touch events.

**Comment by jzatarain** [comment]
I'm seeing that the ngSwipe directive is working even if I'm not using a touch screen.
I tested in the plunkr provided in [https://docs.angularjs.org/api/ngTouch/directive/ngSwipeRight](url)
in chrome Version 62.0.3202.62 (Official Build) (64-bit)
Is this made on purpose or is it a bug?

**Comment by jzatarain** [comment]
Nvm, seems like using the 'ng-swipe-disable-mouse' attribute does the job, which I don't see in the documentation :o

**Comment by Narretz** [comment]
I'm closing this issue since the ngTouch module will be deprecated in AngularJS 1.7.0, and we will not do any more work on it. This is because touch handling is a complex topic, and there are stand-alone libraries that are better equipped to handle all the nuances and edge cases. For example, https://hammerjs.github.io/, which is also used by Angular.
