### ISSUE TITLE
$http cache, why are params not checked?

### ISSUE THREAD

**Issue by apneadiving** [angular/angular.js#4123]
I know caching issues are a pain, but I wonder why request params are not part of the caching system.
Is it to save memory client side? or for other design issue I'm unaware of? Could this be a configuration parameter?

Would be great to suggest some cache compression as well, like https://github.com/pieroxy/lz-string/ could be a mere option, obviously.

Thanks for your hard work,

Ben

**Comment by ryanhart2** [comment]
Request params are part of the caching system since 1.0.0rc3 (Mar 2012), so this comment is no longer relevant.

Cache compression built into the angular core would be a lot of additional bytes for people that don't need to use it and could be implemented themselves by those who do.

@apneadiving This is quite an old issue, can it be closed?

**Comment by apneadiving** [comment]
Ok no problem :)
