### ISSUE TITLE
Allow multiple transcluding directives on an element

### ISSUE THREAD

**Issue by vojtajina** [angular/angular.js#4357]
I believe it's possible, so let's try it.

**Comment by thomas-j-moffett** [comment]
+1

**Comment by dgroomes** [comment]
+1

**Comment by Beaudinn** [comment]
+1

**Comment by goleafs** [comment]
+1 all day long

**Comment by dasois** [comment]
+1

**Comment by kleinerroemer** [comment]
+1

**Comment by jbroquist** [comment]
+1

**Comment by yonatanbe** [comment]
+1

**Comment by moneytree-doug** [comment]
:+1: Is this still on the roadmap?

**Comment by squadwuschel** [comment]
+1

**Comment by nodesman** [comment]
+1

**Comment by redaz808** [comment]
+1

**Comment by ro0sterjam** [comment]
+1

**Comment by trumbitta** [comment]
:+1: :shipit:

**Comment by mnewmedia** [comment]
+1

**Comment by danielnord2** [comment]
+1

**Comment by davidetrapani** [comment]
+1

**Comment by gabrielmaldi** [comment]
This is being worked on in #12934

**Comment by schoettler** [comment]
+1

**Comment by pankajparkar** [comment]
+1

**Comment by Ramon2000** [comment]
+1

**Comment by petebacondarwin** [comment]
This feature is now in Angular 1.5.

**Comment by brunowego** [comment]
Thanks @petebacondarwin :+1:

**Comment by ahmadhsalim** [comment]
There's a scenario which requires to allow multiple directives on same element that uses transclusion.
For eg: `mdButton` from angular materials library uses `transclude: true`. I have created a directive called `ifCan` where I input permission slugs to show/hide the element. The `ifCan` directive has `transclude: 'element'`. This gives an error, eg:
```
Multiple directives [ifCan, mdButton (module: material.components.button)] asking for transclusion on: <md-button ui-sref="professionals.create" if-can="professionals.store" class="md-icon-button">
```

`ngIf` directive does the same thing with `transclude: 'element'` but it does not throw error due to a private property called `$$tlb` when declaring the directive. If there's a way to allow multiple transcluding directives without using a private property then it'll be solved. For now I'm using `$$tlb: true` as a workaround to fix this, which is actually unreliable because it's private.

**Comment by petebacondarwin** [comment]
@ahmadhsalim - please create a new issue if you have a problem. It is best not to try to add on to close issues.
