### ISSUE TITLE
Tolerances for $swipe

### ISSUE THREAD

**Issue by CWSpear** [angular/angular.js#4550]
I was working on a directive to make it so you can slideout an offscreen menu via swipe, and I noticed a lot of the time, it was calling the cancel action seemingly prematurely.

Digging into the docs and code, it seems that the `$swipe` service has some tolerances: if you move Y pixels vertically before moving X pixels horizontally, it will cancel the swipe.

Thing is, the tolerances seem a bit too tight when testing on my Nexus 4. 

Using this demo: http://cwspear.github.io/angular-menu-slideout/, I was logging when cancel was getting called and it was calling it about 1 out or every 3 or 4 times on what I would have considered perfectly good swipes.

Is it possible to make the tolerances Angular uses configurable?

---

PR: #5812

**Comment by Narretz** [comment]
I'm closing this issue since the ngTouch module will be deprecated in AngularJS 1.7.0, and we will not do any more work on it. This is because touch handling is a complex topic, and there are stand-alone libraries that are better equipped to handle all the nuances and edge cases. For example, https://hammerjs.github.io/, which is also used by Angular.
