### ISSUE TITLE
input does not watch ngPattern value for changes

### ISSUE THREAD

**Issue by taralx** [angular/angular.js#5226]
If you use input ng-pattern="var" with $scope.var = some regexp, and then you change that regexp in a handler, the validation doesn't react until the user modifies the field.

I'm working around this by using this hack:

var c = angular.element(document.getElementById('id')).controller('ngModel');
c.$setViewValue(c.$viewValue);

**Comment by thelgevold** [comment]
I think it would be very useful to allow binding to ng-pattern. Perhaps make it a standalone directive as suggested above. 
One use case that comes to mind is that it would allow us to define complex regex expressions in services/controllers instead of hard coding the expression in the markup. This will allow us to unit test the expressions, but also make reuse easier.

**Comment by alexander-87** [comment]
+1

**Comment by Narretz** [comment]
It actually does that in > 1.3.x:

http://plnkr.co/edit/QNX5dXmRsBMYlMle9LHH

Enter some characters from A-Z -> model is set. Then clichk switch, and the model will be invalidated. `ngPattern` is also already a standalone directive.
