### ISSUE TITLE
[REQ] Tutorial with Plain HTML & Javascript

### ISSUE THREAD

**Issue by gusdecool** [angular/angular.js#5249]
I believe we are noobs really need tutorial with plain HTML.

Current tutorial use nodejs, karma and another scary stuff which i think noobs like me will not understand it and it is not mandatory if we want to use angular lib only.

**Comment by gkalpak** [comment]
IMHO, a tutorial should give an insight on how it feels to actually build an app. Showing how you can use Angular to make your HTML to awesome things, but leaving you clueless on where to get Angular from, how to serve the app you are developing, how to test it and how to keep it up-to-date, isn't much good for a tutorial.

If one wants just an overview of the framework and what you can do with it, there other resources.
For instance, the examples we have on the [home page][1] are fine. And if people want to dive a little deeper, but without getting their hands dirty, they can follow the [online tutorial][2] we link to from the home page (or the dozen of other free online courses).

Then, for people that want to get into building a more "real-world" app, there is the phonecat tutorial.
But still, you don't need to mess around with Node and Bower and all the build tools if you don't want to. You can just read the tutorial, examine the code and code diffs online on GitHub and see a live running demo of the application at each step.

So, I think we are good :smiley:
--
Besides, things have evolved much since this was first requested, so now tools like Git, Node, Karma etc are the norm in a web developer's workflow.

So, I'm going to close this (but if anyone is feeling too strongly about it, feel free to reopen :smiley:) 

[1]: https://angularjs.org
[2]: http://campus.codeschool.com/courses/shaping-up-with-angular-js/intro
