### ISSUE TITLE
touchend / mouseup listeners for ngSwipe should be bound to window

### ISSUE THREAD

**Issue by patrickmarabeas** [angular/angular.js#5732]
As touchend / mouseup listeners are bound to `element`, if the user releases outside of the element's boundaries, the touchend / mouseup listeners wont be called.

A mouse up event from an element is intrinsically a mouse up event from the window.

https://github.com/angular/angular.js/blob/master/src/ngTouch/swipe.js
Line 130:

```
angular.element(window).on('touchend mouseup', function(event) {
    if (!active) return;
    active = false;
    eventHandlers['end'] && eventHandlers['end'](getCoordinates(event), event);
});
```

http://plnkr.co/edit/VebWtE3HiFX3xHWzJmif

**Comment by Narretz** [comment]
I'm closing this issue since the ngTouch module will be deprecated in AngularJS 1.7.0, and we will not do any more work on it. This is because touch handling is a complex topic, and there are stand-alone libraries that are better equipped to handle all the nuances and edge cases. For example, https://hammerjs.github.io/, which is also used by Angular.
