### ISSUE TITLE
$transclusion fails inside of recursive directives

### ISSUE THREAD

**Issue by joshkurz** [angular/angular.js#5753]
The directive mentioned here #2670, is a recursive style directive that uses transclusion to help accomplish its recursion. This is a nice idea, however it is halted by $transclusion failing when certain directives are used inside of the transcluded content. 

I have reproduced the scenario in the directive mentioned in the above issue with the latest release and also reproduced it in an entirely different directive that performs similar actions. 

http://plnkr.co/edit/QD8KfOhwy2xOoxb0NN6g?p=preview works with ngIf
http://plnkr.co/edit/m3ZcWPPAWaQtj25zcqwC?p=preview fails with ngShow

This directive fails under the same conditions. 
http://jsfiddle.net/joshkurz/DsvX6/25/ Works with ngIf 
http://jsfiddle.net/joshkurz/DsvX6/26/ fails with ngShow

Im curious as to why ngIf works and ngShow does not. 

Thought I should mention that this functionality is available by not even using a custom directive at all. However, it is not using transclusion.

http://jsfiddle.net/joshkurz/uXbn6/821/ ngIf passes
http://jsfiddle.net/joshkurz/uXbn6/822/ ngShow passes.

**Comment by petebacondarwin** [comment]
Both JSFiddles work with Angular 1.4.x (i.e. the ones using the directive that transcludes its contents).

The Plunker examples should not really work in 1.4.x since you should not use `ngTransclude` when there is no transclusion. (In this case there is only one transclude directive in the whole app, which is the `ngRepeat`).

@joshkurz do you still need this to work for 1.2?

**Comment by joshkurz** [comment]
nope. Thanks for checking on it though. :)
