### ISSUE TITLE
Callback "$animate:close" isn't called after an ng-leave animation finishes

### ISSUE THREAD

**Issue by ravishivt** [angular/angular.js#6049]
The $animate:after and $animate:close callbacks fire for ng-enter events but they do not fire for ng-leave events.  Is this expected since the element/directive doesn't exist anymore?  Is there a workaround besides using JS animations?

Example at http://jsbin.com/utOrAPO/11/edit?html,js,output

**Comment by urpro-bas** [comment]
This issue still seems to exist in 1.4, is that correct? Any estimation on when it's done or any workaround?

**Comment by urpro-bas** [comment]
I have made a work around, it's kind of a dirty hack, but it works for me maybe it also works for others. The problem is caused by the parent no longer being available when the leave animation is finished (it's removed from the dom). My hack adds the option to listen to "*" instead of a dom element. So `$animate.on('leave', '*', function(element, phase){  })`

My code can be found here: https://github.com/urpro-bas/bower-angular-animate

**Comment by johngrogg** [comment]
Just encountered this issue today. An update on the status of a solution would be great.

**Comment by chucksellick** [comment]
Just ran into this. Really confusing behaviour. At the very least it should be mentioned in the $animate documentation if this phase will never fire for the "leave" event. Trying to write a scrollbar that will automatically update its handle after any transitions finish and now I need a dirty workaround!

**Comment by Narretz** [comment]
AS far as I can see, this works in 1.4: http://plnkr.co/edit/092B9gDPtqcJQ7q9WXXG?p=preview The event syntax has changed, though.

**Comment by ahagelstein** [comment]
If I try out your sample with version 1.5.2 (I only changed the script tags on index.html) then I missed the leave close event. Any ideas??
