### ISSUE TITLE
ngTouch scrolling - performance problems with addClass/removeClass and using ngSwipeLeft/Right - also touch too sensitive as scrolling through list with ng-click accidentally clicks too often

### ISSUE THREAD

**Issue by NathanWalker** [angular/angular.js#6347]
Sorry guys, I love the core team with this project and Angular as a whole but I have struggled with ngTouch (ngMobile before that) ever since the module was introduced. The advantages it brings are all nullified, imo, by the incredible degradation to fluid scrolling on mobile devices. 
I have found that the addClass/removeClass behavior of ng-click-active is the culprit to causing the browser to reflow, which is even noted as being something to minimize in an official google guide by Lindsey Simon: https://developers.google.com/speed/articles/reflow
# frustratedwithngTouch

**Comment by drpicox** [comment]
I know that this issue is closed, but I have confirmed (by removing addClass and removeClass frome code) that it is a serious performance problem. It does appears in some iPads (the oldest ones), and in WindowsPhone, both with Cordova. In some complex app, with complex list elements, **delays** introduced because of painting, are **up to 5 seconds** when scroll begins.

I have built a small demo to reproduce it:

- https://github.com/drpicox/cordova-wp-performanceissue

It is simple, but it happens. If you enlarge the list, it get worst. (note: no digest are performed in scroll operations)

**Comment by NathanWalker** [comment]
Thanks @drpicox , I will add that I recently had to remove the `ngTouch` library again as we found that using `ng-swipe-left` on a list on a mobile device was completely unusable and caused an unreasonable amount of jankiness. Removing `ngTouch` was the only way we could make our mobile app acceptable for usability. :(

**Comment by NathanWalker** [comment]
I'll reopen as I am confident that using `ngTouch` is not good for the large majority of mobile experiences.

**Comment by adamchenwei** [comment]
then why its there for?

**Comment by NathanWalker** [comment]
It's a solid attempt at solving some mobile touch features as well as canceling the 300ms delay on iOS. Probably suffices most small projects but for anything substantial, I've found the cons to greatly outweigh the pros.

**Comment by NathanWalker** [comment]
@adamchenwei Keep in mind, Angular 2 will be the way to go as it will squarely address mobile better than ever just by way of the framework design itself.

**Comment by drpicox** [comment]
Yep, theoretically that's true, but for now, Angular2 is not ready for production. So until then, we're developing with Angular 1, and avoiding to use ngTouch :( (by the way, in iPhone 6S works like a charm)

**Comment by Narretz** [comment]
We'v removed the ngClick override from ngTouch by default in 1.5. And afaict ngSwipe has nothing to do with this.
