### ISSUE TITLE
directives with isolated scope and a optional function '&?' should be returned as undefined if the function is missing

### ISSUE THREAD

**Issue by davidemoro** [angular/angular.js#6404]
Overview of the issue
----------------------------
It is not a bug, probably just a design issue about directives with isolated scope and optional functions passed via '&?'.

If you don't pass any function to the directive, you get a function that returns undefined instead of undefined.

Errors
---------
No errors are thrown.

Motivation for or Use Case
-------------------------------------
If you declare a scope property as optional, probably the expected behaviour is getting undefined if you try to access this property.
This is exactly what happens when you have a '@?' binding and you don't fill in the optional attribute: you get undefined trying to access $scope.property.

The way to understand if there is a function parameter is inspecting the attrs.
So this seems a special case not motivated for '&?'.

Angular Version(s)
--------------------------
All versions, no regression.

Browsers and Operating System
---------------------------------------------
All browsers and operting systems.

Suggestion
----------------
In order to get a common behaviour for optional parameters you could just add the following control to https://github.com/angular/angular.js/blob/4a6a3ba7fb08ce99007893ef75365a3e8aff938a/src/ng/compile.js#L1463:
                if (optional && !attrs[attrName]) {
                  return;
                }

If you find that this proposal is ok I can make a pull request from: https://github.com/davidemoro/angular.js/blob/master/src/ng/compile.js

I've just run the tests and all seems fine.

**Comment by sramilli** [comment]
Hi,
i still see this behaviour in Angular 1.5.8
i´m passing an optional function to a sub-sub-component with "&?" in both steps. 
The first sub-component detects "undefined", but the sub-sub-component got a function instead.

In my sub-component's template i would like to avoid having some logic toggling between
**<sub-sub-component some-attribute="$ctrl.anAttribute">.......</...>**
and
**<sub-sub-component some-attribute="$ctrl.anAttribute" optional-function="$ctrl.myFunction()">.....</...>**

As a workaround i use instead "=" as shown
     bindings: {
        myFunction: **"="**
     }

**Comment by ashclarke** [comment]
@sramilli I had the exact same issue today (1.5.8 too). Workaround I applied was the same too.

(Fun fact: I came to this thread again via Google, and then got freaked out just now because I got this notifcation. Wasn't until I visited GitHub to reply that I realised that I'd already participated in this issue over 2 years ago.)

**Comment by tabanliviu** [comment]
@davidemoro @caitp I'd like to mention that we recently hit upon this issue during our upgrade from 1.3 to 1.5 and our unit tests did not capture this behavior because in 1.3 there was no difference in the outcome between using a directive without the optional attribute vs having an optional value that is undefined.

I think this should have been marked as a breaking change or at least had some note about potential breaking change.

I admit I didn't read the full change log line by line and only looked at the breaking changes section but still looking back I would have preferred some hint about this change.

**Comment by tommck** [comment]
This problem still exists in 1.6.10

Optional expression is always a function
