### ISSUE TITLE
ngOptions required ngModel

### ISSUE THREAD

**Issue by reidreid46** [angular/angular.js#7047]
ngModel is required to see any output put into a ngOptions. If ngModel is ommitted, no options are created, and no warning is given.

Possible to?:
a) not require ngModel, display options regardless
b) or show some kind of warning when ngOptions is used without ngModel

**Comment by petebacondarwin** [comment]
Since `ngOptions` without `ngModel` does nothing at the moment, it is fundamentally pointless. Therefore I think we should just throw an error if there is an `ngOptions` without `ngModel`.

Although this is a breaking change (for 1.5) it shouldn't affect anyone in practice since you get no benefit without it.

Does anyone have a view on that?

**Comment by Narretz** [comment]
We can simply remove the `optional` modifier to the `ngOptions.require` property. It's probably leftover from when ngOptions was an attribute to the `select` directive.

**Comment by Narretz** [comment]
See #12840
