### ISSUE TITLE
fix(ngOptions): Only apply terminal: true to select elements

### ISSUE THREAD

**Issue by tdakhla** [angular/angular.js#7291]
Currently the ngOptionsDirective is being built like such:

```javascript
var ngOptionsDirective = valueFn({ terminal: true });
```

However, this is limiting in the case where I want to reuse the concept of ```ng-options``` and add an already-familiar API (instead of ```widget-options```) to my own directive that uses a template, performs transclusion, etc.  For example, because Angular's ```ng-options``` has ```terminal: true``` on it, child nodes aren't linked and {{something}} won't get resolved:

```html
<widget ng-options="blah">
   <div>{{something}}</div>
</widget>
```

I'm not sure exactly what the history is behind why ```terminal: true``` is being applied to ```ng-options```, but I assume it only applies to ```<select>``` since ```ng-options``` is only supported by ```selectDirective``` (as far as Angular core is concerned).  I propose that Angular's ```ng-options``` be changed to the following as to not effect custom elements that want to use it:

```javascript
var ngOptionsDirective = valueFn({
    compile: function (element, attrs) {
        if (element[0].tagName === 'SELECT') {
            this.terminal = true;
        }
    }
});
```

**Comment by Narretz** [comment]
This can't be done imo, because terminal applies to the current element and all its children. If we applied terminal to select, this would mean you could not use ng-repeat inside select. Even the default option element is a directive, so that would break everything.
The reason why ngOptions has terminal is because it renders the option elements based in the options expressions itself, and therefore empties the select anyway. The default (blank/empty) option inside ngOptions select is extracted before this and compiled separately.
