### ISSUE TITLE
Suggestion: provide context information about the exception

### ISSUE THREAD

**Issue by sergiomichels** [angular/angular.js#8217]
Trying to log information about the exception in a production environment seems hard when you compress your JS code. 

The cause variable of ```$exceptionHandler``` don't provide enough information about the context that generated the exception.

If the exception handler be aware of the scope and artifact where this exception occur the log will be more precise.

**Comment by bargitta** [comment]
@sergiomichels  I am also looking for solution of this problem. For exceptions explicitly thrown by our code, we can add the context information, but for those not handled one, any ideas so far?

**Comment by sergiomichels** [comment]
@bargitta Unfortunately no.

**Comment by gkalpak** [comment]
I don't think we can provide such info. Note that most errors will be caught by the generic `try/catch` in `$digest`, which means it could have been thrown in any scope and by any "artifact type". In that case, we would be able to pass the scope as context, but (a) it won't be possible in other context (outside `$digest`) and (b) I'm not sure how useful the scope will be in determining where the error came from (I can't imagine it being more useful that the stacktrace).

BTW, if you want to log the current URL (i.e. route), you can easily decorate `$exceptionHandler` and do it yourself.

--
I'm going to close this, since it hasn't seen much activity for over a year, but if anyone has a concrete suggestion on how we could improve the debugging experience, please open a new issue (or better yet submit a PR and be our hero :smiley:).
