### ISSUE TITLE
ngSwitch error when using Angular with Polymer's platform.js loaded

### ISSUE THREAD

**Issue by theefer** [angular/angular.js#8598]
Context: As part of a large AngularJS application, we're trying to bring in a small Polymer Web Component. `platform.js` is loaded first in the page, and Angular is manually bootstrapped on a wrapped document node.

It all works fine in latest Chromium (likely because the platform.js polyfills don't do much as most/all? APIs exist natively), but fails with an error in FF 31. I've isolated the error to nested ngSwitch, which result in a slightly weird minimal failing reduced case that you can see at http://jsbin.com/roxif/6/edit

The offending code is the following:

``` html
<div ng:switch="3">
  <div ng:switch-when="3">
    <div>
      <div ng:switch="3">
        <div ng:switch-when="3">3</div>
      </div>
    </div>
  </div>
</div>
```

Note that the extra wrapping `div` in between the nested ngSwitches is required for the error to occur. Without that extra element, the error disappears.

The following error gets thrown:

```
Error: node is undefined
compositeLinkFn@https://rawgit.com/angular/bower-angular/v1.2.16/angular.js:5989:13
nodeLinkFn@https://rawgit.com/angular/bower-angular/v1.2.16/angular.js:6573:9
compositeLinkFn@https://rawgit.com/angular/bower-angular/v1.2.16/angular.js:5983:1
nodeLinkFn@https://rawgit.com/angular/bower-angular/v1.2.16/angular.js:6573:9
compositeLinkFn@https://rawgit.com/angular/bower-angular/v1.2.16/angular.js:5986:15
publicLinkFn@https://rawgit.com/angular/bower-angular/v1.2.16/angular.js:5891:30
ngViewFillContentFactory/<.link@https://rawgit.com/angular/bower-angular-route/v1.2.16/angular-route.js:921:7
nodeLinkFn@https://rawgit.com/angular/bower-angular/v1.2.16/angular.js:6580:1
compositeLinkFn@https://rawgit.com/angular/bower-angular/v1.2.16/angular.js:5986:15
publicLinkFn@https://rawgit.com/angular/bower-angular/v1.2.16/angular.js:5891:30
boundTranscludeFn@https://rawgit.com/angular/bower-angular/v1.2.16/angular.js:6005:13
controllersBoundTransclude@https://rawgit.com/angular/bower-angular/v1.2.16/angular.js:6600:11
update@https://rawgit.com/angular/bower-angular-route/v1.2.16/angular-route.js:871:17
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@https://rawgit.com/angular/bower-angular/v1.2.16/angular.js:12691:15
updateRoute/<@https://rawgit.com/angular/bower-angular-route/v1.2.16/angular-route.js:552:15
etc...
```

It looks like the error maps to the last line of the following function (`node.childNodes` where `node` is `undefined`):

``` js
      function compositeLinkFn(scope, nodeList, $rootElement, boundTranscludeFn) {
        var nodeLinkFn, childLinkFn, node, $node, childScope, childTranscludeFn, i, ii, n;

        // copy nodeList so that linking doesn't break due to live list updates.
        var nodeListLength = nodeList.length,
            stableNodeList = new Array(nodeListLength);
        for (i = 0; i < nodeListLength; i++) {
          stableNodeList[i] = nodeList[i];
        }

        for(i = 0, n = 0, ii = linkFns.length; i < ii; n++) {
          node = stableNodeList[n];
          nodeLinkFn = linkFns[i++];
          childLinkFn = linkFns[i++];
          $node = jqLite(node);

          if (nodeLinkFn) {
            if (nodeLinkFn.scope) {
              childScope = scope.$new();
              $node.data('$scope', childScope);
            } else {
              childScope = scope;
            }
            childTranscludeFn = nodeLinkFn.transclude;
            if (childTranscludeFn || (!boundTranscludeFn && transcludeFn)) {
              nodeLinkFn(childLinkFn, childScope, node, $rootElement,
                createBoundTranscludeFn(scope, childTranscludeFn || transcludeFn)
              );
            } else {
              nodeLinkFn(childLinkFn, childScope, node, $rootElement, boundTranscludeFn);
            }
          } else if (childLinkFn) {
            childLinkFn(scope, node.childNodes, undefined, boundTranscludeFn);
          }
        }
```

Note that this fails even with the latest stable Angular version (1.2.22) as per [this other example](http://jsbin.com/noheta/1/edit) and also with the latest unstable Angular version (1.3.0-beta.18) as per [this example](http://jsbin.com/baviy/1/edit).

It seems likely that this is a broken edge case of the wrapping platform.js does to polyfill Shadow DOM in FF?

Any hints as to where this error comes from and how to solve it?

I will cross-file this issue in the Polymer bug tracker as they may also be interested to know about this.

Thanks in advance.

**Comment by theefer** [comment]
This issue still seems to be occurring even after I [bumped the jsbin](http://jsbin.com/mapizewuke/1/edit?html,js,output) to use the latest versions of angular (1.3.8) and ~~platform~~ webcomponents.js (0.5.2).

I'd be keen to help get this fixed if someone can point me in the right direction, as we'd like to start using web components within an Angular app, and this is currently a blocker.

I could try and pursue the suggestions in the thread above, but @IgorMinar you suggested the problem is *not* caused by the live NodeList? If not, do you have any ideas and we could address this problem?

/cc @robdodson

**Comment by addyosmani** [comment]
Issue 78 appears to have been moved as part of our repo clean-up after consolidating platform.js into https://github.com/webcomponents/webcomponentsjs. 

After digging into the issue briefly mentioned, I can't see anything other than the NodeList (`nodeList[i]`) limitations under ShadowDOM polyfill being at fault here. You could try digging into that polyfill (see https://github.com/webcomponents/webcomponentsjs/tree/master/src/ShadowDOM) to try monkey-patching it, but I would check with @jmesserly if that's even possible.

**Comment by theefer** [comment]
OK, I might give it a go in the coming days, thanks.

**Comment by jmesserly** [comment]
as far as I know, it's not possible to patch the indexer, unless you can depend on [ES6 Proxies](https://github.com/lukehoban/es6features#proxies). Once proxies are everywhere we could return a proxy. Though I'm unsure the performance implications of going that route for NodeList, because it is often used in performance critical parts of the code.

One other approach that might work with currently available EcmaScript 5: instead of building childNodes/children on demand, cache them and mutate in every appendChild/insertBefore/removeChild operation. This is possible because SD polyfill traps these calls. Problem with that is it might be expensive, especially for inserts in the middle of the list. Then again, computing those lists on-demand is also expensive in its own way, so it might be a wash.

If you're up for the experiment, probably the place to start is at https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowDOM/wrappers/Node.js#L660 ... have that return this.childNodes_, which is a cached list. Then change insertBefore/removeChild to update the list. Probably could be done about here: https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowDOM/wrappers/Node.js#L426

**Comment by bkardell** [comment]
I'm honestly not sure if this is related but I have a custom element - just the custom element with non-polymer polyfill, so it actually mutates the DOM, there's no shadow... This actually seems to work fine (if you make your element carefully so that it is kind of self-aware that it can be in an uplifted state or not), you can see an example in this codepen http://codepen.io/bkardell/pen/NPMqeY - however, for some reason if we use angular-ui-router I see this same error in non-chrome browsers (so, the polyfilled ones) http://plnkr.co/edit/icl2EgMHwnXpu6phbX2a?p=preview  there.  I realize this is -likely- a different bug, but I'm wondering if anyone understands the internals enough to understand why it appears that in some cases that stableNodeList/linkNodes gets hosed so I can figure out which angle/project to chase this from.

**Comment by laicosly** [comment]
I'm experiencing this issue on Safari when using ngSwitch in a template.

**Comment by lgalfaso** [comment]
There is nothing Angular is doing out of the spec. This is an issue in platform.js and should be fixed there.

**Comment by morewry** [comment]
Potentially of interest https://github.com/webcomponents/shadydom/pull/286
