### ISSUE TITLE
$location injection causes / insertion after hash on page refresh when not in html5mode

### ISSUE THREAD

**Issue by RichardLitt** [angular/angular.js#8675]
When not in html5mode, and using a URL of the format `example.com/example#param=params`, refreshing the page will automatically cause the URL to be rerouted to `example.com/example#/param=params`.  In the particular case I am encountering, angular isn't being used for routing at all, and this functionality is undesired. 

Related to #4608.

**Comment by petebacondarwin** [comment]
Actually this is not a bug - it works as designed. Hashbang mode, as its names suggests should use a `#!` character to indicate the start of the route path. So in that case your URL would look like `example.com/example#!#param=params`.

Unfortunately we seem to have provided a default of just `#`, which is confusing for people, since to actually provide a real hash fragment you need to put two hash characters next to each other: `example.com/example##param=params`.

I think the best course of action is to change our default hash prefix to `!` in 1.5 as a breaking change.

**Comment by Narretz** [comment]
The hashbang is going to be ! by default starting in 1.6
