### ISSUE TITLE
feat(dateFilter): don't coerce string input to integer

### ISSUE THREAD

**Issue by bresting** [angular/angular.js#9284]
Hi i am using @license AngularJS v1.3.0-rc.3
I am not sure it is bug or not but please check it.

var myDate = $filter('date')('20140920', 'yyyy/MM/dd');
console.log(myDate); -> i expected 2014/09/20 but it is printed to 1970/01/01

becuse this problem is 20140920 to parsing int first even i send string("20140920");

line number about 16261
=================================
    format = format || 'mediumDate';
    format = $locale.DATETIME_FORMATS[format] || format;
    if (isString(date)) {
      date = NUMBER_STRING.test(date) ? int(date) : jsonStringToDate(date);
    }
=================================

i think "date = NUMBER_STRING.test(date) ? int(date) : jsonStringToDate(date);" should be change like this date = jsonStringToDate(date);

i am not good at english please understand. Thank you.

**Comment by lgalfaso** [comment]
I think we are doing the right thing here, and this issue is invalid. @caitp @petebacondarwin WDYT?

**Comment by cameronjacobson** [comment]
I'm participating in CodeTriage, so I don't necessarily have a stake one way or another here, but thought it might be worth pointing out that even timestamp `30000101` (ie. `january 1 3000`) is a 1970 timestamp (`Mon, 14 Dec 1970 05:21:41 GMT`).  So perhaps the combination of (1) a string, and (2) a value of length=8 is precise enough to warrant consideration for a special case.

Then again it's such a specific case that no one without having combed through the documentation or source code with a fine-toothed comb may ever learn this exists.  It's bound to trip up some unsuspecting developers, though I imagine they would be the exception and not the rule.

Intuitiveness is perhaps slightly in favor of the OP's suggestion only because I imagine it's extremely rare that people encounter a timestamp that maps to a date in 1970, where it was actually intended to be a date from the 1970s.

Then again, simple function could be created to fix this before passing to angular.  Something like this might work [not considering special cases]:

```
function convertit(v){
  return [
    v.substr(0,4),
    v.substr(4,2),
    v.substr(6,2)
  ].join('-')
}
```

**Comment by Narretz** [comment]
I agree that special casing this and introducing a BC because of it is not worth it for this very rare case.
