### ISSUE TITLE
Feature request: need 'delay' option in $resource

### ISSUE THREAD

**Issue by megapotz** [angular/angular.js#9384]
Let's suppose we need to update some data from server when $watch calls for it. If user changes model too frequently (typing etc), it generates too many requests to server. Of cource, this can easily be avoided with little of code, but it would be sweet if $resource could take such option as 'delay' : '500ms' and send request to server if no more calls happenes in half a second.

**Comment by wesleycho** [comment]
I don't think this feature makes much sense in something like $resource (or angular 1) - fundamentally, this is the wrong way to approach saving user data because one can potentially end up saving the lower character entry before the higher character entry depending on how long the server takes to handle the requests. This is actually one of the major use cases for something like observables - one could hack to create a queue and peel off the end of the queue after a prior update happens, but $scope.$watch is a completely flawed approach for this type of operation.

**Comment by gkalpak** [comment]
For lack of a better way, I think this way of handling user data is fine. It sure needs some extra work to avoid the overwriting newer data with older, but we'll have to leave with that, I guess, since we don't have observables built into ng1's `$http` (for the time being :wink:).

But the debouncing feature doesn't sound like a good addition for `$resource`. `$resource` is about _how_ to communicate with a (restful) data-source. The _when_ to trigger that communication is beyond its scope and the two should remain decoupled imho.

I understand that it could be convenient in specific usecases, but would increase the complexity (both for users and maintainers) for the vast majority of usecases.
