### ISSUE TITLE
<template> alias for <script type="text/ng-template">

### ISSUE THREAD

**Issue by jimmywarting** [angular/angular.js#9412]
Should we support it?
coding in a `<script>` tag feels awkward...

**Comment by wesleycho** [comment]
Given that it is recommended with Angular 1 to bundle all the templates in $templateCache (a lot of ngAnimate related templateUrl issues for example), I recommend that this be closed as something that won't be supported due to the addition of complexity and confusion since it doesn't seem like this adds enough benefit but too much cost.

It should be noted that Angular 2 embraces Web Components, so it uses the template tag under the hood for structural directives and uses a virtual DOM representation in its templating.

**Comment by gkalpak** [comment]
I agree that this doesn't offer any real benefit, while it does add confusion and increase maintainance costs. If anyone needs it, it should be trivial to add though; e.g.: [Demo][1]

Based on the above, I'm going to close this.

[1]: https://codepen.io/ExpertSystem/pen/OXNdXv?editors=1010
