### ISSUE TITLE
docs(changelog): export the changelog and contributing.md to the site

### ISSUE THREAD

**Issue by thorn0** [angular/angular.js#9444]
It's inconsistent that the most part of the docs is on the site, and to see other (quite important) parts, we need to go to GitHub.

**Comment by ilanbiala** [comment]
Any progress on this?

**Comment by petebacondarwin** [comment]
No progress yet. Perhaps a task for over Xmas...

**Comment by Narretz** [comment]
I think we should use the changelog from master as a single source of truth for all versions. That way, we can have one changelog on the website that is always up to date for all versions (given that we update the master changelog with stable release changes).

**Comment by ilanbiala** [comment]
@Narretz having 1 changelog is fine, but when all the versions are mixed together, it gets too confusing trying to see everything that has changed between 2 versions. It would be nice to have every version grouped under the minor version, and the versions ordered in latest at the top and oldest at the bottom.

**Comment by Narretz** [comment]
Absolutely. I was just suggesting to use the latest changelog as the source
for all versions. Because the angular docs are usually generated from the
files of each version individually.
Basically, whatever version you have selected in the docs, the cl should
always be generated from the latest version.
Am 07.12.2015 14:44 schrieb "Ilan Biala" <notifications@github.com>:

**Comment by wesleycho** [comment]
This should probably just be a simple link on the docs site, with maybe a link to the specific section if the user is in a particular version of the site, unless it is desired for it to be in a more central location.

**Comment by petebacondarwin** [comment]
Good idea @wesleycho - anyone want to do a PR?
