### ISSUE TITLE
Expressions don't understand Infinity 

### ISSUE THREAD

**Issue by Alexsey** [angular/angular.js#9492]
Infinity in expressions is not treating as Infinity number, but as variable
<a href="http://plnkr.co/edit/laRgQmM4m1d2ZNkP7ruk?p=preview">Plunker</a>
So it even can be override 
<a href="http://plnkr.co/edit/esQA4npcLTWiGD7MGC9y?p=preview">Plunker</a>

**Comment by jjlorenzo** [comment]
``` js
ng-if="reactor.operationTime === Infinity"
```

IMHO this is a simple expression, at least more than the hack that works for me: 
``` js
ng-if="reactor.operationTime === 1/0"
```

**Comment by AlexanderLeonov** [comment]
Will do some necroposting here. :)
Another use case for that would be like this:

`<select ui-select2="{ minimumResultsForSearch: Infinity }">`

It doesn't make sense for me to add something onto scope for select2 configuration which is that simple - all I want is just hide search box, that's it. Otherwise I'd have to create controller or directive which would place this config on the scope for me, or to make some existing entity to do it. Then if we consider 3-4 such select2's on the page, and 3-4 is not even close to "many"... No, that's definitely overkill. But I'm using angular 1.5.0 and it still doesn't work. :(

**Comment by jjlorenzo** [comment]
I don't know if works for you, but in my case I use a hack: 1/0

<select ui-select2="{ minimumResultsForSearch: 1/0 }">

**Comment by AlexanderLeonov** [comment]
@jjlorenzo Thanks for helping me, I've seen your earlier comment here. It can work of course, but I'm not fond of any kind of hacks if it could be done in a proper way. Also if tomorrow they'll change 1/0 behavior to throw an exception or return zero or whatever else then this code will break. I'm not excited of dealing with such things, so still +1 for implementing explicit support for Infinite

**Comment by jjlorenzo** [comment]
I'm totally agree with you, but comming from django world where the
template language are very limited, this design decision is not new for me.
​
