### ISSUE TITLE
ng-include rendering slowness

### ISSUE THREAD

**Issue by meaganc** [angular/angular.js#9559]
We have been using ng-include for partials in our new angular app, but we had to remove them because they were loading so slowly. This had significant visual impact on page load. Here's a great example of this issue:
http://plnkr.co/edit/dTUUPhsVrCbeSIjZzqmx?p=preview

How can we help address this? Is there something we're missing?

**Comment by S-YOU** [comment]
Anyone know any projects that can inline/expand ng-includes during build process?

**Comment by Narretz** [comment]
(Don't mind m, just cleaning old issues)
This is definitely faster in new versions (1.4 and beyond, approx 50% faster).
Inlining the templates is also a good idea, as it removes the async behavior.
If you only want to include so that you can structure your templates better, simply use a directive with a templateUrl. This is almost as fast as inlined templates.
