### ISSUE TITLE
Can the Angular docs on the website be made to deault to the latest stable release?

### ISSUE THREAD

**Issue by keirlawson** [angular/angular.js#9674]
They seem to point to the latest git revision by default which is probably not what most people are using.

**Comment by Narretz** [comment]
The main thing that needs to be done is:

* create a build on Jenkins to push the latest release to a standard url such as `code.angularjs.org/latest`
* change the configuration of the angularjs.org web-server to point docs.angularjs.org to point that url
* change the version dropdown so that `master` points to `code.angularjs.org/snapshot`
