### ISSUE TITLE
Bug with select binding to an array of integers

### ISSUE THREAD

**Issue by fwanicka** [angular/angular.js#9700]
I am trying to bind an array of integers to a select using 1.3.0. There is a difference if the array is populated when the controller is initialized versus after an event occurs. If it's populated after an event, the wrong item is selected.

http://jsfiddle.net/fwanicka/n0sbeuab/ (array populated when controller initialized)
http://jsfiddle.net/fwanicka/6sx152dm/ (array populated after a timeout/event)

The second fiddle works in 1.2.23, so this is a breaking change from that version, which we just upgraded from:

http://jsfiddle.net/fwanicka/6s5rzz9j/ (array populated after a timeout/event using 1.2.23)

**Comment by kentcdodds** [comment]
This issue is still broken in 1.3.15 but it is fixed in 1.4.0-rc.0 http://jsfiddle.net/8xc9pctd/2/

**Comment by Narretz** [comment]
It's unlikely that this is going to be fixed in 1.3.x, because ngOptions was pretty heavily refactored.

----- Ursprüngliche Nachricht -----
Von: "Kent C. Dodds" <notifications@github.com>
Gesendet: ‎28.‎04.‎2015 15:36
An: "angular/angular.js" <angular.js@noreply.github.com>
Cc: "Martin Staffa" <mjstaffa@googlemail.com>
Betreff: Re: [angular.js] Bug with select binding to an array of integers(#9700)

This issue is still broken in 1.3.15 but it is fixed in 1.4.0-rc.0 http://jsfiddle.net/8xc9pctd/2/

**Comment by petebacondarwin** [comment]
This will not be fixed in 1.3
