### ISSUE TITLE
Feature Request: Add arbitrary  attributes to ng-repeat.

### ISSUE THREAD

**Issue by garymazz** [angular/angular.js#9784]
I'd like to add arbitrary attributes to ng-repeat elements based on scope.  The attributes are injected into the elements created by ng-repeat without requiring a changes to existing templates. 

I'm assuming this can be easily achieved injecting a property into scope the compiler recognizes.

**Comment by gkalpak** [comment]
It is not clear what the exact usecase is (or feature) is. From what I can tell, the idea to basically be able to magically modify a template, by assigning some properties on the scope.

This sounds like a bad idea. Manipulating the DOM from a controller is considered an anti-pattern.
If you want to change the template, you could use a custom directive wrapped around the `ngRepeat` - I can't be more specific as I don't fully understand your usecase and requirements.

--
I'm going to close this, because in its current state it is not something we would add to the core.
In case I misunderstood the nature of the requested feature, please open a new issue with a concise explanation including _how_ this feature would be used (e.g. a code snippet using the proposed syntax) and _what_ its behavior would be (e.g. showing the resulting HTML).

Thx
