### ISSUE TITLE
Why doesn't $resource have a PUT for updating model?

### ISSUE THREAD

**Issue by jansoren** [angular/angular.js#9807]
Is it possible to expand the `$resource` with a `create` and a `update` action?

```
Example: 
{ 'get':    {method:'GET'},
  'save':   {method:'POST'},
  'create': {method:'POST'},
  'update': {method:'PUT'},
  'query':  {method:'GET', isArray:true},
  'remove': {method:'DELETE'},
  'delete': {method:'DELETE'} };
```

Is it also possible to override the `save` action to call `create` when id is null and `update` when id is set?

**Comment by tdhsmith** [comment]
Well the contrast between PUT and POST isn't specifically whether you are creating or updating, but whether you are editing a resource or a resource's child. From [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html):

> The PUT method requests that the enclosed entity be stored under the supplied Request-URI.

...versus...

> The POST method is used to request that the origin server accept the entity enclosed in the request as a new subordinate of the resource identified by the Request-URI ...

For most RESTful systems, this ends up being create and update, but it isn't a guarantee, and that's why I'm a big fan of Angular's current neutral term `save` for POST, which doesn't have strong connotations either way. I also agree that adding a `create` function that also calls POST wouldn't be helpful because, as others have noted, its communication with the server would not be distinguishable from `save`.

*However*, I am a big fan of including a PUT method: PUT is by definition idempotent (see section 9.1.2 above) so multiple copies of a request should generally have the same result as a single copy. POST does not have this property, and frequently servers will interpret multiple copies of a request independently and create duplicate resources for each of them. In my mind, this is enough to merit inclusion, as there should be at least one non-duplicative editing route in any "standard" REST toolbox.

The two back-end REST resource implementations I use include a PUT:

* [Laravel's resource controllers](http://laravel.com/docs/4.2/controllers#restful-resource-controllers) have `PUT /resource/{resource} -> update` as a default part of the `Route::resource` method.

* ExpressJS's resource package has [a very similar mapping](https://github.com/expressjs/express-resource#default-action-mapping), with the exact same `PUT /resource/{resource} -> update`.

Plus, the hundreds of routing libraries out there nearly all consider PUT to be an essential core method.

Granted, it isn't *broken* not to have it, but it feels odd to be using all the defaults and then having to add my own PUT to every `$resource` I define.

**Comment by balliegojr** [comment]
@tdhsmith 
I agree with you, it would be very interesting to have a PUT method, I would call him "update", and a PATCH would be "partial_update"

I took these names from DJango REST Framework, the generic views have the two methods:

def update(self, request, pk=None):
        pass

def partial_update(self, request, pk=None):
       pass

I think the correct implementation of a back-end REST must have a method PUT that perform updates, but i know that not everybody implements it.
My current implementations in ASP.NET don't have the PUT method because, since c# is strongly typed, it is easier to implement control flow in the back-end

**Comment by syndicatedshannon** [comment]
It seems pretty typical to require a PUT method in v1 of any data app, though, right? +1 for finding some convention that allows standard inclusion of these few lines of code in angular.

**Comment by sjatkins** [comment]
See http://kirkbushell.me/angular-js-using-ng-resource-in-a-more-restful-manner/ for one pretty clean way to add your custom methods to $resource.

**Comment by gbezerras** [comment]
@sjatkins For me, that's more of a workaround.

I also agree that $resource should have a default option for PUT, it seems weird to have to configure it manually every time you need to use PUT to update a record, which is pretty common, IMO. A default option for PATCH can be discussed even though it's a bit more uncommon, but at least one for PUT is reasonable.

Also, people were asking what would be the difference between $save and $create. Well, maybe the same difference between $delete and $remove, i.e. none? I see no problems with aliases, even ngResource has one already.

**Comment by JemiloII** [comment]
Resource is suppose to based off of Rest, so why doesn't it just have the http restful routes baked in...

Example: 

    {
        'get':    {method:'GET'},
        'post':   {method:'POST'},
        'update': {method:'PUT'},
        'query':  {method:'GET', isArray:true},
        'delete': {method:'DELETE'}
    };

**Comment by gkalpak** [comment]
Because different backends have different opinions about the verbs that should be used.
`$resource` provides a generic solutionand is easily extensible.

Basically, you can set the default actions using `$resourceProvider.defaults.actions`.
Not sure if leaving this undocumented was intentional or just an oversight.

**Comment by JemiloII** [comment]
Well fancy that, I'll give resource another go then! I love extensible components.

**Comment by Narretz** [comment]
The docs have been updated with clearer info on default actions. This should allow easy configuration of PUT if you want it.
