### ISSUE TITLE
multiple {{}} interpolations inside <option> are causing value created by ngValue to be replaced by <option>'s text

### ISSUE THREAD

**Issue by fxck** [angular/angular.js#9842]
See http://plnkr.co/edit/MXxLZ5wkVj4Cq2e5qQ4e?p=preview

##### works fine

```html
    <select ng-model="baz.val">
      <option 
        ng-value="foo.val" 
        ng-repeat="foo in bar">
        {{ foo.name + ' ' + foo.second_name }}
      </option>
    </select> 

```

##### ng-value replaced in this case

```html
    <select ng-model="baz.val">
      <option 
        ng-value="foo.val" 
        ng-repeat="foo in bar">
        {{ foo.name }} {{ foo.second_name }}
      </option>
    </select> 

```

also it's happening only if you use `ng-value`, it works fine when you use `value="{{ val }}"`, see https://github.com/angular/angular.js/issues/9840

**Comment by awerlang** [comment]
This behavior is explained by looking at https://github.com/angular/angular.js/blob/master/src/ng/rootScope.js#L445:

```js
if (watchExpressions.length === 1) {
  // Special case size of one
  return this.$watch(watchExpressions[0], function watchGroupAction(value, oldValue, scope) {
      // omitted for brevity
  });
}

forEach(watchExpressions, function(expr, i) {
  var unwatchFn = self.$watch(expr, function watchGroupSubAction(value, oldValue) {
      // omitted for brevity
      self.$evalAsync(watchGroupAction);
  });
  deregisterFns.push(unwatchFn);
});
```

Whenever there's more that one expression to evaluate, because of `$evalAsync()` that'll be done some time later...later than assignment at `option` at least.

But...why does https://github.com/angular/angular.js/blob/master/src/ng/directive/select.js#L297 overwrites the value for option, when it already has one? I could trace this assignment back to https://github.com/angular/angular.js/commit/904b69c745ea4afc1d6ecd2a5f3138c6f947b157.

So, I believe a correction may be to verify if an option there's a value already.
