### ISSUE TITLE
feat(ngTouch): Service as well as directive

### ISSUE THREAD

**Issue by jrgleason** [angular/angular.js#9943]
ngTouch has a great directive for handling swipes. On my project, I need to register a swipe no matter what div it was done on and also would like to publish this swipe to all subscribers. Because of this need I had to retrofit the directive as a service. Would it be beneficial to include a service (that actually interprets the swipe) as well as the directive?

**Comment by Narretz** [comment]
I'm closing this issue since the ngTouch module will be deprecated in AngularJS 1.7.0, and we will not do any more work on it. This is because touch handling is a complex topic, and there are stand-alone libraries that are better equipped to handle all the nuances and edge cases. For example, https://hammerjs.github.io/, which is also used by Angular.
