### ISSUE TITLE
Using $compile() seems to ignore my directive's "restrict" setting

### ISSUE THREAD

**Issue by onlywei** [angular/angular.js#9966]
Please see this JSBin: http://jsbin.com/puxevo/1/edit?js,console

Note that if you change the CSS class in the string being $compile()-ed, it works!

**Comment by wesleycho** [comment]
This can probably be closed as won't fix - $compile needs to fetch the DDO, but if it is being called in the factory function that ultimately returns the DDO, one will never get the DDO. Angular needs to get the DDO for the directive with that class name because it needs to determine if it satisfies the restrict settings.

**Comment by gkalpak** [comment]
@wesleycho is right. This is working as expected. We need to execute the directive factory in order to get the restrict property (which is less than ideal, but would be too much of breaking change to get rid of - that's a different discussion though).

There are several ways to work around this limitation, e.g. compile inside the compile function (and cache the result after the first time), add the `wut` class after compiling the element (assuming there are no other directives that match `.wut`), use `ng-class` or interpolation etc.
